#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf binutils-${BINUTILS_VER} ${LOGDIR}/binutils-pass1-${BINUTILS_VER}.log

tar xf ${SROOT}/binutils-${BINUTILS_VER}.tar.bz2

{

  time {
  mkdir binutils-${BINUTILS_VER}/binutils-build
  pushd binutils-${BINUTILS_VER}/binutils-build
    ../configure --prefix=/tools     \
                 --with-sysroot=$LFS \
                 --target=$LFS_TGT   \
                 --disable-nls       \
                 --disable-werror    \
                 --enable-multilib   \
                 --with-lib-path=/tools/lib32:/tools/lib
    make
    make install
    mkdir /tools/lib
    ln -s lib /tools/lib64
  popd
  }

} 2>&1 | tee ${LOGDIR}/binutils-pass1-${BINUTILS_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf binutils-${BINUTILS_VER} binutils-build
