#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf gcc-${GCC_VER} ${LOGDIR}/libstdc++-${GCC_VER}.log

tar xf ${SROOT}/gcc-${GCC_VER}.tar.bz2

{

  time {
  mkdir gcc-${GCC_VER}/build
  pushd gcc-${GCC_VER}/build
    ../libstdc++-v3/configure       \
        --host=$LFS_TGT             \
        --prefix=/tools             \
        --disable-multilib          \
        --disable-nls               \
        --disable-libstdcxx-threads \
        --disable-libstdcxx-pch     \
        --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/$(cat ../gcc/BASE-VER)
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/libstdc++-${GCC_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf gcc-${GCC_VER} gcc-build
