#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf binutils-${BINUTILS_VER} binutils-build ${LOGDIR}/binutils-pass2-${BINUTILS_VER}.log

tar xf ${SROOT}/binutils-${BINUTILS_VER}.tar.bz2

{

  time {
  mkdir -v binutils-build
  pushd binutils-build
    CC=$LFS_TGT-gcc        \
    AR=$LFS_TGT-ar         \
    RANLIB=$LFS_TGT-ranlib \
    ../binutils-${BINUTILS_VER}/configure \
        --prefix=/tools   \
        --with-sysroot    \
        --disable-nls     \
        --disable-werror  \
        --enable-multilib \
        --with-lib-path=/tools/lib32:/tools/lib
    make
    make install
    make -C ld clean
    make -C ld LIB_PATH=/usr/lib32:/lib32:/usr/lib:/lib
    cp -v ld/ld-new /tools/bin
  popd
  }

} 2>&1 | tee ${LOGDIR}/binutils-pass2-${BINUTILS_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf binutils-${BINUTILS_VER} binutils-build
