#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf make-${MAKE_VER} ${LOGDIR}/make-${MAKE_VER}.log

tar xf ${SROOT}/make-${MAKE_VER}.tar.bz2

{

  time {
  pushd make-${MAKE_VER}
    ./configure --prefix=/tools --without-guile
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/make-${MAKE_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf make-${MAKE_VER}
