#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf nano-${NANO_VER} ${LOGDIR}/nano-${NANO_VER}.log

tar xf ${SROOT}/nano-${NANO_VER}.tar.xz

{

  time {
  pushd nano-${NANO_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/nano-${NANO_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf nano-${NANO_VER}
