#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf libffi-${LIBFFI_VER} ${LOGDIR}/libffi-${LIBFFI_VER}.log

tar xf ${SROOT}/libffi-${LIBFFI_VER}.tar.gz

{

  time {
  pushd libffi-${LIBFFI_VER}
    patch -Np1 -i ${PROOT}/libffi.patch
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/libffi-${LIBFFI_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf libffi-${LIBFFI_VER}
