#!/bin/bash

for file in *
do

  v=$(tail $file | grep real | awk '{print $2}' | sed "s/s//;s/m/*60+/;s/h/*3600+/")
  v2=$( echo "scale=2; ($v)/150" | bc )
  echo "$file $v2 SBU" | sed "s:\.log::g;s: \.: 0\.:g"

done | sort
