#!/bin/bash -e

export PKGNAME=lcms2
export PKGVER=2.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/lcms/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
