#!/bin/bash -e

export PKGNAME=hdf5
export PKGVER=1.10.0-patch1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.hdfgroup.org/ftp/HDF5/current/src/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-build-mode=production --disable-sharedlib-rpath)

make_install_post() {
  rm -rf ${DEST}/usr/share
}

. $(dirname $0)/master.sh
