#!/bin/bash -e

export PKGNAME=libspatialite
export PKGVER=4.3.0a
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.gaia-gis.it/gaia-sins/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-libxml2)

. $(dirname $0)/master.sh
