#!/bin/bash -e

export PKGNAME=qhull
export PKGVER=2015.2
export PKGTAR=${PKGNAME}-2015-src-7.2.0.tgz
export PKGURL="http://www.qhull.org/download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
