#!/bin/bash -e

export PKGNAME=ctags
export PKGVER=5.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/ctags/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-external-sort)
export MAKE_INSTALL_FLAGS="prefix=\${DEST}/usr mandir=\${DEST}/usr/share/man"

. $(dirname $0)/master.sh
