#!/bin/bash -e

export PKGNAME=geos
export PKGVER=3.6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.osgeo.org/geos/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
