#!/bin/bash -e

export PKGNAME=libgeotiff
export PKGVER=1.4.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://download.osgeo.org/geotiff/libgeotiff/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
