#!/bin/bash -e

export PKGNAME=mupdf
export PKGVER=1.9a
export PKGTAR=${PKGNAME}-${PKGVER}-source.tar.gz
export PKGURL="http://mupdf.com/downloads/${PKGTAR}"
export PKGDIR=${PKGNAME}-${PKGVER}-source
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("mupdf-fixes.patch" "mupdf-sharedlib.patch")
export KEEP_STATIC=1
export MAKE_INSTALL_FLAGS="prefix=/usr"

configure_override() {
  rm -rf thirdparty/curl thirdparty/freetype thirdparty/harfbuzz
  rm -rf thirdparty/jpeg thirdparty/openjpeg thirdparty/zlib

  export XCFLAGS=${CFLAGS}
}

. $(dirname $0)/master.sh
