#!/bin/bash -e

export PKGNAME=libdc1394
export PKGVER=2.2.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/libdc1394/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export DEFAULT_CC="gcc"

. $(dirname $0)/master.sh
