#!/bin/bash -e

case $(basename $0) in
  buildpyatspi )
    export PKGNAME=pyatspi
    export PKGVER=2.18.0
    export MULTILIB_BUILD=1
    export CONFIGURE_FLAGS=(PYTHON=/usr/bin/python3)
    export CONFIGURE_FLAGS_32=(PYTHON=/usr/bin/python --libdir=/usr/lib)
    configure_pre_32() {
      unset PKG_CONFIG_PATH
    }
    make_install_override() {
      make install DESTDIR=${DEST}
    }
  ;;
  buildpygobject2 )
    export PKGNAME=pygobject
    export PKGVER=2.28.6
    export PATCHES_LIST=("pygobject-fixes.patch")
    export CONFIGURE_FLAGS=(--disable-introspection)
  ;;
  buildpygtk )
    export PKGNAME=pygtk
    export PKGVER=2.24.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    make_install_post() {
      rm -rf ${DEST}/usr/bin/pygtk-demo
      rm -rf ${DEST}/usr/lib/pygtk
    }
  ;;
esac

if [ -z ${PKGTAR} ]
then
  export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
fi

export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export DEFAULT_CC_M32="clang"

. $(dirname $0)/master.sh
