#!/bin/bash -e

export PKGNAME=GraphicsMagick
export PKGVER=1.3.23
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://downloads.sourceforge.net/graphicsmagick/${PKGTAR}"
export KEEP_LA=1
export MAKE_JOBS_FLAGS="-j4"

export CONFIGURE_FLAGS=(--enable-shared
                        --with-modules
                        --with-perl
                        --with-quantum-depth=16
                        --with-gs-font-dir=/usr/share/ghostscript/fonts)

make_install_post() {
  pushd PerlMagick

    sed -i -e "s:'LDDLFLAGS'  => \"\(.*\)\":'LDDLFLAGS'  => \"-L${DEST}/usr/lib \1\":" Makefile.PL
    perl Makefile.PL INSTALLDIRS=vendor PREFIX=/usr DESTDIR="${DEST}"
    sed -i -e "s/LDLOADLIBS =/LDLOADLIBS = -lGraphicsMagick/" Makefile

    make ${MAKE_JOBS_FLAGS}
    make install

  popd

  rm -rf ${DEST}/usr/lib/*.la

}

. $(dirname $0)/master.sh
