#!/bin/bash -e

export PKGNAME=vigra
export PKGVER=1.11.0
export PKGTAR=${PKGNAME}-${PKGVER}-src.tar.gz
export PKGURL="https://github.com/ukoethe/vigra/releases/download/Version-$(echo ${PKGVER} | sed 's|\.|_|g')/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DWITH_OPENEXR=true)

configure_pre() {
  sed -i "s:tr1/::g" ../${PKGDIR}/include/vigra/memory.hxx
}

. $(dirname $0)/master.sh
