#!/bin/bash -e

export PKGNAME=QGnomePlatform
export PKGVER=0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/MartinBriza/QGnomePlatform/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_INSTALL_FLAGS="INSTALL_ROOT=\${DEST}"

configure_override() {
  qmake
}

. $(dirname $0)/master.sh
