#!/bin/bash -e

export PKGNAME=elementary
export PKGVER=1.16.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://download.enlightenment.org/rel/libs/elementary/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
