#!/bin/bash -e

export PKGNAME=socat
export PKGVER=1.7.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.dest-unreach.org/socat/download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("socat-fixes.patch")

. $(dirname $0)/master.sh
