#!/bin/bash -e

export PKGNAME=npapi-sdk
export PKGVER=0.27.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://bitbucket.org/mgorny/npapi-sdk/downloads/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
