#!/bin/bash -e

export PKGNAME=dirmngr
export PKGVER=1.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.gnupg.org/gcrypt/dirmngr/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("dirmngr-pth-fix.patch")

. $(dirname $0)/master.sh
