#!/bin/bash -e

export PKGNAME=libindicator
export PKGVER=12.10.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export DEST=/binary/${PKGNAME}-gtk2-${PKGVER}
export PKGURL="https://launchpad.net/libindicator/${PKGVER:0:5}/${PKGVER}/+download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--with-gtk=2)
export CONFIGURE_FLAGS_32=(--with-gtk=2)

configure_pre() {
  sed -i 's/-Werror/-Wno-deprecated-declarations/' libindicator/Makefile.in
  sed -i 's/+="$LIBM"/+=" $LIBM"/' configure
}

configure_pre_32() {
  sed -i 's/-Werror/-Wno-deprecated-declarations/' libindicator/Makefile.in
  sed -i 's/+="$LIBM"/+=" $LIBM"/' configure
}

post_install_config() {
  rm -rf ${DEST}/usr/lib*/libdummy* ${DEST}/usr/share
}

. $(dirname $0)/master.sh
