#!/bin/bash -e

case $(basename $0) in

  buildperl-xml-namespacesupport )
    export PKGNAME=XML-NamespaceSupport
    export PKGVER=1.11
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://search.cpan.org/CPAN/authors/id/P/PE/PERIGRIN/${PKGTAR}"
    export DEST=/binary/perl/perl-xml-namespacesupport-${PKGVER}
  ;;
  buildperl-xml-sax )
    export PKGNAME=XML-SAX
    export PKGVER=0.99
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/${PKGTAR}"
    export DEST=/binary/perl/perl-xml-sax-${PKGVER}
    export PATCHES_LIST=("perl-xml-sax.patch")
  ;;
  buildperl-xml-sax-base )
    export PKGNAME=XML-SAX-Base
    export PKGVER=1.08
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/${PKGTAR}"
    export DEST=/binary/perl/perl-xml-sax-base-${PKGVER}
  ;;
  buildperl-xml-sax-expat )
    export PKGNAME=XML-SAX-Expat
    export PKGVER=0.51
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://search.cpan.org/CPAN/authors/id/B/BJ/BJOERN/${PKGTAR}"
    export DEST=/binary/perl/perl-xml-sax-expat-${PKGVER}

make_install_override() {
  make pure_install DESTDIR=${DEST}
}
  ;;
  buildperl-xml-simple )
    export PKGNAME=XML-Simple
    export PKGVER=2.22
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/${PKGTAR}"
    export DEST=/binary/perl/perl-xml-simple-${PKGVER}
  ;;

esac

configure_override() {
  perl Makefile.PL INSTALLDIRS=vendor
}

export MAKE_JOBS_FLAGS="-j4"
export NO_OPTIMIZATION=1

. $(dirname $0)/master.sh
