#!/bin/bash -e

export PKGNAME=virt-viewer
export PKGVER=3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://virt-manager.org/download/sources/virt-viewer/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-update-mimedb)

. $(dirname $0)/master.sh
