#!/bin/bash -e

export PKGNAME=libpng
export PKGVER=1.2.56
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://downloads.sourceforge.net/libpng/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

post_install_config() {
  find ${DEST} -name "*.la" -delete
  find ${DEST} -name "*.so" -delete

  rm -rf ${DEST}/usr/bin ${DEST}/usr/include
  rm -rf ${DEST}/usr/lib*/pkgconfig ${DEST}/usr/share
}

. $(dirname $0)/master.sh
