#!/bin/bash -e

export PKGNAME=xterm
export PKGVER=320
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="ftp://invisible-island.net/xterm/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-app-defaults=/usr/share/X11/app-defaults)

. $(dirname $0)/master.sh
