#!/bin/bash -e

export PKGNAME=libzip
export PKGVER=1.1.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.nih.at/libzip/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done\n"
                    "cp -rf --remove-destination usr/share/man/man3 /usr/share/man")

make_install_post() {
  ln -sf ../lib/libzip/include/zipconf.h ${DEST}/usr/include/zipconf.h
}

. $(dirname $0)/master.sh
