#!/bin/bash -e

export PKGNAME=inkscape
export PKGVER=0.91
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://launchpad.net/inkscape/${PKGVER}.x/${PKGVER}/+download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export USER_CXXFLAGS="-std=c++11"

configure_pre() {
  sed -i "s#abs(#&(double)#g" src/libavoid/connector.cpp
  sed -i "s#abs(static_cast<int>#abs(static_cast<double>#g" src/ui/tools/flood-tool.cpp
  sed -i "s#Glib::ScopedPtr<char>#Glib::make_unique_ptr_gfree#g" src/ui/clipboard.cpp
}

make_install_post() {
  sed -i "s:application/pdf;application/postscript;image/x-eps;::g" ${DEST}/usr/share/applications/inkscape.desktop

  for man in el fr ja sk zh_TW
  do
    rm -rf ${DEST}/usr/share/man/man1/inkscape.${man}.1
  done
}

. $(dirname $0)/master.sh
