#!/bin/bash -e

export PKGNAME=id3lib
export PKGVER=3.8.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/id3lib/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export PATCHES_LIST=("id3lib.patch")

configure_pre() {
  libtoolize -fc
  aclocal
  autoconf
  automake --add-missing --copy
}

. $(dirname $0)/master.sh
