#!/bin/bash -e

export PKGNAME=foomatic-db
export PKGVER=4.0-20160314
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGDIR=${PKGNAME}-20160314
export PKGURL="https://www.openprinting.org/download/foomatic/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
