#!/bin/bash -e

export PKGNAME=evolution
export PKGVER=3.20.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
export CONFIGURE_FLAGS=(--disable-autoar
                        --enable-contact-maps
                        --with-openldap
                        --without-spamassassin)

. $(dirname $0)/master.sh
