#!/bin/bash -e

export PKGNAME=libmatroska
export PKGVER=1.4.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://dl.matroska.org/downloads/libmatroska/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
