#!/bin/bash -e

export PKGNAME=libvirt-glib
export PKGVER=0.2.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://libvirt.org/sources/glib/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
