#!/bin/bash -e

export PKGNAME=docker
export PKGVER=1.9.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/docker/docker/archive/v${PKGVER}.tar.gz"
export POSTINST_TRIGGER=("getent group docker > /dev/null || groupadd -g 98 docker")

export GO_VER=1.5.2
export GO_MD2MAN_VER=1.0.4

configure_override() {
  rm -rf go go-md2man

  wget -c https://storage.googleapis.com/golang/go${GO_VER}.linux-amd64.tar.gz -O - | bsdtar xf -

  export PATH=${PATH}:${PWD}/go/bin
  export GOROOT=${PWD}/go

  install -dm755 go-md2man

  pushd go-md2man

    git clone https://github.com/cpuguy83/go-md2man.git

    pushd go-md2man
      git checkout v${GO_MD2MAN_VER}
    popd

    export GOPATH=${PWD}

    install -dm755 src/github.com/cpuguy83

    ln -sf ../../../go-md2man src/github.com/cpuguy83/go-md2man

    pushd src/github.com/cpuguy83/go-md2man
      go get -v ./...
    popd

  popd

  export PATH=${PATH}:${PWD}/go-md2man/bin

  export AUTO_GOPATH=1
  export DOCKER_GITCOMMIT=${PKGVER}

  sed -i "s#fd://#& --exec-opt native.cgroupdriver=cgroupfs#" contrib/init/systemd/docker.service
}

make_override() {
  hack/make.sh dynbinary
  man/md2man-all.sh
}

make_install_override() {
  install -dm755 ${DEST}/lib/systemd/system ${DEST}/usr/bin ${DEST}/usr/lib/docker ${DEST}/usr/share/man

  install -m644 contrib/init/systemd/docker.* ${DEST}/lib/systemd/system

  cp -L bundles/latest/dynbinary/docker ${DEST}/usr/bin
  cp -L bundles/latest/dynbinary/dockerinit ${DEST}/usr/lib/docker

  mv man/man* ${DEST}/usr/share/man

  rm -rf ../go ../go-md2man
}

. $(dirname $0)/master.sh
