#!/bin/bash -e

export PKGNAME=soundtouch
export PKGVER=1.9.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}
export PKGURL="http://www.surina.net/soundtouch/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  ./bootstrap
}

. $(dirname $0)/master.sh
