#!/bin/bash -e

export PKGNAME=lightdm-gtk-greeter
export PKGVER=2.0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://launchpad.net/lightdm-gtk-greeter/${PKGVER:0:3}/${PKGVER}/+download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-libxklavier)

. $(dirname $0)/master.sh
