#!/bin/bash -e

export PKGNAME=systemd-kcm
export PKGVER=1.2.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.kde.org/stable/systemd-kcm/${PKGTAR}"
export DEST=/binary/plasma/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DSYSCONF_INSTALL_DIR=/etc
                    -DLIB_INSTALL_DIR=lib
                    -DBUILD_TESTING=OFF
                    -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins)

. $(dirname $0)/master.sh
