#!/bin/bash -e

export PKGNAME=which
export PKGVER=2.21
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/which/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
