#!/bin/bash -e

export PKGNAME=openldap
export PKGVER=2.4.42
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export PATCHES_LIST=("openldap-blfs-paths.patch" "openldap-symbol-versions.patch")
export PATCHES_LIST_32=("openldap-blfs-paths.patch" "openldap-symbol-versions.patch")
export MAKE_FLAGS_32="-C libraries"
export MAKE_INSTALL_FLAGS_32="-C libraries"

export COMMON_CONFIGURE_FLAGS=(--libexecdir=/usr/lib
                               --disable-debug
                               --enable-dynamic
                               --enable-crypt
                               --enable-modules
                               --enable-rlookups
                               --enable-backends=mod
                               --enable-overlays=mod
                               --disable-bdb
                               --disable-hdb
                               --disable-ndb)

export CONFIGURE_FLAGS=("${COMMON_CONFIGURE_FLAGS[@]}" --enable-spasswd --enable-sql)
export CONFIGURE_FLAGS_32=("${COMMON_CONFIGURE_FLAGS[@]}" --disable-spasswd --disable-sql)

configure_pre() {
  autoconf
}

make_pre() {
  make depend
}

configure_pre_32() {
  autoconf
}

configure_post_32() {
  make -C include
  make -C libraries depend
}

make_install_post() {
  rm -rf ${DEST}/etc/openldap/ldap.conf ${DEST}/etc/openldap/slapd.conf ${DEST}/etc/openldap/slapd.ldif
  rm -rf ${DEST}/var/run

  install -dm755 ${DEST}/etc/default ${DEST}/etc/openldap/slapd.d ${DEST}/etc/systemd/system/multi-user.target.wants
  install -dm755 ${DEST}/lib/systemd/system ${DEST}/usr/lib/tmpfiles.d ${DEST}/var/lib/openldap

  touch ${DEST}/etc/openldap/slapd.d/.keepdir ${DEST}/var/lib/openldap/.keepdir

cat > ${DEST}/etc/default/slapd << "EOF"
# Begin /etc/default/slapd

# Options to pass to slapd.
# See slapd(8) for more details.
#SLAPD_OPTS=""

# slapd normally serves ldap only on all TCP-ports 389. slapd can also
# service requests on TCP-port 636 (ldaps) and requests via unix
# sockets.
#SLAPD_OPTS='-h "ldap://127.0.0.1:389/ ldaps:/// ldapi:///"'

# End /etc/default/slapd
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/slapd.conf << "EOF"
d /run/openldap 0755 ldap ldap -
EOF

cat > ${DEST}/lib/systemd/system/slapd.service << "EOF"
[Unit]
Description=OpenLDAP server daemon
After=network.target

[Service]
Type=forking
EnvironmentFile=/etc/default/slapd
ExecStart=/usr/sbin/slapd -u ldap -g ldap $SLAPD_OPTS

[Install]
WantedBy=multi-user.target
EOF

  ln -sf /lib/systemd/system/slapd.service ${DEST}/etc/systemd/system/multi-user.target.wants/slapd.service
}

post_install_config() {
  find ${DEST} -type f -name .keepdir -delete
}

generate_install_override() {
cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

getent group ldap >/dev/null || groupadd -g 83 ldap
getent passwd ldap >/dev/null || useradd -c "OpenLDAP Daemon Owner" -d /var/lib/openldap -u 83 -g ldap -s /bin/false ldap

install -dm750 -o ldap -g ldap /run/openldap

if [ ! -e /etc/openldap/ldap.conf ]; then
   cp -r /etc/openldap/ldap.conf.default /etc/openldap/ldap.conf
fi

if [ ! -e /etc/openldap/slapd.conf ]; then
   cp -r /etc/openldap/slapd.conf.default /etc/openldap/slapd.conf
fi

if [ ! -e /etc/openldap/slapd.ldif ]; then
   cp -r /etc/openldap/slapd.ldif.default /etc/openldap/slapd.ldif
fi

chmod 700 /etc/openldap/slapd.d /var/lib/openldap
chown -R ldap:ldap /etc/openldap/slapd.d /var/lib/openldap

chmod 640 /etc/openldap/slapd.conf /etc/openldap/slapd.ldif
chown root:ldap /etc/openldap/slapd.conf /etc/openldap/slapd.ldif

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q /usr/share/man
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

  chmod 755 ${DEST}/INSTALL
}

. $(dirname $0)/master.sh
