#!/bin/bash -e

export PKGNAME=libva-intel-driver
export PKGVER=1.6.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.freedesktop.org/software/vaapi/releases/libva-intel-driver/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
