#!/bin/bash -e

export PKGNAME=popt
export PKGVER=1.16
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://rpm5.org/files/popt/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
