#!/bin/bash -e

export PKGNAME=media-player-info
export PKGVER=22
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.freedesktop.org/software/media-player-info/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
