#!/bin/bash -e

export PKGNAME=dejagnu
export PKGVER=1.5.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/dejagnu/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
