#!/bin/bash -e

export PKGNAME=itstool
export PKGVER=2.0.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://files.itstool.org/itstool/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

. $(dirname $0)/master.sh
