#!/bin/bash -e

export PKGNAME=gtk-engines
export PKGVER=2.21.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-animation)

. $(dirname $0)/master.sh
