#!/bin/bash -e

export PKGNAME=kpartx
export PKGVER=0.5.0
export PKGTAR=multipath-tools-${PKGVER}.tar.bz2
export PKGDIR=multipath-tools-${PKGVER}
export PKGBUILD=${PKGDIR}/kpartx
export PKGURL="http://christophe.varoqui.free.fr/multipath-tools/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  sed -i "s:lib64:lib:g" ../Makefile.inc
  sed -i "s:-O2:${CFLAGS}:g" ../Makefile.inc

  unset CFLAGS
}

make_install_post() {
  mv ${DEST}/etc/udev/rules.d ${DEST}/lib/udev
  rm -rf ${DEST}/etc

  gzip -d ${DEST}/usr/share/man/man8/*.gz
}

. $(dirname $0)/master.sh
