#!/bin/bash -e

export PKGNAME=pcsx2
export PKGVER=1.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/PCSX2/pcsx2/archive/v${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_LIBRARY_PATH=/usr/lib32
                    -DPLUGIN_DIR=/usr/lib32/pcsx2
                    -DGAMEINDEX_DIR=/usr/share/pcsx2
                    -DEXTRA_PLUGINS=TRUE
                    -DGLSL_API=TRUE
                    -DPACKAGE_MODE=TRUE
                    -DREBUILD_SHADER=TRUE
                    -DXDG_STD=TRUE
                    -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config32
                    -DwxWidgets_wxrc_EXECUTABLE=/usr/bin/wxrc32
                    -DCMAKE_TOOLCHAIN_FILE="cmake/linux-compiler-i386-multilib.cmake")
export USER_CFLAGS="-w"
export USER_CXXFLAGS="-w"
export DEFAULT_CC="gcc -m32"
export DEFAULT_CXX="g++ -m32"

configure_pre() {
  export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
}

. $(dirname $0)/master.sh
