#!/bin/bash -e

export PKGNAME=cracklib
export PKGVER=2.9.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/cracklib/cracklib/releases/download/cracklib-${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libcrack.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libcrack.so) ${DEST}/usr/lib/libcrack.so
}

. $(dirname $0)/master.sh
