#!/bin/bash -e

export PKGNAME=cabextract
export PKGVER=1.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.cabextract.org.uk/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
