#!/bin/bash -e

export PKGNAME=speexdsp
export PKGVER=1.2rc3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://downloads.xiph.org/releases/speex/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
