#!/bin/bash -e

case $(basename $0) in
  buildqtmodules )
    export PKG_AUTO_INSTALL=1

    $(dirname $0)/buildqtimageformats
    $(dirname $0)/buildqtscript
    $(dirname $0)/buildqtserialport
    $(dirname $0)/buildqtsvg
    $(dirname $0)/buildqtwayland
    $(dirname $0)/buildqtx11extras
    $(dirname $0)/buildqtxmlpatterns
    $(dirname $0)/buildqtdeclarative
    $(dirname $0)/buildqtconnectivity
    $(dirname $0)/buildqtgraphicaleffects
    $(dirname $0)/buildqtlocation
    $(dirname $0)/buildqtmultimedia
    $(dirname $0)/buildqtquickcontrols
    $(dirname $0)/buildqtsensors
    $(dirname $0)/buildqtwebchannel
    $(dirname $0)/buildqtwebsockets
    $(dirname $0)/buildqtwebengine
    $(dirname $0)/buildqtwebkit
    $(dirname $0)/buildqttools
    $(dirname $0)/buildqtquick1

    exit 0
  ;;
esac

qtmodules=(
  qtimageformats
  qtscript
  qtserialport
  qtsvg
  qtwayland
  qtx11extras
  qtxmlpatterns
  qtdeclarative
  qtconnectivity
  qtgraphicaleffects
  qtlocation
  qtmultimedia
  qtquickcontrols
  qtsensors
  qtwebchannel
  qtwebsockets
  qtwebengine
  qtwebkit
  qttools
  qtquick1
)

for qtmodule in ${qtmodules[@]}
do
  case $(basename $0) in
    build${qtmodule} )
      export PKGNAME=${qtmodule}
      export PKGVER=5.5.0
      export PKGTAR=${PKGNAME}-opensource-src-${PKGVER}.tar.xz
      export PKGURL="http://download.qt.io/official_releases/qt/5.5/${PKGVER}/submodules/${PKGTAR}"
      export PKGDIR=${PKGNAME}-opensource-src-${PKGVER}
    ;;
  esac
done

export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export NO_OPTIMIZATION=1
export MAKE_INSTALL_FLAGS="INSTALL_ROOT=\${DEST}"

if [ ${PKGNAME} == "qtwebengine" ] ||
   [ ${PKGNAME} == "qtwebkit" ]
then
  configure_post() {
    # No debug symbols for this module. Taken from Debian
    echo "QMAKE_CXXFLAGS -= -g" >> .qmake.conf
    echo "QMAKE_CXXFLAGS -= -gstabs" >> .qmake.conf
    unset DEBUG_BUILD
  }
fi


configure_override() {
  qmake
}

make_post() {
  find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;
}

make_install_post() {
  find ${DEST}/usr/lib -name "*.prl" -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

  if [ -d ${DEST}/usr/bin ]
  then
    # Transitional
    for file in ${DEST}/usr/bin/*
    do
      ln -sf $(basename $file) ${DEST}/usr/bin/$(basename $file)-qt5
    done
  fi

  if [ ${PKGNAME} == "qttools" ]
  then
    install -Dm644 src/assistant/assistant/images/assistant-128.png \
                   ${DEST}/usr/share/pixmaps/assistant.png
    install -Dm644 src/designer/src/designer/images/designer.png \
                   ${DEST}/usr/share/pixmaps/designer.png
    install -Dm644 src/linguist/linguist/images/icons/linguist-128-32.png \
                   ${DEST}/usr/share/pixmaps/linguist.png
    install -Dm644 src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                   ${DEST}/usr/share/pixmaps/qdbusviewer.png
    install -dm755 ${DEST}/usr/share/applications

cat > ${DEST}/usr/share/applications/assistant.desktop << "EOF"
[Desktop Entry]
Name=Qt5 Assistant
Comment=Shows Qt5 documentation and examples
Exec=assistant
Icon=assistant
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Documentation;
EOF
cat > ${DEST}/usr/share/applications/designer.desktop << "EOF"
[Desktop Entry]
Name=Qt5 Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt5 applications
Exec=designer
Icon=designer
MimeType=application/x-designer;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF
cat > ${DEST}/usr/share/applications/linguist.desktop << "EOF"
[Desktop Entry]
Name=Qt5 Linguist
Comment=Add translations to Qt5 applications
Exec=linguist
Icon=linguist
MimeType=text/vnd.trolltech.linguist;application/x-linguist;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF
cat > ${DEST}/usr/share/applications/qdbusviewer.desktop << "EOF"
[Desktop Entry]
Name=Qt5 QDBusViewer
GenericName=D-Bus Debugger
Comment=Debug D-Bus applications
Exec=qdbusviewer
Icon=qdbusviewer
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Debugger;
EOF
  fi
}

. $(dirname $0)/master.sh
