#!/bin/bash -e

export PKGNAME=libmcrypt
export PKGVER=2.5.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/mcrypt/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1

. $(dirname $0)/master.sh
