#!/bin/bash -e

export PKGNAME=arpack-ng
export PKGVER=3.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/opencollab/arpack-ng/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-mpi)

configure_pre() {
  autoreconf -fi
}

. $(dirname $0)/master.sh
