#!/bin/bash -e

export PKGNAME=Orion
export PKGVER=1.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/shimmerproject/Orion/archive/v${PKGVER}.tar.gz"
export DEST=/binary/plasma/${PKGNAME}-${PKGVER}
export NO_STRIP=1

configure_override() {
  true
}

make_override() {
  true
}

make_install_override() {
  install -dm755 ${DEST}/usr/share/themes/Orion

  mv gtk-2.0 gtk-3.0 index.theme ${DEST}/usr/share/themes/Orion
  mv metacity-1 openbox-3 xfwm4 ${DEST}/usr/share/themes/Orion
}

. $(dirname $0)/master.sh
