#!/bin/bash -e

export PKGNAME=libvdpau-va-gl
export PKGVER=0.3.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/i-rinat/libvdpau-va-gl/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
