#!/bin/bash -e

export PKGNAME=x265
export PKGVER=1.8
export PKGTAR=${PKGNAME}_${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}_11047
export PKGBUILD=${PKGDIR}/build/linux
export PKGURL="https://bitbucket.org/multicoreware/x265/downloads/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATH_TO_SOURCE="../../source"
export CMAKE_BUILD=1

make_install_post() {
  find ${DEST} -name "*.a" -delete
}

. $(dirname $0)/master.sh
