#!/bin/bash -e

export PKGNAME=prison
export PKGVER=1.2.1
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DLIB_INSTALL_DIR=lib
                    -DBUILD_TESTING=OFF
                    -DECM_MKSPECS_INSTALL_DIR=/usr/lib/qt5/mkspecs/modules)

. $(dirname $0)/master.sh
