#!/bin/bash -e

export PKGNAME=ed
export PKGVER=1.12
export PKGTAR=${PKGNAME}-${PKGVER}.tar.lz
export PKGURL="https://ftp.gnu.org/gnu/ed/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  ./configure --prefix=/usr --bindir=/bin CFLAGS="${CFLAGS}"
}

. $(dirname $0)/master.sh
