#!/bin/bash -e

export PKGNAME=libcerf
export PKGVER=1.4
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="http://apps.jcns.fz-juelich.de/src/libcerf/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
