#!/bin/bash -e

export PKGNAME=pangox-compat
export PKGVER=0.0.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/pangox-compat/${PKGVER:0:3}/${PKGTAR}"
export DEST=/binary/mate/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
