#!/bin/bash -e

export PKGNAME=uhttpmock
export PKGVER=0.5.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://tecnocode.co.uk/downloads/uhttpmock/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
