#!/bin/bash -e

export PKGNAME=qtbase
export PKGVER=5.5.0
export PKGTAR=${PKGNAME}-opensource-src-${PKGVER}.tar.xz
export PKGURL="http://download.qt.io/official_releases/qt/5.5/${PKGVER}/submodules/${PKGTAR}"
export PKGDIR=${PKGNAME}-opensource-src-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export MAKE_INSTALL_FLAGS="INSTALL_ROOT=\${DEST}"

configure_override() {
  ./configure -prefix         /usr               \
              -sysconfdir     /etc/xdg           \
              -headerdir      /usr/include/qt5   \
              -archdatadir    /usr/lib/qt5       \
              -datadir        /usr/share/qt5     \
              -docdir         /usr/share/doc/qt5 \
              -translationdir /usr/share/qt5/translations \
              -examplesdir    /usr/share/doc/qt5/examples \
              -confirm-license        \
              -opensource             \
              -dbus-linked            \
              -openssl-linked         \
              -gstreamer 1.0          \
              -journald               \
              -libinput               \
              -system-harfbuzz        \
              -system-sqlite          \
              -nomake examples        \
              -no-reduce-relocations  \
              -no-rpath               \
              -no-strip               \
              -no-separate-debug-info \
              -optimized-qmake        \
              -no-use-gold-linker
}

make_post() {
  find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;
}

make_install_post() {
  sed -i -e "s:$PWD:/usr/lib/qt5:g" \
      ${DEST}/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri
  find ${DEST}/usr/lib/*.prl -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
  rm -rf ${DEST}/usr/share

  # Transitional
  for file in ${DEST}/usr/bin/*
  do
    ln -sf $(basename $file) ${DEST}/usr/bin/$(basename $file)-qt5
  done
}

. $(dirname $0)/master.sh
