#!/bin/bash -e

export PKGNAME=openmpi
export PKGVER=1.10.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://www.open-mpi.org/software/ompi/v${PKGVER:0:4}/downloads/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--sysconfdir=/etc/openmpi
                        --with-hwloc=/usr
                        --with-libltdl=/usr
                        --with-threads=posix
                        --with-valgrind
                        --without-slurm)

configure_pre() {
  rm -rf opal/libltdl

  export FC=/usr/bin/gfortran
}

make_install_post() {
  mv ${DEST}/usr/bin/otfinfo ${DEST}/usr/bin/otfinfompi

  rm -rf ${DEST}/usr/share/vampirtrace/config.log
}

. $(dirname $0)/master.sh
