#!/bin/bash -e

export PKGNAME=sqlite
export PKGVER=3.9.1
export PKGDLVER=3090100
export PKGTAR=${PKGNAME}-autoconf-${PKGDLVER}.tar.gz
export PKGDIR=${PKGNAME}-autoconf-${PKGDLVER}
export PKGURL="http://sqlite.org/2015/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export USER_CFLAGS="-DSQLITE_ENABLE_FTS3=1 \
                    -DSQLITE_ENABLE_COLUMN_METADATA=1 \
                    -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 \
                    -DSQLITE_ENABLE_DBSTAT_VTAB=1 \
                    -DSQLITE_SECURE_DELETE=1"

make_install_post() {
  pushd tea

  ./configure --prefix=/usr        \
              --with-system-sqlite \
              --with-tcl=/usr/lib

  make
  make install DESTDIR=${DEST}

  popd
}

. $(dirname $0)/master.sh
