#!/bin/bash -e

export PKGNAME=gl2ps
export PKGVER=1.3.9
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="http://geuz.org/gl2ps/src/${PKGTAR}"
export PKGDIR=${PKGNAME}-${PKGVER}-source
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_EXE_LINKER_FLAGS="-lm")

make_install_post() {
  find ${DEST} -name "*.a" -delete
}

. $(dirname $0)/master.sh
