#!/bin/bash -e

export PKGNAME=libvirt-glib
export PKGVER=0.2.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://libvirt.org/sources/glib/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
