#!/bin/bash -e

export PKGNAME=rtkit
export PKGVER=0.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://0pointer.de/public/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("rtkit.patch")
export POSTINST_TRIGGER=("getent group rtkit > /dev/null || groupadd -g 65 rtkit"
                         "getent passwd rtkit > /dev/null || useradd -c \"RealtimeKit\" -d /proc -g rtkit -u 65 -s /sbin/nologin rtkit")
export CONFIGURE_FLAGS=(--with-systemdsystemunitdir=/lib/systemd/system)

configure_pre() {
  autoreconf -fi
}

make_install_post() {
  install -dm755 ${DEST}/etc/systemd/system/graphical.target.wants
  install -dm755 ${DEST}/usr/share/dbus-1/interfaces

  ./rtkit-daemon --introspect > ${DEST}/usr/share/dbus-1/interfaces/org.freedesktop.RealtimeKit1.xml

  ln -sf /lib/systemd/system/rtkit-daemon.service ${DEST}/etc/systemd/system/graphical.target.wants/rtkit-daemon.service
}

. $(dirname $0)/master.sh
