#!/bin/bash -e

export PKGNAME=libogg
export PKGVER=1.3.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://downloads.xiph.org/releases/ogg/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
