#!/bin/bash -e

export PKGNAME=sed
export PKGVER=4.2.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://ftp.gnu.org/gnu/sed/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--bindir=/bin)

. $(dirname $0)/master.sh
