#!/bin/bash -e

export PKGNAME=wildmidi
export PKGVER=0.3.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-${PKGNAME}-${PKGVER}
export PKGURL="https://github.com/Mindwerks/wildmidi/archive/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
