#!/bin/bash -e

export PKGNAME=libmodplug
export PKGVER=0.8.8.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/modplug-xmms/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
