#!/bin/bash -e

export PKGNAME=gnome-keyring
export PKGVER=3.16.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/${PKGVER:0:4}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export POSTINST_TRIGGER=("setcap cap_ipc_lock=ep /usr/bin/gnome-keyring-daemon")
export CONFIGURE_FLAGS=(--with-pam-dir=/lib/security)

. $(dirname $0)/master.sh
