#!/bin/bash -e

export PKGNAME=tidy
export PKGVER=cvs_20101110
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://anduin.linuxfromscratch.org/BLFS/tidy/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
