#!/bin/bash -e

export PKGNAME=kscreengenie
export PKGVER=2.0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.kde.org/stable/kscreengenie/${PKGVER:0:3}/src/${PKGTAR}"
export DEST=/binary/plasma/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export KEEP_DOC=1
export CMAKE_FLAGS=(-DLIB_INSTALL_DIR=lib -DBUILD_TESTING=OFF)

. $(dirname $0)/master.sh
