#!/bin/bash -e

export PKGNAME=libass
export PKGVER=0.13.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/libass/libass/releases/download/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
