#!/bin/bash -e

export PKGNAME=soundtouch
export PKGVER=1.9.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}
export PKGURL="http://www.surina.net/soundtouch/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

configure_pre() {
  ./bootstrap
}

configure_pre_32() {
  ./bootstrap
}

. $(dirname $0)/master.sh
