#!/bin/bash -e

export PKGNAME=mtdev
export PKGVER=1.1.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://bitmath.org/code/mtdev/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
