#!/bin/bash -e

export PKGNAME=p11-kit
export PKGVER=0.23.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://p11-glue.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--enable-doc)
export CONFIGURE_FLAGS_32=(--with-module-path=/usr/lib32/pkcs11)

. $(dirname $0)/master.sh
