#!/bin/bash -e

export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export MULTILIB_BUILD=1

case $(basename $0) in
  buildglib2 )
    export PKGNAME=glib
    export PKGVER=2.46.1
    export PATCHES_LIST=("glib-compile-schemas-quiet.patch")
    export CONFIGURE_FLAGS="--with-pcre=system"
    export CONFIGURE_FLAGS_32="--with-pcre=system"
    make_install_post() {
      rm -rf ${DEST}/usr/share/gdb
      install -dm755 ${DEST}/lib
      mv ${DEST}/usr/lib/libglib-2.0.so.* ${DEST}/lib
      ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libglib-2.0.so) ${DEST}/usr/lib/libglib-2.0.so
    }
    make_install_post_32() {
      touch ${DEST}/usr/lib{,32}/gio/modules/.keepdir
      mv dest/usr/bin/gio-querymodules ${DEST}/usr/bin/gio-querymodules-32
    }
    post_install_config() {
      find ${DEST} -type f -name .keepdir -delete
    }
  ;;
  buildgobject-introspection )
    export PKGNAME=gobject-introspection
    export PKGVER=1.46.0
    unset MULTILIB_BUILD
  ;;
  buildvala )
    export PKGNAME=vala
    export PKGVER=0.30.0
    unset MULTILIB_BUILD
  ;;
  buildatk )
    export PKGNAME=atk
    export PKGVER=2.18.0
    export CONFIGURE_FLAGS_32="--disable-introspection"
  ;;
  buildcairo )
    export PKGNAME=cairo
    export PKGVER=1.14.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/glib/${PKGVER:0:4}/${PKGTAR}"
    export CONFIGURE_FLAGS="--enable-tee"
    export CONFIGURE_FLAGS_32="--enable-tee"
    configure_post_32() {
      sed -i "/DIST_SUBDIRS/s:boilerplate test::" Makefile
      sed -i "/am__append_1/s:boilerplate test::" Makefile
    }
  ;;
  buildgdk-pixbuf )
    export PKGNAME=gdk-pixbuf
    export PKGVER=2.32.1
    export CONFIGURE_FLAGS="--with-x11 --with-libjasper"
    export CONFIGURE_FLAGS_32="--with-x11 --with-libjasper --disable-introspection"
    make_install_post_32() {
      export SPACE_ADDED=1
      mv dest/usr/bin/gdk-pixbuf-query-loaders ${DEST}/usr/bin/gdk-pixbuf-query-loaders-32
    }
export POSTINST_TRIGGER=("[ -x /usr/bin/gdk-pixbuf-query-loaders ] && echo \"Processing triggers for gdk-pixbuf-2.0\" && /usr/bin/gdk-pixbuf-query-loaders --update-cache"
                         "[ -x /usr/bin/gdk-pixbuf-query-loaders-32 ] && echo \"Processing triggers for gdk-pixbuf-2.0 (32 bit)\" && /usr/bin/gdk-pixbuf-query-loaders-32 --update-cache")
  ;;
  buildpango )
    export PKGNAME=pango
    export PKGVER=1.38.1
    export CONFIGURE_FLAGS_32="--disable-introspection"
  ;;
  buildat-spi2-core )
    export PKGNAME=at-spi2-core
    export PKGVER=2.18.1
    export CONFIGURE_FLAGS_32="--disable-introspection"
  ;;
  buildat-spi2-atk )
    export PKGNAME=at-spi2-atk
    export PKGVER=2.18.1
  ;;
  buildgtk2 )
    export PKGNAME=gtk+
    export PKGVER=2.24.28
    export CONFIGURE_FLAGS="--enable-man"
    export CONFIGURE_FLAGS_32="--disable-introspection"
    export POSTINST_TRIGGER=("[ -x /usr/bin/gtk-query-immodules-2.0 ] && echo \"Processing triggers for gtk-2.0\" && /usr/bin/gtk-query-immodules-2.0 --update-cache"
                             "[ -x /usr/bin/gtk-query-immodules-2.0-32 ] && echo \"Processing triggers for gtk-2.0 (32 bit)\" && /usr/bin/gtk-query-immodules-2.0-32 --update-cache")
    configure_pre() {
      sed -i 's#l \(gtk-.*\).sgml#& -o \1#' docs/{faq,tutorial}/Makefile.in
    }
    configure_pre_32() {
      sed -i 's#l \(gtk-.*\).sgml#& -o \1#' docs/{faq,tutorial}/Makefile.in
    }
    make_install_post() {
      rm -rf ${DEST}/usr/bin/gtk-update-icon-cache ${DEST}/usr/share/man/man1/gtk-update-icon-cache.1

cat > ${DEST}/usr/share/gtk-2.0/gtkrc << "EOF"
gtk-icon-theme-name = "Adwaita"
gtk-theme-name = "Adwaita"
gtk-font-name = "Cantarell 11"
EOF
    }
    make_install_post_32() {
      export SPACE_ADDED=1
      mv dest/usr/bin/gtk-query-immodules-2.0 ${DEST}/usr/bin/gtk-query-immodules-2.0-32
    }
  ;;
  buildgtk3 )
    export PKGNAME=gtk+
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS="--enable-broadway-backend --enable-wayland-backend --enable-x11-backend --enable-man"
    export CONFIGURE_FLAGS_32="${CONFIGURE_FLAGS} --disable-cloudprint --disable-introspection --disable-libcanberra"
    export POSTINST_TRIGGER=("[ -x /usr/bin/gtk-query-immodules-3.0 ] && echo \"Processing triggers for gtk-3.0\" && /usr/bin/gtk-query-immodules-3.0 --update-cache"
                             "[ -x /usr/bin/gtk-query-immodules-3.0-32 ] && echo \"Processing triggers for gtk-3.0 (32 bit)\" && /usr/bin/gtk-query-immodules-3.0-32 --update-cache")
    configure_post() {
      sed -i "/SRC_SUBDIRS/s# demos tests testsuite examples# tests#" Makefile
    }
    configure_post_32() {
      sed -i "/SRC_SUBDIRS/s# demos tests testsuite examples# tests#" Makefile
    }
    make_install_post() {
      rm -f ${DEST}/usr/share/man/man1/gtk3-*

cat > ${DEST}/usr/share/gtk-3.0/settings.ini << "EOF"
[Settings]
gtk-icon-theme-name = Adwaita
gtk-theme-name = Adwaita
gtk-font-name = Cantarell 11
EOF
    }
    make_install_post_32() {
      export SPACE_ADDED=1
      mv dest/usr/bin/gtk-query-immodules-3.0 ${DEST}/usr/bin/gtk-query-immodules-3.0-32
    }
  ;;
  buildcogl )
    export PKGNAME=cogl
    export PKGVER=1.22.0
    export CONFIGURE_FLAGS="--enable-gles1                \
                            --enable-gles2                \
                            --enable-wayland-egl-server   \
                            --enable-wayland-egl-platform \
                            --enable-kms-egl-platform     \
                            --enable-xlib-egl-platform"
    unset MULTILIB_BUILD
  ;;
  buildclutter )
    export PKGNAME=clutter
    export PKGVER=1.24.2
    export CONFIGURE_FLAGS="--enable-egl-backend        \
                            --enable-gdk-backend        \
                            --enable-wayland-backend    \
                            --enable-wayland-compositor \
                            --enable-x11-backend        \
                            --enable-evdev-input"
    unset MULTILIB_BUILD
  ;;
  buildclutter-gtk )
    export PKGNAME=clutter-gtk
    export PKGVER=1.6.6
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    unset MULTILIB_BUILD
  ;;
  buildclutter-gst )
    export PKGNAME=clutter-gst
    export PKGVER=3.0.14
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    unset MULTILIB_BUILD
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
if [ -z ${PKGURL} ]
then
  export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
fi

. $(dirname $0)/master.sh
