#!/bin/bash -e

export PKGNAME=libvdpau
export PKGVER=1.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://people.freedesktop.org/~aplattner/vdpau/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
