#!/bin/bash -e

export PKGNAME=mobile-broadband-provider-info
export PKGVER=20120614
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/mobile-broadband-provider-info/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
