#!/bin/bash -e

export PKGNAME=mpg123
export PKGVER=1.22.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/mpg123/"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--with-module-suffix=.so)
export CONFIGURE_FLAGS_32=(--with-module-suffix=.so --with-cpu=i586)

. $(dirname $0)/master.sh
