#!/bin/bash -e

export PKGNAME=highlight
export PKGVER=3.23
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.andre-simon.de/zip/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  sed -i "/TEMPLATE/a QT += widgets" src/gui-qt/highlight.pro
}

if [ -z $1 ]
then
  make_post() {
    make QMAKE=qmake gui ${MAKE_JOBS_FLAGS}
  }

  make_install_post() {
    make install-gui DESTDIR=${DEST}
  }
fi

post_install_config() {
  gzip -d ${DEST}/usr/share/man/man1/*.gz
}

. $(dirname $0)/master.sh
