#!/bin/bash -e

export PKGNAME=x264
export PKGVER=20150923
export PKGTAR=${PKGNAME}-snapshot-${PKGVER}-2245.tar.bz2
export PKGDIR=${PKGNAME}-snapshot-${PKGVER}-2245
export PKGURL="http://download.videolan.org/pub/videolan/x264/snapshots/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  ./configure --prefix=/usr    \
              --enable-shared  \
              --system-libx264
}

. $(dirname $0)/master.sh
