#!/bin/bash -e

export PKGNAME=murrine
export PKGVER=0.98.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/murrine/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-animation --enable-animationrtl)

. $(dirname $0)/master.sh
