#!/bin/bash -e

export PKGNAME=tar
export PKGVER=1.28
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/tar/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--bindir=/bin)

configure_pre() {
  export FORCE_UNSAFE_CONFIGURE=1
}

. $(dirname $0)/master.sh
