#!/bin/bash -e

export PKGNAME=openal-soft
export PKGVER=1.16.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://kcat.strangesoft.net/openal-releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export MULTILIB_BUILD=1
export CMAKE_FLAGS_32=(-DLIB_SUFFIX=32)

. $(dirname $0)/master.sh
