#!/bin/bash -e

export PKGNAME=libunique
export PKGVER=3.0.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/libunique/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
