#!/bin/bash -e

export PKGNAME=recode
export PKGVER=3.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export PATCHES_LIST=("recode-fixes.patch")
export CONFIGURE_FLAGS=(--without-included-gettext)

configure_pre() {
  rm -rf acinclude.m4
  autoreconf -fi
}

. $(dirname $0)/master.sh
