#!/bin/bash -e

export PKGNAME=qhull
export PKGVER=2012.1
export PKGTAR=${PKGNAME}-${PKGVER}-src.tgz
export PKGURL="http://www.qhull.org/download/${PKGVER}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

. $(dirname $0)/master.sh
