#!/bin/bash -e

export PKGNAME=libgusb
export PKGVER=0.2.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://people.freedesktop.org/~hughsient/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
