#!/bin/bash -e

export PKGNAME=openjpeg
export PKGVER=1.5.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/openjpeg.mirror/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done\n"
                    "cp -rf --remove-destination usr/share/man/man3 /usr/share/man")

configure_pre() {
  autoreconf -fi
}

. $(dirname $0)/master.sh
