#!/bin/bash -e

export PKGNAME=libebml
export PKGVER=1.3.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://dl.matroska.org/downloads/libebml/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
