#!/bin/bash -e

export PKGNAME=cgmanager
export PKGVER=0.39
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://linuxcontainers.org/downloads/cgmanager/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
