#!/bin/bash -e

export PKGNAME=iw
export PKGVER=4.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/software/network/iw/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  sed -i "s:-O2 -g:${CFLAGS}:g" Makefile

  unset CFLAGS
}

make_install_post() {
  gzip -d ${DEST}/usr/share/man/man8/*
}

. $(dirname $0)/master.sh
