#!/bin/bash -e

export PKGNAME=libmtp
export PKGVER=1.1.10
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/libmtp/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done\n"
                    "cp -rf --remove-destination lib /\n"
                    "udevadm hwdb --update")
export CONFIGURE_FLAGS=(--with-udev=/lib/udev)

. $(dirname $0)/master.sh
