#!/bin/bash -e

export PKGNAME=vte
export PKGVER=0.36.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/mate/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-introspection)

make_install_post() {
  rm -rf ${DEST}/etc
}

. $(dirname $0)/master.sh
