#!/bin/bash -e

export PKGNAME=libmng
export PKGVER=2.0.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/libmng/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
