#!/bin/bash -e

export PKGNAME=telepathy-glib
export PKGVER=0.24.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://telepathy.freedesktop.org/releases/telepathy-glib/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-vala-bindings)

. $(dirname $0)/master.sh
