#!/bin/bash -e

export PKGNAME=libimobiledevice
export PKGVER=1.2.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.libimobiledevice.org/downloads/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

. $(dirname $0)/master.sh
