#!/bin/bash -e

export VER=0.1.4
export DEST=/binary/lxmenu-data-${VER}

pushd lxmenu-data-${VER}

./configure --prefix=/usr --sysconfdir=/etc

make -j4
make install DESTDIR=${DEST}

popd

rm -rf lxmenu-data-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done
EOF

chmod 755 ${DEST}/INSTALL
