#!/bin/bash -e

export VER=0.403
export DEST=/binary/perl-extutils-depends-${VER}

pushd ExtUtils-Depends-${VER}


perl Makefile.PL INSTALLDIRS=vendor

make -j4
make install DESTDIR=${DEST}

popd

rm -rf ExtUtils-Depends-${VER}

rm -rf ${DEST}/usr/lib

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
