#!/bin/bash -e

export VER=0.5.1
export DEST=/binary/lxde-icon-theme-${VER}

pushd lxde-icon-theme-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf lxde-icon-theme-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for lxde-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/nuoveXT2
EOF

chmod 755 ${DEST}/INSTALL
