#!/bin/bash -e

export VER=1.8.1
export DEST=/binary/avr-libc-${VER}

pushd avr-libc-${VER}

CFLAGS="-O2 -pipe"   \
CXXFLAGS="-O2 -pipe" \
./configure --prefix=/usr \
            --host=avr    \
            --build=$(./config.guess)

make -j4
make install DESTDIR=${DEST}

popd

rm -rf avr-libc-${VER}

rm -rf ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
