#!/bin/bash -e

export VER=3.12.0
export DEST=/binary/gnome-icon-theme-symbolic-${VER}

pushd gnome-icon-theme-symbolic-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnome-icon-theme-symbolic-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for gnome-icon-theme-symbolic" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/gnome
EOF

chmod 755 ${DEST}/INSTALL
