#!/bin/bash -e

pkg_remove() {
  find * -type f -o -type l | while read file ; do rm -fv "/$file" ; done
  find * -type d | sort -r | while read file ; do rmdir --ignore-fail-on-non-empty -v "/$file" ; done
}

$(dirname $0)/buildfceux
$(dirname $0)/buildoctave
$(dirname $0)/buildpcsxr
$(dirname $0)/buildyoutube-dl
$(dirname $0)/buildlibmatekbd
$(dirname $0)/buildlibmatemixer
$(dirname $0)/buildlibmateweather
$(dirname $0)/buildmate-backgrounds
$(dirname $0)/buildmate-icon-theme
$(dirname $0)/buildmate-menus
$(dirname $0)/buildmate-themes
$(dirname $0)/buildmarco
$(dirname $0)/buildmate-panel
$(dirname $0)/buildmate-settings-daemon
$(dirname $0)/buildmate-control-center
$(dirname $0)/buildmate-applets
$(dirname $0)/buildmate-media
$(dirname $0)/buildmate-notification-daemon
$(dirname $0)/buildmate-polkit
$(dirname $0)/buildmate-power-manager
$(dirname $0)/buildmate-screensaver
$(dirname $0)/buildmate-screensaver-hacks
$(dirname $0)/buildmate-sensors-applet
$(dirname $0)/buildmate-session-manager
$(dirname $0)/buildmate-system-monitor
$(dirname $0)/buildmate-terminal
$(dirname $0)/buildmate-utils
$(dirname $0)/buildatril
$(dirname $0)/buildcaja-extensions
$(dirname $0)/buildengrampa
$(dirname $0)/buildpluma
$(dirname $0)/buildextra-cmake-modules
$(dirname $0)/buildkde-frameworks
$(dirname $0)/buildplasma
$(dirname $0)/buildbaloo-widgets
$(dirname $0)/buildkio-extras
$(dirname $0)/buildlibkdcraw
$(dirname $0)/buildlibkexiv2
$(dirname $0)/buildlibkipi
$(dirname $0)/buildlibksane
$(dirname $0)/buildsnorenotify
$(dirname $0)/buildokular
$(dirname $0)/buildark
$(dirname $0)/builddolphin
$(dirname $0)/buildgwenview
$(dirname $0)/buildkate
$(dirname $0)/buildkcalc
$(dirname $0)/buildkdebugsettings
$(dirname $0)/buildkid3
$(dirname $0)/buildkile
$(dirname $0)/buildkonsole
$(dirname $0)/buildksystemlog
$(dirname $0)/buildkwalletmanager
$(dirname $0)/buildquassel
$(dirname $0)/buildskanlite
$(dirname $0)/buildsmb4k
$(dirname $0)/buildspectacle
$(dirname $0)/buildsystemd-kcm
$(dirname $0)/buildkdepim-frameworks
$(dirname $0)/buildlibkgapi
$(dirname $0)/buildlibkolabxml
$(dirname $0)/buildlibkolab
$(dirname $0)/buildprison
$(dirname $0)/buildkdepim-runtime
$(dirname $0)/buildkdepim
$(dirname $0)/buildacpica
$(dirname $0)/buildbridge-utils
$(dirname $0)/buildcelt051
$(dirname $0)/builddnsmasq
$(dirname $0)/buildebtables
$(dirname $0)/buildlibcacard
$(dirname $0)/buildlibiscsi
$(dirname $0)/buildlibnih
$(dirname $0)/buildlibosinfo
$(dirname $0)/buildpython-ipaddr
$(dirname $0)/buildpython-pyparsing
$(dirname $0)/buildpython-requests
$(dirname $0)/buildradvd
$(dirname $0)/buildspice-protocol
$(dirname $0)/buildusbredir
$(dirname $0)/buildvde2
$(dirname $0)/buildyajl
$(dirname $0)/buildcgmanager
$(dirname $0)/buildspice
$(dirname $0)/buildspice-gtk
$(dirname $0)/buildlxc
$(dirname $0)/buildqemu
$(dirname $0)/buildlibvirt
$(dirname $0)/buildlibvirt-glib
$(dirname $0)/buildlibvirt-python
$(dirname $0)/buildseabios
$(dirname $0)/buildvirt-manager
$(dirname $0)/buildvirt-viewer
$(dirname $0)/buildchromium
$(dirname $0)/buildchromium-pepper-flash
$(dirname $0)/buildlibreoffice
$(dirname $0)/buildwine
$(dirname $0)/buildtexlive

pushd /binary
  tar xf libkpathsea-[0-9]*.tar.xz
  rm -f libkpathsea-[0-9]*.tar.xz
popd

pushd /binary/libkpathsea-[0-9]*
  pkg_remove
popd

rm -rf /binary/libkpathsea-[0-9]*

pushd /binary/texlive-[0-9]*
  ./INSTALL
popd

$(dirname $0)/builddblatex

find /binary -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

find /binary -type d -name "*-[0-9]*" ! -path "*/etc/*" ! -path "*/usr/*" | while read dir
do
  P=$(basename ${dir})
  D=$(dirname ${dir})

  pushd ${D}
    tar cf ${P}.tar ${P}
    rm -rf ${P}
  popd
done

find /binary -name "*.tar" -exec xz -T4 {} \;
