#!/bin/bash -e

pkg_remove() {
  find * -type f -o -type l | while read file ; do rm -fv "/$file" ; done
  find * -type d | sort -r | while read file ; do rmdir --ignore-fail-on-non-empty -v "/$file" ; done
}

export PKG_AUTO_INSTALL=1

$(dirname $0)/builddjvulibre
$(dirname $0)/buildexiv2
$(dirname $0)/buildfribidi
$(dirname $0)/buildijs
$(dirname $0)/buildlibexif
$(dirname $0)/buildlibgd
$(dirname $0)/buildlibraw
$(dirname $0)/buildopenjpeg2
$(dirname $0)/buildghostscript
$(dirname $0)/buildlibgphoto2
$(dirname $0)/buildpoppler
$(dirname $0)/buildgraphviz
$(dirname $0)/buildImageMagick
$(dirname $0)/buildlibcddb
$(dirname $0)/buildlibdvdread
$(dirname $0)/buildv4l-utils
$(dirname $0)/buildchromaprint
$(dirname $0)/buildfdk-aac
$(dirname $0)/buildlame
$(dirname $0)/buildlibass
$(dirname $0)/buildlibbluray
$(dirname $0)/buildlibcanberra
$(dirname $0)/buildlibcdio
$(dirname $0)/buildlibdca
$(dirname $0)/buildlibdvdcss
$(dirname $0)/buildlibdvdnav
$(dirname $0)/buildlibiec61883
$(dirname $0)/buildlibmtp
$(dirname $0)/buildlibnfs
$(dirname $0)/buildlibshout
$(dirname $0)/buildlibssh
$(dirname $0)/buildluajit
$(dirname $0)/buildneon
$(dirname $0)/buildtaglib
$(dirname $0)/buildvo-aacenc
$(dirname $0)/buildvo-amrwbenc
$(dirname $0)/buildwavpack
$(dirname $0)/buildx264
$(dirname $0)/buildx265
$(dirname $0)/buildxvidcore
$(dirname $0)/buildlibcdio-paranoia
$(dirname $0)/buildffmpeg

$(dirname $0)/buildx264

$(dirname $0)/buildmpv
$(dirname $0)/buildVulkan-Docs
$(dirname $0)/buildvulkan-runtime
$(dirname $0)/buildgst-plugins-good
$(dirname $0)/buildgst-plugins-bad
$(dirname $0)/buildgst-plugins-ugly
$(dirname $0)/buildgst-libav
$(dirname $0)/buildgstreamer-vaapi
$(dirname $0)/buildlibassuan
$(dirname $0)/buildlibksba
$(dirname $0)/buildnpth
$(dirname $0)/buildpkcs11-helper
$(dirname $0)/buildpth
$(dirname $0)/buildgnupg
$(dirname $0)/buildgcr
$(dirname $0)/buildgpgme
$(dirname $0)/buildopenssh
$(dirname $0)/buildpinentry
$(dirname $0)/buildmedia-player-info
$(dirname $0)/buildmobile-broadband-provider-info
$(dirname $0)/buildlibplist
$(dirname $0)/buildlibusbmuxd
$(dirname $0)/buildlibimobiledevice
$(dirname $0)/buildcmrt
$(dirname $0)/buildlibatasmart
$(dirname $0)/buildlm_sensors
$(dirname $0)/buildmozjs24
$(dirname $0)/buildparted
$(dirname $0)/buildxapian-core
$(dirname $0)/buildalsa-plugins
$(dirname $0)/buildalsa-utils
$(dirname $0)/builddoxygen
$(dirname $0)/buildudisks
$(dirname $0)/buildupower
$(dirname $0)/buildwebkitgtk

find /binary -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

find /binary -type d -name "*-[0-9]*" ! -path "*/etc/*" ! -path "*/usr/*" | while read dir
do
  P=$(basename ${dir})
  D=$(dirname ${dir})

  pushd ${D}
    tar cf ${P}.tar ${P}
    rm -rf ${P}
  popd
done

find /binary -name "*.tar" -exec xz -T4 {} \;
