#!/bin/bash -e

pkg_remove() {
  find * -type f -o -type l | while read file ; do rm -fv "/$file" ; done
  find * -type d | sort -r | while read file ; do rmdir --ignore-fail-on-non-empty -v "/$file" ; done
}

export PKG_AUTO_INSTALL=1

$(dirname $0)/buildlinux-api-headers
$(dirname $0)/buildglibc
$(dirname $0)/buildtzdata

{
  mv -v /tools/bin/{ld,ld-old}
  mv -v /tools/bin/{ld-new,ld}

  gcc -dumpspecs | sed -e 's@/tools@@g'                   \
      -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
      -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' >      \
      `dirname $(gcc --print-libgcc-file-name)`/specs

  for L in bs_BA en_US hr_HR
  do
    sed -i "s:^#${L}:${L}:g" /etc/locale.gen
  done

  locale-gen
}

$(dirname $0)/buildzlib
$(dirname $0)/buildfile
$(dirname $0)/buildm4
$(dirname $0)/buildbison
$(dirname $0)/buildflex
$(dirname $0)/buildattr
$(dirname $0)/buildacl
$(dirname $0)/buildsed
$(dirname $0)/buildbinutils
$(dirname $0)/buildgmp
$(dirname $0)/buildmpfr
$(dirname $0)/buildmpc
$(dirname $0)/buildgcc
$(dirname $0)/buildpkg-config
$(dirname $0)/buildncurses
$(dirname $0)/buildutil-linux
$(dirname $0)/builde2fsprogs
$(dirname $0)/buildprocps-ng
$(dirname $0)/buildbzip2
$(dirname $0)/buildreadline
$(dirname $0)/buildxz
$(dirname $0)/buildbc
$(dirname $0)/buildpsmisc
$(dirname $0)/buildcracklib
$(dirname $0)/buildopenssl
$(dirname $0)/buildpcre
$(dirname $0)/buildtcl
$(dirname $0)/buildbdb
$(dirname $0)/buildpam
$(dirname $0)/buildlibcap
$(dirname $0)/buildbash
$(dirname $0)/buildcoreutils
$(dirname $0)/buildgrep
$(dirname $0)/buildexpat
$(dirname $0)/buildshadow
$(dirname $0)/buildgdbm
$(dirname $0)/buildlibffi
$(dirname $0)/buildlibtool
$(dirname $0)/buildsqlite
$(dirname $0)/buildhostname
$(dirname $0)/buildrun-parts
$(dirname $0)/buildwhich
$(dirname $0)/buildperl
$(dirname $0)/buildpython2
$(dirname $0)/buildpython3
$(dirname $0)/buildautoconf
$(dirname $0)/buildautoconf2.13
$(dirname $0)/buildautomake
$(dirname $0)/builddiffutils
$(dirname $0)/buildfindutils
$(dirname $0)/buildgawk
$(dirname $0)/buildgperf
$(dirname $0)/buildgroff
$(dirname $0)/buildgzip
$(dirname $0)/buildmake
$(dirname $0)/buildpatch
$(dirname $0)/buildtar
$(dirname $0)/buildtexinfo
$(dirname $0)/buildcheck
$(dirname $0)/buildlibmnl
$(dirname $0)/buildlibnftnl
$(dirname $0)/buildiptables
$(dirname $0)/buildless
$(dirname $0)/buildlibpipeline
$(dirname $0)/buildiproute2
$(dirname $0)/buildkbd
$(dirname $0)/buildkmod
$(dirname $0)/buildman-db
$(dirname $0)/buildnano
$(dirname $0)/buildunzip
$(dirname $0)/buildzip
$(dirname $0)/buildperl-modules 1
$(dirname $0)/buildicu
$(dirname $0)/buildboost
$(dirname $0)/buildlibgpg-error
$(dirname $0)/buildlibgcrypt
$(dirname $0)/buildlibidn
$(dirname $0)/buildlibunistring
$(dirname $0)/buildlibxml2
$(dirname $0)/buildlibxslt
$(dirname $0)/buildlua
$(dirname $0)/buildhighlight 1
$(dirname $0)/buildca-certificates
$(dirname $0)/buildwget
$(dirname $0)/builddocbook-xml
$(dirname $0)/builddocbook-xsl
$(dirname $0)/buildintltool
$(dirname $0)/builditstool
$(dirname $0)/buildxmlto
$(dirname $0)/buildsgml-common
$(dirname $0)/builddocbook
$(dirname $0)/builddocbook-dsssl
$(dirname $0)/buildOpenSP
$(dirname $0)/buildopenjade
$(dirname $0)/builddocbook-utils
$(dirname $0)/buildasciidoc
$(dirname $0)/buildgtk-doc
$(dirname $0)/buildglib2
$(dirname $0)/buildlibcroco
$(dirname $0)/buildgettext
$(dirname $0)/buildpython-modules 1
$(dirname $0)/buildelfutils
$(dirname $0)/buildgobject-introspection
$(dirname $0)/buildlibaio
$(dirname $0)/buildlibatomic_ops
$(dirname $0)/buildlibcap-ng
$(dirname $0)/buildlibpng
$(dirname $0)/buildlibssh2
$(dirname $0)/buildlibtasn1
$(dirname $0)/buildlibuv
$(dirname $0)/buildlz4
$(dirname $0)/buildlzo
$(dirname $0)/buildnettle
$(dirname $0)/buildnspr
$(dirname $0)/buildnss
$(dirname $0)/buildp11-kit
$(dirname $0)/buildpopt
$(dirname $0)/buildrtmpdump
$(dirname $0)/buildvala
$(dirname $0)/buildcurl
$(dirname $0)/buildfreetype
$(dirname $0)/buildfontconfig
$(dirname $0)/buildgc
$(dirname $0)/buildgnutls
$(dirname $0)/buildlibarchive
$(dirname $0)/buildlibmicrohttpd
$(dirname $0)/buildpixman
$(dirname $0)/buildsystemd
$(dirname $0)/buildlibgudev
$(dirname $0)/buildLVM2
$(dirname $0)/buildcryptsetup

pushd /binary/systemd-[0-9]*
  pkg_remove
popd

cp -rfv /binary/systemd-[0-9]*/lib/*.so.* /lib

$(dirname $0)/buildsystemd

pushd /binary/util-linux-[0-9]*
  pkg_remove
popd

$(dirname $0)/buildutil-linux

$(dirname $0)/buildxorg-proto
$(dirname $0)/buildutil-macros
$(dirname $0)/buildxorg-lib
$(dirname $0)/buildxorg-xcb-util
$(dirname $0)/buildchrpath
$(dirname $0)/buildcmake 1
$(dirname $0)/builddbus
$(dirname $0)/builddbus-glib
$(dirname $0)/builddbus-python
$(dirname $0)/buildefivar
$(dirname $0)/buildguile
$(dirname $0)/buildhtop
$(dirname $0)/buildiana-etc
$(dirname $0)/buildlibedit
$(dirname $0)/buildlibevent
$(dirname $0)/buildlibgnome-keyring
$(dirname $0)/buildlibical
$(dirname $0)/buildlibusb
$(dirname $0)/buildlibusb-compat
$(dirname $0)/buildman-pages
$(dirname $0)/buildnasm
$(dirname $0)/buildpciutils
$(dirname $0)/buildscons
$(dirname $0)/buildswig
$(dirname $0)/buildtk
$(dirname $0)/buildunixODBC
$(dirname $0)/buildusbutils
$(dirname $0)/buildwayland
$(dirname $0)/buildwayland-protocols
$(dirname $0)/buildyaml
$(dirname $0)/buildyasm
$(dirname $0)/buildruby
$(dirname $0)/buildcyrus-sasl
$(dirname $0)/buildopenldap
$(dirname $0)/buildkrb5

pushd /binary/curl-[0-9]*
  pkg_remove
popd

$(dirname $0)/buildcurl
$(dirname $0)/buildapr
$(dirname $0)/buildapr-util
$(dirname $0)/buildbluez
$(dirname $0)/buildgit
$(dirname $0)/buildserf

pushd /binary/python/Python-2.[0-9]*
  pkg_remove
popd

$(dirname $0)/buildpython2

pushd /binary/python/Python-3.[0-9]*
  pkg_remove
popd

$(dirname $0)/buildpython3

$(dirname $0)/buildsubversion
$(dirname $0)/buildllvm
$(dirname $0)/buildintel-ucode
$(dirname $0)/buildlsb-release
$(dirname $0)/buildfuse
$(dirname $0)/buildntfs-3g
$(dirname $0)/buildkernel
$(dirname $0)/buildefibootmgr
$(dirname $0)/buildsyslinux

find /binary -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

find /binary -type d -name "*-[0-9]*" ! -path "*/etc/*" ! -path "*/usr/*" | while read dir
do
  P=$(basename ${dir})
  D=$(dirname ${dir})

  pushd ${D}
    tar cf ${P}.tar ${P}
    rm -rf ${P}
  popd
done

find /binary -name "*.tar" -exec xz -T4 {} \;
