#!/bin/bash -e

pkg_remove() {
  find * -type f -o -type l | while read file ; do rm -fv "/$file" ; done
  find * -type d | sort -r | while read file ; do rmdir --ignore-fail-on-non-empty -v "/$file" ; done
}

export PKG_AUTO_INSTALL=1

$(dirname $0)/buildfceux
$(dirname $0)/buildpcsxr
$(dirname $0)/buildyoutube-dl
$(dirname $0)/buildkde-frameworks
$(dirname $0)/buildplasma
$(dirname $0)/buildadwaita-qt
$(dirname $0)/buildQGnomePlatform
$(dirname $0)/buildbaloo-widgets
$(dirname $0)/buildkio-extras
$(dirname $0)/buildlibkdcraw
$(dirname $0)/buildlibkexiv2
$(dirname $0)/buildlibkipi
$(dirname $0)/buildsnorenotify
$(dirname $0)/buildokular
$(dirname $0)/buildark
$(dirname $0)/builddolphin
$(dirname $0)/buildgwenview
$(dirname $0)/buildkate
$(dirname $0)/buildkcalc
$(dirname $0)/buildkdebugsettings
$(dirname $0)/buildkhelpcenter
$(dirname $0)/buildkid3
$(dirname $0)/buildkile
$(dirname $0)/buildkonsole
$(dirname $0)/buildksystemlog
$(dirname $0)/buildkwalletmanager
$(dirname $0)/buildquassel
$(dirname $0)/buildsmb4k
$(dirname $0)/buildspectacle
$(dirname $0)/buildsystemd-kcm
$(dirname $0)/buildkdepim-frameworks
$(dirname $0)/buildlibkolabxml
$(dirname $0)/buildlibkolab
$(dirname $0)/buildprison
$(dirname $0)/buildkdepim-runtime
$(dirname $0)/buildkdepim
$(dirname $0)/buildkleopatra
$(dirname $0)/buildacpica
$(dirname $0)/buildlibiscsi
$(dirname $0)/buildusbredir
$(dirname $0)/buildvde2
$(dirname $0)/buildvirglrenderer
$(dirname $0)/buildseabios
$(dirname $0)/buildqemu
$(dirname $0)/buildlibreoffice-upstream
$(dirname $0)/buildwine
$(dirname $0)/buildtexlive

pushd /binary
  tar xf libkpathsea-[0-9]*.tar.xz
  rm -f libkpathsea-[0-9]*.tar.xz
popd

pushd /binary/libkpathsea-[0-9]*
  pkg_remove
popd

rm -rf /binary/libkpathsea-[0-9]*

pushd /binary/texlive-[0-9]*
  ./INSTALL
popd

$(dirname $0)/builddblatex

find /binary -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

find /binary -type d -name "*-[0-9]*" ! -path "*/etc/*" ! -path "*/opt/*" ! -path "*/usr/*" | while read dir
do
  P=$(basename ${dir})
  D=$(dirname ${dir})

  pushd ${D}
    tar cf ${P}.tar ${P}
    rm -rf ${P}
  popd
done

find /binary -name "*.tar" -exec xz -T4 {} \;
