#!/bin/bash -e

export PKGNAME=v4l-utils
export PKGVER=1.10.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.linuxtv.org/downloads/v4l-utils/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export DEFAULT_CXX="clang++ -std=c++11"

configure_pre() {
  sed -i "/unistd.h/i #include <ctime>" utils/v4l2-ctl/v4l2-ctl-streaming.cpp utils/rds-ctl/rds-ctl.cpp
}
make_install_post() {
  rm -rf ${DEST}/usr/bin/ivtv-ctl ${DEST}/usr/sbin
}

. $(dirname $0)/master.sh
