#!/bin/bash -e

export VER=8.6.9
export DEST=/binary/asciidoc-${VER}

pushd asciidoc-${VER}

./configure --prefix=/usr --sysconfdir=/etc

make -j4
make install DESTDIR=${DEST}

popd

rm -rf asciidoc-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
