#!/bin/bash -e

export PKGNAME=pixman
export PKGVER=0.32.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://cairographics.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export MULTILIB_BUILD=1
export PATCHES_LIST=("pixman-clang.patch")
export PATCHES_LIST_32=("pixman-clang.patch")
export CONFIGURE_FLAGS=(--disable-gtk --disable-libpng)
export CONFIGURE_FLAGS_32=(--disable-gtk --disable-libpng)

configure_pre() {
  autoreconf -fi
  sed -i "s:fopenmp:&=libgomp:g" configure
}

configure_pre_32() {
  autoreconf -fi
  sed -i "s:fopenmp:&=libgomp:g" configure
}

. $(dirname $0)/master.sh
