#!/bin/bash -e

export VER=20150619
export DEST=/binary/acpica-${VER}

pushd acpica-unix-${VER}/generate/unix

sed -i "/OPT_CFLAGS/s:-O2:-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong:" Makefile.config

make -j4
make install DESTDIR=${DEST}

popd

rm -rf acpica-unix-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
