#!/bin/bash -e

export PKGNAME=libkate
export PKGVER=0.4.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://libkate.googlecode.com/files/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

export DEFAULT_CC="clang"

configure_pre() {
  export LEXLIB=/usr/lib/libfl.a
}

. $(dirname $0)/master.sh
