#!/bin/bash -e

export PKGNAME=xfsprogs
export PKGVER=4.8.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_INSTALL_FLAGS="install-dev"

configure_override() {
  true
}

make_override() {
  export OPTIMIZER="${CFLAGS}"
  unset CFLAGS

  make DEBUG=-DNDEBUG     \
       INSTALL_USER=root  \
       INSTALL_GROUP=root \
       LOCAL_CONFIGURE_OPTIONS="--enable-readline --disable-lib64" \
       V=1 ${MAKE_JOBS_FLAGS}
}

make_install_post() {
  ln -sf ../../lib/$(readlink ${DEST}/lib/libhandle.so) ${DEST}/usr/lib/libhandle.so
  rm -rf ${DEST}/lib/libhandle.a ${DEST}/usr/lib/libhandle.a ${DEST}/lib/libhandle.so
}

. $(dirname $0)/master.sh
