#!/bin/bash -e

export VER=1.3.3
export DEST=/binary/fltk-${VER}

pushd fltk-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/fltk-fixes.patch

sed -i "s:class Fl_XFont_On_Demand:class FL_EXPORT Fl_XFont_On_Demand:g" FL/x.H

sed -i "/cat./d" documentation/Makefile

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --enable-shared

make -j4
make install DESTDIR=${DEST}

popd

rm -rf fltk-${VER}

find ${DEST} -name "*.a" -delete

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
