#!/bin/bash -e

export VER=1.0.70
export DEST=/binary/cups-filters-${VER}

pushd cups-filters-${VER}

sed -i "s:cups.service:org.cups.cupsd.service:g" utils/cups-browsed.service

# Uses libpoppler.so
CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr              \
            --sysconfdir=/etc          \
            --localstatedir=/var       \
            --disable-static           \
            --without-rcdir            \
            --with-gs-path=/usr/bin/gs \
            --with-pdftops-path=/usr/bin/gs

make -j4
make install DESTDIR=${DEST}

install -Dm644 utils/cups-browsed.service ${DEST}/lib/systemd/system/cups-browsed.service

popd

rm -rf ${DEST}/usr/share/doc

mkdir -p ${DEST}/etc/systemd/system/multi-user.target.wants

ln -sf /lib/systemd/system/cups-browsed.service ${DEST}/etc/systemd/system/multi-user.target.wants/cups-browsed.service

rm -rf cups-filters-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
