#!/bin/bash -e

export PKGNAME=elfutils
export PKGVER=0.167
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://fedorahosted.org/releases/e/l/elfutils/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export CONFIGURE_FLAGS=(--program-prefix="eu-")
export DEFAULT_CC="gcc"
export DEFAULT_CXX="g++"

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libdw.so.* ${DEST}/usr/lib/libdw-*.so ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libdw.so) ${DEST}/usr/lib/libdw.so

  mv ${DEST}/usr/lib/libelf.so.* ${DEST}/usr/lib/libelf-*.so ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libelf.so) ${DEST}/usr/lib/libelf.so
}

. $(dirname $0)/master.sh
