#!/bin/bash -e

export PKGNAME=libevdev
export PKGVER=1.4.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://freedesktop.org/software/libevdev/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
