#!/bin/bash -e

export VER=2.09
export DEST=/binary/lzo-${VER}

pushd lzo-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr   \
            --enable-shared \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf lzo-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/liblzo2.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/liblzo2.so) ${DEST}/usr/lib/liblzo2.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
