#!/bin/bash -e

export PKGNAME=accountsservice
export PKGVER=0.6.40
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.freedesktop.org/software/accountsservice/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export CONFIGURE_FLAGS=(--enable-admin-group=adm)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

make_install_post() {
  install -dm755 ${DEST}/etc/systemd/system/graphical.target.wants

  ln -sf /lib/systemd/system/accounts-daemon.service ${DEST}/etc/systemd/system/graphical.target.wants/accounts-daemon.service
}

. $(dirname $0)/master.sh
