#!/bin/bash -e

export PKGNAME=taglib
export PKGVER=1.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://taglib.github.io/releases/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export MULTILIB_BUILD=1
export CMAKE_FLAGS_32=(-DLIB_SUFFIX=32)

. $(dirname $0)/master.sh
