#!/bin/bash -e

export PKGNAME=game-music-emu
export PKGVER=0.6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://bitbucket.org/mpyne/game-music-emu/downloads/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
