#!/bin/bash -e

export VER=5.2.5
export DEST=/binary/whois-${VER}

pushd whois-${VER}

make CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
     CONFIG_FILE=/etc/whois.conf \
     HAVE_LIBIDN=1 HAVE_ICONV=1 -j4

make prefix=/usr BASEDIR=${DEST} install-whois

install -Dm644 whois.conf ${DEST}/etc/whois.conf

popd

rm -rf whois-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
