#!/bin/bash -e

export VER=4.2.6p5
export DEST=/binary/ntp-${VER}

pushd ntp-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr      \
            --sysconfdir=/etc  \
            --enable-linuxcaps \
            --with-lineeditlibs=readline

make -j4
make install DESTDIR=${DEST}

rm -rf ${DEST}/usr/lib ${DEST}/usr/share/man/*

pushd html
../scripts/html2man
popd

mv html/man/* ${DEST}/usr/share/man

popd

rm -rf ntp-${VER}

for file in ntpd ntpdate ntp-keygen ntptime ntp-wait tickadj
do
  mv ${DEST}/usr/bin/${file} ${DEST}/usr/sbin/
done

install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants \
               ${DEST}/lib/systemd/system \
               ${DEST}/usr/lib/systemd/ntp-units.d

echo 'ntpd.service' > ${DEST}/usr/lib/systemd/ntp-units.d/ntp.list

cat > ${DEST}/etc/ntp.conf << "EOF"
# /etc/ntp.conf, configuration for ntpd; see ntp.conf(5) for help

driftfile /var/lib/ntp/ntp.drift

# Enable this if you want statistics to be logged.
#statsdir /var/log/ntpstats/

statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable

# You do need to talk to an NTP server or two (or three).
#server ntp.your-provider.example

# pool.ntp.org maps to about 1000 low-stratum NTP servers.  Your server will
# pick a different set every time it starts up.  Please consider joining the
# pool: <http://www.pool.ntp.org/join.html>
server 0.europe.pool.ntp.org
server 1.europe.pool.ntp.org
server 2.europe.pool.ntp.org
server 3.europe.pool.ntp.org


# Access control configuration; see /usr/share/doc/ntp-doc/html/accopt.html for
# details.  The web page <http://support.ntp.org/bin/view/Support/AccessRestrictions>
# might also be helpful.
#
# Note that "restrict" applies to both servers and clients, so a configuration
# that might be intended to block requests from certain clients could also end
# up blocking replies from your own upstream servers.

# By default, exchange time with everybody, but don't allow configuration.
restrict -4 default kod notrap nomodify nopeer noquery
restrict -6 default kod notrap nomodify nopeer noquery

# Local users may interrogate the ntp server more closely.
restrict 127.0.0.1
restrict ::1

# Clients from this (example!) subnet have unlimited access, but only if
# cryptographically authenticated.
#restrict 192.168.123.0 mask 255.255.255.0 notrust


# If you want to provide time to your local subnet, change the next line.
# (Again, the address is an example only.)
#broadcast 192.168.123.255

# If you want to listen to time broadcasts on your local subnet, de-comment the
# next lines.  Please do this only if you trust everybody on the network!
#disable auth
#broadcastclient
EOF

cat > ${DEST}/lib/systemd/system/ntpd.service << "EOF"
[Unit]
Description=Network Time Protocol daemon
After=network.target nss-lookup.target

[Service]
Type=forking
PrivateTmp=true
ExecStart=/usr/sbin/ntpd -g -u ntp:ntp

[Install]
WantedBy=multi-user.target
EOF

ln -sf /lib/systemd/system/ntpd.service ${DEST}/etc/systemd/system/multi-user.target.wants/ntpd.service

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group ntp > /dev/null || groupadd -g 87 ntp
getent passwd ntp > /dev/null || useradd -c "Network Time Protocol" -d /var/lib/ntp -g ntp -s /bin/false -u 87 ntp

install -dm755 -o ntp -g ntp /var/lib/ntp

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
