#!/bin/bash -e

export PKGNAME=libosinfo
export PKGVER=0.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://fedorahosted.org/releases/l/i/libosinfo/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
