#!/bin/bash -e

export VER=2.9.2
export DEST=/binary/cracklib-${VER}

pushd cracklib-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf cracklib-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/libcrack.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libcrack.so) ${DEST}/usr/lib/libcrack.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL

