#!/bin/bash -e

export PKGNAME=libepoxy
export PKGVER=1.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
