#!/bin/bash -e

export PKGNAME=firefox
export PKGVER=49.0
export PKGTAR=${PKGNAME}-${PKGVER}.source.tar.xz
export PKGURL="https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/${PKGVER}/source/${PKGTAR}"
export NO_OPTIMIZATION=1

export MOZ_PATH="$(dirname $(realpath $0))"

configure_override() {
  sed -i "s:-\$(MOZ_APP_VERSION)::g" config/baseconfig.mk

cat > mozconfig << "EOF"
ac_add_options --enable-application=browser

ac_add_options --prefix=/usr
ac_add_options --enable-release
ac_add_options --enable-gold
ac_add_options --enable-pie

ac_add_options --with-system-bz2
ac_add_options --with-system-icu
ac_add_options --with-system-jpeg
ac_add_options --with-system-libevent
ac_add_options --with-system-libvpx
ac_add_options --with-system-nspr
ac_add_options --with-system-nss
ac_add_options --with-system-png
ac_add_options --with-system-zlib

#ac_add_options --enable-system-cairo
ac_add_options --enable-system-ffi
ac_add_options --enable-system-hunspell
ac_add_options --enable-system-pixman
ac_add_options --enable-system-sqlite

ac_add_options --enable-install-strip
ac_add_options --enable-strip

ac_add_options --enable-gio
ac_add_options --enable-official-branding
ac_add_options --enable-pulseaudio
ac_add_options --enable-safe-browsing
ac_add_options --enable-startup-notification
ac_add_options --enable-update-channel=release
ac_add_options --enable-url-classifier

ac_add_options --disable-gconf
ac_add_options --disable-gnomeui

ac_add_options --disable-crashreporter
ac_add_options --disable-debug
ac_add_options --disable-tests
ac_add_options --disable-updater

export MOZ_ADDON_SIGNING=1
export MOZ_REQUIRE_SIGNING=1
export MOZILLA_OFFICIAL=1
EOF
}

make_override() {
  make -f client.mk
}

make_install_override() {
  make -f client.mk install DESTDIR=${DEST} INSTALL_SDK=

  install -Dm644 ${MOZ_PATH}/../misc/firefox.desktop ${DEST}/usr/share/applications/firefox.desktop

  for i in 16 22 24 32 48 256
  do
    install -Dm644 browser/branding/official/default$i.png ${DEST}/usr/share/icons/hicolor/${i}x${i}/apps/firefox.png
  done

  install -Dm644 browser/branding/official/content/icon64.png ${DEST}/usr/share/icons/hicolor/64x64/apps/firefox.png
  install -Dm644 browser/branding/official/mozicon128.png ${DEST}/usr/share/icons/hicolor/128x128/apps/firefox.png
  install -Dm644 browser/branding/official/content/about-logo.png ${DEST}/usr/share/icons/hicolor/192x192/apps/firefox.png
  install -Dm644 browser/branding/official/content/about-logo@2x.png ${DEST}/usr/share/icons/hicolor/384x384/apps/firefox.png

  rm -rf ${DEST}/usr/lib/firefox/dictionaries
  ln -sf ../../share/hunspell ${DEST}/usr/lib/firefox/dictionaries

  install -dm755 ${DEST}/usr/lib/firefox/browser/defaults/preferences

cat > ${DEST}/usr/lib/firefox/browser/defaults/preferences/vendor.js << "EOF"
// Use LANG environment variable to choose locale
pref("intl.locale.matchOS", true);

// Disable default browser checking.
pref("browser.shell.checkDefaultBrowser", false);
EOF
}

. $(dirname $0)/master.sh
