#!/bin/bash -e

export PKGNAME=extra-cmake-modules
export PKGVER=5.20.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.kde.org/stable/frameworks/${PKGVER:0:4}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export NO_STRIP=1

. $(dirname $0)/master.sh
