#!/bin/bash -e

export VER=2.1.0
export DEST=/binary/cups-${VER}

pushd cups-${VER}

sed -i "/MAN.*.EXT/s:.gz::g" configure config-scripts/cups-manpages.m4
sed -i "s:555:755:g;s:444:644:g" Makedefs.in

cat > conf/pam.std.in << "EOF"
# Begin /etc/pam.d/cups

auth    include system-auth
account include system-account
session include system-session

# End /etc/pam.d/cups
EOF

popd

cp -a cups-${VER} cups-${VER}-32

pushd cups-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --libdir=/usr/lib                 \
            --with-rcdir=/tmp/cupsinit        \
            --with-docdir=/usr/share/cups/doc \
            --with-system-groups=lpadmin      \
            --with-icondir=/usr/share/icons   \
            --with-menudir=/usr/share/applications

make -j4
make install BUILDROOT=${DEST}

popd

pushd cups-${VER}-32

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --libdir=/usr/lib32 \
            --disable-libusb    \
            --disable-avahi     \
            --disable-dbus      \
            --disable-pam

make libs -j4
make install-libs BUILDROOT=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf cups-${VER} cups-${VER}-32

rm -f ${DEST}/etc/cups/*.default ${DEST}/usr/share/cups/banners/* ${DEST}/usr/share/cups/data/testprint
rm -rf ${DEST}/tmp ${DEST}/var/run

perl -p -i -e 's:^(.*\s+bannertops\s*)$:#\1:' ${DEST}/usr/share/cups/mime/mime.convs

touch ${DEST}/etc/cups/classes.conf ${DEST}/etc/cups/printers.conf ${DEST}/etc/cups/subscriptions.conf

cat > ${DEST}/etc/cups/client.conf << "EOF"
# see 'man client.conf'
ServerName /var/run/cups/cups.sock
EOF

chmod 600 ${DEST}/etc/cups/classes.conf ${DEST}/etc/cups/printers.conf
chmod 640 ${DEST}/etc/cups/subscriptions.conf

install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants \
               ${DEST}/etc/systemd/system/printer.target.wants    \
               ${DEST}/etc/systemd/system/sockets.target.wants

ln -sf /lib/systemd/system/org.cups.cupsd.path ${DEST}/etc/systemd/system/multi-user.target.wants/org.cups.cupsd.path
ln -sf /lib/systemd/system/org.cups.cupsd.service ${DEST}/etc/systemd/system/printer.target.wants/org.cups.cupsd.service
ln -sf /lib/systemd/system/org.cups.cupsd.socket ${DEST}/etc/systemd/system/sockets.target.wants/org.cups.cupsd.socket

chgrp -R lp ${DEST}/etc/cups

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

getent group lpadmin > /dev/null || groupadd -g 19 lpadmin

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
