#!/bin/bash -e

export VER=2.30
export DEST=/binary/iana-etc-${VER}

pushd iana-etc-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/iana-etc-fixes.patch

make get
make

make install DESTDIR=${DEST}

popd

rm -rf iana-etc-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination etc /
EOF

chmod 755 ${DEST}/INSTALL
