#!/bin/bash -e

export VER=3.0.0
export DEST=/binary/freeglut-${VER}

cp -a freeglut-${VER} freeglut-${VER}-32

pushd freeglut-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DCMAKE_INSTALL_LIBDIR=lib       \
      -DFREEGLUT_BUILD_STATIC_LIBS=OFF \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"

make -j4
make install DESTDIR=${DEST}

popd

pushd freeglut-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DCMAKE_INSTALL_LIBDIR=lib32     \
      -DFREEGLUT_BUILD_STATIC_LIBS=OFF \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf freeglut-${VER} freeglut-${VER}-32

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
