#!/bin/bash -e

export PKGNAME=ncftp
export PKGVER=3.2.5
export PKGTAR=${PKGNAME}-${PKGVER}-src.tar.bz2
export PKGURL="ftp://ftp.ncftp.com/ncftp/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
