#!/bin/bash -e

export VER=5.5.0
export DEST=/binary/qttools-${VER}

pushd qttools-opensource-src-${VER}

qmake

make -j4

find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;

make install INSTALL_ROOT=${DEST}

find ${DEST}/usr/lib/*.prl -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

install -Dm644 src/assistant/assistant/images/assistant-128.png \
              ${DEST}/usr/share/pixmaps/assistant-qt5.png
install -Dm644 src/designer/src/designer/images/designer.png \
              ${DEST}/usr/share/pixmaps/designer-qt5.png
install -Dm644 src/linguist/linguist/images/icons/linguist-128-32.png \
              ${DEST}/usr/share/pixmaps/linguist-qt5.png
install -Dm644 src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
              ${DEST}/usr/share/pixmaps/qdbusviewer-qt5.png

popd

rm -rf qttools-opensource-src-${VER}

rm -rf ${DEST}/usr/lib/*.la

install -dm755 ${DEST}/usr/share/applications

# Transitional
for file in ${DEST}/usr/bin/*
do
  ln -sf $(basename $file) ${DEST}/usr/bin/$(basename $file)-qt5
done

cat > ${DEST}/usr/share/applications/assistant-qt5.desktop << "EOF"
[Desktop Entry]
Name=Qt5 Assistant
Comment=Shows Qt5 documentation and examples
Exec=assistant-qt5
Icon=assistant-qt5
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Documentation;
EOF
cat > ${DEST}/usr/share/applications/designer-qt5.desktop << "EOF"
[Desktop Entry]
Name=Qt5 Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt5 applications
Exec=designer-qt5
Icon=designer-qt5
MimeType=application/x-designer;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF
cat > ${DEST}/usr/share/applications/linguist-qt5.desktop << "EOF"
[Desktop Entry]
Name=Qt5 Linguist
Comment=Add translations to Qt5 applications
Exec=linguist-qt5
Icon=linguist-qt5
MimeType=text/vnd.trolltech.linguist;application/x-linguist;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF
cat > ${DEST}/usr/share/applications/qdbusviewer-qt5.desktop << "EOF"
[Desktop Entry]
Name=Qt5 QDBusViewer
GenericName=D-Bus Debugger
Comment=Debug D-Bus applications
Exec=qdbusviewer-qt5
Icon=qdbusviewer-qt5
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Debugger;
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    mkdir -p usr/lib/debug/$(dirname ${BUILD_BINARY})
    objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
    strip --strip-unneeded ${BUILD_BINARY}
    objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
