#!/bin/bash -e

export PKGNAME=orc
export PKGVER=0.4.24
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://gstreamer.freedesktop.org/src/orc/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

configure_post() {
  sed "/SUBDIRS/s:testsuite::" -i Makefile
}

configure_post_32() {
  sed "/SUBDIRS/s:testsuite::" -i Makefile
}


. $(dirname $0)/master.sh
