#!/bin/bash -e

export PKGNAME=neon
export PKGVER=0.30.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.webdav.org/neon/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-shared --with-ssl)

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
