#!/bin/bash -e

export PKGNAME=libjpeg-turbo
export PKGVER=1.4.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/libjpeg-turbo/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--with-jpeg8)
export CONFIGURE_FLAGS_32=(--with-jpeg8 --without-simd)
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
