#!/bin/bash -e

export VER=5.3.0
export DEST=/binary/oxygen-fonts-${VER}

pushd oxygen-fonts-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=lib

make -j4
make install DESTDIR=${DEST}

popd

rm -rf oxygen-fonts-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/oxygen
EOF

chmod 755 ${DEST}/INSTALL
