#!/bin/bash -e

export VER=1.42.12
export DEST=/binary/e2fsprogs-${VER}

cp -a e2fsprogs-${VER} e2fsprogs-${VER}-32

pushd e2fsprogs-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr \
            --with-root-prefix="" \
            --enable-elf-shlibs \
            --disable-libblkid \
            --disable-libuuid \
            --disable-uuidd \
            --disable-fsck
 
make -j3
make install install-libs DESTDIR=${DEST}

popd

pushd e2fsprogs-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr \
            --libdir=/usr/lib32 \
            --with-root-prefix="" \
            --enable-elf-shlibs \
            --disable-libblkid \
            --disable-libuuid \
            --disable-uuidd \
            --disable-fsck \
            --disable-debugfs \
            --disable-imager \
            --disable-resizer

make -j3
make install-libs DESTDIR=/binary/e2fslibs

mv /binary/e2fslibs/usr/lib32 ${DEST}/usr
rm -rf /binary/e2fslibs

popd

rm -rf e2fsprogs-${VER} e2fsprogs-${VER}-32

find ${DEST} -name "*.la" -delete

for file in ${DEST}/usr/lib/*.so ; do ln -sf ../..$(readlink $file) $file ; done

sed -i -e 's#^SS_DIR=.*#SS_DIR="/usr/share/ss"#' ${DEST}/usr/bin/mk_cmds
sed -i -e 's#^ET_DIR=.*#ET_DIR="/usr/share/et"#' ${DEST}/usr/bin/compile_et

rm ${DEST}/usr/lib{,32}/*.a

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
