#!/bin/bash -e

export PKGNAME=wayland-protocols
export PKGVER=1.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://wayland.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export NO_STRIP=1

. $(dirname $0)/master.sh
