#!/bin/bash -e

export VER=4.01
export DEST=/binary/man-pages-${VER}

pushd man-pages-${VER}

make install DESTDIR=${DEST}

popd

rm -rf man-pages-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
