#!/bin/bash -e

export PKGNAME=openjpeg
export PKGVER=2.1.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/openjpeg.mirror/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
