#!/bin/bash -e

case $(basename $0) in
  buildatkmm )
    export PKGNAME=atkmm
    export PKGVER=2.24.2
  ;;
  buildcairomm )
    export PKGNAME=cairomm
    export PKGVER=1.12.0
  ;;
  buildglibmm )
    export PKGNAME=glibmm
    export PKGVER=2.46.3
  ;;
  buildgtkmm2 )
    export PKGNAME=gtkmm
    export PKGVER=2.24.4
    export USER_CXXFLAGS="-std=c++11"
  ;;
  buildgtkmm3 )
    export PKGNAME=gtkmm
    export PKGVER=3.18.0
  ;;
  buildlibsigc++ )
    export PKGNAME=libsigc++
    export PKGVER=2.6.2
  ;;
  buildpangomm )
    export PKGNAME=pangomm
    export PKGVER=2.38.1
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export KEEP_DOC=1

. $(dirname $0)/master.sh
