#!/bin/bash -e

export PKGNAME=gdb
export PKGVER=7.10.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/gdb/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-system-readline
                        --without-guile
                        --with-system-gdbinit=/etc/gdb/gdbinit)

export MAKE_INSTALL_FLAGS="-C gdb"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
