#!/bin/bash -e

export VER=3.14.1
export DEST=/binary/gnome-user-share-${VER}

pushd gnome-user-share-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr                \
            --sysconfdir=/etc            \
            --with-httpd=/usr/sbin/httpd \
            --with-modules-path=/usr/lib/httpd/modules

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnome-user-share-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
EOF

chmod 755 ${DEST}/INSTALL
