#!/bin/bash -e

export PKGNAME=bluefish
export PKGVER=2.2.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.bennewitz.com/bluefish/stable/source/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
