#!/bin/bash -e

export VER=1.8.1
export DEST=/binary/mate-applets-${VER}

pushd mate-applets-${VER}

sed -i s:lcpufreq:lcpupower:g configure configure.ac

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-gtk=2.0    \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mate-applets-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for mate-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/mate
EOF

chmod 755 ${DEST}/INSTALL
