#!/bin/bash -e

export VER=1.5.4
export DEST=/binary/apr-util-${VER}

pushd apr-util-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --disable-static    \
            --with-berkeley-db  \
            --with-crypto       \
            --with-dbm=db       \
            --with-ldap         \
            --with-mysql=/usr   \
            --with-odbc=/usr    \
            --with-openssl=/usr \
            --with-pgsql=/usr   \
            --with-sqlite3      \
            --without-gdbm      \
            --without-sqlite2   \
            --with-apr=/usr/bin/apr-1-config

make -j4
make install DESTDIR=${DEST}

popd

rm -rf apr-util-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
