#!/bin/bash -e

export VER=1.2.0
export DEST=/binary/python-snowballstemmer-${VER}

cp -a snowballstemmer-${VER} snowballstemmer-${VER}-3

pushd snowballstemmer-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd snowballstemmer-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf snowballstemmer-${VER} snowballstemmer-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
