#!/bin/bash -e

export PKGNAME=syslinux
export PKGVER=6.03
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/utils/boot/syslinux/${PKGTAR}"
export KEEP_INSTALL_DIRS=1
export NO_OPTIMIZATION=1
export MAKE_FLAGS="bios efi64"
export MAKE_INSTALL_FLAGS="bios efi64 INSTALLROOT=\${DEST} AUXDIR=/usr/lib/syslinux MANDIR=/usr/share/man"
export DEFAULT_CC="gcc"

configure_override() {
  sed -i "s#> /dev/null 2>&1##" efi/check-gnu-efi.sh

  truncate --size 0 mk/devel.mk
}

make_install_post() {
  rm -rf ${DEST}/usr/lib/syslinux/com32 ${DEST}/usr/lib/syslinux/dosutil
  rm -rf ${DEST}/usr/lib/syslinux.com

  install -dm755 ${DEST}/usr/lib/syslinux/bios

  mv ${DEST}/usr/lib/syslinux/*.bin ${DEST}/usr/lib/syslinux/bios
  mv ${DEST}/usr/lib/syslinux/*.c32 ${DEST}/usr/lib/syslinux/bios
  mv ${DEST}/usr/lib/syslinux/*.0 ${DEST}/usr/lib/syslinux/bios
  mv ${DEST}/usr/lib/syslinux/memdisk ${DEST}/usr/lib/syslinux/bios
}

. $(dirname $0)/master.sh
