#!/bin/bash -e

export VER=2015.06.05
export DEST=/binary/wireless-regdb-${VER}

pushd wireless-regdb-${VER}

install -Dm644 regulatory.bin ${DEST}/lib/crda/regulatory.bin
install -Dm644 sforshee.key.pub.pem ${DEST}/lib/crda/pubkeys/sforshee.key.pub.pem
install -Dm644 regulatory.bin.5 ${DEST}/usr/share/man/man5/regulatory.bin.5

install -dm755 ${DEST}/etc/default

cat > ${DEST}/etc/default/wireless-regdom << "EOF"
#
# Wireless regulatory domain configuration
#
EOF

for dom in $(grep ^country db.txt | cut -d' ' -f2 | sed "s#:##g"); do
  echo "#WIRELESS_REGDOM=\"${dom}\"" >> ${DEST}/etc/default/wireless-regdom.tmp
done

sort -u ${DEST}/etc/default/wireless-regdom.tmp >> ${DEST}/etc/default/wireless-regdom
rm ${DEST}/etc/default/wireless-regdom.tmp

popd

rm -rf wireless-regdb-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
