#!/bin/bash -e

case $(basename $0) in
  buildxf86-input-evdev )
    export PKGNAME=xf86-input-evdev
    export PKGVER=2.10.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://www.x.org/releases/individual/driver/${PKGTAR}"
  ;;
  buildxf86-input-libinput )
    export PKGNAME=xf86-input-libinput
    export PKGVER=0.22.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://www.x.org/releases/individual/driver/${PKGTAR}"
    post_install_config() {
      mv ${DEST}/usr/share/X11/xorg.conf.d/40-libinput.conf ${DEST}/usr/share/X11/xorg.conf.d/60-libinput.conf
    }
  ;;
  buildxf86-input-synaptics )
    export PKGNAME=xf86-input-synaptics
    export PKGVER=1.8.99.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://www.x.org/releases/individual/driver/${PKGTAR}"
  ;;
  buildxf86-input-wacom )
    export PKGNAME=xf86-input-wacom
    export PKGVER=0.33.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://downloads.sourceforge.net/linuxwacom/${PKGTAR}"
    export CONFIGURE_FLAGS=(--with-udev-rules-dir=/lib/udev/rules.d
                            --with-systemd-unit-dir=/lib/systemd/system)
  ;;
  buildxf86-video-amdgpu )
    export PKGNAME=xf86-video-amdgpu
    export PKGVER=1.1.99
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://www.x.org/releases/individual/driver/${PKGTAR}"
  ;;
  buildxf86-video-intel )
    export PKGNAME=xf86-video-intel
    export PKGVER=2.99.917
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://www.x.org/releases/individual/driver/${PKGTAR}"
    export CONFIGURE_FLAGS=(--enable-kms-only
                            --enable-sna
                            --with-default-accel=sna
                            --with-default-dri=3)
    export POSTINST_TRIGGER=("chmod 4755 /usr/libexec/xf86-video-intel-backlight-helper")
  ;;
  buildxorg-drivers )
    export PKG_AUTO_INSTALL=1

    $(dirname $0)/buildxf86-input-evdev
    $(dirname $0)/buildxf86-input-libinput
    $(dirname $0)/buildxf86-input-synaptics
    $(dirname $0)/buildxf86-input-wacom
    $(dirname $0)/buildxf86-video-amdgpu
    $(dirname $0)/buildxf86-video-intel

    find /binary/xorg/drivers -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

    exit 0
  ;;
esac

export MAKE_JOBS_FLAGS="-j4"
export DEST=/binary/xorg/drivers/${PKGNAME}-${PKGVER}
export DEFAULT_CC="gcc"
export DEFAULT_CXX="g++"

. $(dirname $0)/master.sh
