#!/bin/bash -e

export PKGNAME=pinentry
export PKGVER=0.9.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.gnupg.org/gcrypt/pinentry/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEFAULT_CXX="clang++ -std=c++11"

. $(dirname $0)/master.sh
