#!/bin/bash -e

export PKGNAME=enchant
export PKGVER=1.6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.abisource.com/downloads/enchant/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
