#!/bin/bash -e

export PKGNAME=smartmontools
export PKGVER=6.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/smartmontools/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export CONFIGURE_FLAGS=(--with-systemdsystemunitdir=/lib/systemd/system)

make_post() {
  sed -e "s:sysconfig/smartmontools:default/smartd:" \
      -e "s:smartd_opts:SMARTD_OPTS:"                \
      -e "/syslog.target/d" -i smartd.service
}

make_install_post() {
  install -dm755 ${DEST}/etc/default

cat > ${DEST}/etc/default/smartd << "EOF"
# Additional options to pass to smartd command line
SMARTD_OPTS=
EOF
}

. $(dirname $0)/master.sh
