#!/bin/bash -e

case $(basename $0) in
  buildaisleriot )
    export PKGNAME=aisleriot
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--with-platform=gtk-only
                            --with-card-theme-formats=svg,fixed,pysol
                            --with-pysol-card-theme-path=/usr/share/PySolFC)
  ;;
  buildcheese )
    export PKGNAME=cheese
    export PKGVER=3.18.1
    export CONFIGURE_FLAGS=(--disable-compile-warnings)
  ;;
  buildeog )
    export PKGNAME=eog
    export PKGVER=3.18.1
  ;;
  buildepiphany )
    export PKGNAME=epiphany
    export PKGVER=3.18.3
    make_install_post() {
      sed -i "s#multipart/related;##" ${DEST}/usr/share/applications/epiphany.desktop
    }
  ;;
  buildevince )
    export PKGNAME=evince
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--enable-introspection --disable-compile-warnings)
    make_install_post() {
      install -dm755 ${DEST}/usr/lib/evince/mozilla
      mv ${DEST}/usr/lib/mozilla/plugins/libevbrowserplugin.so ${DEST}/usr/lib/evince/mozilla
      ln -sf ../../evince/mozilla/libevbrowserplugin.so ${DEST}/usr/lib/mozilla/plugins/libevbrowserplugin.so
    }
  ;;
  buildfile-roller )
    export PKGNAME=file-roller
    export PKGVER=3.16.4
    export CONFIGURE_FLAGS=(--disable-packagekit)
  ;;
  buildgedit )
    export PKGNAME=gedit
    export PKGVER=3.18.3
  ;;
  buildgnome-calculator )
    export PKGNAME=gnome-calculator
    export PKGVER=3.18.3
  ;;
  buildgnome-color-manager )
    export PKGNAME=gnome-color-manager
    export PKGVER=3.18.0
    export CONFIGURE_FLAGS=(--disable-packagekit)
  ;;
  buildgnome-disk-utility )
    export PKGNAME=gnome-disk-utility
    export PKGVER=3.18.3.1
  ;;
  buildgnome-logs )
    export PKGNAME=gnome-logs
    export PKGVER=3.18.1
  ;;
  buildgnome-nettool )
    export PKGNAME=gnome-nettool
    export PKGVER=3.8.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgnome-power-manager )
    export PKGNAME=gnome-power-manager
    export PKGVER=3.18.0
  ;;
  buildgnome-system-monitor )
    export PKGNAME=gnome-system-monitor
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--enable-systemd)
  ;;
  buildgnome-terminal )
    export PKGNAME=gnome-terminal
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--disable-migration)
  ;;
  buildgnome-tweak-tool )
    export PKGNAME=gnome-tweak-tool
    export PKGVER=3.18.1
  ;;
  buildgucharmap )
    export PKGNAME=gucharmap
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--enable-vala)
  ;;
  buildnautilus )
    export PKGNAME=nautilus
    export PKGVER=3.18.5
    export CONFIGURE_FLAGS=(--disable-packagekit
                            --disable-update-mimedb
                            --disable-tracker)
  ;;
  buildnetwork-manager-applet )
    export PKGNAME=network-manager-applet
    export PKGVER=1.1.90
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--disable-migration)
  ;;
  buildseahorse )
    export PKGNAME=seahorse
    export PKGVER=3.18.0
  ;;
  buildvinagre )
    export PKGNAME=vinagre
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--disable-compile-warnings)
  ;;
  buildvino )
    export PKGNAME=vino
    export PKGVER=3.18.1
  ;;
  buildxdg-user-dirs-gtk )
    export PKGNAME=xdg-user-dirs-gtk
    export PKGVER=0.10
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER}/${PKGTAR}"
  ;;
  buildyelp )
    export PKGNAME=yelp
    export PKGVER=3.18.1
  ;;
  buildzenity )
    export PKGNAME=zenity
    export PKGVER=3.18.1.1
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
if [ -z ${PKGURL} ]
then
  export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
fi

. $(dirname $0)/master.sh
