#!/bin/bash -e

export VER=39
export EXTRA=-g4717841
export DEST=/binary/qtchooser-${VER}

pushd qtchooser-${VER}${EXTRA}

patch -Np1 -i /media/ntfs/Other/Linux/patches/qtchooser-fixes.patch

make CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " -j4
make install INSTALL_ROOT=${DEST}

popd

rm -rf qtchooser-${VER}${EXTRA}

install -dm755 ${DEST}/etc/xdg/qtchooser

cat > ${DEST}/etc/xdg/qtchooser/qt4.conf << "EOF"
/usr/lib/qt4/bin
/usr/lib
EOF

cat > ${DEST}/etc/xdg/qtchooser/qt5.conf << "EOF"
/usr/lib/qt5/bin
/usr/lib
EOF

ln -sf qt4.conf ${DEST}/etc/xdg/qtchooser/default.conf

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
