#!/bin/bash -e

export VER=4.4.2
export DEST=/binary/findutils-${VER}

pushd findutils-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --localstatedir=/var/lib/locate

make -j4
make install DESTDIR=${DEST}

popd

rm -rf findutils-${VER}

rm -rf ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

install -dm755 ${DEST}/bin

mv ${DEST}/usr/bin/find ${DEST}/bin
sed -i 's|find:=${BINDIR}|find:=/bin|' ${DEST}/usr/bin/updatedb

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in bin usr var ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
