#!/bin/bash -e

export VER=2014.11.12
export DEST=/binary/live-media-${VER}

pushd live

sed -e 's/$(INCLUDES) -I. -O2 -DSOCKLEN_T/$(INCLUDES) -I. -O2 -pipe -fstack-protector-strong -march=native -mtune=native -I. -fPIC -DSOCKLEN_T/g' \
    -i config.linux

./genMakefiles linux

make -j4

install -dm755 ${DEST}/usr/lib

for dir in BasicUsageEnvironment groupsock liveMedia UsageEnvironment; do
  install -dm755 ${DEST}/usr/include/${dir}
  install -m644 ${dir}/*.a ${DEST}/usr/lib
  install -m644 ${dir}/include/*.h* ${DEST}/usr/include/${dir}
done

popd

rm -rf live

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
