#!/bin/bash -e

export VER=1.8.0
export DEST=/binary/mate-backgrounds-${VER}

pushd mate-backgrounds-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mate-backgrounds-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
