#!/bin/bash -e

export VER=3.8.7.2
export PKGVER=3080702
export DEST=/binary/sqlite-${VER}

pushd sqlite-autoconf-${PKGVER}

./configure --prefix=/usr --disable-static \
            CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong \
           -DSQLITE_ENABLE_FTS3=1 \
           -DSQLITE_ENABLE_COLUMN_METADATA=1 \
           -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 \
           -DSQLITE_SECURE_DELETE=1"

make -j4
make install DESTDIR=${DEST}

pushd tea

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr        \
            --with-system-sqlite \
            --with-tcl=/usr/lib

make
make install DESTDIR=${DEST}

popd

make clean

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-static    \
            CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong \
            -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1 \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 \
            -DSQLITE_SECURE_DELETE=1"

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf sqlite-autoconf-${PKGVER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
