#!/bin/bash -e

export PKGNAME=qtbase
export PKGVER=5.6.0
export PKGTAR=${PKGNAME}-opensource-src-${PKGVER}.tar.xz
export PKGDIR=${PKGNAME}-opensource-src-${PKGVER}

# stable
export PKGURL="https://download.qt.io/official_releases/qt/5.6/${PKGVER}/submodules/${PKGTAR}"

# development
#export PKGURL="https://download.qt.io/development_releases/qt/5.6/${PKGVER}/submodules/${PKGTAR}"

export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export PATCHES_LIST=("qtbase.patch")
export MAKE_INSTALL_FLAGS="INSTALL_ROOT=\${DEST}"

configure_override() {
  sed -i "s:libsystemd-journal:libsystemd:g" config.tests/unix/journald/journald.pro src/corelib/global/global.pri

  ./configure -prefix         /usr               \
              -sysconfdir     /etc/xdg           \
              -headerdir      /usr/include/qt5   \
              -archdatadir    /usr/lib/qt5       \
              -datadir        /usr/share/qt5     \
              -docdir         /usr/share/doc/qt5 \
              -translationdir /usr/share/qt5/translations \
              -examplesdir    /usr/share/doc/qt5/examples \
              -confirm-license        \
              -opensource             \
              -c++std c++14           \
              -dbus-linked            \
              -openssl-linked         \
              -gstreamer 1.0          \
              -journald               \
              -libinput               \
              -system-harfbuzz        \
              -system-sqlite          \
              -nomake examples        \
              -no-reduce-relocations  \
              -no-rpath               \
              -no-strip               \
              -no-separate-debug-info \
              -optimized-qmake        \
              -no-use-gold-linker     \
              -platform linux-clang-libc++
}

make_post() {
  find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;
}

make_install_post() {
  sed -i -e "s:$PWD:/usr/lib/qt5:g" \
      ${DEST}/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri
  find ${DEST}/usr/lib/*.prl -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
  rm -rf ${DEST}/usr/share
}

. $(dirname $0)/master.sh
