#!/bin/bash -e

export PKGNAME=graphite2
export PKGVER=1.3.8
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="https://downloads.sourceforge.net/silgraphite/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

configure_pre() {
  sed -i "/target_link/s# gcc)#)#g" ../${PKGDIR}/src/CMakeLists.txt
}

. $(dirname $0)/master.sh
