#!/bin/bash -e

export VER=1.3.1
export DEST=/binary/pcsx2-${VER}

install -dm755 pcsx2-${VER}/build

pushd pcsx2-${VER}/build

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DCMAKE_LIBRARY_PATH=/usr/lib32  \
      -DPLUGIN_DIR=/usr/lib32/pcsx2    \
      -DGAMEINDEX_DIR=/usr/share/pcsx2 \
      -DEXTRA_PLUGINS=TRUE             \
      -DGLSL_API=TRUE                  \
      -DPACKAGE_MODE=TRUE              \
      -DREBUILD_SHADER=TRUE            \
      -DXDG_STD=TRUE                   \
      -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config32 \
      -DwxWidgets_wxrc_EXECUTABLE=/usr/bin/wxrc32        \
      -DCMAKE_TOOLCHAIN_FILE="cmake/linux-compiler-i386-multilib.cmake" \
      -DCMAKE_C_FLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w"   \
      -DCMAKE_CXX_FLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w" \
      ..

make -j4
make install DESTDIR=${DEST}

popd

rm -rf pcsx2-${VER}

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
