#!/bin/bash -e

export PKGNAME=ncurses
export PKGVER=6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/ncurses/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

configure_pre() {
  install -dm755 buildncursesw6 buildncursesw buildncurses
}

configure_pre_32() {
  install -dm755 buildncursesw6 buildncursesw buildncurses
}

configure_override_shared() {
  local LIBDIR=$1

  local CFG_FLAGS_SHARED=(--prefix=/usr
                          --libdir=/usr/${LIBDIR}
                          --mandir=/usr/share/man
                          --with-shared
                          --without-debug)

  pushd buildncursesw6
    ../configure ${CFG_FLAGS_SHARED[@]}  \
                 --enable-pc-files    \
                 --enable-widec       \
                 --with-abi-version=6 \
                 --with-pkg-config-libdir=/usr/${LIBDIR}/pkgconfig
  popd

  pushd buildncursesw
    ../configure ${CFG_FLAGS_SHARED[@]}  \
                 --enable-widec       \
                 --with-abi-version=5
  popd

  pushd buildncurses
    ../configure ${CFG_FLAGS_SHARED[@]}  \
                 --with-chtype=long   \
                 --with-abi-version=5
  popd
}

configure_override() {
  configure_override_shared lib
}

configure_override_32() {
  configure_override_shared lib32
}

make_override() {
  for d in buildncursesw6 buildncursesw buildncurses
  do
    make -C ${d} ${MAKE_JOBS_FLAGS}
  done
}

make_install_override() {
  if [ ${MULTILIB} == 1 ]
  then
    local LIBDIR=lib32
    make -C buildncursesw6 install DESTDIR=${PWD}/dest
    mv ${PWD}/dest/usr/lib32 ${DEST}/usr
  else
    local LIBDIR=lib
    make -C buildncursesw6 install DESTDIR=${DEST}
  fi

  for lib in ncurses form panel menu
  do
    install -m755 buildncursesw/lib/lib${lib}w.so.5.9 ${DEST}/usr/${LIBDIR}
    ln -sf lib${lib}w.so.5.9 ${DEST}/usr/${LIBDIR}/lib${lib}w.so.5

    install -m755 buildncurses/lib/lib${lib}.so.5.9 ${DEST}/usr/${LIBDIR}
    ln -sf lib${lib}.so.5.9 ${DEST}/usr/${LIBDIR}/lib${lib}.so.5
  done
}

post_install_config() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libncursesw.so.6{,.0} ${DEST}/lib
  ln -sf ../../lib/libncursesw.so.6.0 ${DEST}/usr/lib/libncursesw.so

  for lib in ncurses form panel menu ; do
    rm -rf ${DEST}/usr/lib/lib${lib}.so
    rm -rf ${DEST}/usr/lib32/lib${lib}.so
    echo "INPUT(-l${lib}w)" > ${DEST}/usr/lib/lib${lib}.so
    echo "INPUT(-l${lib}w)" > ${DEST}/usr/lib32/lib${lib}.so
  done

  for lib in ncurses ncurses++ form panel menu; do
    ln -sf ${lib}w.pc ${DEST}/usr/lib/pkgconfig/${lib}.pc
    ln -sf ${lib}w.pc ${DEST}/usr/lib32/pkgconfig/${lib}.pc
  done

  rm -rf ${DEST}/usr/lib/libcursesw.so
  rm -rf ${DEST}/usr/lib32/libcursesw.so
  echo "INPUT(-lncursesw)" > ${DEST}/usr/lib/libcursesw.so
  echo "INPUT(-lncursesw)" > ${DEST}/usr/lib32/libcursesw.so
  ln -sf libncurses.so ${DEST}/usr/lib/libcurses.so
  ln -sf libncurses.so ${DEST}/usr/lib32/libcurses.so

  rm -rf ${DEST}/usr/lib/*.a
  rm -rf ${DEST}/usr/lib32/*.a

  # libtinfo compat
  for lib in lib lib32
  do
    ln -sf libncurses.so.5 ${DEST}/usr/${lib}/libtinfo.so.5
  done
}

. $(dirname $0)/master.sh
