#!/bin/bash -e

export PKGNAME=kvazaar
export PKGVER=0.8.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/ultravideo/kvazaar/archive/v${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  ./autogen.sh
}

. $(dirname $0)/master.sh
