#!/bin/bash -e

export VER=5.5.0
export DEST=/binary/qtimageformats-${VER}

pushd qtimageformats-opensource-src-${VER}

qmake

make -j4
make install INSTALL_ROOT=${DEST}

popd

rm -rf qtimageformats-opensource-src-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    mkdir -p usr/lib/debug/$(dirname ${BUILD_BINARY})
    objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
    strip --strip-unneeded ${BUILD_BINARY}
    objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
