#!/bin/bash -e

export VER=2.3
export DEST=/binary/wpa_supplicant-${VER}

pushd wpa_supplicant-${VER}

export CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -MMD"
export CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -MMD"

cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CFLAGS += -I/usr/include/libnl3
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
EOF

sed -e "s@wpa_supplicant -u@& -s -O /var/run/wpa_supplicant@g" -i wpa_supplicant/dbus/*.service.in
sed -e "s@wpa_supplicant -u@& -s -O /var/run/wpa_supplicant@g" -i wpa_supplicant/systemd/wpa_supplicant.service.in

cd wpa_supplicant

make BINDIR=/sbin LIBDIR=/lib V=1 -j4

pushd wpa_gui-qt4
qmake-qt4 "QMAKE_CFLAGS=-march=native -mtune=native -O2 -pipe -fstack-protector-strong" "QMAKE_CXXFLAGS=-march=native -mtune=native -O2 -pipe -fstack-protector-strong" wpa_gui.pro
make V=1 -j4
popd

mkdir -p ${DEST}/etc/dbus-1/system.d
mkdir -p ${DEST}/etc/systemd/system/multi-user.target.wants
mkdir -p ${DEST}/lib/systemd/system
mkdir -p ${DEST}/sbin

mkdir -p ${DEST}/usr/bin
mkdir -p ${DEST}/usr/lib/pm-utils/sleep.d
mkdir -p ${DEST}/usr/share/applications
mkdir -p ${DEST}/usr/share/dbus-1/system-services
mkdir -p ${DEST}/usr/share/doc/wpa_supplicant
mkdir -p ${DEST}/usr/share/pixmaps

mkdir -p ${DEST}/usr/share/man/man5
mkdir -p ${DEST}/usr/share/man/man8

install -m755 wpa_cli ${DEST}/sbin/
install -m755 wpa_supplicant ${DEST}/sbin/
install -m755 wpa_passphrase ${DEST}/usr/bin/

install -m644 doc/docbook/wpa_supplicant.conf.5 ${DEST}/usr/share/man/man5/
install -m644 doc/docbook/wpa_background.8 ${DEST}/usr/share/man/man8/
install -m644 doc/docbook/wpa_cli.8 ${DEST}/usr/share/man/man8/
install -m644 doc/docbook/wpa_passphrase.8 ${DEST}/usr/share/man/man8/
install -m644 doc/docbook/wpa_supplicant.8 ${DEST}/usr/share/man/man8/

install -m644 dbus/fi.epitest.hostap.WPASupplicant.service ${DEST}/usr/share/dbus-1/system-services/
install -m644 dbus/fi.w1.wpa_supplicant1.service ${DEST}/usr/share/dbus-1/system-services/

install -m644 dbus/dbus-wpa_supplicant.conf ${DEST}/etc/dbus-1/system.d/wpa_supplicant.conf

install -m755 wpa_gui-qt4/wpa_gui ${DEST}/usr/bin/
install -m644 doc/docbook/wpa_gui.8 ${DEST}/usr/share/man/man8/

install -m644 wpa_gui-qt4/wpa_gui.desktop ${DEST}/usr/share/applications/
install -m644 wpa_gui-qt4/icons/wpa_gui.svg ${DEST}/usr/share/pixmaps/

install -m644 examples/*.conf ${DEST}/usr/share/doc/wpa_supplicant/
install -m755 examples/60_wpa_supplicant ${DEST}/usr/lib/pm-utils/sleep.d/60wpa_supplicant
install -m644 systemd/*.service ${DEST}/lib/systemd/system

ln -sf /lib/systemd/system/wpa_supplicant.service ${DEST}/etc/systemd/system/dbus-fi.epitest.hostap.WPASupplicant.service
ln -sf /lib/systemd/system/wpa_supplicant.service ${DEST}/etc/systemd/system/multi-user.target.wants/wpa_supplicant.service

strip --strip-unneeded ${DEST}/sbin/* ${DEST}/usr/bin/*

popd

rm -rf wpa_supplicant-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod +x ${DEST}/INSTALL
