#!/bin/bash -e

export DEST=/binary/xorg

export XORG_HTTP=http://xorg.freedesktop.org/archive/individual

export UTIL_HTTP=${XORG_HTTP}/util

export UTIL_MACROS_VER=1.19.0
export MAKEDEPEND_VER=1.0.5

export CONFIG="--prefix=/usr --sysconfdir=/etc --localstatedir=/var"

wget -c ${UTIL_HTTP}/util-macros-${UTIL_MACROS_VER}.tar.bz2
wget -c ${UTIL_HTTP}/makedepend-${MAKEDEPEND_VER}.tar.bz2

tar xf util-macros-${UTIL_MACROS_VER}.tar.bz2

pushd util-macros-${UTIL_MACROS_VER}
  ./configure ${CONFIG}
  make
  make install DESTDIR=${DEST}/$(basename $PWD)
popd

rm -rf util-macros-${UTIL_MACROS_VER}

tar xf makedepend-${MAKEDEPEND_VER}.tar.bz2

pushd makedepend-${MAKEDEPEND_VER}
  CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" ./configure ${CONFIG}
  make
  make install DESTDIR=${DEST}/$(basename $PWD)
  strip --strip-unneeded ${DEST}/$(basename $PWD)/usr/bin/makedepend
popd

rm -rf makedepend-${MAKEDEPEND_VER}

rm -rf util-macros-${UTIL_MACROS_VER}.tar.bz2  makedepend-${MAKEDEPEND_VER}.tar.bz2

for dir in ${DEST}/util-macros-${UTIL_MACROS_VER} ${DEST}/makedepend-${MAKEDEPEND_VER}
do
cat > ${dir}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF
chmod 755 ${dir}/INSTALL
done

cat >> ${DEST}/makedepend-${MAKEDEPEND_VER}/INSTALL << "EOF"

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF
