#!/bin/bash -e

export PKGNAME=lz4
export PKGVER=1.7.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/lz4/lz4/archive/v${PKGVER}.tar.gz"
export MAKE_FLAGS="lib all PREFIX=/usr"
export MAKE_INSTALL_FLAGS="PREFIX=/usr"

configure_override() {
  sed -i "/install.*liblz4.a/d" lib/Makefile
  sed -i "/CFLAGS/s#-O3#${CFLAGS}#g" lib/Makefile programs/Makefile
}

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/liblz4.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/liblz4.so) ${DEST}/usr/lib/liblz4.so
}

. $(dirname $0)/master.sh
