#!/bin/bash -e

export PKGNAME=icu
export PKGVER=56.1
export PKGTAR=icu4c-56_1-src.tgz
export PKGURL="http://download.icu-project.org/files/icu4c/${PKGVER}/${PKGTAR}"
export PKGDIR=${PKGNAME}
export PKGBUILD=${PKGDIR}/source
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

make_install_post_32() {
  mv dest/usr/bin/icu-config ${DEST}/usr/bin/icu-config-32
}

. $(dirname $0)/master.sh
