#!/bin/bash -e

export VER=2.2.2
export DEST=/binary/fceux-${VER}

pushd fceux-${VER}

scons CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
      GTK=0  \
      GTK3=1 \
      LUA=0  \
      SYSTEM_MINIZIP=1        \
      -i --prefix=${DEST}/usr \
      install

rm -f ${DEST}/usr/share/pixmaps

install -Dm644 fceux.desktop ${DEST}/usr/share/applications/fceux.desktop
install -Dm644 fceux.png ${DEST}/usr/share/pixmaps/fceux.png

popd

rm -rf fceux-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
