#!/bin/bash -e

export VER=24.2.0
export DEST=/binary/mozjs-${VER}

pushd mozjs-${VER}/js/src

CFLAGS="-march=native -mtune=native -O2"   \
CXXFLAGS="-march=native -mtune=native -O2" \
./configure --prefix=/usr       \
            --enable-readline   \
            --enable-threadsafe \
            --with-system-ffi   \
            --with-system-nspr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mozjs-${VER}

find ${DEST} -name "*.a" -delete
find ${DEST} -type f -exec chmod 644 {} \;

chmod 755 ${DEST}/usr/bin/* ${DEST}/usr/lib/*.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
