#!/bin/bash -e

export VER=3.14.0
export DEST=/binary/gnome-online-miners-${VER}

pushd gnome-online-miners-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnome-online-miners-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
