#!/bin/bash -e

export VER=1.8.13
export DEST=/binary/sudo-${VER}

pushd sudo-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr           \
            --libexecdir=/usr/lib   \
            --with-all-insults      \
            --with-env-editor       \
            --with-pam              \
            --with-rundir=/run/sudo \
            --with-passprompt="[sudo] password for %p: "

make -j4
make install DESTDIR=${DEST}

popd

rm -rf sudo-${VER}

find ${DEST} -name "*.so" -exec chmod 755 {} \;

rm -rf ${DEST}/usr/share/doc ${DEST}/run

install -dm755 ${DEST}/etc/pam.d ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/usr/lib/tmpfiles.d/sudo.conf << "EOF"
d /run/sudo 0711 root root -
EOF

cat > ${DEST}/etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr var ; do cp -rf --remove-destination $dir / ; done

chmod 4755 /usr/bin/sudo

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
