#!/bin/bash -e

export VER=1.2.0
export DEST=/binary/dbus-python-${VER}

cp -a dbus-python-${VER} dbus-python-${VER}-3

pushd dbus-python-${VER}-3

PYTHON=/usr/bin/python3 \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

pushd dbus-python-${VER}

PYTHON=/usr/bin/python \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf dbus-python-${VER} dbus-python-${VER}-3

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
