#!/bin/bash -e

export VER=1.5.91
export DEST=/binary/gstreamer-${VER}

cp -a gstreamer-${VER} gstreamer-${VER}-32

pushd gstreamer-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --libexecdir=/usr/lib \
            --with-package-name="GStreamer ${VER} BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/systemd/"

make -j4
make install DESTDIR=${DEST}

popd

pushd gstreamer-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr           \
            --libdir=/usr/lib32     \
            --libexecdir=/usr/lib32 \
            --disable-introspection \
            --with-package-name="GStreamer ${VER} BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/systemd/"

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf gstreamer-${VER} gstreamer-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
