#!/bin/bash -e

export LUA_MAJOR=5.2
export VER=${LUA_MAJOR}.3
export DEST=/binary/lua-${VER}

pushd lua-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/lua-shared-lib.patch
sed -i '/#define LUA_ROOT/s:/usr/local:/usr:' src/luaconf.h 

make MYCFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -fPIC" linux -j4

make INSTALL_TOP=${DEST}/usr TO_LIB="liblua.so liblua.so.${LUA_MAJOR} liblua.so.${VER}" \
     INSTALL_DATA="cp -d" INSTALL_MAN=${DEST}/usr/share/man/man1 install 

popd

rm -rf lua-${VER}

install -dm755 ${DEST}/usr/lib/pkgconfig

cat > ${DEST}/usr/lib/pkgconfig/lua.pc << EOF
prefix=/usr
INSTALL_BIN=\${prefix}/bin
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
INSTALL_MAN=\${prefix}/man/man1
INSTALL_LMOD=\${prefix}/share/lua/${LUA_MAJOR}
INSTALL_CMOD=\${prefix}/lib/lua/${LUA_MAJOR}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: ${VER}
Requires: 
Libs: -L\${libdir} -llua -lm
Cflags: -I\${includedir}
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
