#!/bin/bash -e

export PKGNAME=libatasmart
export PKGVER=0.19
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://0pointer.de/public/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/share ; do cp -rf --remove-destination \$dir /usr ; done")

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
