#!/bin/bash -e

case $(basename $0) in

  buildpython-alabaster )
    export PKGNAME=alabaster
    export PKGVER=0.7.8
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/a/alabaster/${PKGTAR}"
    export DEST=/binary/python/python-alabaster-${PKGVER}
  ;;
  buildpython-babel )
    export PKGNAME=Babel
    export PKGVER=2.3.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/B/Babel/${PKGTAR}"
    export DEST=/binary/python/python-babel-${PKGVER}
    make_install_post() {
      mv ${DEST}/usr/bin/pybabel{,3}
    }
  ;;
  buildpython-beaker )
    export PKGNAME=Beaker
    export PKGVER=1.8.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/B/Beaker/${PKGTAR}"
    export DEST=/binary/python/python-beaker-${PKGVER}
  ;;
  buildpython-cssselect )
    export PKGNAME=cssselect
    export PKGVER=0.9.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/c/cssselect/${PKGTAR}"
    export DEST=/binary/python/python-cssselect-${PKGVER}
  ;;
  buildpython-docutils )
    export PKGNAME=docutils
    export PKGVER=0.12
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://downloads.sourceforge.net/docutils/${PKGTAR}"
    export DEST=/binary/python/python-docutils-${PKGVER}
    make_install_post() {
      for file in ${DEST}/usr/bin/*.py
      do
        ln -sf $(basename ${file}) ${file%.py}
        mv ${file} ${file%.py}3.py
      done
    }
  ;;
  buildpython-imagesize )
    export PKGNAME=imagesize
    export PKGVER=0.7.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/i/imagesize/${PKGTAR}"
    export DEST=/binary/python/python-imagesize-${PKGVER}
  ;;
  buildpython-isodate )
    export PKGNAME=isodate
    export PKGVER=0.5.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/i/isodate/${PKGTAR}"
    export DEST=/binary/python/python-isodate-${PKGVER}
  ;;
  buildpython-jinja2 )
    export PKGNAME=Jinja2
    export PKGVER=2.8
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/J/Jinja2/${PKGTAR}"
    export DEST=/binary/python/python-jinja2-${PKGVER}
  ;;
  buildpython-lxml )
    export PKGNAME=lxml
    export PKGVER=3.6.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/l/lxml/${PKGTAR}"
    export DEST=/binary/python/python-lxml-${PKGVER}
  ;;
  buildpython-mako )
    export PKGNAME=Mako
    export PKGVER=1.0.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/M/Mako/${PKGTAR}"
    export DEST=/binary/python/python-mako-${PKGVER}
    make_install_post() {
      mv ${DEST}/usr/bin/mako-render{,3}
    }
  ;;
  buildpython-markupsafe )
    export PKGNAME=MarkupSafe
    export PKGVER=0.23
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/M/MarkupSafe/${PKGTAR}"
    export DEST=/binary/python/python-markupsafe-${PKGVER}
  ;;
  buildpython-pygments )
    export PKGNAME=Pygments
    export PKGVER=2.1.3
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/P/Pygments/${PKGTAR}"
    export DEST=/binary/python/python-pygments-${PKGVER}
    make_install_post() {
      mv ${DEST}/usr/bin/pygmentize{,3}
    }
  ;;
  buildpython-pyinotify )
    export PKGNAME=pyinotify
    export PKGVER=0.9.6
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://github.com/seb-m/pyinotify/archive/${PKGVER}.tar.gz"
    export DEST=/binary/python/python-pyinotify-${PKGVER}
  ;;
  buildpython-pyparsing )
    export PKGNAME=pyparsing
    export PKGVER=2.1.6
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/p/pyparsing/${PKGTAR}"
    export DEST=/binary/python/python-pyparsing-${PKGVER}
  ;;
  buildpython-pytz )
    export PKGNAME=pytz
    export PKGVER=2016.6.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="https://pypi.python.org/packages/source/p/pytz/${PKGTAR}"
    export DEST=/binary/python/python-pytz-${PKGVER}
  ;;
  buildpython-pyxdg )
    export PKGNAME=pyxdg
    export PKGVER=0.25
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/p/pyxdg/${PKGTAR}"
    export DEST=/binary/python/python-pyxdg-${PKGVER}
  ;;
  buildpython-pyyaml )
    export PKGNAME=PyYAML
    export PKGVER=3.11
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://pyyaml.org/download/pyyaml/${PKGTAR}"
    export DEST=/binary/python/python-pyyaml-${PKGVER}
  ;;
  buildpython-rdflib )
    export PKGNAME=rdflib
    export PKGVER=4.2.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/r/rdflib/${PKGTAR}"
    export DEST=/binary/python/python-rdflib-${PKGVER}
  ;;
  buildpython-setuptools )
    export PKGNAME=setuptools
    export PKGVER=25.1.6
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/s/setuptools/${PKGTAR}"
    export DEST=/binary/python/python-setuptools-${PKGVER}
  ;;
  buildpython-six )
    export PKGNAME=six
    export PKGVER=1.10.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/s/six/${PKGTAR}"
    export DEST=/binary/python/python-six-${PKGVER}
  ;;
  buildpython-snowballstemmer )
    export PKGNAME=snowballstemmer
    export PKGVER=1.2.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/s/snowballstemmer/${PKGTAR}"
    export DEST=/binary/python/python-snowballstemmer-${PKGVER}
  ;;
  buildpython-sphinx )
    export PKGNAME=Sphinx
    export PKGVER=1.4.5
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/S/Sphinx/${PKGTAR}"
    export DEST=/binary/python/python-sphinx-${PKGVER}
    make_install_post() {
      for file in ${DEST}/usr/bin/*
      do
        mv ${file} ${file}3
      done
    }
  ;;
  buildpython-sphinx_rtd_theme )
    export PKGNAME=sphinx_rtd_theme
    export PKGVER=0.1.9
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/s/sphinx_rtd_theme/${PKGTAR}"
    export DEST=/binary/python/python-sphinx_rtd_theme-${PKGVER}
  ;;
  buildpython-systemd )
    export PKGNAME=python-systemd
    export PKGVER=231
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://github.com/systemd/python-systemd/archive/v${PKGVER}.tar.gz"
    export DEST=/binary/python/python-systemd-${PKGVER}
  ;;
  buildpython-modules )
    if [ -z $1 ]
    then
      echo "$(basename $0) 1|2"
      exit 1
    fi

    if [ $1 == 1 ]
    then
      $(dirname $0)/buildpython-setuptools
      $(dirname $0)/buildpython-alabaster
      $(dirname $0)/buildpython-beaker
      $(dirname $0)/buildpython-cssselect
      $(dirname $0)/buildpython-imagesize
      $(dirname $0)/buildpython-isodate
      $(dirname $0)/buildpython-markupsafe
      $(dirname $0)/buildpython-pyparsing
      $(dirname $0)/buildpython-pygments
      $(dirname $0)/buildpython-pytz
      $(dirname $0)/buildpython-pyxdg
      $(dirname $0)/buildpython-six
      $(dirname $0)/buildpython-snowballstemmer
      $(dirname $0)/buildpython-babel
      $(dirname $0)/buildpython-docutils
      $(dirname $0)/buildpython-jinja2
      $(dirname $0)/buildpython-lxml
      $(dirname $0)/buildpython-mako
      $(dirname $0)/buildpython-rdflib
      $(dirname $0)/buildpython-sphinx
      $(dirname $0)/buildpython-sphinx_rtd_theme
    elif [ $1 == 2 ]
    then
      $(dirname $0)/buildpython-m2crypto
      $(dirname $0)/buildpython-pyinotify
      $(dirname $0)/buildpython-pyyaml
      $(dirname $0)/buildpython-systemd
    fi
    exit 0
  ;;

esac

export NO_OPTIMIZATION=1

if [ $(basename $0) == "buildpython-m2crypto" ]
then
  export PYTHON=python
else
  export PYTHON=python3
fi

configure_override() {
  true
}
make_override() {
  if [ ${MULTILIB} == 0 ]
  then
    ${PYTHON} setup.py build ${EXTRA_CFG}
  else
    python setup.py build ${EXTRA_CFG}
  fi
}
make_install_override() {
  if [ ${MULTILIB} == 0 ]
  then
    ${PYTHON} setup.py install --root=${DEST} --optimize=1
  else
    python setup.py install --root=${DEST} --optimize=1
  fi
}

case $(basename $0) in
  buildpython-m2crypto)
    export PKGNAME=M2Crypto
    export PKGVER=0.24.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://pypi.python.org/packages/source/M/M2Crypto/${PKGTAR}"
    export DEST=/binary/python/python-m2crypto-${PKGVER}
  ;;
  *)
    export MULTILIB_BUILD=1
    configure_override_32() {
      true
    }
  ;;
esac

export DEFAULT_CC_M32="clang"

. $(dirname $0)/master.sh
