#!/bin/bash -e

export VER=3.2.25
export DEST=/binary/libnl-${VER}

pushd libnl-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libnl-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/*.so.* ${DEST}/lib

for file in ${DEST}/usr/lib/*.so
do
  ln -sf ../../lib/$(readlink ${file}) ${file}
done

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
