#!/bin/bash -e

export PKGNAME=guile
export PKGVER=2.0.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/guile/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEFAULT_CC="gcc"

configure_pre() {
  export CFLAGS=${CFLAGS/-Ofast/-O3}
  export CFLAGS=${CFLAGS/-march=broadwell/}
}

make_install_post() {
  rm -rf ${DEST}/usr/lib/*.scm
}

. $(dirname $0)/master.sh
