#!/bin/bash -e

export PKGNAME=ijs
export PKGVER=0.35
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://www.openprinting.org/download/ijs/download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-shared)

make_install_post() {
  rm -rf ${DEST}/usr/bin/*example*
}

. $(dirname $0)/master.sh
