#!/bin/bash -e

export PKGNAME=qrencode
export PKGVER=3.4.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://fukuchi.org/works/qrencode/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
