#!/bin/bash -e

export PKGNAME=iso-codes
export PKGVER=3.68
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://pkg-isocodes.alioth.debian.org/downloads/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export NO_STRIP=1

. $(dirname $0)/master.sh
