#!/bin/bash -e

export PKGNAME=mpc
export PKGVER=1.0.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/mpc/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1

. $(dirname $0)/master.sh
