#!/bin/bash -e

export PKGNAME=libproxy
export PKGVER=0.4.12
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/libproxy/libproxy/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_SKIP_RPATH=ON
                    -DBUILD_TESTING=OFF
                    -DPERL_VENDORINSTALL=yes
                    -DWITH_WEBKIT=OFF
                    -DWITH_VALA=ON)

. $(dirname $0)/master.sh
