#!/bin/bash -e

export VER=3.52.9
export DEST=/binary/libiodbc-${VER}

pushd libiodbc-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"    \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"  \
./configure --prefix=/usr                   \
            --with-iodbc-inidir=/etc/iodbc  \
            --includedir=/usr/include/iodbc \
            --disable-gui                   \
            --disable-libodbc               \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libiodbc-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
