#!/bin/bash -e

export VER=1.0.2
export DEST=/binary/lua-bitop-${VER}

pushd LuaBitOp-${VER}

sed -i "s:-O2:-march=native -mtune=native -O2 -pipe -fstack-protector-strong:g" Makefile

make LUA=lua -j4

install -Dm755 bit.so ${DEST}/usr/lib/lua/5.2/bit.so

popd

rm -rf LuaBitOp-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
