#!/bin/bash -e

export PKGNAME=libxslt
export PKGVER=1.1.29
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://xmlsoft.org/sources/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1

. $(dirname $0)/master.sh
