#!/bin/bash -e

export PKGNAME=mesa
export PKGVER=11.1.0

if [ $(basename $0) == "buildmesa-git" ]
then
  prepare_src_override() {
    export PKGDIR=${PKGNAME}
    export PKGBUILD=${PKGDIR}

    if [ -e ${PKGDIR} ] || [ -e ${PKGBUILD} ]
    then
      if [ -z ${RECURSIVE_CALL} ]
      then
        echo "Warning: Old source and/or build dir exists. Removing."
        rm -rf ${PKGDIR} ${PKGBUILD}
      fi
    fi

    if [ -e git/${PKGNAME}.tar.xz ]
    then
      tar xf git/${PKGNAME}.tar.xz
      pushd ${PKGNAME}
        git fetch origin
        git reset --hard origin/master
      popd
    else
      git clone git://anongit.freedesktop.org/mesa/mesa
    fi

    pushd ${PKGDIR}
      export PKGVER="$(cat VERSION | sed s/-devel//)-$(git describe | cut -d - -f 4)"
      autoreconf -fi
    popd

    if [ -z ${DEST_SET} ]
    then
      export DEST=/binary/${PKGNAME}-${PKGVER}
      export DEST_SET=1
    fi

    if [ -e ${DEST} ] || [ -e ${DEST}-debug ]
    then
      if [ ${PKG_BUILDING} != 1 ]
      then
        echo "Warning: Old package installation dir exits. Removing."
        rm -rf ${DEST} ${DEST}-debug
      fi
    fi

    export PKG_BUILDING=1
  }
else
  export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
  export PKGURL="ftp://ftp.freedesktop.org/pub/mesa/${PKGVER}/${PKGTAR}"
fi

export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export MULTILIB_BUILD=1
export PATCHES_LIST=("mesalib-xdemos.patch")
export PATCHES_LIST_32=("mesalib-xdemos.patch")

#export DEFAULT_CC="clang"
#export DEFAULT_CXX="clang++-std=c++11 -stdlib=libc++"

#export DEFAULT_CC_M32="clang -m32"
#export DEFAULT_CXX_M32="clang++ -std=c++11 -stdlib=libc++ -m32"

configure_pre() {
  sed -i 's/LLVM_SO_NAME=.*/LLVM_SO_NAME=LLVM/' configure
}

configure_pre_32() {
  sed -i 's/LLVM_SO_NAME=.*/LLVM_SO_NAME=LLVM/' configure
  export LLVM_CONFIG=/usr/bin/llvm-config32
}

make_post() {
  make -C xdemos
}

make_post_32() {
  make -C xdemos EXT=32 CC="${CC}"
}

make_install_post() {
  make -C xdemos install DESTDIR=${DEST}
}

make_install_post_32() {
  install -m755 xdemos/glxinfo32 ${DEST}/usr/bin
  install -m755 xdemos/glxgears32 ${DEST}/usr/bin
}

export COMMON_FLAGS=(--disable-xvmc
                     --enable-texture-float
                     --enable-gles1
                     --enable-gles2
                     --enable-gbm
                     --enable-vdpau
                     --enable-omx
                     --enable-va
                     --enable-opencl
                     --enable-opencl-icd
                     --enable-glx-tls
                     --enable-llvm-shared-libs
                     --with-dri-drivers=i965
                     --with-egl-platforms=drm,x11,wayland
                     --with-gallium-drivers=r600,swrast)

export CONFIGURE_FLAGS=("${COMMON_FLAGS[@]}")
export CONFIGURE_FLAGS_32=("${COMMON_FLAGS[@]}"
                           --build=i686-pc-linux-gnu
                           --host=i686-pc-linux-gnu)

. $(dirname $0)/master.sh
