#!/bin/bash -e

export PKGNAME=Vulkan-Docs
export PKGVER=1.0.34
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-${PKGVER}-core
export PKGURL="https://github.com/KhronosGroup/Vulkan-Docs/archive/v${PKGVER}-core.tar.gz"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  true
}

make_override() {
  make -C doc/specs/vulkan manpages ${MAKE_JOBS_FLAGS}
  make -C doc/specs/vulkan manpages ${MAKE_JOBS_FLAGS}
}

make_install_override() {
  install -dm755 ${DEST}/usr/include/vulkan ${DEST}/usr/share/man/man3
  install -m644 src/vulkan/*.h ${DEST}/usr/include/vulkan
  install -m644 out/1.0/man/3/*.3 ${DEST}/usr/share/man/man3
}

. $(dirname $0)/master.sh
