#!/bin/bash -e

export DEST=/binary/xorg

export XORG_HTTP=http://xorg.freedesktop.org/archive/individual

export XCB_HTTP=${XORG_HTTP}/xcb

export CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -I${DEST}/tmp/usr/include -I${DEST}/tmp/usr/include/X11 -I${DEST}/tmp/usr/include/GL"
export PKG_CONFIG_PATH="${DEST}/tmp/usr/lib/pkgconfig:${DEST}/tmp/usr/share/pkgconfig"
export LD_LIBRARY_PATH="${DEST}/tmp/usr/lib"
export LDFLAGS="-L${DEST}/tmp/usr/lib"

export CONFIG="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static"

export XCB_UTIL_VER=0.4.0
export XCB_UTIL_CURSOR_VER=0.1.2
export XCB_UTIL_ERRORS_VER=1.0
export XCB_UTIL_IMAGE_VER=0.4.0
export XCB_UTIL_KEYSYMS_VER=0.3.9
export XCB_UTIL_RENDERUTIL_VER=0.3.9
export XCB_UTIL_WM_VER=0.4.1

wget -c ${XCB_HTTP}/xcb-util-${XCB_UTIL_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-util-cursor-${XCB_UTIL_CURSOR_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-util-errors-${XCB_UTIL_ERRORS_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-util-image-${XCB_UTIL_IMAGE_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-util-keysyms-${XCB_UTIL_KEYSYMS_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-util-renderutil-${XCB_UTIL_RENDERUTIL_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-util-wm-${XCB_UTIL_WM_VER}.tar.bz2

tar xf xcb-util-${XCB_UTIL_VER}.tar.bz2

pushd xcb-util-${XCB_UTIL_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-${XCB_UTIL_VER}

tar xf xcb-util-cursor-${XCB_UTIL_CURSOR_VER}.tar.bz2

pushd xcb-util-cursor-${XCB_UTIL_CURSOR_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-cursor-${XCB_UTIL_CURSOR_VER}

tar xf xcb-util-errors-${XCB_UTIL_ERRORS_VER}.tar.bz2

pushd xcb-util-errors-${XCB_UTIL_ERRORS_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-errors-${XCB_UTIL_ERRORS_VER}

tar xf xcb-util-image-${XCB_UTIL_IMAGE_VER}.tar.bz2

pushd xcb-util-image-${XCB_UTIL_IMAGE_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-image-${XCB_UTIL_IMAGE_VER}

tar xf xcb-util-keysyms-${XCB_UTIL_KEYSYMS_VER}.tar.bz2

pushd xcb-util-keysyms-${XCB_UTIL_KEYSYMS_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-keysyms-${XCB_UTIL_KEYSYMS_VER}

tar xf xcb-util-renderutil-${XCB_UTIL_RENDERUTIL_VER}.tar.bz2

pushd xcb-util-renderutil-${XCB_UTIL_RENDERUTIL_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-renderutil-${XCB_UTIL_RENDERUTIL_VER}

tar xf xcb-util-wm-${XCB_UTIL_WM_VER}.tar.bz2

pushd xcb-util-wm-${XCB_UTIL_WM_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/xcb/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
popd

rm -rf xcb-util-wm-${XCB_UTIL_WM_VER}

find ${DEST}/xcb -name "*.la" -delete

rm -rf xcb-util-${XCB_UTIL_VER}.tar.bz2 xcb-util-cursor-${XCB_UTIL_CURSOR_VER}.tar.bz2 xcb-util-errors-${XCB_UTIL_ERRORS_VER}.tar.bz2 xcb-util-image-${XCB_UTIL_IMAGE_VER}.tar.bz2 xcb-util-keysyms-${XCB_UTIL_KEYSYMS_VER}.tar.bz2 xcb-util-renderutil-${XCB_UTIL_RENDERUTIL_VER}.tar.bz2 xcb-util-wm-${XCB_UTIL_WM_VER}.tar.bz2

pushd ${DEST}/xcb

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

rm -rf ${DEST}/tmp

for dir in ${DEST}/xcb/*
do

cat > ${dir}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${dir}/INSTALL

done
