#!/bin/bash -e

export PKGNAME=libpst
export PKGVER=0.6.67
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.five-ten-sg.com/libpst/packages/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export CONFIGURE_FLAGS=(--disable-dii --enable-libpst-shared)

. $(dirname $0)/master.sh
