#!/bin/bash -e

export PKGNAME=newt
export PKGVER=0.52.18
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://fedorahosted.org/releases/n/e/newt/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

export DEFAULT_CC="clang"

make_install_post() {
  find ${DEST} -name "*.a" -delete
}

. $(dirname $0)/master.sh
