#!/bin/bash -e

export PKGNAME=gnome-control-center
export PKGVER=3.18.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://download.gnome.org/sources/gnome-control-center/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
