#!/bin/bash -e

export VER=2.0.27
export DEST=/binary/gnupg-${VER}

pushd gnupg-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --enable-gpgtar      \
            --enable-symcryptrun \
            --enable-standard-socket

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnupg-${VER}

rm -rf ${DEST}/usr/share/doc ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

rm -rf ${DEST}/usr/share/gnupg/com-certs.pem

for f in gpg gpgv
do
  ln -sf ${f}2   ${DEST}/usr/bin/${f}
  ln -sf ${f}2.1 ${DEST}/usr/share/man/man1/${f}.1
done &&

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
