#!/bin/bash -e

export VER=2.4.0
export DEST=/binary/qemu-${VER}

pushd qemu-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-gtk        \
            --enable-linux-aio   \
            --enable-spice       \
            --enable-tpm         \
            --audio-drv-list='pa alsa sdl'

make -j4
make install DESTDIR=${DEST}

popd

rm -rf qemu-${VER}

rm -rf ${DEST}/usr/share/doc ${DEST}/usr/share/qemu/*.aml ${DEST}/usr/share/qemu/bios.bin ${DEST}/var

find ${DEST} -name "*.la" -delete

chmod 755 ${DEST}/usr/lib/libcacard.so

install -dm755 ${DEST}/lib/udev/rules.d

cat > ${DEST}/lib/udev/rules.d/65-kvm.rules << "EOF"
KERNEL=="kvm", GROUP="kvm", MODE="0660"
KERNEL=="vhost-net", GROUP="kvm", MODE="0660", TAG+="uaccess", OPTIONS+="static_node=vhost-net"
EOF

pushd ${DEST}

find usr/bin usr/lib usr/libexec -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

getent group kvm > /dev/null || groupadd -g 61 kvm

chmod 4755 /usr/libexec/qemu-bridge-helper

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
