#!/bin/bash -e

export VER=4.5
export DEST=/binary/docbook-xml-${VER}

tar xf /media/ntfs/Other/Linux/packages/docbook-xml.tar.xz --strip-components=1

for ver in 4.2 4.3 4.4 4.5; do
  mkdir docbook-xml-${ver}
  pushd docbook-xml-${ver}
  unzip "../docbook-xml-${ver}.zip"
  mkdir -p "${DEST}/usr/share/xml/docbook/xml-dtd-${ver}"
  cp -dRf docbook.cat *.dtd ent/ *.mod \
      "${DEST}/usr/share/xml/docbook/xml-dtd-${ver}/"
  popd
  rm -rf docbook-xml-${ver}
  rm -rf docbook-xml-${ver}.zip
done

mkdir docbook-xml-4.1.2
pushd docbook-xml-4.1.2
unzip "../docbkx412.zip"
mkdir -p "${DEST}/usr/share/xml/docbook/xml-dtd-4.1.2"
cp -dRf docbook.cat *.dtd ent/ *.mod \
    "${DEST}/usr/share/xml/docbook/xml-dtd-4.1.2/"
popd
rm -rf docbook-xml-4.1.2
rm -rf docbkx412.zip

mkdir -p "${DEST}/etc/xml"
xmlcatalog --noout --create "${DEST}/etc/xml/docbook-xml"

xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML CALS Table Model V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/calstblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML CALS Table Model V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/calstblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/soextblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook XML Information Pool V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/dbpoolx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/dbhierx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook XML Additional General Entities V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/dbgenent.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook XML Notations V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/dbnotnx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook XML Character Entities V4.1.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.1.2/dbcentx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
  "http://www.oasis-open.org/docbook/xml/4.1.2" \
  "file:///usr/share/xml/docbook/xml-dtd-4.1.2" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
  "http://www.oasis-open.org/docbook/xml/4.1.2" \
  "file:///usr/share/xml/docbook/xml-dtd-4.1.2" \
  "${DEST}/etc/xml/docbook-xml"

xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook CALS Table Model V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/calstblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/soextblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook Information Pool V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/dbpoolx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook Document Hierarchy V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/dbhierx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Additional General Entities V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/dbgenent.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Notations V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/dbnotnx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Character Entities V4.2//EN" \
  "http://www.oasis-open.org/docbook/xml/4.2/dbcentx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
  "http://www.oasis-open.org/docbook/xml/4.2" \
  "file:///usr/share/xml/docbook/xml-dtd-4.2" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
  "http://www.oasis-open.org/docbook/xml/4.2" \
  "file:///usr/share/xml/docbook/xml-dtd-4.2" \
  "${DEST}/etc/xml/docbook-xml"

xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/docbookx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook CALS Table Model V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/calstblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/soextblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook Information Pool V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/dbpoolx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook Document Hierarchy V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/dbhierx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Additional General Entities V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/dbgenent.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Notations V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/dbnotnx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Character Entities V4.3//EN" \
  "http://www.oasis-open.org/docbook/xml/4.3/dbcentx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
  "http://www.oasis-open.org/docbook/xml/4.3" \
  "file:///usr/share/xml/docbook/xml-dtd-4.3" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
  "http://www.oasis-open.org/docbook/xml/4.3" \
  "file:///usr/share/xml/docbook/xml-dtd-4.3" \
  "${DEST}/etc/xml/docbook-xml"

xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook CALS Table Model V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/calstblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook XML HTML Tables V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/htmltblx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/soextblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook Information Pool V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/dbpoolx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook Document Hierarchy V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/dbhierx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Additional General Entities V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/dbgenent.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook Notations V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/dbnotnx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
   "-//OASIS//ENTITIES DocBook Character Entities V4.4//EN" \
  "http://www.oasis-open.org/docbook/xml/4.4/dbcentx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
  "http://www.oasis-open.org/docbook/xml/4.4" \
  "file:///usr/share/xml/docbook/xml-dtd-4.4" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
   "http://www.oasis-open.org/docbook/xml/4.4" \
  "file:///usr/share/xml/docbook/xml-dtd-4.4" \
  "${DEST}/etc/xml/docbook-xml"

xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML V4.5//EN" \
  "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD DocBook XML CALS Table Model V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/calstblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/soextblx.dtd" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook XML Information Pool V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/dbpoolx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/dbhierx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ELEMENTS DocBook XML HTML Tables V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/htmltblx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook XML Notations V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/dbnotnx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook XML Character Entities V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/dbcentx.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
  "-//OASIS//ENTITIES DocBook XML Additional General Entities V4.5//EN" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5/dbgenent.mod" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
  "http://www.oasis-open.org/docbook/xml/4.5" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5" \
  "${DEST}/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
  "http://www.oasis-open.org/docbook/xml/4.5" \
  "file:///usr/share/xml/docbook/xml-dtd-4.5" \
  "${DEST}/etc/xml/docbook-xml"

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -r --remove-destination $dir / ; done

if [ ! -e /etc/xml/catalog ]; then
  xmlcatalog --noout --create /etc/xml/catalog
fi

xmlcatalog --noout --add "delegatePublic" \
  "-//OASIS//ENTITIES DocBook XML" \
  "file:///etc/xml/docbook-xml" \
  /etc/xml/catalog
xmlcatalog --noout --add "delegatePublic" \
  "-//OASIS//DTD DocBook XML" \
  "file:///etc/xml/docbook-xml" \
  /etc/xml/catalog
xmlcatalog --noout --add "delegateSystem" \
  "http://www.oasis-open.org/docbook/" \
  "file:///etc/xml/docbook-xml" \
  /etc/xml/catalog
xmlcatalog --noout --add "delegateURI" \
  "http://www.oasis-open.org/docbook/" \
  "file:///etc/xml/docbook-xml" \
  /etc/xml/catalog
EOF

chmod 755 ${DEST}/INSTALL
