#!/bin/bash -e

export PKGNAME=gsm
export PKGVER=1.0.13
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-1.0-pl13
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export PATCHES_LIST=("gsm.patch")

configure_override() {
  true
}

make_override() {
  make CC="${DEFAULT_CC}" CCFLAGS="-c -fPIC ${CFLAGS}" ${MAKE_JOBS_FLAGS}
}

make_install_override() {
  install -dm755 ${DEST}/usr/bin ${DEST}/usr/include/gsm ${DEST}/usr/lib ${DEST}/usr/share/man/man1 ${DEST}/usr/share/man/man3

  make INSTALL_ROOT=${DEST}/usr \
       GSM_INSTALL_INC=${DEST}/usr/include/gsm \
       GSM_INSTALL_MAN=${DEST}/usr/share/man/man3 \
       TOAST_INSTALL_MAN=${DEST}/usr/share/man/man1 \
       install
}

. $(dirname $0)/master.sh
