#!/bin/bash -e

export PKGNAME=sudo
export PKGVER=1.8.18
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.sudo.ws/dist/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export POSTINST_TRIGGER=("chmod 4755 /usr/bin/sudo")
export CONFIGURE_FLAGS=(--libexecdir=/usr/lib
                        --with-all-insults
                        --with-env-editor
                        --with-pam
                        --with-rundir=/run/sudo
                        --with-passprompt="[sudo] password for %p: ")

make_install_post() {
  rm -rf ${DEST}/run

  install -dm755 ${DEST}/etc/pam.d ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/usr/lib/tmpfiles.d/sudo.conf << "EOF"
d /run/sudo 0711 root root -
EOF

cat > ${DEST}/etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF
}

. $(dirname $0)/master.sh
