#!/bin/bash -e

export VER=1.8.1
export DEST=/binary/seabios-${VER}

pushd seabios-${VER}

rm -rf binaries
mkdir binaries

make clean distclean

# Coreboot
cat > .config << "EOF"
CONFIG_QEMU_HARDWARE=y
CONFIG_COREBOOT=y
EOF

make oldnoconfig
make -j4

mv out/bios.bin.elf binaries/bios-coreboot.bin

make clean distclean

# CSM
cat > .config << "EOF"
CONFIG_QEMU_HARDWARE=y
CONFIG_CSM=y
EOF

make oldnoconfig
make -j4

mv out/Csm16.bin binaries/bios-csm.bin

make clean distclean

# SeaBios-128k
cat > .config << "EOF"
CONFIG_QEMU=y
CONFIG_ROM_SIZE=128
CONFIG_XEN=n
CONFIG_USB_XHCI=n
CONFIG_USB_UAS=n
EOF

make oldnoconfig
make -j4

mv out/bios.bin binaries/bios.bin

make clean distclean

# SeaBios-256k
cat > .config << "EOF"
CONFIG_QEMU=y
CONFIG_ROM_SIZE=256
EOF

make oldnoconfig
make -j4

mv out/bios.bin binaries/bios-256k.bin

cp out/src/fw/*dsdt*.aml binaries

make clean distclean

# VGA Cirrus
cat > .config << "EOF"
CONFIG_BUILD_VGABIOS=y
CONFIG_VGA_CIRRUS=y
CONFIG_VGA_PCI=y
EOF

make oldnoconfig
make -j4 out/vgabios.bin

mv out/vgabios.bin binaries/vgabios-cirrus.bin

make clean distclean

# VGA ISAVGA
cat > .config << "EOF"
CONFIG_BUILD_VGABIOS=y
CONFIG_VGA_BOCHS=y
CONFIG_VGA_PCI=n
EOF

make oldnoconfig
make -j4 out/vgabios.bin

mv out/vgabios.bin binaries/vgabios-isavga.bin

make clean distclean

# VGA QXL
cat > .config << "EOF"
CONFIG_BUILD_VGABIOS=y
CONFIG_VGA_BOCHS=y
CONFIG_VGA_PCI=y
CONFIG_OVERRIDE_PCI_ID=y
CONFIG_VGA_VID=0x1b36
CONFIG_VGA_DID=0x0100
EOF

make oldnoconfig
make -j4 out/vgabios.bin

mv out/vgabios.bin binaries/vgabios-qxl.bin

make clean distclean

# VGA STDVGA
cat > .config << "EOF"
CONFIG_BUILD_VGABIOS=y
CONFIG_VGA_BOCHS=y
CONFIG_VGA_PCI=y
EOF

make oldnoconfig
make -j4 out/vgabios.bin

mv out/vgabios.bin binaries/vgabios-stdvga.bin

make clean distclean

# VGA VMware
cat > .config << "EOF"
CONFIG_BUILD_VGABIOS=y
CONFIG_VGA_BOCHS=y
CONFIG_VGA_PCI=y
CONFIG_OVERRIDE_PCI_ID=y
CONFIG_VGA_VID=0x15ad
CONFIG_VGA_DID=0x0405
EOF

make oldnoconfig
make -j4 out/vgabios.bin

mv out/vgabios.bin binaries/vgabios-vmware.bin

chmod 644 binaries/*

install -dm755 ${DEST}/usr/share

mv binaries ${DEST}/usr/share/qemu

popd

rm -rf pushd seabios-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
