#!/bin/bash -e

export PKGNAME=flex
export PKGVER=2.6.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/westes/flex/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

make_install_post() {
  ln -sf flex ${DEST}/usr/bin/lex
}

. $(dirname $0)/master.sh
