#!/bin/bash -e

export PKGNAME=gegl
export PKGVER=0.3.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.gimp.org/pub/gegl/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-docs)

. $(dirname $0)/master.sh
