#!/bin/bash -e

export VER=2.0.2
export DEST=/binary/python-pygments-${VER}

cp -a Pygments-${VER} Pygments-${VER}-3

pushd Pygments-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

mv ${DEST}/usr/bin/pygmentize{,3}

popd

pushd Pygments-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf Pygments-${VER} Pygments-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
