#!/bin/bash -e

export PKGNAME=powertop
export PKGVER=2.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://01.org/sites/default/files/downloads/powertop/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

configure_pre() {
  sed -i "/stdlib.h/i #include <time.h>" src/devices/gpu_rapl_device.cpp src/parameters/learn.cpp
}

. $(dirname $0)/master.sh
