#!/bin/bash -e

export PKGNAME=run-parts
export PKGVER=4.6
export PKGTAR=debianutils_${PKGVER}.tar.xz
export PKGDIR=debianutils-${PKGVER}
export PKGURL="http://http.debian.net/debian/pool/main/d/debianutils/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

make_install_override() {
  install -Dm755 run-parts ${DEST}/usr/bin/run-parts
  install -Dm644 run-parts.8 ${DEST}/usr/share/man/man8/run-parts.8
}

. $(dirname $0)/master.sh
