#!/bin/bash -e

export PKGNAME=libgta
export PKGVER=1.0.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.savannah.gnu.org/releases/gta/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
