#!/bin/bash -e

export PKGNAME=intltool
export PKGVER=0.51.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://launchpad.net/intltool/trunk/${PKGVER}/+download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

configure_pre() {
  sed -i 's:\\\${:\\\$\\{:' intltool-update.in
}

. $(dirname $0)/master.sh
