#!/bin/bash -e

export VER=0.6.14
export DEST=/binary/docbook-utils-${VER}

pushd docbook-utils-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/docbook-utils.patch

./configure --prefix=/usr --mandir=/usr/share/man

make
make install DESTDIR=${DEST}

popd

rm -rf docbook-utils-${VER}

rm -rf ${DEST}/usr/doc

for type in dvi html man pdf ps rtf tex texi txt ; do
  ln -s docbook2${type} ${DEST}/usr/bin/db2${type}
done

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
