#!/bin/bash

export VER=5.7.2.1
export DEST=/binary/net-snmp-${VER}

pushd net-snmp-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/net-snmp-fixes.patch

autoreconf -fi

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr                                   \
            --sysconfdir=/etc                               \
            --disable-static                                \
            --enable-ipv6                                   \
            --enable-ucd-snmp-compatibility                 \
            --with-default-snmp-version="3"                 \
            --with-sys-contact="root@localhost"             \
            --with-sys-location="Unknown"                   \
            --with-logfile="/var/log/snmpd.log"             \
            --with-persistent-directory="/var/lib/net-snmp" \
            --with-perl-modules="INSTALLDIRS=vendor"        \
            --with-python-modules                           \
            --with-mib-modules="host misc/ipfwacc ucd-snmp/diskio tunnel ucd-snmp/dlmod"

make -j4

sed -i "s:install --basedir=\$\$dir:install --basedir=\$\$dir --root=${DEST}:" Makefile

make install DESTDIR=${DEST}

popd

rm -rf net-snmp-${VER}

rm -rf ${DEST}/usr/lib/perl ${DEST}/usr/lib/perl5/auto/Bundle

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

cp -rf --remove-destination usr/bin/net-snmp-config /usr/bin
cp -rf --remove-destination usr/share/snmp /usr/share
cp -rf --remove-destination usr/share/man/man1/net-snmp-config.1 /usr/share/man/man1
cp -rf --remove-destination usr/share/man/man3 /usr/share/man

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL

