#!/bin/bash -e

export PKGNAME=giflib
export PKGVER=5.1.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/giflib/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
