#!/bin/bash -e

export PKGNAME=libwebp
export PKGVER=0.5.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://downloads.webmproject.org/releases/webp/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

export CONFIGURE_FLAGS=(--enable-swap-16bit-csp
                        --enable-experimental
                        --enable-libwebpdecoder
                        --enable-libwebpdemux
                        --enable-libwebpmux)

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
