#!/bin/bash -e

export VER=0.38.3
export DEST=/binary/vte-${VER}

pushd vte-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --enable-introspection

make -j4
make install DESTDIR=${DEST}

popd

rm -rf vte-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/etc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
