#!/bin/bash -e

export PKGNAME=cmrt
export PKGVER=1.0.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/01org/cmrt/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  autoreconf -fi
}

make_install_post() {
  install -m755 jitter/igfxcmjit64.so ${DEST}/usr/lib
}

. $(dirname $0)/master.sh
