#!/bin/bash -e

export VER=1.2.20140412
export DEST=/binary/opencl-headers-${VER}

install -dm755 ${DEST}/usr/include/CL

for file in cl.h cl.hpp cl_egl.h cl_ext.h cl_gl.h \
            cl_gl_ext.h cl_platform.h opencl.h
do
  wget http://www.khronos.org/registry/cl/api/1.2/${file} -O ${DEST}/usr/include/CL/${file}
done

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
