#!/bin/bash -e

export VER=11.0.2
export DEST=/binary/mesa-${VER}

pushd mesa-${VER}
  patch -Np1 -i /media/ntfs/Other/Linux/patches/mesalib-xdemos.patch

  sed -i 's/LLVM_SO_NAME=.*/LLVM_SO_NAME=LLVM/' configure
popd

cp -a mesa-${VER} mesa-${VER}-32

pushd mesa-${VER}

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --disable-xvmc            \
            --enable-texture-float    \
            --enable-gles1            \
            --enable-gles2            \
            --enable-gbm              \
            --enable-vdpau            \
            --enable-omx              \
            --enable-va               \
            --enable-opencl           \
            --enable-opencl-icd       \
            --enable-glx-tls          \
            --enable-llvm-shared-libs \
            --with-dri-drivers="i965" \
            --with-egl-platforms="drm,x11,wayland" \
            --with-gallium-drivers="r600,swrast"

make -j4
make -C xdemos

make install DESTDIR=${DEST}
make -C xdemos install DESTDIR=${DEST}

popd

pushd mesa-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
export LLVM_CONFIG=/usr/bin/llvm-config32

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --libdir=/usr/lib32       \
            --disable-xvmc            \
            --enable-texture-float    \
            --enable-gles1            \
            --enable-gles2            \
            --enable-vdpau            \
            --enable-omx              \
            --enable-va               \
            --enable-opencl           \
            --enable-opencl-icd       \
            --enable-glx-tls          \
            --enable-llvm-shared-libs \
            --with-dri-drivers="i965" \
            --with-egl-platforms="drm,x11,wayland" \
            --with-gallium-drivers="r600,swrast"   \
            --build=i686-pc-linux-gnu \
            --host=i686-pc-linux-gnu

make -j4
make -C xdemos EXT=32 CC="${CC}"

make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr/

install -m755 xdemos/glxinfo32 ${DEST}/usr/bin/
install -m755 xdemos/glxgears32 ${DEST}/usr/bin/

popd

rm -rf mesa-${VER} mesa-${VER}-32

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}-debug/usr/lib

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

mv ${DEST}/usr/lib/debug ${DEST}-debug/usr/lib

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
