#!/bin/bash -e

export VER=2.7
export DEST=/binary/faad2-${VER}

pushd faad2-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/faad2-fixes.patch

sed -i "s:AM_CONFIG_HEADER:AC_CONFIG_HEADERS:g" configure.in
sed -i "s:man_MANS:man1_MANS:g" frontend/Makefile.am
autoreconf -fi

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf faad2-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
