#!/bin/bash -e

export PKGNAME=expat
export PKGVER=2.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/expat/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export PATCHES_LIST=("expat-fixes.patch")
export PATCHES_LIST_32=("expat-fixes.patch")

. $(dirname $0)/master.sh
