#!/bin/bash -e

export PKGNAME=libteam
export PKGVER=1.23
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://libteam.org/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

make_install_post() {
  install -Dm644 teamd/redhat/systemd/teamd@.service ${DEST}/lib/systemd/system/teamd@.service
  install -Dm644 teamd/dbus/teamd.conf ${DEST}/etc/dbus-1/system.d/teamd.conf
}

. $(dirname $0)/master.sh
