#!/bin/bash -e

export PKGNAME=libva
export PKGVER=1.6.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.freedesktop.org/software/vaapi/releases/libva/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

post_install_config() {
  rm -rf ${DEST}/usr/lib/dri ${DEST}/usr/lib32/dri
}

. $(dirname $0)/master.sh
