#!/bin/bash -e

export DEST=/binary/xorg

export LIB=/media/ntfs/Other/Linux/lib.wget
export XORG_HTTP=http://xorg.freedesktop.org/archive/individual

export LIB_HTTP=${XORG_HTTP}/lib/
export XCB_HTTP=${XORG_HTTP}/xcb

export LIBXAU_VER=1.0.8
export LIBXDMCP_VER=1.1.2
export LIBXCB_VER=1.11.1

export CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -I${DEST}/tmp/usr/include -I${DEST}/tmp/usr/include/X11 -I${DEST}/tmp/usr/include/GL"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:${DEST}/tmp/usr/lib32/pkgconfig:${DEST}/tmp/usr/lib/pkgconfig:${DEST}/tmp/usr/share/pkgconfig"
export LD_LIBRARY_PATH="${DEST}/tmp/usr/lib:${DEST}/tmp/usr/lib32"
export LDFLAGS="-L${DEST}/tmp/usr/lib32 -L${DEST}/tmp/usr/lib"

export CONFIG="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static"
export CONFIG_32="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib32 --disable-static"

sed -i "/xtrans/d" ${LIB}

mkdir -p lib

pushd lib
  grep -v '^#' ${LIB} | awk '{print $2}' | wget -i- -c -B ${LIB_HTTP}
  md5sum -c ${LIB}
popd

wget -c ${LIB_HTTP}/libXau-${LIBXAU_VER}.tar.bz2
wget -c ${LIB_HTTP}/libXdmcp-${LIBXDMCP_VER}.tar.bz2
wget -c ${XCB_HTTP}/libxcb-${LIBXCB_VER}.tar.bz2

tar xf libXau-${LIBXAU_VER}.tar.bz2

pushd libXau-${LIBXAU_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/lib/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
  rm -rf ${DEST}/$(basename $PWD)/usr/share/doc
popd

rm -rf libXau-${LIBXAU_VER}

tar xf libXdmcp-${LIBXDMCP_VER}.tar.bz2

pushd libXdmcp-${LIBXDMCP_VER}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/lib/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
  rm -rf ${DEST}/$(basename $PWD)/usr/share/doc
popd

rm -rf libXdmcp-${LIBXDMCP_VER}

tar xf libxcb-${LIBXCB_VER}.tar.bz2

pushd libxcb-${LIBXCB_VER}
  sed -e "s/pthread-stubs//" -i configure.ac
  autoreconf -fi
  ./configure ${CONFIG} --enable-xinput
  make -j4
  make install DESTDIR=${DEST}/lib/$(basename $PWD)
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
  rm -rf ${DEST}/$(basename $PWD)/usr/share/doc
popd

rm -rf libxcb-${LIBXCB_VER}

pushd lib

for package in $(grep -v '^#' ${LIB} | awk '{print $2}')
do
  packagedir=${package%.tar.bz2}
  tar -xf ${package}
  pushd ${packagedir}
  ./configure ${CONFIG}
  make -j4
  make install DESTDIR=${DEST}/lib/${packagedir}
  make install DESTDIR=${DEST}/tmp
  rm -rf ${DEST}/tmp/usr/lib*/*.la
  popd
  rm -rf ${packagedir}
done

popd

# 32 bit

export CC="gcc -m32"
export CXX="g++ -m32"

tar xf libXau-${LIBXAU_VER}.tar.bz2

pushd libXau-${LIBXAU_VER}
  ./configure ${CONFIG_32}
  make -j4
  make install DESTDIR=${PWD}/dest
  rm -rf dest/usr/lib32/*.la
  cp -a dest/usr/lib32 ${DEST}/tmp/usr
  mv dest/usr/lib32 ${DEST}/lib/$(basename $PWD)/usr
popd

rm -rf libXau-${LIBXAU_VER}

tar xf libXdmcp-${LIBXDMCP_VER}.tar.bz2

pushd libXdmcp-${LIBXDMCP_VER}
  ./configure ${CONFIG_32}
  make -j4
  make install DESTDIR=${PWD}/dest
  rm -rf dest/usr/lib32/*.la
  cp -a dest/usr/lib32 ${DEST}/tmp/usr
  mv dest/usr/lib32 ${DEST}/lib/$(basename $PWD)/usr
popd

rm -rf libXdmcp-${LIBXDMCP_VER}

tar xf libxcb-${LIBXCB_VER}.tar.bz2

pushd libxcb-${LIBXCB_VER}
  sed -e "s/pthread-stubs//" -i configure.ac
  autoreconf -fi
  ./configure ${CONFIG_32} --enable-xinput
  make -j4
  make install DESTDIR=${PWD}/dest
  rm -rf dest/usr/lib32/*.la
  cp -a dest/usr/lib32 ${DEST}/tmp/usr
  mv dest/usr/lib32 ${DEST}/lib/$(basename $PWD)/usr
popd

rm -rf libxcb-${LIBXCB_VER}

pushd lib

for package in $(grep -v '^#' ${LIB} | awk '{print $2}')
do
  packagedir=${package%.tar.bz2}
  tar -xf ${package}
  pushd ${packagedir}
  ./configure ${CONFIG_32}
  make -j4
  make install DESTDIR=${PWD}/dest
  rm -rf dest/usr/lib32/*.la
  cp -a dest/usr/lib32 ${DEST}/tmp/usr
  mv dest/usr/lib32 ${DEST}/lib/${packagedir}/usr
  popd
  rm -rf ${packagedir}
done

popd

rm -rf ${DEST}/lib/*/usr/share/doc
rmdir ${DEST}/lib/*/usr/share || true

find ${DEST}/lib -name "*.la" -delete

pushd ${DEST}/lib

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

rm -rf ${DEST}/tmp

rm -rf lib libXau-${LIBXAU_VER}.tar.bz2 libXdmcp-${LIBXDMCP_VER}.tar.bz2 libxcb-${LIBXCB_VER}.tar.bz2

for dir in ${DEST}/lib/*
do

cat > ${dir}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

EOF

if [ -e ${dir}/usr/share/man ]; then
cat >> ${dir}/INSTALL << "EOF"
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF
fi

cat >> ${dir}/INSTALL << "EOF"
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${dir}/INSTALL

done

find ${DEST}/lib/libXtst-*/usr/share/man/ -type f -name '*.[[:digit:]]' -exec sed -ri '1s|^\.so (.*)\.([0-9]+)|.so man\2/\1.\2|' {} +
