#!/bin/bash -e

export VER=0.4.4
export DEST=/binary/dmz-cursor-theme-${VER}

pushd dmz-cursor-theme-${VER}

for d in DMZ-Black DMZ-White
do
  pushd ${d}/pngs
    ./make.sh
  popd
  install -dm755 ${DEST}/usr/share/icons/${d}/cursors
  install -m644 ${d}/*.theme ${DEST}/usr/share/icons/${d}
  cp -r ${d}/xcursors/* ${DEST}/usr/share/icons/${d}/cursors
done

install -dm755 ${DEST}/usr/share/icons/default
ln -sf ../DMZ-White/cursor.theme ${DEST}/usr/share/icons/default/index.theme

popd

rm -rf dmz-cursor-theme-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
