#!/bin/bash -e

export PKGNAME=libclc
export PKGVER=0.2.0.svn258623
export MAKE_JOBS_FLAGS="-j4"
export NO_STRIP=1

configure_override() {
  ./configure.py --prefix=/usr

  sed -i "s#clang++#& -stdlib=libc++#g" Makefile
}

. $(dirname $0)/master.sh
