#!/bin/bash -e

export PKGNAME=freetype
export PKGVER=2.6.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/freetype/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

configure_pre() {
  sed -i  -e "/AUX.*.gxvalid/s@^# @@" \
          -e "/AUX.*.otvalid/s@^# @@" \
          modules.cfg

  sed -ri -e 's:.*(#.*SUBPIXEL.*) .*:\1:' \
          include/freetype/config/ftoption.h
}

configure_pre_32() {
  sed -i  -e "/AUX.*.gxvalid/s@^# @@" \
          -e "/AUX.*.otvalid/s@^# @@" \
          modules.cfg

  sed -ri -e 's:.*(#.*SUBPIXEL.*) .*:\1:' \
          include/freetype/config/ftoption.h
}

. $(dirname $0)/master.sh
