#!/bin/bash -e

export PKGNAME=libcanberra
export PKGVER=0.30
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://0pointer.de/lennart/projects/libcanberra/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("libcanberra.patch")
export CONFIGURE_FLAGS=(--disable-null --disable-oss)

. $(dirname $0)/master.sh
