#!/bin/bash -e

export PKGNAME=guile
export PKGVER=2.0.12
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/guile/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

make_install_post() {
  rm -rf ${DEST}/usr/lib/*.scm
}

. $(dirname $0)/master.sh
