#!/bin/bash -e

export PKGNAME=aspell
export PKGVER=0.60.6.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/aspell/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("aspell-fixes.patch")

. $(dirname $0)/master.sh
