#!/bin/bash -e

export VER=1.3.1
export DEST=/binary/python-sphinx-${VER}

cp -a Sphinx-${VER} Sphinx-${VER}-3

pushd Sphinx-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

for file in ${DEST}/usr/bin/*
do
  mv ${file} ${file}3
done

popd

pushd Sphinx-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf Sphinx-${VER} Sphinx-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
