#!/bin/bash -e

export PKGNAME=libaio
export PKGVER=0.3.110
export PKGTAR=${PKGNAME}_${PKGVER}.orig.tar.gz
export PKGURL="http://http.debian.net/debian/pool/main/liba/libaio/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_INSTALL_FLAGS="prefix=\${DEST}/usr"

configure_override() {
  true
}

post_install_config() {
  rm -rf ${DEST}/usr/lib*/*.a
}

. $(dirname $0)/master.sh
