#!/bin/bash -e

export PKGNAME=gimp
export PKGVER=2.9.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.gimp.org/pub/gimp/v${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export CONFIGURE_FLAGS=(--with-lcms=lcms2)

. $(dirname $0)/master.sh
