#!/bin/bash -e

export PKGNAME=accountsservice
export PKGVER=0.6.43
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.freedesktop.org/software/accountsservice/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export CONFIGURE_FLAGS=(--enable-admin-group=adm)

. $(dirname $0)/master.sh
