#!/bin/bash -e

export VER=2.3.4
export DEST=/binary/qtwebkit-${VER}

export QTDIR=/usr

install -dm755 ${PWD}/qtwebkit

pushd qtwebkit
  tar xf ../qtwebkit-${VER}.tar.gz
  patch -Np1 -i /media/ntfs/Other/Linux/patches/qtwebkit4.patch
popd

cp -a qtwebkit qtwebkit-32

pushd qtwebkit

Tools/Scripts/build-webkit --qt --no-webkit2 --prefix=/usr --qmakearg='"QMAKE_CFLAGS=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w" "QMAKE_CXXFLAGS=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w"' --makeargs="-j4"

make INSTALL_ROOT=${DEST} -C WebKitBuild/Release install

perl -pi -e "s, -L${PWD}/?\S+,,g" ${DEST}/usr/lib/pkgconfig/QtWebKit.pc
sed -i -e '/^QMAKE_PRL_BUILD_DIR/d;s/\(QMAKE_PRL_LIBS =\).*/\1/' ${DEST}/usr/lib/libQtWebKit.prl

popd

pushd qtwebkit-32

Tools/Scripts/build-webkit --qt --no-webkit2 --prefix=/usr --install-headers=/usr/lib32/qt4/include --install-libs=/usr/lib32 --qmakearg='-spec linux-g++-32 "QMAKE_CFLAGS=-m32 -march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w" "QMAKE_CXXFLAGS=-m32 -march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w"' --makeargs="-j4"

make INSTALL_ROOT=${PWD}/dest -C WebKitBuild/Release install

mv dest/usr/lib32 ${DEST}/usr
mv dest/usr/lib/qt4/imports ${DEST}/usr/lib32/qt4

perl -pi -e "s, -L${PWD}/?\S+,,g" ${DEST}/usr/lib32/pkgconfig/QtWebKit.pc
sed -i -e '/^QMAKE_PRL_BUILD_DIR/d;s/\(QMAKE_PRL_LIBS =\).*/\1/' ${DEST}/usr/lib32/libQtWebKit.prl

popd

rm -rf qtwebkit qtwebkit-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
