#!/bin/bash -e

export PKGNAME=libass
export PKGVER=0.13.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/libass/libass/releases/download/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS_32=(--disable-asm)

. $(dirname $0)/master.sh
