#!/bin/bash -e

export PKGNAME=libnftnl
export PKGVER=1.0.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.netfilter.org/projects/libnftnl/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
