#!/bin/bash -e

export VER=6.1.19
export DEST=/binary/db-${VER}

pushd db-${VER}/build_unix

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../dist/configure --prefix=/usr      \
                  --disable-static   \
                  --enable-compat185 \
                  --enable-cxx       \
                  --enable-dbm       \
                  --enable-stl       \
                  --enable-sql       \
                  --enable-tcl       \
                  --with-tcl=/usr/lib

make -j4
make install DESTDIR=${DEST}

popd

rm -rf db-${VER}

rm -rf ${DEST}/usr/docs

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
