#!/bin/bash -e

export PKGNAME=libdrm
export PKGVER=2.4.74
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://dri.freedesktop.org/libdrm/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-udev --disable-valgrind)

configure_pre() {
  sed -e "/pthread-stubs/d" -i configure.ac
  autoreconf -fi
}

. $(dirname $0)/master.sh
