#!/bin/bash -e

export PKGNAME=libomxil-bellagio
export PKGVER=0.9.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/omxil/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export PATCHES_LIST=("libomxil-bellagio-fixes.patch")
export PATCHES_LIST_32=("libomxil-bellagio-fixes.patch")

configure_pre() {
  autoreconf -fi
}

configure_pre_32() {
  autoreconf -fi
}

make_install_post_32() {
  mv dest/usr/bin/omxregister-bellagio ${DEST}/usr/bin/omxregister-bellagio-32
}

. $(dirname $0)/master.sh
