#!/bin/bash -e

export PKGNAME=ruby
export PKGVER=2.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://cache.ruby-lang.org/pub/ruby/2.3/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export KEEP_STATIC=1
export CONFIGURE_FLAGS=(--enable-shared --disable-install-capi)

. $(dirname $0)/master.sh
