#!/bin/bash -e

export VER=0.99
export DEST=/binary/perl-xml-sax-${VER}

pushd XML-SAX-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/perl-xml-sax.patch

perl Makefile.PL INSTALLDIRS=vendor

make -j4
make install DESTDIR=${DEST}

popd

rm -rf XML-SAX-${VER}

rm -rf ${DEST}/usr/lib

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
