#!/bin/bash -e

export PKGNAME=raptor2
export PKGVER=2.0.15
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://download.librdf.org/source/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-icu-config=/usr/bin/icu-config)

. $(dirname $0)/master.sh
