#!/bin/bash -e

export VER=2.9
export DEST=/binary/qscintilla-${VER}

pushd QScintilla-gpl-${VER}

popd

pushd QScintilla-gpl-${VER}/Qt4Qt5

qmake-qt5 qscintilla.pro "QMAKE_CFLAGS+=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" "QMAKE_CXXFLAGS+=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"

make -j4
make install INSTALL_ROOT=${DEST}

popd

pushd QScintilla-gpl-${VER}/designer-Qt4Qt5

qmake-qt5 designer.pro INCLUDEPATH+=../Qt4Qt5 QMAKE_LIBDIR+=../Qt4Qt5 "QMAKE_CFLAGS+=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" "QMAKE_CXXFLAGS+=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"

make -j4
make install INSTALL_ROOT=${DEST}

popd

rm -rf QScintilla-gpl-${VER}

pushd ${DEST}

find ${DEST} -name "*.so" -exec chmod 755 {} \;

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
