#!/bin/bash -e

export PKGNAME=libtxc_dxtn
export PKGVER=1.0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://people.freedesktop.org/~cbrill/libtxc_dxtn/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
#export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
