#!/bin/bash -e

export PKGNAME=zeitgeist
export PKGVER=0.9.16
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export PKGURL="https://launchpad.net/zeitgeist/${PKGVER:0:3}/${PKGVER}/+download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
