#!/bin/bash -e

export VER=1.3.21
export DEST=/binary/GraphicsMagick-${VER}

pushd GraphicsMagick-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr           \
            --disable-static        \
            --enable-shared         \
            --with-modules          \
            --with-perl             \
            --with-quantum-depth=16 \
            --with-gs-font-dir=/usr/share/ghostscript/fonts

make -j4
make install DESTDIR=${DEST}

pushd PerlMagick

sed -i -e "s:'LDDLFLAGS'  => \"\(.*\)\":'LDDLFLAGS'  => \"-L${DEST}/usr/lib \1\":" Makefile.PL

perl Makefile.PL INSTALLDIRS=vendor PREFIX=/usr DESTDIR="${DEST}"

sed -i -e "s/LDLOADLIBS =/LDLOADLIBS = -lGraphicsMagick/" Makefile

make -j4
make install

popd

popd

rm -rf GraphicsMagick-${VER}

rm -rf ${DEST}/usr/lib/*.la
rm -rf ${DEST}/usr/lib/perl
rm -rf ${DEST}/usr/lib/perl5/auto/Graphics/Magick/.packlist
rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
