#!/bin/bash -e

export VER=0.10.13
export DEST=/binary/gst-ffmpeg-${VER}

pushd gst-ffmpeg-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/gst-ffmpeg-fixes.patch

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --with-package-name="GStreamer FFMpeg Plugins ${VER} BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/systemd/"

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gst-ffmpeg-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
