#!/bin/bash -e

export VER=1.48.04
export DEST=/binary/espeak-${VER}

pushd espeak-${VER}-source/src

cp portaudio19.h portaudio.h

make CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" AUDIO=runtime -j4
make install DESTDIR=${DEST}

popd

rm -rf espeak-${VER}-source

find ${DEST} -name "*.a" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
