#!/bin/bash -e

export PKGNAME=yasm
export PKGVER=1.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.tortall.net/projects/yasm/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
