#!/bin/bash -e

export VER=4.0.1
export DEST=/binary/btrfs-progs-${VER}

pushd btrfs-progs-v${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" ./configure --prefix=/usr --bindir=/sbin

make
make install DESTDIR=${DEST}

popd

rm -rf btrfs-progs-v${VER}

rm -rf ${DEST}/usr/lib/libbtrfs.a ${DEST}/usr/share/man/man8/{btrfsck,btrfs-zero-log}.8.gz

ln -sf btrfs-check.8 ${DEST}/usr/share/man/man8/btrfsck.8
ln -sf btrfs-rescue.8 ${DEST}/usr/share/man/man8/btrfs-zero-log.8

gzip -d ${DEST}/usr/share/man/*/*.gz

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/libbtrfs.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libbtrfs.so) ${DEST}/usr/lib/libbtrfs.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
