#!/bin/bash -e

export VER=2.1.1
export DEST=/binary/python-babel-${VER}

cp -a Babel-${VER} Babel-${VER}-3

pushd Babel-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

mv ${DEST}/usr/bin/pybabel{,3}

popd

pushd Babel-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf Babel-${VER} Babel-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
