#!/bin/bash -e

export MAJORVER=3.5
export VER=${MAJORVER}.0
export DEST=/binary/Python-${VER}

pushd Python-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/python3-bdb.patch

sed -i -e "s|^#.* /usr/local/bin/python|#!/usr/bin/python3|" Lib/cgi.py

rm -r Modules/expat
rm -r Modules/zlib
rm -r Modules/_ctypes/{darwin,libffi}*

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr         \
            --enable-shared       \
            --with-system-expat   \
            --with-system-ffi     \
            --without-ensurepip   \
            --with-dbmliborder=bdb:gdbm:ndbm

make -j4
make install DESTDIR=${DEST}

sed -i "s#$PWD:##" ${DEST}/usr/lib/python${MAJORVER}/config-${MAJORVER}m/Makefile ${DEST}/usr/lib/python${MAJORVER}/_sysconfigdata.py
sed -i "s#$PWD##" ${DEST}/usr/lib/python${MAJORVER}/config-${MAJORVER}m/Makefile ${DEST}/usr/lib/python${MAJORVER}/_sysconfigdata.py

popd

rm -rf Python-${VER}

chmod 755 ${DEST}/usr/lib/libpython${MAJORVER}m.so ${DEST}/usr/lib/libpython3.so

rm -rf ${DEST}/usr/lib/python${MAJORVER}/{distutils/tests,unittest/test,lib2to3/tests,idlelib/idle_test}
rm -rf ${DEST}/usr/lib/python${MAJORVER}/{ctypes/test,tkinter/test,test,sqlite3/test}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
