#!/bin/bash -e

export VER=2.21.0
export DEST=/binary/gtk-engines-${VER}

tar xf /media/ntfs/Other/Linux/packages/gtk-engines-${VER}.tar.gz

pushd gtk-engines-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --enable-animation

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gtk-engines-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
