#!/bin/bash -e

export PKGNAME=exempi
export PKGVER=2.2.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://libopenraw.freedesktop.org/download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

. $(dirname $0)/master.sh
