#!/bin/bash -e

export PKGNAME=hexchat
export PKGVER=2.12.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://dl.hexchat.net/hexchat/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-textfe --enable-python=python3)

. $(dirname $0)/master.sh
