#!/bin/bash -e

export PKGVER=15.11.80
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export KEEP_DOC=1

export CMAKE_FLAGS=(-DSYSCONF_INSTALL_DIR=/etc
                    -DLIB_INSTALL_DIR=lib
                    -DBUILD_TESTING=OFF
                    -DQML_INSTALL_DIR=lib/qt5/qml
                    -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins
                    -DECM_MKSPECS_INSTALL_DIR=/usr/lib/qt5/mkspecs/modules)

case $(basename $0) in
  buildark )
    export PKGNAME=ark
  ;;
  buildbaloo-widgets )
    export PKGNAME=baloo-widgets
    export DEBUG_BUILD=1
  ;;
  builddolphin )
    export PKGNAME=dolphin
  ;;
  buildgwenview )
    export PKGNAME=gwenview
  ;;
  buildk3b )
    export PKGNAME=k3b
    export PKGVER=2.9.90+d5b1016
  ;;
  buildkate )
    export PKGNAME=kate
  ;;
  buildkcalc )
    export PKGNAME=kcalc
  ;;
  buildkdebugsettings )
    export PKGNAME=kdebugsettings
  ;;
  buildkile )
    export PKGNAME=kile
    export PKGVER=2.1+6e914a7
  ;;
  buildkio-extras )
    export PKGNAME=kio-extras
  ;;
  buildkonsole )
    export PKGNAME=konsole
  ;;
  buildksystemlog )
    export PKGNAME=ksystemlog
  ;;
  buildkwalletmanager )
    export PKGNAME=kwalletmanager
  ;;
  buildlibkcddb )
    export PKGNAME=libkcddb
    export PKGVER=4.13.80+1b6ba68
  ;;
  buildlibkdcraw )
    export PKGNAME=libkdcraw
  ;;
  buildlibkexiv2 )
    export PKGNAME=libkexiv2
  ;;
  buildlibkipi )
    export PKGNAME=libkipi
  ;;
  buildlibksane )
    export PKGNAME=libksane
  ;;
  buildokular )
    export PKGNAME=okular
    export PKGVER=15.08.0+709121c
  ;;
  buildskanlite )
    export PKGNAME=skanlite
    export PKGVER=1.1+0999e40
  ;;
  buildsmb4k )
    export PKGNAME=smb4k
    export PKGVER=1.9.65
  ;;
  buildspectacle )
    export PKGNAME=spectacle
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.kde.org/unstable/applications/${PKGVER}/src/${PKGTAR}"
export DEST=/binary/plasma/${PKGNAME}-${PKGVER}

. $(dirname $0)/master.sh
