#!/bin/bash -e

export VER=1.5
export DEST=/binary/Orion-${VER}

pushd Orion-${VER}

install -dm755 ${DEST}/usr/share/themes/Orion

mv gtk-2.0 gtk-3.0 index.theme ${DEST}/usr/share/themes/Orion
mv metacity-1 openbox-3 xfwm4 ${DEST}/usr/share/themes/Orion

popd

rm -rf Orion-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
