#!/bin/bash -e

export PKGNAME=libtasn1
export PKGVER=4.9
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/libtasn1/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-gcc-warnings)

make_install_post() {
  make -C doc/reference install-data-local DESTDIR=${DEST}
}

. $(dirname $0)/master.sh
