#!/bin/bash -e

export PKGNAME=x265
export PKGVER=2.0
export PKGTAR=${PKGNAME}_${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}_${PKGVER}
export PKGBUILD=${PKGDIR}/build/linux
export PKGURL="https://bitbucket.org/multicoreware/x265/downloads/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export PATH_TO_SOURCE="../../source"
export CMAKE_BUILD=1

post_install_config() {
  find ${DEST} -name "*.a" -delete
}

. $(dirname $0)/master.sh
