#!/bin/bash -e

export PKGNAME=openjade
export PKGVER=1.3.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/openjade/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("openjade.patch")

export POSTINST_TRIGGER=("install-catalog --add /etc/sgml/OpenJade.cat /usr/share/sgml/OpenJade/catalog"
                         "install-catalog --add /etc/sgml/sgml-docbook.cat /etc/sgml/OpenJade.cat")

export CONFIGURE_FLAGS=(--datadir=/usr/share/sgml/OpenJade
                        --mandir=/usr/share/man
                        --enable-http
                        --enable-default-catalog=/etc/sgml/catalog
                        --enable-default-search-path=/usr/share/sgml)

export MAKE_INSTALL_FLAGS="install-man"

make_install_post() {
  install -m644 dsssl/catalog ${DEST}/usr/share/sgml/OpenJade
  install -m644 dsssl/*.{dtd,dsl,sgm} ${DEST}/usr/share/sgml/OpenJade

  ln -sf openjade ${DEST}/usr/bin/jade

  for file in grove spgrove style
  do
    ln -sf libo${file}.so ${DEST}/usr/lib/lib${file}.so
  done
}

. $(dirname $0)/master.sh
