#!/bin/bash -e

export VER=5.9-20150425
export DEST=/binary/ncurses-${VER}

pushd ncurses-${VER}

install -dm755 buildncursesw6 buildncursesw buildncurses
install -dm755 buildncursesw6-32 buildncursesw-32 buildncurses-32

pushd buildncursesw6

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr \
             --libdir=/usr/lib \
             --with-pkg-config-libdir=/usr/lib/pkgconfig \
             --mandir=/usr/share/man \
             --with-shared \
             --without-debug \
             --enable-pc-files \
             --enable-widec \
             --enable-ext-colors \
             --enable-ext-mouse

make -j4
make install DESTDIR=${DEST}

popd

pushd buildncursesw

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr \
             --libdir=/usr/lib \
             --mandir=/usr/share/man \
             --with-shared \
             --without-debug \
             --enable-widec

make -j4

for lib in ncursesw formw panelw menuw; do
  install -m755 lib/lib${lib}.so.5.9 ${DEST}/usr/lib
  ln -sf lib${lib}.so.5.9 ${DEST}/usr/lib/lib${lib}.so.5
done

popd

pushd buildncurses

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr \
             --libdir=/usr/lib \
             --mandir=/usr/share/man \
             --with-shared \
             --without-debug \
             --with-chtype=long

make -j4

for lib in ncurses form panel menu; do
  install -m755 lib/lib${lib}.so.5.9 ${DEST}/usr/lib
  ln -sf lib${lib}.so.5.9 ${DEST}/usr/lib/lib${lib}.so.5
done

popd

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

pushd buildncursesw6-32

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr \
             --libdir=/usr/lib32 \
             --with-pkg-config-libdir=/usr/lib32/pkgconfig \
             --mandir=/usr/share/man \
             --with-shared \
             --without-debug \
             --enable-pc-files \
             --enable-widec \
             --enable-ext-colors \
             --enable-ext-mouse

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

pushd buildncursesw-32

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr \
             --libdir=/usr/lib32 \
             --mandir=/usr/share/man \
             --with-shared \
             --without-debug \
             --enable-widec

make -j4

for lib in ncursesw formw panelw menuw; do
  install -m755 lib/lib${lib}.so.5.9 ${DEST}/usr/lib32
  ln -sf lib${lib}.so.5.9 ${DEST}/usr/lib32/lib${lib}.so.5
done

popd

pushd buildncurses-32

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr \
             --libdir=/usr/lib32 \
             --mandir=/usr/share/man \
             --with-shared \
             --without-debug \
             --with-chtype=long

make -j4

for lib in ncurses form panel menu; do
  install -m755 lib/lib${lib}.so.5.9 ${DEST}/usr/lib32
  ln -sf lib${lib}.so.5.9 ${DEST}/usr/lib32/lib${lib}.so.5
done

popd

popd

rm -rf ncurses-${VER}

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/libncursesw.so.6{,.0} ${DEST}/lib
ln -sf ../../lib/libncursesw.so.6.0 ${DEST}/usr/lib/libncursesw.so

for lib in ncurses form panel menu ; do
  rm -rf ${DEST}/usr/lib/lib${lib}.so
  rm -rf ${DEST}/usr/lib32/lib${lib}.so
  echo "INPUT(-l${lib}w)" > ${DEST}/usr/lib/lib${lib}.so
  echo "INPUT(-l${lib}w)" > ${DEST}/usr/lib32/lib${lib}.so
done

for lib in ncurses ncurses++ form panel menu; do
  ln -sf ${lib}w.pc ${DEST}/usr/lib/pkgconfig/${lib}.pc
  ln -sf ${lib}w.pc ${DEST}/usr/lib32/pkgconfig/${lib}.pc
done

rm -rf ${DEST}/usr/lib/libcursesw.so
rm -rf ${DEST}/usr/lib32/libcursesw.so
echo "INPUT(-lncursesw)" > ${DEST}/usr/lib/libcursesw.so
echo "INPUT(-lncursesw)" > ${DEST}/usr/lib32/libcursesw.so
ln -sf libncurses.so ${DEST}/usr/lib/libcurses.so
ln -sf libncurses.so ${DEST}/usr/lib32/libcurses.so

rm -rf ${DEST}/usr/lib/*.a
rm -rf ${DEST}/usr/lib32/*.a

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
