#!/bin/bash -e

export PKGNAME=libsamplerate
export PKGVER=0.1.9
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.mega-nerd.com/SRC/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS_32=(--disable-fftw)

. $(dirname $0)/master.sh
