#!/bin/bash -e

export VER=3.14.1
export DEST=/binary/adwaita-icon-theme-${VER}

pushd adwaita-icon-theme-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf adwaita-icon-theme-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for adwaita-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/Adwaita
EOF

chmod 755 ${DEST}/INSTALL
