#!/bin/bash -e

export VER=1.13.2
export DEST=/binary/krb5-${VER}

pushd krb5-${VER}

if [ -e /media/ntfs/Other/Linux/patches/krb5-fixes.patch ]
then
   patch -Np1 -i /media/ntfs/Other/Linux/patches/krb5-fixes.patch
fi

popd

pushd krb5-${VER}/src

sed -e "s@python2.5/Python.h@& python2.7/Python.h@g" \
    -e "s@-lpython2.5]@&,\n  AC_CHECK_LIB(python2.7,main,[PYTHON_LIB=-lpython2.7])@g" \
    -i configure.in

sed -e "/KRB5ROOT=/s@/local@@" \
    -i util/ac_check_krb5.m4

autoconf

popd

cp -a krb5-${VER} krb5-${VER}-32

pushd krb5-${VER}/src

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr            \
            --sysconfdir=/etc        \
            --localstatedir=/var/lib \
            --enable-dns-for-realm   \
            --with-system-et         \
            --with-system-ss         \
            --with-ldap              \
            --without-system-verto

make -j4
make install DESTDIR=${DEST}

mkdir -p ${DEST}/usr/share/krb5/examples

install -Dm644 config-files/kdc.conf ${DEST}/var/lib/krb5kdc/kdc.conf
install -Dm644 config-files/krb5.conf ${DEST}/etc/krb5.conf

install -Dm644 util/ac_check_krb5.m4 ${DEST}/usr/share/aclocal/ac_check_krb5.m4

install -m644 config-files/kdc.conf config-files/krb5.conf ${DEST}/usr/share/krb5/examples
install -m644 plugins/kdb/ldap/libkdb_ldap/kerberos.ldif plugins/kdb/ldap/libkdb_ldap/kerberos.schema ${DEST}/usr/share/krb5/examples

popd

pushd krb5-${VER}-32/src

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr            \
            --sysconfdir=/etc        \
            --localstatedir=/var/lib \
            --libdir=/usr/lib32      \
            --enable-dns-for-realm   \
            --with-system-et         \
            --with-system-ss         \
            --with-ldap              \
            --without-tcl            \
            --without-system-verto   \
            --disable-aesni

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf krb5-${VER} krb5-${VER}-32

rm -rf ${DEST}/usr/share/examples ${DEST}/usr/share/gnats
rm -rf ${DEST}/usr/share/man/cat1 ${DEST}/usr/share/man/cat5 ${DEST}/usr/share/man/cat8

mkdir -p ${DEST}/etc/systemd/system/multi-user.target.wants ${DEST}/lib/systemd/system

chmod 755 ${DEST}/usr/lib32/*.so.*.* ${DEST}/usr/lib32/krb5/plugins/*/*.so
chmod 755 ${DEST}/usr/lib/*.so.*.* ${DEST}/usr/lib/krb5/plugins/*/*.so

cat > ${DEST}/lib/systemd/system/krb5-kdc.service << "EOF"
[Unit]
Description=Kerberos 5 KDC

[Service]
ExecStart=/usr/sbin/krb5kdc -n
Restart=always

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/lib/systemd/system/krb5-kadmind.service << "EOF"
[Unit]
Description=Kerberos 5 Administration Server

[Service]
ExecStart=/usr/sbin/kadmind -nofork

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/lib/systemd/system/krb5-kpropd.service << "EOF"
[Unit]
Description=Kerberos 5 Propagation Server

[Service]
ExecStart=/usr/sbin/kpropd -S

[Install]
WantedBy=multi-user.target
EOF

ln -sf /lib/systemd/system/krb5-kdc.service ${DEST}/etc/systemd/system/multi-user.target.wants/krb5-kdc.service
ln -sf /lib/systemd/system/krb5-kpropd.service ${DEST}/etc/systemd/system/multi-user.target.wants/krb5-kpropd.service
ln -sf /lib/systemd/system/krb5-kadmind.service ${DEST}/etc/systemd/system/multi-user.target.wants/krb5-kadmind.service

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q /usr/share/man
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
