#!/bin/bash -e

export PKGNAME=ncurses
export PKGVER=6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/ncurses/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  install -dm755 buildncursesw6 buildncursesw buildncurses
}

configure_override() {
  local LIBDIR=$1

  local CFG_FLAGS_SHARED=(--prefix=/usr
                          --libdir=/usr/lib
                          --mandir=/usr/share/man
                          --with-shared
                          --without-debug)

  pushd buildncursesw6
    ../configure ${CFG_FLAGS_SHARED[@]}  \
                 --enable-pc-files    \
                 --enable-widec       \
                 --with-abi-version=6 \
                 --with-pkg-config-libdir=/usr/lib/pkgconfig
  popd

  pushd buildncursesw
    ../configure ${CFG_FLAGS_SHARED[@]}  \
                 --enable-widec       \
                 --with-abi-version=5
  popd

  pushd buildncurses
    ../configure ${CFG_FLAGS_SHARED[@]}  \
                 --with-chtype=long   \
                 --with-abi-version=5
  popd
}

make_override() {
  for d in buildncursesw6 buildncursesw buildncurses
  do
    make -C ${d} ${MAKE_JOBS_FLAGS}
  done
}

make_install_override() {
  make -C buildncursesw6 install DESTDIR=${DEST}

  for lib in ncurses form panel menu
  do
    install -m755 buildncursesw/lib/lib${lib}w.so.5.9 ${DEST}/usr/lib
    ln -sf lib${lib}w.so.5.9 ${DEST}/usr/lib/lib${lib}w.so.5

    install -m755 buildncurses/lib/lib${lib}.so.5.9 ${DEST}/usr/lib
    ln -sf lib${lib}.so.5.9 ${DEST}/usr/lib/lib${lib}.so.5
  done
}

post_install_config() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libncursesw.so.6{,.0} ${DEST}/lib
  ln -sf ../../lib/libncursesw.so.6.0 ${DEST}/usr/lib/libncursesw.so

  for lib in ncurses form panel menu ; do
    rm -rf ${DEST}/usr/lib/lib${lib}.so
    echo "INPUT(-l${lib}w)" > ${DEST}/usr/lib/lib${lib}.so
  done

  for lib in ncurses ncurses++ form panel menu; do
    ln -sf ${lib}w.pc ${DEST}/usr/lib/pkgconfig/${lib}.pc
  done

  rm -rf ${DEST}/usr/lib/libcursesw.so
  echo "INPUT(-lncursesw)" > ${DEST}/usr/lib/libcursesw.so
  ln -sf libncurses.so ${DEST}/usr/lib/libcurses.so

  rm -rf ${DEST}/usr/lib/*.a

  # libtinfo compat
  ln -sf libncurses.so.5 ${DEST}/usr/lib/libtinfo.so.5
}

. $(dirname $0)/master.sh
