#!/bin/bash -e

export PKGNAME=libgd
export PKGVER=2.2.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/libgd/libgd/releases/download/gd-${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done\n"
                    "cp -rf --remove-destination usr/bin/gdlib-config /usr/bin")

. $(dirname $0)/master.sh
