#!/bin/bash -e

export PKGNAME=libgcrypt
export PKGVER=1.6.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.gnupg.org/gcrypt/libgcrypt/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--disable-padlock-support)
export CONFIGURE_FLAGS_32=(--disable-padlock-support)

configure_pre_32() {
  sed 's:path="amd64":path="i586 i386":' -i mpi/config.links
}

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libgcrypt.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libgcrypt.so) ${DEST}/usr/lib/libgcrypt.so
}

. $(dirname $0)/master.sh
