#!/bin/bash -e

export PKGNAME=xfsprogs
export PKGVER=4.2.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="ftp://oss.sgi.com/projects/xfs/cmd_tars/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_INSTALL_FLAGS="install-dev"

configure_override() {
  true
}

make_override() {
  make DEBUG=-DNDEBUG     \
       INSTALL_USER=root  \
       INSTALL_GROUP=root \
       LOCAL_CONFIGURE_OPTIONS="--enable-readline" \
       OPTIMIZER="${CFLAGS}" V=1 ${MAKE_JOBS_FLAGS}
}

make_install_post() {
  ln -sf ../../lib/$(readlink ${DEST}/lib/libhandle.so) ${DEST}/usr/lib/libhandle.so
  rm -rf ${DEST}/lib/libhandle.a ${DEST}/usr/lib/libhandle.a ${DEST}/lib/libhandle.so
}

. $(dirname $0)/master.sh
