#!/bin/bash -e

export PKGNAME=dbus-python
export PKGVER=1.2.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://dbus.freedesktop.org/releases/dbus-python/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(PYTHON=/usr/bin/python3)
export CONFIGURE_FLAGS_32=(PYTHON=/usr/bin/python --libdir=/usr/lib)
export DEFAULT_CC_M32="clang"

configure_pre_32() {
  unset PKG_CONFIG_PATH
}

make_install_override() {
  make install DESTDIR=${DEST}
}

. $(dirname $0)/master.sh
