#!/bin/bash -e

export PKGNAME=ffmpeg
export PKGVER=3.1.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ffmpeg.org/releases/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export NO_OPTIMIZATION=1

configure_override() {
  sed -i "s: -lstdc++::g" configure

  ./configure --prefix=/usr              \
              --enable-chromaprint       \
              --enable-fontconfig        \
              --enable-gpl               \
              --enable-ladspa            \
              --enable-libass            \
              --enable-libbluray         \
              --enable-libbs2b           \
              --enable-libcaca           \
              --enable-libcelt           \
              --enable-libcdio           \
              --enable-libdc1394         \
              --enable-libfaac           \
              --enable-libfdk-aac        \
              --enable-libfreetype       \
              --enable-libfribidi        \
              --enable-libgme            \
              --enable-libgsm            \
              --enable-libiec61883       \
              --enable-libilbc           \
              --enable-libkvazaar        \
              --enable-libmodplug        \
              --enable-libmp3lame        \
              --enable-libopencore-amrnb \
              --enable-libopencore-amrwb \
              --enable-libopenjpeg       \
              --enable-libopus           \
              --enable-libpulse          \
              --enable-librtmp           \
              --enable-libschroedinger   \
              --enable-libshine          \
              --enable-libsoxr           \
              --enable-libspeex          \
              --enable-libssh            \
              --enable-libtheora         \
              --enable-libtwolame        \
              --enable-libv4l2           \
              --enable-libvidstab        \
              --enable-libvo-amrwbenc    \
              --enable-libvorbis         \
              --enable-libvpx            \
              --enable-libwavpack        \
              --enable-libwebp           \
              --enable-libx264           \
              --enable-libx265           \
              --enable-libxvid           \
              --enable-libzimg           \
              --enable-libzvbi           \
              --enable-nonfree           \
              --enable-openal            \
              --enable-opengl            \
              --enable-openssl           \
              --enable-postproc          \
              --enable-shared            \
              --enable-vaapi             \
              --enable-vdpau             \
              --enable-version3          \
              --enable-x11grab           \
              --disable-debug            \
              --disable-opencl           \
              --disable-static           \
              --extra-cflags="${DEFAULT_CFLAGS}"   \
              --extra-cxxflags="${DEFAULT_CXXFLAGS}" \
              --cc="${CC}" --cxx="${CXX}"
}

. $(dirname $0)/master.sh
