#!/bin/bash -e

export PKGNAME=nettle
export PKGVER=3.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/nettle/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS_32=(--with-include-path=/usr/lib32/gmp)

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

post_install_config() {
  rm -rf ${DEST}/usr/*/*.a
}

. $(dirname $0)/master.sh
