#!/bin/bash -e

export MATE_MAJOR_VER=1.12

case $(basename $0) in
  buildcaja )
    export PKGNAME=caja
    export PKGVER=1.14.0
    export CONFIGURE_FLAGS=(--disable-packagekit
                            --disable-update-mimedb
                            --disable-icon-update
                            --disable-schemas-compile)
  ;;
  buildmate-desktop )
    export PKGNAME=mate-desktop
    export PKGVER=1.14.0
    export CONFIGURE_FLAGS=(--disable-desktop-docs)
  ;;
esac

if [ -z ${PKGTAR} ]
then
  export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
fi

export PKGURL="http://pub.mate-desktop.org/releases/${MATE_MAJOR_VER}/${PKGTAR}"
export DEST=/binary/mate/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=("${CONFIGURE_FLAGS[@]}" --with-gtk=3.0)

. $(dirname $0)/master.sh
