#!/bin/bash -e

export PKGNAME=unixODBC
export PKGVER=2.3.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="ftp://ftp.unixodbc.org/pub/unixODBC/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export CONFIGURE_FLAGS=(--sysconfdir=/etc/unixODBC)

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
