#!/bin/bash -e

export VER=0.1.7
export DEST=/binary/python-sphinx_rtd_theme-${VER}

cp -a sphinx_rtd_theme-${VER} sphinx_rtd_theme-${VER}-3

pushd sphinx_rtd_theme-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd sphinx_rtd_theme-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf sphinx_rtd_theme-${VER} sphinx_rtd_theme-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
