#!/bin/bash -e

export VER=1.16.2
export DEST=/binary/xorg-server-${VER}

pushd xorg-server-${VER}

if [ -f /media/ntfs/Other/Linux/patches/xserver-fixes.patch ]; then
  patch -Np1 -i /media/ntfs/Other/Linux/patches/xserver-fixes.patch
fi

#patch -Np1 -i /media/ntfs/Other/Linux/patches/xserver-autobind-hotplug.patch
autoreconf -fi

CFLAGS="-march=native -mtune=native -g -O2"   \
CXXFLAGS="-march=native -mtune=native -g -O2" \
./configure --prefix=/usr            \
            --sysconfdir=/etc        \
            --localstatedir=/var     \
            --disable-install-setuid \
            --enable-dmx             \
            --enable-dri2            \
            --enable-dri3            \
            --enable-glamor          \
            --enable-present         \
            --enable-suid-wrapper    \
            --enable-systemd-logind  \
            --enable-xephyr          \
            --enable-xnest           \
            --enable-xvfb            \
            --enable-xwayland        \
            --with-systemd-daemon    \
            --with-xkb-output=/var/lib/xkb

make -j4
make install DESTDIR=${DEST}

rm -rf ${DEST}/var/log

popd

rm -rf xorg-server-${VER}

install -dm755 ${DEST}/etc/X11/xorg.conf.d

find ${DEST} -name "*.la" -delete

mv ${DEST}/usr/lib/xorg/modules/extensions/libglx.so ${DEST}/usr/lib/xorg/modules/extensions/libglx.so.xorg

ln -sf libglx.so.xorg ${DEST}/usr/lib/xorg/modules/extensions/libglx.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr var ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
