#!/bin/bash -e

export PKGNAME=libidn
export PKGVER=1.33
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/libidn/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

make_install_post() {
  rm -rf ${DEST}/usr/share/emacs ${DEST}/usr/share/info/*.png
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libidn.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libidn.so) ${DEST}/usr/lib/libidn.so
}

. $(dirname $0)/master.sh
