#!/bin/bash -e

export VER=3.14.1
export DEST=/binary/gsettings-desktop-schemas-${VER}

pushd gsettings-desktop-schemas-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gsettings-desktop-schemas-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
EOF

chmod 755 ${DEST}/INSTALL
