#!/bin/bash -e

export PKGNAME=util-linux
export PKGVER=2.29
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/utils/util-linux/v${PKGVER:0:4}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export POSTINST_TRIGGER=("chmod 4755 /bin/mount /bin/umount"
                         "chgrp tty /usr/bin/wall"
                         "chmod 2755 /usr/bin/wall")

export COMMON_CONFIGURE_FLAGS=(--enable-mesg
                               --disable-nologin
                               --disable-chfn-chsh
                               --disable-su
                               --disable-login
                               --disable-kill
                               --with-systemdsystemunitdir=/lib/systemd/system)

configure_override() {
  ./configure ${COMMON_CONFIGURE_FLAGS[@]}
}

. $(dirname $0)/master.sh
