#!/bin/bash -e

export VER=0.48.5
export DEST=/binary/inkscape-${VER}

pushd inkscape-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/inkscape-fixes.patch

sed -i "s|GfxColorSpace::parse(|&NULL, |g" src/extension/internal/pdfinput/pdf-parser.cpp

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf inkscape-${VER}

sed -i "s:application/pdf;application/postscript;image/x-eps;::g" ${DEST}/usr/share/applications/inkscape.desktop

for man in el fr ja sk zh_TW
do
  rm -rf ${DEST}/usr/share/man/${man}
  rm -rf ${DEST}/usr/share/man/man1/inkscape.${man}.1
done

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
