#!/bin/bash -e

export PKGNAME=intel-hybrid-driver
export PKGVER=1.0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/01org/intel-hybrid-driver/archive/${PKGVER}.tar.gz"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export DEFAULT_CXX="clang++"

configure_pre() {
  autoreconf -fi
}

. $(dirname $0)/master.sh
