#!/bin/bash -e

export VER=2.0.21
export DEST=/binary/traceroute-${VER}

pushd traceroute-${VER}

sed -i "s:-O2:-march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" Make.rules

make -j4
make install prefix=${DEST}/usr

popd

rm -rf traceroute-${VER}

ln -sf traceroute ${DEST}/usr/bin/traceroute6
ln -sf traceroute.8 ${DEST}/usr/share/man/man8/traceroute6.8

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
