#!/bin/bash -e

export PKGNAME=libsamplerate
export PKGVER=0.1.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.mega-nerd.com/SRC/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS_32=(--disable-fftw)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

. $(dirname $0)/master.sh
