#!/bin/bash -e

export PKGNAME=netcdf
export PKGVER=4.4.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="ftp://ftp.unidata.ucar.edu/pub/netcdf/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-shared --enable-netcdf-4 --enable-dap-netcdf)

. $(dirname $0)/master.sh
