#!/bin/bash -e

export PKGNAME=libpipeline
export PKGVER=1.4.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://download.savannah.gnu.org/releases/libpipeline/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
