#!/bin/bash -e

export PKGNAME=libidn
export PKGVER=1.32
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/libidn/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

make_install_post() {
  rm -rf ${DEST}/usr/share/emacs ${DEST}/usr/share/info/*.png
}

. $(dirname $0)/master.sh
