#!/bin/bash -e

export VER=4.14.2
export DEST=/binary/print-manager-${VER}

pushd print-manager-${VER}
  patch -Np1 -i /media/ntfs/Other/Linux/patches/print-manager-fixes.patch
popd

install -dm755 print-manager-${VER}/build

pushd print-manager-${VER}/build

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DKDE4_BUILD_TESTS=OFF      \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
      -Wno-dev ..

make -j4
make install DESTDIR=${DEST}

popd

rm -rf print-manager-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
