#!/bin/bash -e

export PKGNAME=openexr
export PKGVER=2.2.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://download.savannah.nongnu.org/releases/openexr/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/share ; do cp -rf --remove-destination \$dir /usr ; done")

. $(dirname $0)/master.sh
