#!/bin/bash -e

export VER=1.0.4
export DEST=/binary/xcursor-themes-${VER}

pushd xcursor-themes-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf xcursor-themes-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
