#!/bin/bash -e

export VER=3.0-rc1
export DEST=/binary/lua-socket-${VER}

pushd luasocket-${VER}

sed -i "s:-O2 -ggdb3:-march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" src/makefile

make LUAV=5.2 prefix=/usr -j4
make install-unix LUAV=5.2 prefix=/usr DESTDIR=${DEST}

popd

rm -rf luasocket-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
