#!/bin/bash -e

export VER=4.0
export DEST=/binary/iw-${VER}

pushd iw-${VER}

sed -i "s:-O2 -g:-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong:g" Makefile

make -j4
make install DESTDIR=${DEST}

popd

rm -rf iw-${VER}

gzip -d ${DEST}/usr/share/man/man8/*

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
