#!/bin/bash -e

export VER=1.0.2
export DEST=/binary/NetworkManager-${VER}

pushd NetworkManager-${VER}

sed -i "/CFLAGS/s: -Werror::" configure

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --enable-doc \
            --with-session-tracking=systemd \
            --with-suspend-resume=systemd \
            --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7 \
            --with-systemdsystemunitdir=/lib/systemd/system

make -j4
make install DESTDIR=${DEST}

popd

rm -rf NetworkManager-${VER}

rm -rf ${DEST}/lib/systemd/system/network-online.target.wants
rm -rf ${DEST}/usr/share/doc
rm -rf ${DEST}/var/run

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/etc/NetworkManager/NetworkManager.conf << "EOF"
[main]
plugins=keyfile
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/NetworkManager.conf << "EOF"
d /run/NetworkManager 755 root root -
EOF

ln -sf /lib/systemd/system/NetworkManager.service ${DEST}/etc/systemd/system/multi-user.target.wants/NetworkManager.service
ln -sf /lib/systemd/system/NetworkManager-wait-online.service ${DEST}/etc/systemd/system/multi-user.target.wants/NetworkManager-wait-online.service
ln -sf /lib/systemd/system/NetworkManager.service ${DEST}/etc/systemd/system/dbus-org.freedesktop.NetworkManager.service
ln -sf /lib/systemd/system/NetworkManager-dispatcher.service ${DEST}/etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
