#!/bin/bash -e

export DEST=/binary/octave-forge

# http://octave.sourceforge.net/packages.php

packages=(
    actuarial-1.1.0
    bim-1.1.5
    cgi-0.1.0
    communications-1.2.0
    control-2.6.6
    data-smoothing-1.3.0
    database-2.3.0
    dataframe-1.1.0
    divand-1.1.2
    econometrics-1.1.1
    fenv-0.1.0
    financial-0.4.0
    fits-1.0.5
    fpl-1.3.4
    fuzzy-logic-toolkit-0.4.5
    ga-0.10.0
    general-1.3.4
    generate_html-0.1.6
    geometry-1.7.0
    gnuplot-1.0.1
    image-2.2.2
    image-acquisition-0.2.1
    instrument-control-0.2.0
    io-2.2.5
    level-set-0.1.0
    linear-algebra-2.2.0
    lssa-0.1.2
    ltfat-2.0.1
    mechanics-1.3.1
    miscellaneous-1.2.1
    mpi-1.2.0
    msh-1.0.10
    mvn-1.1.0
    nan-2.5.9
    ncarray-1.0.3
    netcdf-1.0.5
    nlwing2-1.2.0
    nurbs-1.3.9
    ocs-0.1.3
    octcdf-1.1.7
    octclip-1.0.3
    octgpr-1.2.0
    octproj-1.1.2
    odepkg-0.8.4
    optics-0.1.1
    optim-1.4.0
    optiminterp-0.3.4
    parallel-2.2.0
    plot-1.1.0
    quaternion-2.2.2
    queueing-1.2.3
    secs1d-0.0.9
    secs2d-0.0.8
    secs3d-0.0.1
    signal-1.3.0
    sockets-1.0.8
    specfun-1.1.0
    splines-1.2.7
    statistics-1.2.3
    stk-2.2.0
    strings-1.1.0
    struct-1.0.10
    tsa-4.2.7
    vrml-1.0.13
)

install -dm755 octave-forge

pushd octave-forge

for package in ${packages[@]}
do
    wget -c http://downloads.sourceforge.net/octave/${package}.tar.gz
    mkdir builddir
    octave -q -f --eval "pkg build -verbose -nodeps builddir ${package}.tar.gz"
    install -dm755 ${DEST}/octave-${package}/usr/share/octave
    install -m644 builddir/${package}.tar.gz ${DEST}/octave-${package}/usr/share/octave/${package%-*.*}.tar.gz
    rm -rf builddir

cat > ${DEST}/octave-${package}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

    chmod 755 ${DEST}/octave-${package}/INSTALL
done

popd
