#!/bin/bash -e

export PKGNAME=dosfstools
export PKGVER=4.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/dosfstools/dosfstools/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--sbindir=/sbin --enable-compat-symlinks)

. $(dirname $0)/master.sh
