#!/bin/bash -e

export VER=5.5
export DEST=/binary/lpsolve-${VER}.2.0

pushd lp_solve_${VER}

sed -e "s|-O3|-march=native -mtune=native -O2 -pipe -fstack-protector-strong|g" -i lp_solve/ccc lpsolve55/ccc

pushd lpsolve55
  sh -x ccc
  rm bin/ux*/liblpsolve55.a

popd
pushd lp_solve
  sh -x ccc
popd


install -dm755 ${DEST}/usr/bin ${DEST}/usr/lib ${DEST}/usr/include/lpsolve

install -m755 lp_solve/bin/ux*/lp_solve ${DEST}/usr/bin/
install -m755 lpsolve55/bin/ux*/liblpsolve55.so ${DEST}/usr/lib/
install -m644 lp*.h ${DEST}/usr/include/lpsolve/

popd

rm -rf lp_solve_${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
