#!/bin/bash -e

export VER=3.1.0
export DEST=/binary/python-urlgrabber-${VER}

pushd urlgrabber-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf urlgrabber-${VER}

rm -rf ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
