#!/bin/bash -e

export PKGNAME=Vulkan-LoaderAndValidationLayers
export PKGVER=1.0.30.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-sdk-${PKGVER}
export PKGURL="https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_INSTALL_SYSCONFDIR=/etc
                    -DCMAKE_SKIP_RPATH=ON
                    -DBUILD_TESTS=OFF
                    -DBUILD_WSI_XCB_SUPPORT=On
                    -DBUILD_WSI_XLIB_SUPPORT=On
                    -DBUILD_WSI_WAYLAND_SUPPORT=On)

export DEFAULT_CC="gcc"
export DEFAULT_CXX="g++"

post_extract_action() {
  pushd ${PKGDIR}
    sed -i "114,128d" demos/CMakeLists.txt

    export CC="gcc"
    export CXX="g++"

    export CFLAGS=${DEFAULT_CFLAGS}
    export CXXFLAGS=${DEFAULT_CXXFLAGS}

    ./update_external_sources.sh

    unset CC CXX CFLAGS CXXFLAGS
  popd
}

make_install_override() {
  install -dm755 ${DEST}/etc                \
                 ${DEST}/usr/bin            \
                 ${DEST}/usr/include/vulkan \
                 ${DEST}/usr/lib

  install -dm755 ${DEST}/usr/share/vulkan/explicit_layer.d \
                 ${DEST}/usr/share/vulkan/implicit_layer.d

  install -m755 demos/vulkaninfo ${DEST}/usr/bin
  install -m644 ../${PKGDIR}/include/vulkan/*.h ${DEST}/usr/include/vulkan

  rm -rf ${DEST}/usr/include/vulkan/vk_platform.h ${DEST}/usr/include/vulkan/vulkan.h

  install -m755 layers/*.so ${DEST}/usr/lib

  install -m755 loader/*.so.*.* ${DEST}/usr/lib
  cp -rf loader/*.so.? ${DEST}/usr/lib
  cp -rf loader/*.so ${DEST}/usr/lib

  for i in ../${PKGDIR}/layers/linux/*.json
  do
    sed 's#./##' $i > ${DEST}/usr/share/vulkan/explicit_layer.d/$(basename $i)
  done
}

. $(dirname $0)/master.sh
