#!/bin/bash -e

export PKGNAME=emotion_generic_players
export PKGVER=1.16.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://download.enlightenment.org/rel/libs/emotion_generic_players/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
