#!/bin/bash -e

export PKGNAME=gnutls
export PKGVER=3.5.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="ftp://ftp.gnutls.org/gcrypt/gnutls/v${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--enable-local-libopts --disable-guile)
export CONFIGURE_FLAGS_32=(--enable-local-libopts --disable-guile --disable-hardware-acceleration)

make_install_post() {
  make -C doc/reference install-data-local DESTDIR=${DEST}

  rm -rf ${DEST}/usr/share/info/*.png ${DEST}/usr/share/info/*guile*
}

. $(dirname $0)/master.sh
