#!/bin/bash -e

export PKGNAME=libcdio
export PKGVER=0.93
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://ftp.gnu.org/gnu/libcdio/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export CONFIGURE_FLAGS_32=(--disable-cddb --disable-vcd-info)

. $(dirname $0)/master.sh
