#!/bin/bash -e

export PKGNAME=libcap
export PKGVER=2.24
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export MAKE_FLAGS_32="-C libcap prefix=/usr lib=lib32"
export MAKE_INSTALL_FLAGS="RAISE_SETFCAP=no PAM_LIBDIR=\${DEST}/lib prefix=/usr"
export MAKE_INSTALL_FLAGS_32="-C libcap prefix=/usr lib=lib32"

configure_override() {
  sed -i "s|-D_FILE_OFFSET_BITS=64|& ${CFLAGS}|" Make.Rules
  sed -i "s| gcc| ${CC}|" Make.Rules
  sed -i "s:LIBDIR:PAM_&:g" pam_cap/Makefile

  unset CFLAGS
}

configure_override_32() {
  sed -i "s|-D_FILE_OFFSET_BITS=64|& ${CFLAGS}|" Make.Rules
  sed -i "s| gcc| ${CC}|" Make.Rules

  unset CFLAGS
}

make_install_post() {
  install -dm755 ${DEST}/etc/security
  install -m644 pam_cap/capability.conf ${DEST}/etc/security
}

post_install_config() {
  rm -rf ${DEST}/usr/*/libcap.a

  mv ${DEST}/usr/lib/libcap.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libcap.so) ${DEST}/usr/lib/libcap.so
}

. $(dirname $0)/master.sh
