#!/bin/bash -e

export PKGNAME=libguess
export PKGVER=1.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://rabbit.dereferenced.org/~nenolod/distfiles/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
