#!/bin/bash -e

export PKGNAME=libilbc
export PKGVER=2.0.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://github.com/TimothyGu/libilbc/releases/download/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
