#!/bin/bash -e

export VER=1.10.1
export DEST=/binary/mate-screensaver-${VER}

pushd mate-screensaver-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-gtk=3.0    \
            --with-libgl      \
            --with-systemd    \
            --disable-static  \
            --with-xscreensaverhackdir=/usr/libexec/xscreensaver \
            --with-xscreensaverdir=/usr/share/xscreensaver/config

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mate-screensaver-${VER}

find ${DEST} -name "*.la" -delete

cat > ${DEST}/etc/pam.d/mate-screensaver << "EOF"
# Begin /etc/pam.d/mate-screensaver

auth     include        system-auth
-auth    optional       pam_gnome_keyring.so

account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/mate-screensaver
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
