#!/bin/bash -e

export PKGNAME=iproute2
export PKGVER=4.5.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/utils/net/iproute2/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_FLAGS="CCOPTS=\${CFLAGS} CC=\${DEFAULT_CC}"

configure_override() {
  true
}

make_install_post() {
  install -dm755 ${DEST}/bin ${DEST}/usr/bin ${DEST}/usr/sbin

  mv ${DEST}/sbin/ip ${DEST}/sbin/ss ${DEST}/bin
  mv ${DEST}/sbin/arpd ${DEST}/sbin/genl ${DEST}/usr/sbin

  mv ${DEST}/sbin/ctstat ${DEST}/sbin/lnstat ${DEST}/sbin/nstat ${DEST}/usr/bin
  mv ${DEST}/sbin/routef ${DEST}/sbin/routel ${DEST}/sbin/rtstat ${DEST}/usr/bin

  ln -sf ../bin/ip ${DEST}/sbin/ip
}

. $(dirname $0)/master.sh
