#!/bin/bash -e

export PKGNAME=texlive
export PKGVER=20160523
export TEXVER=20160523b
export PKGTAR=texlive-${TEXVER}-source.tar.xz
export TEXMFTAR=texlive-${TEXVER}-texmf.tar.xz
export TEXEXTRATAR=texlive-${PKGVER}-extra.tar.xz
export PKGDIR=texlive-${PKGVER}-source
export PKGBUILD=texlive-${PKGVER}-source/build
export PKGURL="ftp://tug.org/texlive/historic/2016/${PKGTAR}"
export TEXMFURL="ftp://tug.org/texlive/historic/2016/${TEXMFTAR}"
export TEXEXTRAURL="ftp://tug.org/texlive/historic/2016/${TEXEXTRATAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATH_TO_SOURCE=".."
export NO_STRIP=1

export POSTINST_TRIGGER=("/usr/bin/mktexlsr"
                         "/usr/bin/fmtutil-sys --all 1>/dev/null")

# Poppler bumps soname on each version and it's no fun
# rebuilding this package
export CONFIGURE_FLAGS=(--datarootdir=/usr/share
                        --datadir=/usr/share
                        --disable-native-texlive-build
                        --disable-dialog
                        --disable-multiplatform
                        --disable-psutils
                        --disable-t1utils
                        --enable-shared
                        --with-system-cairo
                        --with-system-freetype2
                        --with-system-gd
                        --with-system-gmp
                        --with-system-graphite2
                        --with-system-harfbuzz
                        --with-system-icu
                        --with-system-kpathsea
                        --with-system-libgs
                        --with-system-libpaper
                        --with-system-libpng
                        --with-system-mpfr
                        --with-system-pixman
                        --with-system-zlib
                        --with-system-zziplib
                        --with-banner-add=" - BLFS")

post_extract_action() {
  if [ ! -e ${SROOT}/${TEXMFTAR} ]
  then
    wget -c ${TEXMFURL} -O ${SROOT}/${TEXMFTAR} || exit ${PIPESTATUS}
  fi

  if [ ! -e ${SROOT}/${TEXEXTRATAR} ]
  then
    wget -c ${TEXEXTRAURL} -O ${SROOT}/${TEXEXTRATAR} || exit ${PIPESTATUS}
  fi

  install -dm755 ${PKGBUILD}
}

mypkg_strip() {
  find * -type f 2>/dev/null | while read BUILD_BINARY ; do
    case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
      strip --strip-unneeded ${BUILD_BINARY}
    esac
  done

  find * -name "*.a" -exec strip --strip-unneeded {} \;
}

make_install_post() {
  make texlinks DESTDIR=${DEST}

  tar --exclude=*/texmf-dist/doc --exclude=*/texmf-dist/source --strip-components=1 -xf ${SROOT}/${TEXMFTAR} -C ${DEST}/usr/share
  tar --wildcards --strip-components=1 -xf ${SROOT}/${TEXEXTRATAR} -C ${DEST}/usr/share "*/tlpkg"

  # libkpathsea
  rm -rf ${DEST}/usr/share/texmf-dist/web2c/mktex.opt
  rm -rf ${DEST}/usr/share/texmf-dist/web2c/mktexdir{,.opt}
  rm -rf ${DEST}/usr/share/texmf-dist/web2c/mktexnam{,.opt}
  rm -rf ${DEST}/usr/share/texmf-dist/web2c/mktexupd
  rm -rf ${DEST}/usr/share/texmf-dist/web2c/texmf.cnf

  # saves a lot of time
  pushd ${DEST}/usr/bin
    mypkg_strip
  popd

  pushd ${DEST}/usr/lib
    mypkg_strip
  popd
}

. $(dirname $0)/master.sh
