#!/bin/bash -e

export VER=5.5.0-beta
export DEST=/binary/qtwayland-${VER}

pushd qtwayland-opensource-src-${VER}

qmake-qt5

make sub-src-qmake_all
make -C src sub-client-qmake_all

sed -i "/LIBS/s:lXcomposite:& -lXrender:;/PKGCONFIG/s:xcomposite:& xrender:" src/hardwareintegration/client/xcomposite-glx/xcomposite-glx.pri
sed -i "/LIBS/s:-lQt5PlatformSupport:& -lQt5DBus:g" src/client/Makefile

make -j4

find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;

make install INSTALL_ROOT=${DEST}

find ${DEST}/usr/lib/*.prl -exec sed -i -e \
     '/^QMAKE_PRL_BUILD_DIR/d;s/\(QMAKE_PRL_LIBS =\).*/\1/' {} \;

popd

rm -rf qtwayland-opensource-src-${VER}

rm -rf ${DEST}/usr/lib/*.la

install -dm755 ${DEST}/usr/bin

for file in ${DEST}/usr/lib/qt5/bin/*
do
  ln -sf ../lib/qt5/bin/$(basename $file) ${DEST}/usr/bin/$(basename $file)-qt5
done

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
