#!/bin/bash -e

export PKGNAME=vlc
export PKGVER=3.0.0-git
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.videolan.org/pub/videolan/vlc/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export POSTINST_TRIGGER=("/usr/lib/vlc/vlc-cache-gen /usr/lib/vlc/plugins")

export CONFIGURE_FLAGS=(--enable-aa
                        --enable-gles2
                        --enable-realrtsp
                        --disable-jack)

export BUILDCC="clang"

configure_pre() {
  sed -i "/LUA_COMPAT_MODULE/a #define LUA_COMPAT_APIINTCASTS" modules/lua/vlc.h
}

. $(dirname $0)/master.sh
