#!/bin/bash -e

export PKGNAME=openvswitch
export PKGVER=2.4.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://openvswitch.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export KEEP_STATIC=1
export POSTINST_TRIGGER=("if [ ! -e /etc/openvswitch/conf.db ]" "then" "  ovsdb-tool create /etc/openvswitch/conf.db /usr/share/openvswitch/vswitch.ovsschema" "fi")

make_install_post() {
  rm -rf ${DEST}/etc/bash_completion.d ${DEST}/var/run

  install -dm755 ${DEST}/lib/systemd/system ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/lib/systemd/system/ovs-vswitchd.service << "EOF"
[Unit]
Description=Open vSwitch Daemon
Documentation=man:ovs-vswitchd
Wants=network.target
Before=network.target
Requires=ovsdb-server.service
After=ovsdb-server.service

[Service]
ExecStartPre=/sbin/modprobe openvswitch
PIDFile=/run/openvswitch/ovs-vswitchd.pid
ExecStart=/usr/sbin/ovs-vswitchd --pidfile=/run/openvswitch/ovs-vswitchd.pid

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/lib/systemd/system/ovsdb-server.service << "EOF"
[Unit]
Description = Open vSwitch Database Server
Documentation = man:ovsdb-server

[Service]
PIDFile=/run/openvswitch/ovsdb-server.pid
ExecStart=/usr/sbin/ovsdb-server --remote=punix:/run/openvswitch/db.sock --pidfile=/run/openvswitch/ovsdb-server.pid
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/openvswitch.conf << "EOF"
d /run/openvswitch 0770 root root -
EOF
}

. $(dirname $0)/master.sh
