#!/bin/bash -e

export PKGNAME=man-pages
export PKGVER=4.07
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/docs/man-pages/${PKGTAR}"
export NO_STRIP=1

configure_override() {
  true
}

make_override() {
  true
}

. $(dirname $0)/master.sh
