#!/bin/bash -e

export VER=22
export DEST=/binary/media-player-info-${VER}

pushd media-player-info-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf media-player-info-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done
EOF

chmod 755 ${DEST}/INSTALL
