#!/bin/bash -e

export BAEKMUK_VER=2.2
export CANTARELL_VER=0.0.21
export CM_UNICODE_VER=0.7.0
export DEJAVU_VER=2.35
export FREEFONT_VER=20120503
export GENTIUMBASIC_VER=110
export GENTIUMPLUS_VER=5.000
export HANNOM_VER=2005
export LIBERATION_VER=2.00.1
export MGOPEN_VER=1.1
export NOTO_VER=2015-12-17
export NOTO_REV=3f1dc1296bc3d01495a1478bb9a6f76d19040195
export OPENDESKTOP_VER=1.4.2
export PARATYPE_VER=20140730
export SCHEHERAZADE_VER=2.100
export VLGOTHIC_VER=20141206

checkdest() {
  if [ -e ${DEST} ]
  then
    echo "Old package installation directory exists. Removing."
    rm -rf ${DEST}
  fi
}

case $(basename $0) in
  buildfonts-baekmuk )

    # Begin baekmuk

    wget -c https://kldp.net/frs/download.php/1429/baekmuk-ttf-${BAEKMUK_VER}.tar.gz -O - | tar xfz -

    export DEST=/binary/fonts/fonts-baekmuk-${BAEKMUK_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/baekmuk
    install -m644 baekmuk-ttf-${BAEKMUK_VER}/ttf/*.ttf ${DEST}/usr/share/fonts/truetype/baekmuk

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/baekmuk
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf baekmuk-ttf-${BAEKMUK_VER}

    # End baekmuk

  ;;
  buildfonts-cantarell )

    # Begin cantarell

    wget -c https://download.gnome.org/sources/cantarell-fonts/0.0/cantarell-fonts-${CANTARELL_VER}.tar.xz -O - | tar xfJ -

    export DEST=/binary/fonts/fonts-cantarell-${CANTARELL_VER}

    checkdest

    pushd cantarell-fonts-${CANTARELL_VER}

    ./configure --prefix=/usr --with-fontdir=/usr/share/fonts/opentype/cantarell

    make install DESTDIR=${DEST}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/opentype/cantarell
EOF

    chmod 755 ${DEST}/INSTALL

    popd

    rm -rf cantarell-fonts-${CANTARELL_VER}

    # End cantarell

  ;;
  buildfonts-cm-unicode )

    # Begin cm-unicode

    wget -c http://downloads.sourceforge.net/cm-unicode/cm-unicode-${CM_UNICODE_VER}-ttf.tar.xz -O - | tar xfJ -

    export DEST=/binary/fonts/fonts-cm-unicode-${CM_UNICODE_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/cm-unicode
    install -m644 cm-unicode-${CM_UNICODE_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/cm-unicode

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/cm-unicode
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf cm-unicode-${CM_UNICODE_VER}

    # End cm-unicode

  ;;
  buildfonts-dejavu )

    # Begin dejavu

    wget -c http://downloads.sourceforge.net/dejavu/dejavu-fonts-ttf-${DEJAVU_VER}.tar.bz2 -O - | tar xfj -

    export DEST=/binary/fonts/fonts-dejavu-${DEJAVU_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fontconfig/conf.avail ${DEST}/usr/share/fonts/truetype/dejavu

    install -m644 dejavu-fonts-ttf-${DEJAVU_VER}/fontconfig/*.conf ${DEST}/usr/share/fontconfig/conf.avail
    install -m644 dejavu-fonts-ttf-${DEJAVU_VER}/ttf/*.ttf ${DEST}/usr/share/fonts/truetype/dejavu

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/dejavu
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf dejavu-fonts-ttf-${DEJAVU_VER}

    # End dejavu

  ;;
  buildfonts-freefont )

    # Begin freefont

    wget -c https://ftp.gnu.org/pub/gnu/freefont/freefont-ttf-${FREEFONT_VER}.zip -O - | bsdtar xf -

    export DEST=/binary/fonts/fonts-freefont-${FREEFONT_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/freefont
    install -m644 freefont-${FREEFONT_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/freefont

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/freefont
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf freefont-${FREEFONT_VER}

    # End freefont

  ;;
  buildfonts-gentiumbasic )

    # Begin gentiumbasic

    export DEST=/binary/fonts/fonts-gentiumbasic-${GENTIUMBASIC_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/gentiumbasic

    wget -c "http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=GentiumBasic_${GENTIUMBASIC_VER}&filename=GentiumBasic_${GENTIUMBASIC_VER}.zip" -O - | bsdtar xf - --strip-components=1 -C ${DEST}/usr/share/fonts/truetype/gentiumbasic

    rm -f ${DEST}/usr/share/fonts/truetype/gentiumbasic/*.txt

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/gentiumbasic
EOF

    chmod 755 ${DEST}/INSTALL

    # End gentiumbasic

  ;;
  buildfonts-gentiumplus )

    # Begin gentiumplus

    wget -c "https://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=GentiumPlus-${GENTIUMPLUS_VER}.zip&filename=GentiumPlus-${GENTIUMPLUS_VER}.zip" -O - | bsdtar xf -

    export DEST=/binary/fonts/fonts-gentiumplus-${GENTIUMPLUS_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/gentiumplus
    install -m644 GentiumPlus-${GENTIUMPLUS_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/gentiumplus

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/gentiumplus
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf GentiumPlus-${GENTIUMPLUS_VER}

    # End gentiumplus

  ;;
  buildfonts-hannom )

    # Begin hannom

    export DEST=/binary/fonts/fonts-hannom-${HANNOM_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/hannom

    wget -c http://downloads.sourceforge.net/vietunicode/hannomH.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/hannom

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/hannom
EOF

    chmod 755 ${DEST}/INSTALL

    # End hannom

  ;;
  buildfonts-liberation )

    # Begin liberation

    wget -c https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-ttf-${LIBERATION_VER}.tar.gz -O - | tar xfz -

    export DEST=/binary/fonts/fonts-liberation-${LIBERATION_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/liberation
    install -m644 liberation-fonts-ttf-${LIBERATION_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/liberation

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/liberation
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf liberation-fonts-ttf-${LIBERATION_VER}

    # End liberation

  ;;
  buildfonts-mgopen )

    # Begin mgopen

    wget -c http://http.debian.net/debian/pool/main/f/fonts-mgopen/fonts-mgopen_${MGOPEN_VER}.orig.tar.bz2 -O - | tar xfj -

    export DEST=/binary/fonts/fonts-mgopen-${MGOPEN_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/mgopen
    install -m644 fonts-mgopen-${MGOPEN_VER}/TTFs/*.ttf ${DEST}/usr/share/fonts/truetype/mgopen

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/mgopen
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf fonts-mgopen-${MGOPEN_VER}

    # End mgopen

  ;;
  buildfonts-noto )

    # Begin noto

    #wget -c https://github.com/googlei18n/noto-fonts/archive/v${NOTO_VER}-license-adobe.tar.gz -O - | tar xfz -

    install -dm755 noto-fonts

    wget -c https://github.com/googlei18n/noto-fonts/archive/${NOTO_REV}.zip -O - | bsdtar xf - -C noto-fonts --strip-components=1

    export DEST=/binary/fonts/fonts-noto-${NOTO_VER//-}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/noto

    #install -m644 noto-fonts-${NOTO_VER}-license-adobe/hinted/Noto*.ttf ${DEST}/usr/share/fonts/truetype/noto
    install -m644 noto-fonts/hinted/Noto*.ttf ${DEST}/usr/share/fonts/truetype/noto

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/noto
EOF

    chmod 755 ${DEST}/INSTALL

    #rm -rf noto-fonts-${NOTO_VER}-license-adobe
    rm -rf noto-fonts

    # End noto

  ;;
  buildfonts-opendesktop )

    # Begin opendesktop

    wget -c https://sources.archlinux.org/other/opendesktop-fonts/opendesktop-fonts-${OPENDESKTOP_VER}.tar.gz -O - | tar xfz -

    export DEST=/binary/fonts/fonts-opendesktop-${OPENDESKTOP_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/opendesktop
    install -m644 opendesktop-fonts-${OPENDESKTOP_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/opendesktop

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/opendesktop
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf opendesktop-fonts-${OPENDESKTOP_VER}

    # End opendesktop

  ;;
  buildfonts-paratype )

    # Begin paratype

    export DEST=/binary/fonts/fonts-paratype-${PARATYPE_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/paratype

    wget -c http://www.paratype.com/uni/public/PTSans.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/paratype
    wget -c http://www.paratype.com/uni/public/PTSerif.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/paratype
    wget -c http://www.paratype.com/uni/public/PTMono.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/paratype

    rm -f ${DEST}/usr/share/fonts/truetype/paratype/*.txt

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/paratype
EOF

    chmod 755 ${DEST}/INSTALL

    # End paratype

  ;;
  buildfonts-scheherazade )

    # Begin scheherazade

    wget -c "http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=Scheherazade-${SCHEHERAZADE_VER}.zip&filename=Scheherazade-${SCHEHERAZADE_VER}.zip" -O - | bsdtar xf -

    export DEST=/binary/fonts/fonts-scheherazade-${SCHEHERAZADE_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/scheherazade
    install -m644 Scheherazade-${SCHEHERAZADE_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/scheherazade

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/scheherazade
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf Scheherazade-${SCHEHERAZADE_VER}

    # End scheherazade

  ;;
  buildfonts-vlgothic )

    # Begin vlgothic

    wget -c http://jaist.dl.sourceforge.jp/vlgothic/62375/VLGothic-${VLGOTHIC_VER}.tar.xz -O - | tar xfJ -

    export DEST=/binary/fonts/fonts-vlgothic-${VLGOTHIC_VER}

    checkdest

    install -dm755 ${DEST}/usr/share/fonts/truetype/vlgothic

    install -m644 VLGothic/*.ttf ${DEST}/usr/share/fonts/truetype/vlgothic

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/vlgothic
EOF

    chmod 755 ${DEST}/INSTALL

    rm -rf VLGothic

    # End vlgothic

  ;;
  buildfonts )
    $(dirname $0)/buildfonts-baekmuk
    $(dirname $0)/buildfonts-cantarell
    $(dirname $0)/buildfonts-cm-unicode
    $(dirname $0)/buildfonts-dejavu
    $(dirname $0)/buildfonts-freefont
    $(dirname $0)/buildfonts-gentiumbasic
    $(dirname $0)/buildfonts-gentiumplus
    $(dirname $0)/buildfonts-hannom
    $(dirname $0)/buildfonts-liberation
    $(dirname $0)/buildfonts-mgopen
    $(dirname $0)/buildfonts-noto
    $(dirname $0)/buildfonts-opendesktop
    $(dirname $0)/buildfonts-paratype
    $(dirname $0)/buildfonts-scheherazade
    $(dirname $0)/buildfonts-vlgothic

    if [ ! -z $1 ]
    then
      for dir in /binary/fonts/*
      do
        pushd ${dir}
          ./INSTALL
        popd
      done
    fi
  ;;
esac
