#!/bin/bash -e

export VER=1.9.0
export DEST=/binary/python-six-${VER}

cp -a six-${VER} six-${VER}-3

pushd six-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd six-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf six-${VER} six-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
