#!/bin/bash -e

export PKGVER=1.8.0
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

case $(basename $0) in
  buildgst-libav )
    export PKGNAME=gst-libav
    export MODULE=" Libav Plugins"
    export CONFIGURE_ADD_32=(--with-libav-extra-configure="--disable-inline-asm")
  ;;
  buildgst-plugins-bad )
    export PKGNAME=gst-plugins-bad
    export MODULE=" Bad Plugins"
    export CONFIGURE_ADD_32=(--build=i686-unknown-linux-gnu --disable-chromaprint --disable-qt --disable-teletextdec --disable-zbar)
    configure_pre() {
      sed -i "s:openjpeg-2.0:openjpeg-2.1:g" configure ext/openjpeg/gstopenjpeg.h
      sed -i "/user_data (/ s/mstream/&, NULL/" ext/openjpeg/gstopenjpegdec.c ext/openjpeg/gstopenjpegenc.c
    }
    configure_pre_32() {
      sed -i "s:openjpeg-2.0:openjpeg-2.1:g" configure ext/openjpeg/gstopenjpeg.h
      sed -i "/user_data (/ s/mstream/&, NULL/" ext/openjpeg/gstopenjpegdec.c ext/openjpeg/gstopenjpegenc.c
    }
  ;;
  buildgst-plugins-base )
    export PKGNAME=gst-plugins-base
    export MODULE=" Base Plugins"
  ;;
  buildgst-plugins-good )
    export PKGNAME=gst-plugins-good
    export MODULE=" Good Plugins"
    export CONFIGURE_ADD_32=(--build=i686-unknown-linux-gnu)
  ;;
  buildgst-plugins-ugly )
    export PKGNAME=gst-plugins-ugly
    export MODULE=" Ugly Plugins"
  ;;
  buildgstreamer )
    export PKGNAME=gstreamer
  ;;
  buildgstreamer-vaapi )
    export PKGNAME=gstreamer-vaapi
    export MODULE=" VAAPI Plugins"
  ;;
esac

export EXTRA_ARGS=(--with-package-name="GStreamer${MODULE} ${PKGVER} BLFS"
                   --with-package-origin="http://www.linuxfromscratch.org/blfs/view/systemd/")

export CONFIGURE_FLAGS=(--libexecdir=/usr/lib "${EXTRA_ARGS[@]}")
export CONFIGURE_FLAGS_32=(--libexecdir=/usr/lib32
                           --disable-examples
                           --disable-introspection
                           "${EXTRA_ARGS[@]}" "${CONFIGURE_ADD_32[@]}")

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://gstreamer.freedesktop.org/src/${PKGNAME}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}

. $(dirname $0)/master.sh
