#!/bin/bash -e

export VER=9.4.2
export DEST=/binary/postgresql-${VER}

pushd postgresql-${VER}

sed -e "s@DEFAULT_PGSOCKET_DIR  \"/tmp\"@DEFAULT_PGSOCKET_DIR  \"/run/postgresql\"@" -i src/include/pg_config_manual.h

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-gssapi \
            --with-ldap \
            --with-libxml \
            --with-openssl \
            --with-pam \
            --with-perl \
            --with-python \
            --with-tcl \
            --with-system-tzdata=/usr/share/zoneinfo \
            --enable-nls \
            --enable-thread-safety

make -j4
make install DESTDIR=${DEST}
make -C doc/src/sgml install DESTDIR=${DEST}

popd

rm -rf postgresql-${VER}

rm -rf ${DEST}/usr/share/doc

mkdir -p ${DEST}/etc/pam.d/
mkdir -p ${DEST}/etc/systemd/system/multi-user.target.wants/
mkdir -p ${DEST}/lib/systemd/system/
mkdir -p ${DEST}/usr/lib/tmpfiles.d/

cat > /etc/pam.d/postgresql << "EOF"
# Begin /etc/pam.d/postgresql

auth    include system-auth
account include system-account
session include system-session

# End /etc/pam.d/postgresql
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/postgresql.conf << "EOF"
d /run/postgresql 0775 postgres postgres -
EOF

cat > ${DEST}/lib/systemd/system/postgresql.service << "EOF"
[Unit]
Description=PostgreSQL database server
After=network.target

[Service]
Type=forking
TimeoutSec=120
User=postgres
Group=postgres

Environment=PGROOT=/var/lib/postgresql

SyslogIdentifier=postgres
PIDFile=/var/lib/postgresql/data/postmaster.pid

ExecStart= /usr/bin/pg_ctl -s -D ${PGROOT}/data start -w -t 120
ExecReload=/usr/bin/pg_ctl -s -D ${PGROOT}/data reload
ExecStop=  /usr/bin/pg_ctl -s -D ${PGROOT}/data stop -m fast

# Due to PostgreSQL's use of shared memory, OOM killer is often overzealous in
# killing Postgres, so adjust it downward
OOMScoreAdjust=-200

[Install]
WantedBy=multi-user.target
EOF

ln -sf /lib/systemd/system/postgresql.service ${DEST}/etc/systemd/system/multi-user.target.wants/postgresql.service

pushd ${DEST}
find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done
popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group postgres >/dev/null || groupadd -g 41 postgres
getent passwd postgres >/dev/null || useradd -c "PostgreSQL Server" -g postgres -d /var/lib/postgresql -u 41 postgres

install -dm755 -o postgres -g postgres /run/postgresql

if [ ! -e /var/lib/postgresql/data ]; then
  install -dm700 -o postgres -g postgres /var/lib/postgresql/data
  su - postgres -c '/usr/bin/initdb -D /var/lib/postgresql/data'
fi

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL

unset VER DEST
