#!/bin/bash -e

case $(basename $0) in
  buildatkmm )
    export PKGNAME=atkmm
    export PKGVER=2.24.2
  ;;
  buildcairomm )
    export PKGNAME=cairomm
    export PKGVER=1.12.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="https://www.cairographics.org/releases/${PKGTAR}"
  ;;
  buildglibmm )
    export PKGNAME=glibmm
    export PKGVER=2.50.0
  ;;
  buildgtkmm2 )
    export PKGNAME=gtkmm
    export PKGVER=2.24.5
  ;;
  buildgtkmm3 )
    export PKGNAME=gtkmm
    export PKGVER=3.22.0
  ;;
  buildlibsigc++ )
    export PKGNAME=libsigc++
    export PKGVER=2.10.0
  ;;
  buildpangomm )
    export PKGNAME=pangomm
    export PKGVER=2.40.1
  ;;
esac

export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export KEEP_DOC=1

if [ -z ${PKGTAR} ]
then
  export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
fi

if [ -z ${PKGURL} ]
then
  export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
fi

. $(dirname $0)/master.sh
