#!/bin/bash -e

export DEST=/binary/xorg

export PROTO=/media/ntfs/Other/Linux/proto.wget
export XORG_HTTP=http://xorg.freedesktop.org/archive/individual

export PROTO_HTTP=${XORG_HTTP}/proto/
export LIB_HTTP=${XORG_HTTP}/lib
export XCB_HTTP=${XORG_HTTP}/xcb

export XTRANS_VER=1.3.5
export XCB_PROTO_VER=1.11

export CONFIG="--prefix=/usr --sysconfdir=/etc --localstatedir=/var"

mkdir -p proto

pushd proto
  grep -v '^#' ${PROTO} | awk '{print $2}' | wget -i- -c -B ${PROTO_HTTP}
  md5sum -c ${PROTO}
popd

wget -c ${LIB_HTTP}/xtrans-${XTRANS_VER}.tar.bz2
wget -c ${XCB_HTTP}/xcb-proto-${XCB_PROTO_VER}.tar.bz2

pushd proto

for package in $(grep -v '^#' ${PROTO} | awk '{print $2}')
do
  packagedir=${package%.tar.bz2}
  tar -xf ${package}
  pushd ${packagedir}
  ./configure ${CONFIG}
  make install DESTDIR=${DEST}/proto/${packagedir}
  popd
  rm -rf ${packagedir}
done

popd

rm -rf ${DEST}/proto/*/usr/share

tar xf xtrans-${XTRANS_VER}.tar.bz2

pushd xtrans-${XTRANS_VER}
  ./configure ${CONFIG}
  make
  make install DESTDIR=${DEST}/$(basename $PWD)
  rm -rf ${DEST}/$(basename $PWD)/usr/share/doc
popd

rm -rf xtrans-${XTRANS_VER}

tar xf xcb-proto-${XCB_PROTO_VER}.tar.bz2

pushd xcb-proto-${XCB_PROTO_VER}
  ./configure ${CONFIG}
  make
  make install DESTDIR=${DEST}/$(basename $PWD)
popd

rm -rf xcb-proto-${XCB_PROTO_VER}

rm -rf proto xtrans-${XTRANS_VER}.tar.bz2  xcb-proto-${XCB_PROTO_VER}.tar.bz2

for dir in ${DEST}/proto/* ${DEST}/xtrans-${XTRANS_VER} ${DEST}/xcb-proto-${XCB_PROTO_VER}
do
cat > ${dir}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF
chmod 755 ${dir}/INSTALL
done
