#!/bin/bash -e

export BVER=3.01
export VER=${BVER}a25
export DEST=/binary/cdrtools-${VER}

pushd cdrtools-${BVER}

sed -i "s:-D_GNU_SOURCE:& -march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" DEFAULTS/Defaults.linux
sed -i 's|/opt/schily|/usr|g' DEFAULTS/Defaults.linux
sed -i 's|DEFINSGRP=.*|DEFINSGRP=root|' DEFAULTS/Defaults.linux

export GMAKE_NOWARN=true

make INS_BASE=/usr INS_RBASE=/
make install INS_BASE=/usr INS_RBASE=/ DESTDIR=${DEST}

popd

rm -rf cdrtools-${BVER}

rm -rf ${DEST}/usr/include
rm -rf ${DEST}/usr/lib/*.a
rm -rf ${DEST}/usr/lib/profiled
rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
