#!/bin/bash -e

export PKGNAME=grep
export PKGVER=2.22
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/grep/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--bindir=/bin)

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
