#!/bin/bash -e

export PKGNAME=e2fsprogs
export PKGVER=1.43.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/e2fsprogs/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-root-prefix=""
                        --enable-elf-shlibs
                        --disable-libblkid
                        --disable-libuuid
                        --disable-uuidd
                        --disable-fsck)
export MAKE_INSTALL_FLAGS="install-libs"

configure_override() {
  ./configure --prefix=/usr "${CONFIGURE_FLAGS[@]}"
}

post_install_config() {
  for file in ${DEST}/usr/lib/*.so ; do ln -sf ../..$(readlink $file) $file ; done

  sed -i -e 's#^SS_DIR=.*#SS_DIR="/usr/share/ss"#' ${DEST}/usr/bin/mk_cmds
  sed -i -e 's#^ET_DIR=.*#ET_DIR="/usr/share/et"#' ${DEST}/usr/bin/compile_et

  rm -f ${DEST}/usr/lib/*.a
}

. $(dirname $0)/master.sh
