#!/bin/bash -e

export PKGNAME=upower
export PKGVER=0.99.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://upower.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export PATCHES_LIST=("upower-fixes.patch")

make_install_post() {
  install -dm755 ${DEST}/etc/systemd/system/graphical.target.wants

  ln -sf /lib/systemd/system/upower.service ${DEST}/etc/systemd/system/graphical.target.wants/upower.service
}

. $(dirname $0)/master.sh
