#!/bin/bash -e

export VER=2.11
export DEST=/binary/radvd-${VER}

pushd radvd-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --sysconfdir=/etc

make -j4
make install DESTDIR=${DEST}

install -Dm644 radvd.conf.example ${DEST}/etc/radvd.conf

popd

rm -rf radvd-${VER}

install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants ${DEST}/lib/systemd/system

cat > ${DEST}/lib/systemd/system/radvd.service << "EOF"
[Unit]
Description=IPv6 Router Advertisement Daemon
After=network.target

[Service]
ExecStart=/usr/sbin/radvd --nodaemon --logmethod=stderr

[Install]
WantedBy=multi-user.target
EOF

ln -sf /lib/systemd/system/radvd.service ${DEST}/etc/systemd/system/multi-user.target.wants/radvd.service

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
