#!/bin/bash -e

export PKGNAME=jansson
export PKGVER=2.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.digip.org/jansson/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
