#!/bin/bash -e

export VER=20140525
export DEST=/binary/texlive-${VER}

install -dm755 texlive-${VER}-source/build

pushd texlive-${VER}-source/build

# Uses libpoppler.so
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
../configure --prefix=/usr                  \
             --sysconfdir=/etc              \
             --datarootdir=/usr/share       \
             --datadir=/usr/share           \
             --infodir=/usr/share/info      \
             --mandir=/usr/share/man        \
             --disable-native-texlive-build \
             --disable-dialog               \
             --disable-multiplatform        \
             --disable-psutils              \
             --disable-static               \
             --disable-t1utils              \
             --enable-shared                \
             --with-system-cairo            \
             --with-system-fontconfig       \
             --with-system-freetype2        \
             --with-system-gd               \
             --with-system-graphite2        \
             --with-system-harfbuzz         \
             --with-system-icu              \
             --with-system-libgs            \
             --with-system-libpaper         \
             --with-system-libpng           \
             --with-system-ncurses          \
             --with-system-pixman           \
             --with-system-pnglib           \
             --with-system-poppler          \
             --with-system-t1lib            \
             --with-system-xpdf             \
             --with-system-zlib             \
             --with-system-zziplib          \
             --with-banner-add=" - BLFS"

make -j4

make install DESTDIR=${DEST}
make texlinks DESTDIR=${DEST}

popd

rm -rf texlive-${VER}-source

tar --exclude=*/texmf-dist/doc --exclude=*/texmf-dist/source --strip-components=1 -xf texlive-${VER}-texmf.tar.xz -C ${DEST}/usr/share

sed -i "s@TEXMFROOT = \$SELFAUTOPARENT@TEXMFROOT = /usr/share@g" ${DEST}/usr/share/texmf-dist/web2c/texmf.cnf
sed -i "s@TEXMFSYSVAR = \$TEXMFROOT/texmf-var@TEXMFSYSVAR = /var/lib/texmf@g" ${DEST}/usr/share/texmf-dist/web2c/texmf.cnf
sed -i "s@TEXMFSYSCONFIG = \$TEXMFROOT/texmf-config@TEXMFSYSCONFIG = /etc/texmf@g" ${DEST}/usr/share/texmf-dist/web2c/texmf.cnf
sed -i "s@TEXMFHOME = ~/texmf@TEXMFHOME = ~/.texmf@g" ${DEST}/usr/share/texmf-dist/web2c/texmf.cnf

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

pushd ${DEST}

find usr/bin usr/lib -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

/usr/bin/mktexlsr
/usr/bin/fmtutil-sys --all 1>/dev/null

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
