#!/bin/bash -e

export VER=3.15.3.1
export DEST=/binary/gdm-${VER}

pushd gdm-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-static     \
            --without-plymouth   \
            --with-default-pam-config=lfs

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gdm-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/var/run

sed -i "/user = gdm/d" ${DEST}/etc/pam.d/gdm-launch-environment

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group gdm > /dev/null || groupadd -g 21 gdm
getent passwd gdm > /dev/null || useradd -c "GDM Daemon Owner" -d /var/lib/gdm -g gdm -s /bin/false -u 21 gdm

if [ ! -e /var/log/gdm ]; then
   cp -rf --remove-destination var/log/gdm /var/log
   chmod 755 /var/log/gdm
   chown root:root /var/log/gdm
fi

if [ ! -e /var/lib/gdm ]; then
   cp -rf --remove-destination var/lib/gdm /var/lib
   chown -R gdm:gdm /var/lib/gdm
   chmod 1770 /var/lib/gdm
   chown root:gdm /var/lib/gdm
fi

if [ ! -e /var/cache/gdm ]; then
   cp -rf --remove-destination var/cache/gdm /var/cache
   chmod 1755 /var/cache/gdm
   chown -R root:gdm /var/cache/gdm
fi

if [ ! -e /run/gdm ]; then
   install -dm711 -o root -g gdm /run/gdm
   install -dm755 -o gdm  -g gdm /run/gdm/greeter
fi

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
