#!/bin/bash -e

export VER=0.1.1
export DEST=/binary/python-notify-${VER}

pushd notify-python-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/notify-python-fixes.patch

PYTHON=/usr/bin/python \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

touch src/pynotify.override

make clean
make -j4
make install DESTDIR=${DEST}

popd

rm -rf notify-python-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
