#!/bin/bash -e

export VER=0.23
export DEST=/binary/python-markupsafe-${VER}

cp -a MarkupSafe-${VER} MarkupSafe-${VER}-3

pushd MarkupSafe-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd MarkupSafe-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf MarkupSafe-${VER} MarkupSafe-${VER}-3

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
