#!/bin/bash -e

export PKGNAME=kid3
export PKGVER=3.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/kid3/${PKGTAR}"
export DEST=/binary/plasma/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export KEEP_DOC=1
export CMAKE_FLAGS=(-DWITH_QT5=ON -DWITH_APPS="CLI;KDE")

make_install_post() {
  rm -f ${DEST}/usr/share/man/man1/kid3-cli.1.gz

  ln -sf kid3.1 ${DEST}/usr/share/man/man1/kid3-cli.1

  gzip -d ${DEST}/usr/share/man/man1/*.gz
}

. $(dirname $0)/master.sh
