#!/bin/bash -e

export PKGNAME=libpng
export PKGVER=1.2.56
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://downloads.sourceforge.net/libpng/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

make_override() {
  make libpng.la ${ADDITIONAL_MAKE_FLAGS}
}

make_install_override() {
  make lib_LTLIBRARIES="libpng.la libpng12.la" install-libLTLIBRARIES ${ADDITIONAL_MAKE_INSTALL_FLAGS}
}

post_install_config() {
  rm -rf ${DEST}/usr/lib*/*.so
}

. $(dirname $0)/master.sh
