#!/bin/bash -e

export PKGVER=44.0.2403.107
export DEST=/binary/chromium-${PKGVER}

export -n CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"
export -n CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"

export CC=clang
export CXX=clang++

chromium_conf=(
    -Dgoogle_api_key=AIzaSyCnwAWeKPGN7pGmQJyDitvcb1uTSlE2R1w
    -Dgoogle_default_client_id=11433373901.apps.googleusercontent.com
    -Dgoogle_default_client_secret=xZ5yO6MG_uMyrh0srUAkJ4KG
    -Dwerror=
    -Dclang=1
    -Dclang_use_chrome_plugins=0
    -Dpython_ver=2.7
    -Dlinux_link_gsettings=1
    -Dlinux_link_libpci=1
    -Dlinux_link_libspeechd=1
    -Dlinux_link_pulseaudio=1
    -Dlinux_strip_binary=1
    -Dlinux_use_bundled_binutils=0
    -Dlinux_use_bundled_gold=0
    -Dlinux_use_gold_flags=0
    -Dicu_use_data_file_flag=0
    -Dlogging_like_official_build=1
    -Drelease_extra_cflags="$CFLAGS"
    -Dlibspeechd_h_prefix=speech-dispatcher/
    -Dffmpeg_branding=Chrome
    -Dproprietary_codecs=1
    -Duse_system_bzip2=1
    -Duse_system_flac=1
    -Duse_system_harfbuzz=1
    -Duse_system_icu=1
    -Duse_system_libevent=1
    -Duse_system_libjpeg=1
    -Duse_system_libpng=1
    -Duse_system_libvpx=1
    -Duse_system_libwebp=1
    -Duse_system_libxml=1
    -Duse_system_libxslt=1
    -Duse_system_minizip=1
    -Duse_system_nspr=1
    -Duse_system_speex=1
    -Duse_system_xdg_utils=1
    -Duse_system_yasm=1
    -Duse_system_zlib=1
    -Dicu_use_data_file_flag=0
    -Duse_gconf=0
    -Duse_gnome_keyring=0
    -Duse_mojo=0
    -Dusb_ids_path=/usr/share/misc/usb.ids
    -Dtarget_arch=x64
    -Dcups=1
    -Ddisable_fatal_linker_warnings=1
    -Ddisable_nacl=1
    -Ddisable_pnacl=1
    -Ddisable_sse2=1
    -Ddisable_glibc=1)

case "$1" in
   fetch)
      wget -c https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${PKGVER}.tar.xz
      rm -rf chromium-${PKGVER}
      tar xf chromium-${PKGVER}.tar.xz

      pushd chromium-${PKGVER}

         find third_party/icu -type f \! -regex '.*\.\(gyp\|gypi\|isolate\)' -delete

         if [ -e /media/ntfs/Other/Linux/patches/chromium-fixes.patch ]; then
            patch -Np1 -i /media/ntfs/Other/Linux/patches/chromium-fixes.patch
         fi

        mkdir -p third_party/llvm-build/Release+Asserts/bin
        ln -sf /usr/bin/clang third_party/llvm-build/Release+Asserts/bin/
        ln -sf /usr/bin/clang++ third_party/llvm-build/Release+Asserts/bin/
        ln -sf /usr/bin/llvm-symbolizer third_party/llvm-build/Release+Asserts/bin/

      popd
   ;;
   build)
      pushd chromium-${PKGVER}
         build/linux/unbundle/replace_gyp_files.py "${chromium_conf[@]}"
         build/gyp_chromium --depth=. "${chromium_conf[@]}"

         ninja -C out/Release chrome chrome_sandbox chromedriver -j4
      popd
   ;;
   install)
      install -dm755 ${DEST}/etc/chromium \
                     ${DEST}/usr/bin \
                     ${DEST}/usr/lib/chromium

cat > ${DEST}/etc/chromium/default << "EOF"
# Default settings for chromium. This file is sourced by /usr/bin/chromium

# Options to pass to chromium
CHROMIUM_FLAGS=""
EOF

cat > ${DEST}/usr/bin/chromium << "EOF"
#!/bin/bash

# Allow users to override command-line options
# Based on Gentoo's chromium package
if [[ -f /etc/chromium/default ]]; then
	. /etc/chromium/default
fi
# Source additional configuration files
for file in /etc/chromium/*; do
	# Don't source /etc/chromium/default again
	[[ $file == /etc/chromium/default ]] && continue

	if [[ -f $file ]]; then
		. $file
	fi
done

# Prefer user defined CHROMIUM_USER_FLAGS (from env) over system
# default CHROMIUM_FLAGS (from /etc/chromium/default)
CHROMIUM_FLAGS=${CHROMIUM_USER_FLAGS:-$CHROMIUM_FLAGS}

export CHROME_WRAPPER=$(readlink -f "$0")
export CHROME_DESKTOP=chromium.desktop

exec /usr/lib/chromium/chromium $CHROMIUM_FLAGS "$@"
EOF

      chmod 644 ${DEST}/etc/chromium/default
      chmod 755 ${DEST}/usr/bin/chromium

      install -Dm644 /media/ntfs/Other/Linux/chromium.desktop ${DEST}/usr/share/applications/chromium.desktop

      pushd chromium-${PKGVER}
         install -m755 -o root -g root out/Release/chrome ${DEST}/usr/lib/chromium/chromium
         install -m4755 -o root -g root out/Release/chrome_sandbox ${DEST}/usr/lib/chromium/chrome-sandbox
         install -m755 -o root -g root out/Release/chromedriver ${DEST}/usr/lib/chromium/chromedriver

         ln -sf ../lib/chromium/chromedriver ${DEST}/usr/bin/chromedriver

         install -Dm644 out/Release/chrome.1 ${DEST}/usr/share/man/man1/chromium.1

         for size in 22 24 48 64 128 256; do
            install -Dm644 chrome/app/theme/chromium/product_logo_${size}.png \
                           ${DEST}/usr/share/icons/hicolor/${size}x${size}/apps/chromium.png
         done

         cp -rf out/Release/locales ${DEST}/usr/lib/chromium/

         # Bundled ICU
         #cp -rf out/Release/icudtl.dat ${DEST}/usr/lib/chromium/

         cp -rf out/Release/chrome_100_percent.pak \
                out/Release/chrome_200_percent.pak \
                out/Release/content_resources.pak  \
                out/Release/keyboard_resources.pak \
                out/Release/natives_blob.bin  \
                out/Release/resources.pak     \
                out/Release/snapshot_blob.bin \
                ${DEST}/usr/lib/chromium/

#                out/Release/libffmpegsumo.so \
#                out/Release/libpdf.so \
#                out/Release/nacl_helper \
#                out/Release/nacl_helper_bootstrap \
#                out/Release/nacl_irt_x86_64.nexe \

      popd

      strip --strip-unneeded ${DEST}/usr/lib/chromium/chromium
      strip --strip-unneeded ${DEST}/usr/lib/chromium/chrome-sandbox
      strip --strip-unneeded ${DEST}/usr/lib/chromium/chromedriver
      #strip --strip-unneeded ${DEST}/usr/lib/chromium/nacl_helper
      #strip --strip-unneeded ${DEST}/usr/lib/chromium/nacl_helper_bootstrap
      #strip --strip-unneeded ${DEST}/usr/lib/chromium/libffmpegsumo.so
      #strip --strip-unneeded ${DEST}/usr/lib/chromium/libpdf.so

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

chmod 4755 /usr/lib/chromium/chrome-sandbox

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

      chmod 755 ${DEST}/INSTALL

   ;;
esac
