#!/bin/bash -e

export PKGNAME=gegl
export PKGVER=0.3.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.gimp.org/pub/gegl/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
