#!/bin/bash -e

export PKGNAME=libiscsi
export PKGVER=1.17.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/sahlberg/libiscsi/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

configure_pre() {
  ./autogen.sh
}

. $(dirname $0)/master.sh
