#!/bin/bash -e

export PKGNAME=groff
export PKGVER=1.22.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/groff/${PKGTAR}"
export KEEP_EMPTY_DIRS=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

make_install_post() {
  for file in eqn tbl
  do
    ln -sf $file ${DEST}/usr/bin/g${file}
    ln -sf $file.1 ${DEST}/usr/share/man/man1/g${file}.1
  done
}

. $(dirname $0)/master.sh
