#!/bin/bash -e

export PKGNAME=orc
export PKGVER=0.4.26
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://gstreamer.freedesktop.org/src/orc/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_post() {
  sed "/SUBDIRS/s:testsuite::" -i Makefile
}

. $(dirname $0)/master.sh
