#!/bin/bash -e

export VER=9
export DEST=/binary/mime-types-${VER}

pushd mime-types-${VER}

install -Dm644 mime.types ${DEST}/etc/mime.types

popd

rm -rf mime-types-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination etc /
EOF

chmod 755 ${DEST}/INSTALL
