#!/bin/bash -e

export PKGNAME=speex
export PKGVER=1.2rc2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://downloads.xiph.org/releases/speex/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
#export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
