#!/bin/bash -e

export PKGNAME=libusbmuxd
export PKGVER=1.0.10
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.libimobiledevice.org/downloads/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
