#!/bin/bash -e

export PKGNAME=libdvdread
export PKGVER=5.0.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.videolan.org/pub/videolan/libdvdread/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
