#!/bin/bash -e

export VER=1.4.0
export DEST=/binary/libjpeg-turbo-${VER}

#pushd libjpeg-turbo-${VER}
#  patch -Np1 -i /media/ntfs/Other/Linux/patches/libjpeg-turbo.patch
#popd

cp -a libjpeg-turbo-${VER} libjpeg-turbo-${VER}-32

pushd libjpeg-turbo-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-jpeg8            \
            --disable-static

make -j4
make docdir=/usr/share/doc/libjpeg-turbo     \
     exampledir=/usr/share/doc/libjpeg-turbo \
     DESTDIR=${DEST} install

popd

pushd libjpeg-turbo-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr           \
            --libdir=/usr/lib32     \
            --mandir=/usr/share/man \
            --with-jpeg8            \
            --disable-static        \
            --without-simd


make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf libjpeg-turbo-${VER} libjpeg-turbo-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
