#!/bin/bash -e

export PKGNAME=libdvbpsi
export PKGVER=1.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.videolan.org/pub/libdvbpsi/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

configure_pre() {
  sed -i "s:-Werror ::g" configure
}

. $(dirname $0)/master.sh
