#!/bin/bash -e

export VER=6.3
export DEST=/binary/readline-${VER}

pushd readline-${VER}

if [ -f /media/ntfs/Other/Linux/patches/readline-fixes.patch ]
then
   patch -Np1 -i /media/ntfs/Other/Linux/patches/readline-fixes.patch
fi

popd

cp -a readline-${VER} readline-${VER}-32

pushd readline-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-static

make SHLIB_LIBS=-lncurses -j4
make install DESTDIR=${DEST}

popd

pushd readline-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-static

make SHLIB_LIBS=-lncurses -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf readline-${VER} readline-${VER}-32

install -dm755 ${DEST}/etc ${DEST}/lib

rm -rf ${DEST}/usr/bin ${DEST}/usr/share/doc ${DEST}/usr/share/info/dir

gzip -9 ${DEST}/usr/share/info/*

mv ${DEST}/usr/lib/libhistory.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libhistory.so) ${DEST}/usr/lib/libhistory.so

mv ${DEST}/usr/lib/libreadline.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libreadline.so) ${DEST}/usr/lib/libreadline.so

cat > ${DEST}/etc/inputrc << "EOF"
# Begin /etc/inputrc

set bell-style none
set horizontal-scroll-mode Off

set meta-flag on
set input-meta on
set convert-meta off
set output-meta on

$if mode=emacs

# for linux console and RH/Debian xterm
"\e[1~": beginning-of-line
"\e[4~": end-of-line
"\e[5~": beginning-of-history
"\e[6~": end-of-history
"\e[7~": beginning-of-line
"\e[3~": delete-char
"\e[2~": quoted-insert
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
"\e[1;5C": forward-word
"\e[1;5D": backward-word

# for rxvt
"\e[8~": end-of-line

# for non RH/Debian xterm, can't hurt for RH/Debian xterm
"\eOH": beginning-of-line
"\eOF": end-of-line

# for freebsd console
"\e[H": beginning-of-line
"\e[F": end-of-line
$endif

# End /etc/inputrc
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
