#!/bin/bash -e

export PKGNAME=evas_generic_loaders
export PKGVER=1.16.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://download.enlightenment.org/rel/libs/evas_generic_loaders/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
