#!/bin/bash -e

export PKGNAME=zip
export PKGVER=3.0
export PKGTAR=zip30.tar.gz
export PKGDIR=zip30
export PKGURL="https://downloads.sourceforge.net/infozip/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_FLAGS="-f unix/Makefile generic_gcc"
export MAKE_INSTALL_FLAGS="-f unix/Makefile prefix=\${DEST}/usr MANDIR=\${DEST}/usr/share/man/man1"

configure_override() {
  sed -i "s:-O3:${CFLAGS}:g" unix/configure

  unset CFLAGS
}

. $(dirname $0)/master.sh
