#!/bin/bash -e

export VER=4.88
export DEST=/binary/lsof-${VER}

install -dm755 lsof-${VER}

wget -c ftp://sunsite.ualberta.ca/pub/Mirror/lsof/lsof_${VER}.tar.bz2

tar -xf lsof_${VER}.tar.bz2 lsof_${VER}/lsof_${VER}_src.tar --strip-components=1
tar -xf lsof_${VER}_src.tar --strip-components=1 -C lsof-${VER}

pushd lsof-${VER}

./Configure -n linux

sed -i "/DEBUG/s:-O:-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong:" Makefile

make -j4

install -Dm755 lsof ${DEST}/usr/bin/lsof
install -Dm644 lsof.8 ${DEST}/usr/share/man/man8/lsof.8

popd

rm -rf lsof-${VER} lsof_${VER}.tar.bz2 lsof_${VER}_src.tar

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
