#!/bin/bash -e

export VER=4.2.1
export DEST=/binary/shadow-${VER}

pushd shadow-${VER}

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;
sed -i -e 's/ ko//' -e 's/ zh_CN zh_TW//' man/Makefile.in

sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

sed -i -e 's@PATH=/sbin:/bin:/usr/sbin:/usr/bin@&:/usr/local/sbin:/usr/local/bin@' \
       -e 's@PATH=/bin:/usr/bin@&:/usr/local/bin@' etc/login.defs

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr --sysconfdir=/etc --with-group-name-max-length=32

make -j4
make install DESTDIR=${DEST}

popd

rm -rf shadow-${VER}

for FUNCTION in FAIL_DELAY FAILLOG_ENAB \
                LASTLOG_ENAB \
                MAIL_CHECK_ENAB \
                OBSCURE_CHECKS_ENAB \
                PORTTIME_CHECKS_ENAB \
                QUOTAS_ENAB \
                CONSOLE MOTD_FILE \
                FTMP_FILE NOLOGINS_FILE \
                ENV_HZ PASS_MIN_LEN \
                SU_WHEEL_ONLY \
                CRACKLIB_DICTPATH \
                PASS_CHANGE_TRIES \
                PASS_ALWAYS_WARN \
                CHFN_AUTH ENCRYPT_METHOD \
                ENVIRON_FILE
do
    sed -i "s/^${FUNCTION}/# &/" ${DEST}/etc/login.defs
done

sed -i 's/yes/no/' ${DEST}/etc/default/useradd

rm -rf ${DEST}/usr/share/man/{cs,da,de,fi,fr,hu,id}
rm -rf ${DEST}/usr/share/man/{it,ja,pl,pt_BR,ru,sv,tr}

cat > ${DEST}/etc/pam.d/login << "EOF"
# Begin /etc/pam.d/login

auth	 requisite      pam_nologin.so
auth	 required       pam_securetty.so
auth	 optional       pam_faildelay.so delay=3000000
auth     optional       pam_group.so

auth     include        system-auth

account  required       pam_access.so
account	 include        system-account

password include        system-password

session  required       pam_env.so
session  required       pam_limits.so
session  optional       pam_lastlog.so
session  optional       pam_motd.so
session  optional       pam_mail.so standard

session	 include        system-session

# End /etc/pam.d/login
EOF

cat > ${DEST}/etc/pam.d/su << "EOF"
# Begin /etc/pam.d/su

auth	 sufficient     pam_rootok.so
auth	 include        system-auth

account  include        system-account

session  required       pam_env.so
session  optional       pam_mail.so nopen
session  include        system-session

# End /etc/pam.d/su
EOF

cat > ${DEST}/etc/pam.d/passwd << "EOF"
# Begin /etc/pam.d/passwd

password   include      system-password

# End /etc/pam.d/passwd
EOF

cat > ${DEST}/etc/pam.d/chage << "EOF"
# Begin /etc/pam.d/chage

auth     sufficient	pam_rootok.so

auth     include	system-auth
account  include	system-account
session  include	system-session

password required	pam_permit.so

# End /etc/pam.d/chage
EOF

for PROGRAM in chfn chgpasswd chpasswd chsh groupadd groupdel \
               groupmems groupmod newusers useradd userdel usermod
do
  sed "s:chage:$PROGRAM:g" ${DEST}/etc/pam.d/chage > ${DEST}/etc/pam.d/${PROGRAM}
done

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in bin etc sbin usr ; do cp -rf --remove-destination $dir / ; done

chmod 4755 /bin/su /usr/bin/chage /usr/bin/chfn
chmod 4755 /usr/bin/chsh /usr/bin/expiry /usr/bin/gpasswd
chmod 4755 /usr/bin/newgidmap /usr/bin/newgrp
chmod 4755 /usr/bin/newuidmap /usr/bin/passwd

grpconv
pwconv

passwd

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL

