#!/bin/bash -e

export VER=1.0.28
export DEST=/binary/alsa-plugins-${VER}

cp -a alsa-plugins-${VER} alsa-plugins-${VER}-32

pushd alsa-plugins-${VER}

#patch -Np1 -i /media/ntfs/Other/Linux/patches/alsa-plugins.patch

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

pushd alsa-plugins-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-avcodec

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf alsa-plugins-${VER} alsa-plugins-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
