#!/bin/bash -e

export PKGNAME=curl
export PKGVER=7.46.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://curl.haxx.se/download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

if [ -z $1 ]
then
  export ADDITIONAL_CONFIGURE_FLAGS=(--with-gssapi)
fi

export CONFIGURE_FLAGS=(--enable-threaded-resolver ${ADDITIONAL_CONFIGURE_FLAGS[@]})
export CONFIGURE_FLAGS_32=(--enable-threaded-resolver ${ADDITIONAL_CONFIGURE_FLAGS[@]})

. $(dirname $0)/master.sh
