#!/bin/bash -e

export VER=0.99.beta19
export DEST=/binary/libcaca-${VER}

pushd libcaca-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr    \
            --disable-static \
            --disable-doc    \
            --disable-gl     \
            --disable-csharp \
            --disable-cxx    \
            --disable-java   \
            --disable-python \
            --disable-ruby

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libcaca-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

cp -rf --remove-destination usr/bin/caca-config /usr/bin
cp -rf --remove-destination usr/share/man/man1/caca-config.1 /usr/share/man/man1/

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
