#!/bin/bash -e

export VER=0.2.3
export DEST=/binary/rpcbind-${VER}

pushd rpcbind-${VER}

sed -i "/servname/s:rpcbind:sunrpc:" src/rpcbind.c
sed -i "/error = getaddrinfo/s:rpcbind:sunrpc:" src/rpcinfo.c

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --bindir=/sbin      \
            --with-rpcuser=rpc  \
            --enable-warmstarts \
            --with-statedir=/var/lib/rpcbind

make -j4
make install DESTDIR=${DEST}

popd

rm -rf rpcbind-${VER}

install -dm755 ${DEST}/etc/systemd/system/sockets.target.wants ${DEST}/lib/systemd/system

cat > ${DEST}/lib/systemd/system/rpcbind.service << "EOF"
[Unit]
Description=RPC Bind Service
Requires=rpcbind.socket

[Service]
Type=forking
ExecStart=/sbin/rpcbind -w

[Install]
Also=rpcbind.socket
EOF

cat > ${DEST}/lib/systemd/system/rpcbind.socket << "EOF"
[Unit]
Description=RPC Bind Server Activation Socket

[Socket]
ListenStream=/var/run/rpcbind.sock

[Install]
WantedBy=sockets.target
EOF

ln -sf /lib/systemd/system/rpcbind.socket ${DEST}/etc/systemd/system/sockets.target.wants/rpcbind.socket

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib sbin usr ; do cp -rf --remove-destination $dir / ; done

getent group rpc > /dev/null || groupadd -g 28 rpc
getent passwd rpc > /dev/null || useradd -c "RPC Bind Daemon Owner" -d /dev/null -g rpc -s /bin/false -u 28 rpc

install -o rpc -g rpc -dm755 /var/lib/rpcbind

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
