#!/bin/bash -e

export PKGNAME=less
export PKGVER=481
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.greenwoodsoftware.com/less/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
