#!/bin/bash -e

export VER=0.04.18
export DEST=/binary/python-unidecode-${VER}

cp -a Unidecode-${VER} Unidecode-${VER}-3

pushd Unidecode-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd Unidecode-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf Unidecode-${VER} Unidecode-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
