#!/bin/bash -e

export VER=8.0.01
export DEST=/binary/unifont-${VER}

pushd unifont-${VER}

make CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"
make install DESTDIR=${DEST}

popd

rm -rf unifont-${VER}

rm -f ${DEST}/usr/share/unifont/ChangeLog.gz
rm -f ${DEST}/usr/share/unifont/INSTALL.gz
rm -f ${DEST}/usr/share/unifont/NEWS.gz
rm -f ${DEST}/usr/share/unifont/README.gz
rm -f ${DEST}/usr/share/unifont/unifont.txt.gz

install -dm755 ${DEST}/usr/share/info

mv ${DEST}/usr/share/unifont/unifont.info.gz ${DEST}/usr/share/info

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/unifont
[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
