#!/bin/bash -e

export PKGNAME=serf
export PKGVER=1.3.9
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://archive.apache.org/dist/serf/${PKGTAR}"

configure_override() {
  sed -i "/Append/s:RPATH=libdir,::"   SConstruct
  sed -i "/Default/s:lib_static,::"    SConstruct
  sed -i "/Alias/s:install_static,::"  SConstruct
}

make_override() {
  scons PREFIX=/usr
}

make_install_override() {
  scons PREFIX=${DEST}/usr install
}

. $(dirname $0)/master.sh
