#!/bin/bash -e

export VER=1.5.3
export DEST=/binary/ninja-${VER}

pushd ninja-${VER}

python ./bootstrap.py

install -Dm755 ninja ${DEST}/usr/bin/ninja

popd

rm -rf ninja-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
