#!/bin/bash -e

export VER=1.11.0
export DEST=/binary/glew-${VER}

cp -a glew-${VER} glew-${VER}-32

pushd glew-${VER}

sed -i 's|lib64|lib|' config/Makefile.linux
sed -i '/^.PHONY: .*\.pc$/d' Makefile

make -j4 CFLAGS.EXTRA="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -fPIC"
make GLEW_DEST=${DEST}/usr install.all

popd

pushd glew-${VER}-32

sed -i 's|CC = cc|CC = gcc -m32|' config/Makefile.linux
sed -i 's|LD = cc|LD = gcc -m32|' config/Makefile.linux
sed -i 's|lib64|lib32|' config/Makefile.linux

make -j4 CFLAGS.EXTRA="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -fPIC"
make GLEW_DEST=${PWD}/dest/usr install.all

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf glew-${VER} glew-${VER}-32

rm -rf ${DEST}/usr/lib*/*.a
chmod 755 ${DEST}/usr/lib*/*.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
