#!/bin/bash -e

export PKGNAME=wavpack
export PKGVER=4.80.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.wavpack.com/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export CONFIGURE_FLAGS_32=(--disable-asm)

. $(dirname $0)/master.sh
