#!/bin/bash -e

export PKGNAME=popt
export PKGVER=1.16
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://rpm5.org/files/popt/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libpopt.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libpopt.so) ${DEST}/usr/lib/libpopt.so
}

. $(dirname $0)/master.sh
