#!/bin/bash -e

export VER=1.36.8
export DEST=/binary/pango-${VER}

cp -a pango-${VER} pango-${VER}-32

pushd pango-${VER}

CFLAGS="-march=native -mtune=native -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --sysconfdir=/etc

make -j4
make install DESTDIR=${DEST}

popd

pushd pango-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --sysconfdir=/etc   \
            --disable-introspection

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr
mv dest/usr/bin/pango-querymodules ${DEST}/usr/bin/pango-querymodules-32

popd

rm -rf pango-${VER} pango-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

pango-querymodules --update-cache
pango-querymodules-32 --update-cache

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
