#!/bin/bash -e

export PKGNAME=ethtool
export PKGVER=4.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/software/network/ethtool/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
