#!/bin/bash -e

export PKGNAME=xmlto
export PKGVER=0.0.28
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://fedorahosted.org/releases/x/m/xmlto/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
