#!/bin/bash -e

export VER=5.6.24
export DEST=/binary/mysql-${VER}

sed -i "s:#define\[:#\[\\\t \]\*define\[:" mysql-${VER}/cmake/ssl.cmake

mkdir -p mysql-${VER}/build

pushd mysql-${VER}/build

sed -i "s@data/test@\${INSTALL_MYSQLSHAREDIR}@g" ../sql/CMakeLists.txt
sed -i "s@data/mysql@\${INSTALL_MYSQLTESTDIR}@g" ../sql/CMakeLists.txt

sed -i "s/srv_buf_size/srv_sort_buf_size/" ../storage/innobase/row/row0log.cc

cmake -DCMAKE_BUILD_TYPE=Release                    \
      -DCMAKE_INSTALL_PREFIX=/usr                   \
      -DINSTALL_DOCDIR=share/doc/mysql              \
      -DINSTALL_DOCREADMEDIR=share/doc/mysql        \
      -DINSTALL_INCLUDEDIR=include/mysql            \
      -DINSTALL_INFODIR=share/info                  \
      -DINSTALL_MANDIR=share/man                    \
      -DINSTALL_MYSQLDATADIR=/var/lib/mysql         \
      -DINSTALL_MYSQLSHAREDIR=share/mysql           \
      -DINSTALL_MYSQLTESTDIR=share/mysql/test       \
      -DINSTALL_PLUGINDIR=lib/mysql/plugin          \
      -DINSTALL_SBINDIR=sbin                        \
      -DINSTALL_SCRIPTDIR=bin                       \
      -DINSTALL_SQLBENCHDIR=share/mysql/bench       \
      -DINSTALL_SUPPORTFILESDIR=share/mysql         \
      -DMYSQL_DATADIR=/var/lib/mysql                \
      -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock     \
      -DSYSCONFDIR=/etc/mysql                       \
      -DWITH_PARTITION_STORAGE_ENGINE=ON            \
      -DWITH_PERFSCHEMA_STORAGE_ENGINE=ON           \
      -DWITH_EXTRA_CHARSETS=complex                 \
      -DWITH_SSL=system                             \
      -DCMAKE_C_FLAGS="-fPIC -march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-fPIC -march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
      ..

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mysql-${VER}

rm -rf ${DEST}/usr/data
rm -rf ${DEST}/usr/lib/mysql/plugin/debug
rm -rf ${DEST}/usr/share/doc

rm -rf ${DEST}/usr/share/mysql/bench
rm -rf ${DEST}/usr/share/mysql/test

rm -rf ${DEST}/usr/lib/mysql/plugin/daemon_example.ini
rm -rf ${DEST}/usr/lib/mysql/plugin/libdaemon_example.so

mkdir -p ${DEST}/etc/mysql
mkdir -p ${DEST}/etc/systemd/system/multi-user.target.wants
mkdir -p ${DEST}/lib/systemd/system
mkdir -p ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/etc/mysql/my.cnf << "EOF"
# Begin /etc/mysql/my.cnf

# The following options will be passed to all MySQL clients
[client]
#password       = your_password
port            = 3306
socket          = /run/mysqld/mysqld.sock

# The MySQL server
[mysqld]
port            = 3306
socket          = /run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
skip-external-locking
key_buffer_size = 16M
max_allowed_packet = 1M
sort_buffer_size = 512K
net_buffer_length = 16K
myisam_sort_buffer_size = 8M

# Don't listen on a TCP/IP port at all.
skip-networking

# required unique id between 1 and 2^32 - 1
server-id       = 1

# Uncomment the following if you are using BDB tables
#bdb_cache_size = 4M
#bdb_max_lock = 10000

# Uncomment the following if you are using InnoDB tables
#innodb_data_home_dir = /var/lib/mysql
#innodb_data_file_path = ibdata1:10M:autoextend
#innodb_log_group_home_dir = /var/lib/mysql
# You can set .._buffer_pool_size up to 50 - 80 %
# of RAM but beware of setting memory usage too high
#innodb_buffer_pool_size = 16M
#innodb_additional_mem_pool_size = 2M
# Set .._log_file_size to 25 % of buffer pool size
#innodb_log_file_size = 5M
#innodb_log_buffer_size = 8M
#innodb_flush_log_at_trx_commit = 1
#innodb_lock_wait_timeout = 50

[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash
# Remove the next comment character if you are not familiar with SQL
#safe-updates

[isamchk]
key_buffer = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[myisamchk]
key_buffer_size = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[mysqlhotcopy]
interactive-timeout

# End /etc/mysql/my.cnf
EOF

cat > ${DEST}/lib/systemd/system/mysqld.service << "EOF"
[Unit]
Description=MySQL Server
After=network.target

[Service]
User=mysql
Group=mysql
ExecStart=/usr/sbin/mysqld --pid-file=/run/mysqld/mysqld.pid
Restart=always
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/mysqld.conf << "EOF"
d /run/mysqld 0755 mysql mysql -
EOF

ln -sf /lib/systemd/system/mysqld.service ${DEST}/etc/systemd/system/multi-user.target.wants/mysqld.service

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group mysql > /dev/null || groupadd -g 40 mysql
getent passwd mysql > /dev/null || useradd -c "MySQL Server" -d /var/lib/mysql -g mysql -s /bin/false -u 40 mysql

systemctl daemon-reload

if [ ! -e /var/lib/mysql ]; then
   mkdir -p /var/lib/mysql
   /usr/bin/mysql_install_db --user=mysql --datadir=/var/lib/mysql --basedir=/usr
   chown -R mysql:mysql /var/lib/mysql
fi

if [ ! -e /run/mysqld ]; then
   install -m755 -d -o mysql -g mysql /run/mysqld
fi

if [ -e /run/systemd ]; then

  if [ ! -e /run/mysqld/mysqld.pid ]; then
     systemctl start mysqld
  else
     systemctl restart mysqld
  fi

  echo "Upgrading MySQL tables, please enter root password:"
  /usr/bin/mysql_upgrade -u root -p

  systemctl restart mysqld

fi

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd
