#!/bin/bash -e

export PKGNAME=libkpathsea
export PKGVER=20150521
export PKGTAR=texlive-${PKGVER}-source.tar.xz
export PKGDIR=texlive-${PKGVER}-source
export PKGBUILD=texlive-${PKGVER}-source/texk/kpathsea
export PKGURL="ftp://tug.org/texlive/historic/2015/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
