#!/bin/bash -e

export VER=2.0.10-4
export DEST=/binary/ebtables-${VER}

pushd ebtables-v${VER}

sed -i "/CFLAGS/s:-Werror:-march=sandybridge -O2 -pipe -fstack-protector-strong:" Makefile
sed -i "/CFLAGS_SH_LIB/s:-O3:-march=sandybridge -O2 -pipe -fstack-protector-strong:" Makefile

make LDFLAGS="-Wl,-rpath,/lib/ebtables"
make install BINDIR=/sbin INITDIR=/etc/rc.d LIBDIR=/lib/ebtables MANDIR=/usr/share/man SYSCONFIGDIR=/etc DESTDIR=${DEST}

popd

rm -rf ebtables-v${VER}

rm -rf ${DEST}/etc/ebtables-config ${DEST}/etc/rc.d

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
