#!/bin/bash -e

export VER=0.4.1
export DEST=/binary/gnome-video-effects-${VER}

pushd gnome-video-effects-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnome-video-effects-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
