#!/bin/bash -e

export PKGNAME=ladspa
export PKGVER=1.13
export PKGTAR=${PKGNAME}_sdk_${PKGVER}.tgz
export PKGDIR=${PKGNAME}_sdk/src
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MULTILIB_BUILD=1
export PATCHES_LIST=("ladspa-fixes.patch")
export PATCHES_LIST_32=("ladspa-fixes.patch")
export MAKE_FLAGS="targets"
export MAKE_FLAGS_32="targets"
export MAKE_INSTALL_FLAGS="INSTALL_PLUGINS_DIR=\${DEST}/usr/lib/ladspa/ \
                           INSTALL_INCLUDE_DIR=\${DEST}/usr/include/ \
                           INSTALL_BINARY_DIR=\${DEST}/usr/bin/"

export MAKE_INSTALL_FLAGS_32="INSTALL_PLUGINS_DIR=\${PWD}/dest/usr/lib32/ladspa/ \
                              INSTALL_INCLUDE_DIR=\${PWD}/dest/usr/include/ \
                              INSTALL_BINARY_DIR=\${PWD}/dest/usr/bin/"
configure_override_common() {
  sed -e 's/mkdirhier/mkdir -p/' \
      -e "s#-O3#${CFLAGS}#"      \
      -e "/CC/s#cc#${CC}#"       \
      -e "/CPP/s#c++#${CXX}#"    \
      -i makefile

  unset CFLAGS
}

configure_override() {
  configure_override_common
}

configure_override_32() {
  configure_override_common

  sed -i "/CPP.*=/a LD = ld -m elf_i386" makefile
}

post_install_config() {
  rm -rf ladspa_sdk
}

configure_pre_32() {
  rm -f ../plugins/* ../bin/*
}

. $(dirname $0)/master.sh
