#!/bin/bash -e

export VER=0.24
export DEST=/binary/exiv2-${VER}

pushd exiv2-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr --disable-static

#make -j4
make -j4 install DESTDIR=${DEST}

popd

rm -rf exiv2-${VER}

find ${DEST} -name "*.la" -delete

chmod 755 ${DEST}/usr/lib/libexiv2.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
