#!/bin/bash -e

export PKGNAME=mpfr
export PKGVER=3.1.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/mpfr/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export CONFIGURE_FLAGS=(--enable-thread-safe)

. $(dirname $0)/master.sh
