#!/bin/bash -e

export VER=2.17.90
export DEST=/binary/at-spi2-core-${VER}

pushd at-spi2-core-${VER}

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --sysconfdir=/etc

make -j4
make install DESTDIR=${DEST}

popd

rm -rf at-spi2-core-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
