#!/bin/bash -e

export VER=3.3.5
export DEST=/binary/lm_sensors-${VER}

pushd lm_sensors-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/lm_sensors-fixes.patch

make PREFIX=/usr           \
     BUILD_STATIC_LIB=0    \
     MANDIR=/usr/share/man \
     CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" -j4

make PREFIX=/usr           \
     BUILD_STATIC_LIB=0    \
     MANDIR=/usr/share/man \
     CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" install DESTDIR=${DEST}

popd

rm -rf lm_sensors-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
