#!/bin/bash -e

export PKGNAME=libtirpc
export PKGVER=1.0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/libtirpc/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-gssapi)

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libtirpc.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libtirpc.so) ${DEST}/usr/lib/libtirpc.so
}

. $(dirname $0)/master.sh
