#!/bin/bash -e

case $(basename $0) in
  buildgrantlee )
    export PKGNAME=grantlee
    export PKGVER=5.1.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
    export PKGURL="http://downloads.grantlee.org/${PKGTAR}"
    export CMAKE_FLAGS=(-DBUILD_TESTS=OFF)
  ;;
  buildlibdbusmenu-qt )
    export PKGNAME=libdbusmenu-qt
    export PKGVER=0.9.3+16.04.20160218
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://anduin.linuxfromscratch.org/BLFS/other/${PKGTAR}"
    export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib -DWITH_DOC=OFF)
  ;;
  buildphonon )
    export PKGNAME=phonon
    export PKGVER=4.9.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://download.kde.org/stable/phonon/${PKGVER}/${PKGTAR}"
    export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib
                        -DCMAKE_SKIP_RPATH=ON
                        -DPHONON_BUILD_PHONON4QT5=ON
                        -DPHONON_INSTALL_QT_EXTENSIONS_INTO_SYSTEM_QT=ON)
  ;;
  buildphonon-backend-gstreamer )
    export PKGNAME=phonon-backend-gstreamer
    export PKGVER=4.9.0
    export PKGDIR=phonon-gstreamer-${PKGVER}
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://download.kde.org/stable/phonon/phonon-backend-gstreamer/${PKGVER}/${PKGTAR}"
    export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib
                        -DCMAKE_SKIP_RPATH=ON
                        -DPHONON_BUILD_PHONON4QT5=ON)
  ;;
  buildphonon-backend-vlc )
    export PKGNAME=phonon-backend-vlc
    export PKGVER=0.9.0
    export PKGDIR=phonon-vlc-${PKGVER}
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://download.kde.org/stable/phonon/phonon-backend-vlc/${PKGVER}/${PKGTAR}"
    export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib
                        -DCMAKE_SKIP_RPATH=ON
                        -DPHONON_BUILD_PHONON4QT5=ON)
  ;;
  buildpolkit-qt-1 )
    export PKGNAME=polkit-qt-1
    export PKGVER=0.112.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="http://download.kde.org/stable/apps/KDE4.x/admin/${PKGTAR}"
    export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib)
  ;;
  buildqca )
    export PKGNAME=qca
    export PKGVER=2.1.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://download.kde.org/stable/qca/${PKGVER}/src/${PKGTAR}"
    export CMAKE_FLAGS=(-DBUILD_TESTS=OFF -DQCA_INSTALL_IN_QT_PREFIX=ON)
    export PATCHES_LIST=("qca-fixes.patch")
    configure_pre() {
      sed -i "/BSD_SOURCE/d" ../${PKGDIR}/CMakeLists.txt
    }
  ;;
esac

export DEST=/binary/plasma/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
