#!/bin/bash -e

export VER=3.14.2
export DEST=/binary/gnome-tweak-tool-${VER}

pushd gnome-tweak-tool-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnome-tweak-tool-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
EOF

chmod 755 ${DEST}/INSTALL
