#!/bin/bash -e

export VER=8.36
export DEST=/binary/pcre-${VER}

cp -a pcre-${VER} pcre-${VER}-32

pushd pcre-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr                  \
            --enable-unicode-properties    \
            --enable-pcre16                \
            --enable-pcre32                \
            --enable-jit                   \
            --enable-pcregrep-libz         \
            --enable-pcregrep-libbz2       \
            --enable-pcretest-libreadline  \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

pushd pcre-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr                  \
            --libdir=/usr/lib32            \
            --enable-unicode-properties    \
            --enable-pcre16                \
            --enable-pcre32                \
            --enable-jit                   \
            --disable-static

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf pcre-${VER} pcre-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/doc

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/libpcre.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libpcre.so) ${DEST}/usr/lib/libpcre.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
