#!/bin/bash -e

export PKGNAME=libcue
export PKGVER=2.1.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/lipnitsk/libcue/archive/v${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

make_install_post() {
  rm -rf ${DEST}/usr/lib/*.a
}

. $(dirname $0)/master.sh
