#!/bin/bash -e

export VER=0.22.0
export DEST=/binary/shotwell-${VER}

pushd shotwell-${VER}

sed -i "s:-O2 -g:-march=native -mtune=native -O2 -pipe -fstack-protector-strong:g" Makefile

./configure --prefix=/usr             \
            --disable-desktop-update  \
            --disable-icon-update     \
            --disable-schemas-compile
make -j4
make install DESTDIR=${DEST}

popd

rm -rf shotwell-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
EOF

chmod 755 ${DEST}/INSTALL
