#!/bin/bash -e

export VER=0.13.0
export DEST=/binary/xf86-input-libinput-${VER}

pushd xf86-input-libinput-${VER}

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf xf86-input-libinput-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/usr/share/X11/xorg.conf.d

cat > ${DEST}/usr/share/X11/xorg.conf.d/90-libinput.conf << "EOF"
# Match on all types of devices but tablet devices and joysticks

Section "InputClass"
        Identifier "libinput pointer catchall"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection

Section "InputClass"
        Identifier "libinput keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection

Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection

Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
