#!/bin/bash -e

export VER=4.6.6
export DEST=/binary/gnuplot-${VER}

pushd gnuplot-${VER}

WX_CONFIG=/usr/bin/wx-config-2.8           \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr \
            --enable-qt   \
            --libexecdir=/usr/bin

make pkglibexecdir=/usr/bin -j4
make install pkglibexecdir=/usr/bin DESTDIR=${DEST}

popd

rm -rf gnuplot-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
