#!/bin/bash -e

export PKGNAME=libtar
export PKGVER=1.2.20
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}
export PKGURL="http://pkgbuild.com/~giovanni/libtar/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  autoreconf -fi
}

. $(dirname $0)/master.sh
