#!/bin/bash -e

export VER=1.3.2
export DEST=/binary/python-astroid-${VER}

cp -a astroid-${VER} astroid-${VER}-3

pushd astroid-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd astroid-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf astroid-${VER} astroid-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
