#!/bin/bash -e

export PKGNAME=libssh
export PKGVER=0.7.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://red.libssh.org/attachments/download/195/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
