#!/bin/bash -e

export VER=2.25.2
export DEST=/binary/util-linux-${VER}

cp -a util-linux-${VER} util-linux-${VER}-32

pushd util-linux-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --enable-mesg \
            --disable-nologin \
            --disable-chfn-chsh \
            --disable-su \
            --disable-login \
            --disable-kill \
            --disable-static \
            --with-systemdsystemunitdir=/lib/systemd/system

make -j3
make install DESTDIR=${DEST}

popd

pushd util-linux-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --without-ncurses \
            --libdir=/usr/lib32 \
            --disable-static

make lib{uuid,blkid,mount}.la

make DESTDIR=${DEST} install-usrlib_execLTLIBRARIES install-pkgconfigDATA

popd

rm -rf util-linux-${VER} util-linux-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in bin lib sbin usr ; do cp -rf --remove-destination $dir / ; done

chmod 4755 /bin/mount /bin/umount
chgrp tty /usr/bin/wall
chmod 2755 /usr/bin/wall

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
