#!/bin/bash -e

export VER=1.4.4
export DEST=/binary/ModemManager-${VER}

pushd ModemManager-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-static     \
            --enable-gtk-doc     \
            --with-polkit=permissive

find . -name Makefile | xargs sed -i "s:-Werror ::g"

make -j4
make install DESTDIR=${DEST}

popd

rm -rf ModemManager-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants

ln -sf /lib/systemd/system/ModemManager.service ${DEST}/etc/systemd/system/multi-user.target.wants/ModemManager.service
ln -sf /lib/systemd/system/ModemManager.service ${DEST}/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
