#!/bin/bash -e

export VER=4.14.2
export DEST=/binary/kde-wallpapers-${VER}

pushd kde-wallpapers-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf kde-wallpapers-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
