#!/bin/bash -e

export PKGNAME=xsd
export PKGVER=4.0.0
export PKGTAR=${PKGNAME}-${PKGVER}+dep.tar.bz2
export PKGDIR=${PKGNAME}-${PKGVER}+dep
export PKGURL="http://www.codesynthesis.com/download/xsd/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("xsd-fixes.patch")

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

configure_override() {
  sed -i "/algorithm/a #include <iostream>" libxsd-frontend/xsd-frontend/semantic-graph/elements.cxx
}

make_install_override() {
  make install install_prefix=${DEST}/usr

  mv ${DEST}/usr/bin/xsd ${DEST}/usr/bin/xsdcxx
  mv ${DEST}/usr/share/man/man1/xsd.1 ${DEST}/usr/share/man/man1/xsdcxx.1
}

. $(dirname $0)/master.sh
