#!/bin/bash -e

export PKGNAME=tidy
export PKGVER=5.0.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-html5-${PKGVER}
export PKGURL="https://github.com/htacg/tidy-html5/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
