#!/bin/bash -e

export VER=3.5.0
export DEST=/binary/lapack-${VER}

install -dm755 lapack-${VER}/build

pushd lapack-${VER}/build

cmake -DCMAKE_INSTALL_PREFIX=/usr       \
      -DCMAKE_BUILD_TYPE=Release        \
      -DCMAKE_SKIP_RPATH=ON             \
      -DLAPACKE=ON                      \
      -DBUILD_SHARED_LIBS=ON            \
      -DCMAKE_Fortran_COMPILER=gfortran \
      -Wno-dev ..

make -j4
make install DESTDIR=${DEST}

for file in ${DEST}/usr/lib/*.so
do
  ln -sf $(basename ${file}) ${DEST}/usr/lib/$(basename ${file}).so.3
  ln -sf $(basename ${file}) ${DEST}/usr/lib/$(basename ${file}).so.${VER}
done

popd

rm -rf lapack-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
