#!/bin/bash -e

export VER=1.7.0
export DEST=/binary/python-beaker-${VER}

cp -a Beaker-${VER} Beaker-${VER}-3

pushd Beaker-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd Beaker-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf Beaker-${VER} Beaker-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
