#!/bin/bash -e

export VER=4.14.4
export DEST=/binary/kdepimlibs-${VER}

pushd kdepimlibs-${VER}

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_SKIP_RPATH=ON       \
      -DKDE4_BUILD_TESTS=OFF      \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
      -Wno-dev

make -j4
make install DESTDIR=${DEST}/kdepimlibs-libs

popd

rm -rf kdepimlibs-${VER}

install -dm755 ${DEST}/kdepimlibs-binaries/usr/lib

mv ${DEST}/kdepimlibs-libs/usr/bin ${DEST}/kdepimlibs-binaries/usr
mv ${DEST}/kdepimlibs-libs/usr/lib/kde4 ${DEST}/kdepimlibs-binaries/usr/lib
mv ${DEST}/kdepimlibs-libs/usr/share ${DEST}/kdepimlibs-binaries/usr

install -dm755 ${DEST}/kdepimlibs-libs/usr/share/apps

mv ${DEST}/kdepimlibs-binaries/usr/share/apps/cmake ${DEST}/kdepimlibs-libs/usr/share/apps

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/kdepimlibs-binaries/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/update-mime-database ] && echo "Processing triggers for shared-mime-info" && /usr/bin/update-mime-database /usr/share/mime
EOF

cat > ${DEST}/kdepimlibs-libs/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/kdepimlibs-binaries/INSTALL ${DEST}/kdepimlibs-libs/INSTALL
