#!/bin/bash -e

# Check https://get.adobe.com/flashplayer/ for newer version
export VER=11.2.202.508
export DEST=/binary/flashplayer-${VER}

wget -c http://fpdownload.macromedia.com/get/flashplayer/pdc/${VER}/install_flash_player_11_linux.x86_64.tar.gz

install -dm755 ${DEST}

tar -xzf install_flash_player_11_linux.x86_64.tar.gz usr
tar -xzf install_flash_player_11_linux.x86_64.tar.gz libflashplayer.so

rm -rf usr/lib usr/lib64 usr/share/kde4

install -dm755 usr/lib/flashplayer usr/lib/mozilla/plugins

chmod 755 libflashplayer.so

ln -sf ../../flashplayer/libflashplayer.so usr/lib/mozilla/plugins/libflashplayer.so

rm -rf install_flash_player_11_linux.x86_64.tar.gz

mv libflashplayer.so usr/lib/flashplayer
mv usr ${DEST}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
EOF

chmod 755 ${DEST}/INSTALL
