#!/bin/bash -e

export PKGNAME=usbutils
export PKGVER=008
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/linux/utils/usb/usbutils/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-zlib --datadir=/usr/share/misc)

export DEFAULT_CC="clang"

configure_pre() {
  wget -c http://www.linux-usb.org/usb.ids
}

make_install_post() {
  install -Dm644 usb.ids ${DEST}/usr/share/misc/usb.ids
}

. $(dirname $0)/master.sh
