#!/bin/bash -e

export VER=2.15
export DEST=/binary/xkeyboard-config-${VER}

pushd xkeyboard-config-${VER}

./configure --prefix=/usr --with-xkb-rules-symlink=xorg

make -j4
make install DESTDIR=${DEST}

popd

rm -rf xkeyboard-config-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
