#!/bin/bash -e

export PKGNAME=mutter
export PKGVER=3.18.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/mutter/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export CONFIGURE_FLAGS=(--enable-compile-warnings=minimum)

. $(dirname $0)/master.sh
