#!/bin/bash -e

export PKGNAME=a52dec
export PKGVER=0.7.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://liba52.sourceforge.net/files/${PKGNAME}-${PKGVER}.tar.gz"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export PATCHES_LIST=("a52dec-fixes.patch")
export PATCHES_LIST_32=("a52dec-fixes.patch")
export CONFIGURE_FLAGS=(--enable-shared)
export CONFIGURE_FLAGS_32=(--enable-shared)

configure_pre() {
  autoreconf -fi
}

configure_pre_32() {
  autoreconf -fi
}

make_install_post() {
  install -m644 liba52/a52_internal.h ${DEST}/usr/include/a52dec
}

. $(dirname $0)/master.sh
