#!/bin/bash -e

export VER=1.0.25
export DEST=/binary/sane-backends-${VER}

pushd sane-backends-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/sane-backends-fixes.patch

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-locking    \
            --disable-rpath      \
            --enable-avahi       \
            --enable-libusb_1_0

make -j4
make install DESTDIR=${DEST}

popd

rm -rf sane-backends-${VER}

rm -rf ${DEST}/usr/doc

find ${DEST} -name "*.la" -delete

echo "#hpaio" >> ${DEST}/etc/sane.d/dll.conf

install -dm755 ${DEST}/etc/systemd/system/sockets.target.wants ${DEST}/lib/systemd/system

cat > ${DEST}/lib/systemd/system/saned.socket << "EOF"
[Unit]
Description=saned incoming socket

[Socket]
ListenStream=6566
Accept=yes

[Install]
WantedBy=sockets.target
EOF

cat > ${DEST}/lib/systemd/system/saned@.service << "EOF"
[Unit]
Description=Scanner Service

[Service]
Group=scanner
ExecStart=/usr/sbin/saned
StandardInput=socket
StandardError=syslog
EOF

ln -sf /lib/systemd/system/saned.socket ${DEST}/etc/systemd/system/sockets.target.wants/saned.socket

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group scanner > /dev/null || groupadd -g 70 scanner

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
