#!/bin/bash -e

export PKGNAME=libcanberra
export PKGVER=0.30
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://0pointer.de/lennart/projects/libcanberra/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export PATCHES_LIST=("libcanberra.patch")
export PATCHES_LIST_32=("libcanberra.patch")
export CONFIGURE_FLAGS=(--disable-oss --disable-null)
export CONFIGURE_FLAGS_32=(--disable-gstreamer
                           --disable-gtk3
                           --disable-gtk
                           --disable-oss
                           --disable-null)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

. $(dirname $0)/master.sh
