#!/bin/bash -e

case $(basename $0) in
  buildbdftopcf )
    export PKGNAME=bdftopcf
    export PKGVER=1.0.5
  ;;
  buildiceauth )
    export PKGNAME=iceauth
    export PKGVER=1.0.7
  ;;
  buildluit )
    export PKGNAME=luit
    export PKGVER=1.1.1

    configure_pre() {
      line1="#ifdef _XOPEN_SOURCE"
      line2="#  undef _XOPEN_SOURCE"
      line3="#  define _XOPEN_SOURCE 600"
      line4="#endif"

      sed -i -e "s@#ifdef HAVE_CONFIG_H@$line1\n$line2\n$line3\n$line4\n\n&@" sys.c
      unset line1 line2 line3 line4
    }
  ;;
  buildmkfontdir )
    export PKGNAME=mkfontdir
    export PKGVER=1.0.7
  ;;
  buildmkfontscale )
    export PKGNAME=mkfontscale
    export PKGVER=1.1.2
  ;;
  buildsessreg )
    export PKGNAME=sessreg
    export PKGVER=1.1.0
    export CPPFLAGS="-P"
  ;;
  buildsetxkbmap )
    export PKGNAME=setxkbmap
    export PKGVER=1.3.1
  ;;
  buildsmproxy )
    export PKGNAME=smproxy
    export PKGVER=1.0.6
  ;;
  buildx11perf )
    export PKGNAME=x11perf
    export PKGVER=1.6.0
  ;;
  buildxauth )
    export PKGNAME=xauth
    export PKGVER=1.0.9
  ;;
  buildxbacklight )
    export PKGNAME=xbacklight
    export PKGVER=1.2.1
  ;;
  buildxcmsdb )
    export PKGNAME=xcmsdb
    export PKGVER=1.0.5
  ;;
  buildxcursorgen )
    export PKGNAME=xcursorgen
    export PKGVER=1.0.6
  ;;
  buildxdpyinfo )
    export PKGNAME=xdpyinfo
    export PKGVER=1.3.2
  ;;
  buildxdriinfo )
    export PKGNAME=xdriinfo
    export PKGVER=1.0.5
  ;;
  buildxev )
    export PKGNAME=xev
    export PKGVER=1.2.2
  ;;
  buildxgamma )
    export PKGNAME=xgamma
    export PKGVER=1.0.6
  ;;
  buildxhost )
    export PKGNAME=xhost
    export PKGVER=1.0.7
  ;;
  buildxinput )
    export PKGNAME=xinput
    export PKGVER=1.6.2
  ;;
  buildxkbcomp )
    export PKGNAME=xkbcomp
    export PKGVER=1.3.1
  ;;
  buildxkbevd )
    export PKGNAME=xkbevd
    export PKGVER=1.1.4
  ;;
  buildxkbutils )
    export PKGNAME=xkbutils
    export PKGVER=1.0.4
  ;;
  buildxkill )
    export PKGNAME=xkill
    export PKGVER=1.0.4
  ;;
  buildxlsatoms )
    export PKGNAME=xlsatoms
    export PKGVER=1.1.2
  ;;
  buildxlsclients )
    export PKGNAME=xlsclients
    export PKGVER=1.1.3
  ;;
  buildxmessage )
    export PKGNAME=xmessage
    export PKGVER=1.0.4
  ;;
  buildxmodmap )
    export PKGNAME=xmodmap
    export PKGVER=1.0.9
  ;;
  buildxpr )
    export PKGNAME=xpr
    export PKGVER=1.0.4
  ;;
  buildxprop )
    export PKGNAME=xprop
    export PKGVER=1.2.2
  ;;
  buildxrandr )
    export PKGNAME=xrandr
    export PKGVER=1.5.0
  ;;
  buildxrdb )
    export PKGNAME=xrdb
    export PKGVER=1.1.0
  ;;
  buildxrefresh )
    export PKGNAME=xrefresh
    export PKGVER=1.0.5
  ;;
  buildxset )
    export PKGNAME=xset
    export PKGVER=1.2.3
  ;;
  buildxsetroot )
    export PKGNAME=xsetroot
    export PKGVER=1.1.1
  ;;
  buildxvinfo )
    export PKGNAME=xvinfo
    export PKGVER=1.1.3
  ;;
  buildxwd )
    export PKGNAME=xwd
    export PKGVER=1.0.6
  ;;
  buildxwininfo )
    export PKGNAME=xwininfo
    export PKGVER=1.1.3
  ;;
  buildxwud )
    export PKGNAME=xwud
    export PKGVER=1.0.4
  ;;
  buildxorg-app )
    export PKG_AUTO_INSTALL=1

    $(dirname $0)/buildbdftopcf
    $(dirname $0)/buildiceauth
    $(dirname $0)/buildluit
    $(dirname $0)/buildmkfontdir
    $(dirname $0)/buildmkfontscale
    $(dirname $0)/buildsessreg
    $(dirname $0)/buildsetxkbmap
    $(dirname $0)/buildsmproxy
    $(dirname $0)/buildx11perf
    $(dirname $0)/buildxauth
    $(dirname $0)/buildxbacklight
    $(dirname $0)/buildxcmsdb
    $(dirname $0)/buildxcursorgen
    $(dirname $0)/buildxdpyinfo
    $(dirname $0)/buildxdriinfo
    $(dirname $0)/buildxev
    $(dirname $0)/buildxgamma
    $(dirname $0)/buildxhost
    $(dirname $0)/buildxinput
    $(dirname $0)/buildxkbcomp
    $(dirname $0)/buildxkbevd
    $(dirname $0)/buildxkbutils
    $(dirname $0)/buildxkill
    $(dirname $0)/buildxlsatoms
    $(dirname $0)/buildxlsclients
    $(dirname $0)/buildxmessage
    $(dirname $0)/buildxmodmap
    $(dirname $0)/buildxpr
    $(dirname $0)/buildxprop
    $(dirname $0)/buildxrandr
    $(dirname $0)/buildxrdb
    $(dirname $0)/buildxrefresh
    $(dirname $0)/buildxset
    $(dirname $0)/buildxsetroot
    $(dirname $0)/buildxvinfo
    $(dirname $0)/buildxwd
    $(dirname $0)/buildxwininfo
    $(dirname $0)/buildxwud

    find /binary/xorg/app -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

    exit 0
  ;;
esac

export MAKE_JOBS_FLAGS="-j4"
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export DEST=/binary/xorg/app/${PKGNAME}-${PKGVER}
export PKGURL="https://www.x.org/releases/individual/app/${PKGTAR}"

. $(dirname $0)/master.sh
