#!/bin/bash -e

export PKGNAME=libssh2
export PKGVER=1.7.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://libssh2.org/download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
