#!/bin/bash -e

export PKGNAME=openal-soft
export PKGVER=1.17.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://kcat.strangesoft.net/openal-releases/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
