#!/bin/bash -e

export PKGNAME=ModemManager
export PKGVER=1.6.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.freedesktop.org/software/ModemManager/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-gtk-doc --with-polkit=permissive --disable-more-warnings)

make_install_post() {
  install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants

  ln -sf /lib/systemd/system/ModemManager.service ${DEST}/etc/systemd/system/multi-user.target.wants/ModemManager.service
  ln -sf /lib/systemd/system/ModemManager.service ${DEST}/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service
}

. $(dirname $0)/master.sh
