#!/bin/bash -e

export VER=1.57.0
export TARVER=1_57_0
export DEST=/binary/boost-${VER}

pushd boost_${TARVER}

./bootstrap.sh --with-toolset=gcc --with-icu

./b2 install threading=multi link=shared runtime-link=shared toolset=gcc cflags="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " --prefix=${DEST}/usr -j4

popd

rm -rf boost_${TARVER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
