#!/bin/bash -e

export VER=0.0.16
export DEST=/binary/cantarell-fonts-${VER}

pushd cantarell-fonts-${VER}

./configure --prefix=/usr --with-fontdir=/usr/share/fonts/opentype/cantarell

make -j4
make install DESTDIR=${DEST}

popd

rm -rf cantarell-fonts-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/opentype/cantarell
EOF

chmod 755 ${DEST}/INSTALL
