#!/bin/bash -e

export PKGNAME=efibootmgr
export PKGVER=13
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/rhinstaller/efibootmgr/archive/${PKGVER}.tar.gz"
export MAKE_FLAGS="EXTRA_CFLAGS=\${DEFAULT_CFLAGS}"
export DEFAULT_CC="gcc"

configure_override() {
  true
}

. $(dirname $0)/master.sh
