#!/bin/bash -e

export PKGNAME=mhash
export PKGVER=0.9.9.9
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/mhash/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
