#!/bin/bash -e

export VER=1.2.53
export DEST=/binary/libpng-${VER}

cp -a libpng-${VER} libpng-${VER}-32

pushd libpng-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-static

make -j4
make install DESTDIR=${DEST}

popd

pushd libpng-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-static    \
            --program-suffix=-32

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf libpng-${VER} libpng-${VER}-32

find ${DEST} -name "*.la" -delete
find ${DEST} -name "*.so" -delete

rm -rf ${DEST}/usr/bin ${DEST}/usr/include
rm -rf ${DEST}/usr/lib*/pkgconfig ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
