#!/bin/bash -e

export PKGNAME=libkolabxml
export PKGVER=1.1.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://mirror.kolabsys.com/pub/releases/${PKGTAR}"
export DEST=/binary/kdepim/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DBUILD_TESTS=OFF -DQT5_BUILD=ON)
export USER_CXXFLAGS="-stdlib=libc++"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++"

. $(dirname $0)/master.sh
