#!/bin/bash -e

export PKGNAME=hunspell
export PKGVER=1.4.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/hunspell/hunspell/archive/v${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
