#!/bin/bash -e

export VER=2.5.7
export DEST=/binary/libgphoto2-${VER}

pushd libgphoto2-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-rpath

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libgphoto2-${VER}

rm -rf ${DEST}/usr/include/gphoto2/gphoto2
rm -rf ${DEST}/usr/lib/*.la
rm -rf ${DEST}/usr/lib/udev
rm -rf ${DEST}/usr/share/doc

install -dm755 ${DEST}/lib/udev/hwdb.d
install -dm755 ${DEST}/lib/udev/rules.d

LD_LIBRARY_PATH=${DEST}/usr/lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH \
CAMLIBS=${DEST}/usr/lib/libgphoto2/${VER} \
    ${DEST}/usr/lib/libgphoto2/print-camera-list hwdb > \
    ${DEST}/lib/udev/hwdb.d/20-gphoto2.hwdb

LD_LIBRARY_PATH=${DEST}/usr/lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH \
CAMLIBS=${DEST}/usr/lib/libgphoto2/${VER} \
    ${DEST}/usr/lib/libgphoto2/print-camera-list udev-rules version 201 > \
    ${DEST}/lib/udev/rules.d/40-gphoto.rules

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

udevadm hwdb --update

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
