#!/bin/bash -e

export VER=0.8.90
export DEST=/binary/icon-naming-utils-${VER}

pushd icon-naming-utils-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf icon-naming-utils-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
