#!/bin/bash -e

export PKGNAME=wpa_supplicant
export PKGVER=2.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://hostap.epitest.fi/releases/${PKGTAR}"
export PKGDIR=${PKGNAME}-${PKGVER}
export PKGBUILD=${PKGDIR}/wpa_supplicant
export MAKE_JOBS_FLAGS="-j4"
export KEEP_DOC=1
export USER_CFLAGS="-MMD"
export USER_CXXFLAGS="-MMD"

configure_override() {
cat > .config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CFLAGS += -I/usr/include/libnl3
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
EOF

  sed -e "s@wpa_supplicant -u@& -s -O /var/run/wpa_supplicant@g" -i dbus/*.service.in
  sed -e "s@wpa_supplicant -u@& -s -O /var/run/wpa_supplicant@g" -i systemd/wpa_supplicant.service.in
}

if [ -z $1 ]
then
  additional_build() {
    pushd wpa_gui-qt4
      qmake "QMAKE_CFLAGS+=${CFLAGS}" "QMAKE_CXXFLAGS+=${CFLAGS}" wpa_gui.pro
      make V=1 ${ADDITIONAL_MAKE_FLAGS}
    popd
  }
  additional_install() {
    install -m755 wpa_gui-qt4/wpa_gui ${DEST}/usr/bin
    install -m644 doc/docbook/wpa_gui.8 ${DEST}/usr/share/man/man8

    install -m644 wpa_gui-qt4/wpa_gui.desktop ${DEST}/usr/share/applications
    install -m644 wpa_gui-qt4/icons/wpa_gui.svg ${DEST}/usr/share/pixmaps
  }
else
  additional_build() {
    true
  }
  additional_install() {
    true
  }
fi

make_override() {
  make BINDIR=/sbin LIBDIR=/lib V=1 ${ADDITIONAL_MAKE_FLAGS}

  additional_build
}

make_install_override() {
  install -dm755 ${DEST}/etc/dbus-1/system.d ${DEST}/etc/systemd/system/multi-user.target.wants ${DEST}/lib/systemd/system
  install -dm755 ${DEST}/sbin ${DEST}/usr/bin ${DEST}/usr/share/applications ${DEST}/usr/share/dbus-1/system-services
  install -dm755 ${DEST}/usr/share/doc/wpa_supplicant ${DEST}/usr/share/pixmaps  ${DEST}/usr/share/man/man5 ${DEST}/usr/share/man/man8

  install -m755 wpa_cli wpa_supplicant ${DEST}/sbin
  install -m755 wpa_passphrase ${DEST}/usr/bin

  install -m644 doc/docbook/wpa_supplicant.conf.5 ${DEST}/usr/share/man/man5
  install -m644 doc/docbook/wpa_background.8 doc/docbook/wpa_cli.8 ${DEST}/usr/share/man/man8
  install -m644 doc/docbook/wpa_passphrase.8 doc/docbook/wpa_supplicant.8 ${DEST}/usr/share/man/man8

  install -m644 dbus/fi.epitest.hostap.WPASupplicant.service ${DEST}/usr/share/dbus-1/system-services
  install -m644 dbus/fi.w1.wpa_supplicant1.service ${DEST}/usr/share/dbus-1/system-services

  install -m644 dbus/dbus-wpa_supplicant.conf ${DEST}/etc/dbus-1/system.d/wpa_supplicant.conf

  additional_install

  install -m644 examples/*.conf ${DEST}/usr/share/doc/wpa_supplicant
  install -m644 systemd/*.service ${DEST}/lib/systemd/system

  ln -sf /lib/systemd/system/wpa_supplicant.service ${DEST}/etc/systemd/system/dbus-fi.epitest.hostap.WPASupplicant.service
  ln -sf /lib/systemd/system/wpa_supplicant.service ${DEST}/etc/systemd/system/multi-user.target.wants/wpa_supplicant.service
}

. $(dirname $0)/master.sh
