#!/bin/bash

export VER=1.3.2
export DEST=/binary/openjade-${VER}

pushd openjade-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/openjade.patch

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --datadir=/usr/share/sgml/OpenJade \
            --mandir=/usr/share/man \
            --enable-http \
            --disable-static \
            --enable-default-catalog=/etc/sgml/catalog \
            --enable-default-search-path=/usr/share/sgml

make
make install-man install DESTDIR=${DEST}

install -m644 dsssl/catalog ${DEST}/usr/share/sgml/OpenJade
install -m644 dsssl/*.{dtd,dsl,sgm} ${DEST}/usr/share/sgml/OpenJade

popd

rm -rf openjade-${VER}

ln -s openjade ${DEST}/usr/bin/jade

for file in grove spgrove style ; do
  ln -s libo${file}.so ${DEST}/usr/lib/lib${file}.so
done

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

install-catalog --add /etc/sgml/OpenJade.cat /usr/share/sgml/OpenJade/catalog
install-catalog --add /etc/sgml/sgml-docbook.cat /etc/sgml/OpenJade.cat

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
