#!/bin/bash -e

export VER=22.21
export DEST=/binary/psmisc-${VER}

pushd psmisc-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf psmisc-${VER}

install -dm755 ${DEST}/bin

mv ${DEST}/usr/bin/fuser ${DEST}/bin
mv ${DEST}/usr/bin/killall ${DEST}/bin

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in bin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
