#!/bin/bash -e

export PKGNAME=hplip
export PKGVER=3.15.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/hplip/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-qt4
                        --enable-foomatic-ppd-install
                        --enable-hpcups-install
                        --enable-new-hpcups
                        --enable-cups-ppd-install
                        --enable-cups-drv-install
                        --enable-hpijs-install
                        --enable-foomatic-drv-install
                        --enable-pp-build
                        --disable-foomatic-rip-hplip-install)
export MAKE_INSTALL_FLAGS="rulesdir=/lib/udev/rules.d rulessystemdir=/lib/systemd/system"

configure_pre() {
  for i in ppd/hpijs/*.ppd.gz
  do
    rm -f ${i}.temp
    gunzip -c ${i} | sed 's/foomatic-rip-hplip/foomatic-rip/g' | gzip > ${i}.temp || return 1
    mv ${i}.temp ${i}
  done

  export AUTOMAKE='automake --foreign'
  autoreconf --force --install
}

make_install_post() {
  rm -rf ${DEST}/etc/sane.d ${DEST}/etc/xdg ${DEST}/usr/share/doc ${DEST}/usr/share/hal
}

. $(dirname $0)/master.sh
