#!/bin/bash -e

export VER=5.2.0
export DEST=/binary/oxygen-${VER}

install -dm755 oxygen-${VER}/kde5 oxygen-${VER}/kde4

pushd oxygen-${VER}/kde5

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DLIB_INSTALL_DIR=lib       \
      -DBUILD_TESTING=OFF         \
      -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins             \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
      -Wno-dev ..

make -j4
make install DESTDIR=${DEST}

popd

pushd oxygen-${VER}/kde4

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DBUILD_TESTING=OFF         \
      -DUSE_KDE4=ON               \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
      -Wno-dev ..

make -j4
make install DESTDIR=${DEST}

popd

rm -rf oxygen-${VER}

rm -rf ${DEST}/usr/bin/oxygen-demo*

install -dm755 ${DEST}/usr/lib/qt4/plugins/styles

ln -sfr ${DEST}/usr/lib/kde4/plugins/styles/oxygen.so ${DEST}/usr/lib/qt4/plugins/styles

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
