#!/bin/bash -e

export VER=5.2.95
export DEST=/binary/plasma-workspace-wallpapers-${VER}

pushd plasma-workspace-wallpapers-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf plasma-workspace-wallpapers-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
