#!/bin/bash -e

export PKGNAME=libtool
export PKGVER=2.4.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/libtool/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
#export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
