#!/bin/bash -e

export VER=3.0
export PKGVER=30
export DEST=/binary/zip-${VER}

pushd zip${PKGVER}

sed -i "s:-O3:-march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" unix/configure

make -f unix/Makefile -j4 generic_gcc
make -f unix/Makefile prefix=${DEST}/usr MANDIR=${DEST}/usr/share/man/man1 install

popd

rm -rf zip${PKGVER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
