#!/bin/bash -e

export PKGNAME=lapack
export PKGVER=3.6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="http://www.netlib.org/lapack/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib
                    -DCMAKE_SKIP_RPATH=ON
                    -DCBLAS=ON
                    -DLAPACKE=ON
                    -DBUILD_DEPRECATED=ON
                    -DBUILD_SHARED_LIBS=ON
                    -DBUILD_TESTING=OFF
                    -DCMAKE_Fortran_COMPILER=gfortran)

configure_pre() {
  sed -e 's|/CMAKE/|/cmake/|' -i ../${PKGDIR}/CBLAS/CMakeLists.txt
}

. $(dirname $0)/master.sh
