#!/bin/bash -e

export VER=1.69
export DEST=/binary/perl-uri-${VER}

pushd URI-${VER}


perl Makefile.PL INSTALLDIRS=vendor

make -j4
make install DESTDIR=${DEST}

popd

rm -rf URI-${VER}

rm -rf ${DEST}/usr/lib

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
