#!/bin/bash -e

export PKGNAME=texinfo
export PKGVER=6.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/texinfo/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

generate_install_override() {
cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

rm -rf /usr/share/info/dir

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in /usr/share/info/* ; do /usr/bin/install-info $file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

if [ ! -z ${PKG_AUTO_INSTALL} ]
then
cat >> ${DEST}/INSTALL << EOF

exit 0
EOF
fi

chmod 755 ${DEST}/INSTALL
}

. $(dirname $0)/master.sh
