#!/bin/bash -e

export PKGNAME=ocl-icd
export PKGVER=2.2.9
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://forge.imag.fr/frs/download.php/716/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
