#!/bin/bash -e

export PKGNAME=libjpeg-turbo
export PKGVER=1.5.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export DEST=/binary/${PKGNAME}6-${PKGVER}
export PKGURL="https://downloads.sourceforge.net/libjpeg-turbo/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--without-simd)
export CONFIGURE_FLAGS_32=(--without-simd)

make_override() {
  make libjpeg.la ${ADDITIONAL_MAKE_FLAGS}
}

make_install_override() {
  make lib_LTLIBRARIES="libjpeg.la" install-libLTLIBRARIES ${ADDITIONAL_MAKE_INSTALL_FLAGS}
}

post_install_config() {
  rm -rf ${DEST}/usr/lib*/*.so
}

. $(dirname $0)/master.sh
