#!/bin/bash -e

export VER=4.2.3
export DEST=/binary/samba-${VER}

pushd samba-${VER}

_samba4_idmap_modules=idmap_ad,idmap_rid,idmap_adex,idmap_hash,idmap_tdb2
_samba4_pdb_modules=pdb_tdbsam,pdb_ldap,pdb_ads,pdb_smbpasswd,pdb_wbc_sam,pdb_samba4
_samba4_auth_modules=auth_unix,auth_wbc,auth_server,auth_netlogond,auth_script,auth_samba4

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --enable-fhs \
            --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --libdir=/usr/lib \
            --with-lockdir=/run/samba \
            --with-pammodulesdir=/lib/security \
            --enable-gnutls \
            --with-shared-modules=${_samba4_idmap_modules},${_samba4_pdb_modules},${_samba4_auth_modules} \
            --disable-rpath-install

make -j4
make install DESTDIR=${DEST} -j4

install -o root -g root -m644 examples/smb.conf.default ${DEST}/etc/samba/smb.conf.default

popd

rm -rf samba-${VER}

rm -rf ${DEST}/run ${DEST}/var/run

install -o root -g root -dm 755 ${DEST}/etc/default
install -o root -g root -dm 755 ${DEST}/etc/pam.d
install -o root -g root -dm 755 ${DEST}/etc/systemd/system/multi-user.target.wants
install -o root -g root -dm 755 ${DEST}/usr/lib/tmpfiles.d

install -o root -g root -dm 755 ${DEST}/lib/systemd/system
install -o root -g root -dm 755 ${DEST}/usr/lib/cups/backend

cat > ${DEST}/etc/default/samba << "EOF"
# Additional options to pass to nmbd command line
NMBD_OPTS=

# Additional options to pass to smbd command line
SMBD_OPTS=

# Additional options to pass to winbindd command line
WINBINDD_OPTS=
EOF

cat > ${DEST}/etc/pam.d/samba << "EOF"
# Begin /etc/pam.d/samba

auth    include system-auth
account include system-account
session include system-session

# End /etc/pam.d/samba
EOF

ln -sf /lib/systemd/system/nmbd.service ${DEST}/etc/systemd/system/multi-user.target.wants/nmbd.service
ln -sf /lib/systemd/system/smbd.service ${DEST}/etc/systemd/system/multi-user.target.wants/smbd.service
ln -sf /lib/systemd/system/winbindd.service ${DEST}/etc/systemd/system/multi-user.target.wants/winbindd.service

cat > ${DEST}/usr/lib/tmpfiles.d/samba.conf << "EOF"
d /run/samba 755 root root -
EOF

sed -e 's|MYGROUP|WORKGROUP|g' -i ${DEST}/etc/samba/smb.conf.default
sed -e 's|log file = .*$|log file = /var/log/samba/log.%m|g' -i ${DEST}/etc/samba/smb.conf.default
sed -e 's|/usr/spool/samba|/var/spool/samba|g' -i ${DEST}/etc/samba/smb.conf.default
sed -e 's|log.%m|%m.log|g' -i ${DEST}/etc/samba/smb.conf.default

mv ${DEST}/usr/lib/libnss_win{bind,s}.so{,.2} ${DEST}/lib

cat > ${DEST}/lib/systemd/system/nmbd.service << "EOF"
[Unit]
Description=Samba NetBIOS name server
After=network.target

[Service]
Type=forking
EnvironmentFile=/etc/default/samba
PIDFile=/run/samba/nmbd.pid
ExecStart=/usr/sbin/nmbd -D $NMBD_OPTS
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/lib/systemd/system/smbd.service << "EOF"
[Unit]
Description=Samba SMB/CIFS server
After=network.target nmbd.service winbindd.service

[Service]
Type=forking
EnvironmentFile=/etc/default/samba
PIDFile=/run/samba/smbd.pid
ExecStart=/usr/sbin/smbd -D $SMBD_OPTS
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/lib/systemd/system/smbd.socket << "EOF"
[Unit]
Description=Samba SMB/CIFS server socket

[Socket]
ListenStream=445
Accept=yes

[Install]
WantedBy=sockets.target
EOF

cat > ${DEST}/lib/systemd/system/smbd@.service << "EOF"
[Unit]
Description=Samba SMB/CIFS server instance

[Service]
Type=forking
EnvironmentFile=/etc/default/samba
PIDFile=/run/samba/smbd.pid
ExecStart=/usr/sbin/smbd -F $SMBD_OPTS
ExecReload=/bin/kill -HUP $MAINPID
StandardInput=socket
EOF

cat > ${DEST}/lib/systemd/system/winbindd.service << "EOF"
[Unit]
Description=Samba Winbind daemon
After=network.target nmbd.service

[Service]
Type=forking
EnvironmentFile=/etc/default/samba
PIDFile=/run/samba/winbindd.pid
ExecStart=/usr/sbin/winbindd -D $WINBINDD_OPTS
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
EOF

ln -s /usr/bin/smbspool ${DEST}/usr/lib/cups/backend/smb

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

getent group sambashare > /dev/null || groupadd -g 97 sambashare

if [ ! -e /var/lib/samba/usershares ]; then
   install -o root -g root -dm 1770 -g sambashare /var/lib/samba/usershares
fi

if [ ! -e /var/spool/samba ]; then
   install -o root -g root -dm 1777 /var/spool/samba
fi

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 644 ${DEST}/etc/default/*
chmod 644 ${DEST}/etc/pam.d/*
chmod 644 ${DEST}/lib/systemd/system/*
chmod 644 ${DEST}/usr/lib/tmpfiles.d/*

chmod 755 ${DEST}/INSTALL

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd
