#!/bin/bash -e

export VER=3.2.4
export DEST=/binary/eigen-${VER}

install -dm755 eigen-${VER}/build

wget https://bitbucket.org/eigen/eigen/get/${VER}.tar.bz2 -O - | tar xfj - --strip-components=1 -C eigen-${VER}

pushd eigen-${VER}/build

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -Wno-dev ..

make -j4
make install DESTDIR=${DEST}

popd

rm -rf eigen-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
