#!/bin/bash -e

export VER=0.51
export DEST=/binary/perl-xml-sax-expat-${VER}

pushd XML-SAX-Expat-${VER}

perl Makefile.PL INSTALLDIRS=vendor

make -j4
make pure_install DESTDIR=${DEST}

popd

rm -rf XML-SAX-Expat-${VER}

rm -rf ${DEST}/usr/lib

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
