#!/bin/bash -e

export VER=1.6.3
export DEST=/binary/libgcrypt-${VER}

cp -a libgcrypt-${VER} libgcrypt-${VER}-32

pushd libgcrypt-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr    \
            --disable-static \
            --disable-padlock-support

make -j4
make install DESTDIR=${DEST}

popd

pushd libgcrypt-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

sed 's:path="amd64":path="i586 i386":' -i mpi/config.links

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-static    \
            --disable-padlock-support

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf libgcrypt-${VER} libgcrypt-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/libgcrypt.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libgcrypt.so) ${DEST}/usr/lib/libgcrypt.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
