#!/bin/bash -e

export PKGNAME=icon-naming-utils
export PKGVER=0.8.90
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://tango.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
