#!/bin/bash -e

export VER=0.10.19
export DEST=/binary/gst-plugins-ugly-${VER}

pushd gst-plugins-ugly-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/gst-plugins-ugly-fixes.patch

sed "s:interf:opencore-amrnb/&:g" -i ext/amrnb/amrnb{de,en}c.h
sed "s:dec_if:opencore-amrwb/&:g" -i ext/amrwbdec/amrwbdec.h
sed "s:if_rom:opencore-amrwb/&:g" -i ext/amrwbdec/amrwbdec.h

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --with-package-name="GStreamer Ugly Plugins ${VER} BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/systemd/"

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gst-plugins-ugly-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
