#!/bin/bash -e

export PKGNAME=graphite2
export PKGVER=1.3.5
export PKGTAR=${PKGNAME}-${PKGVER}.tgz
export PKGURL="https://downloads.sourceforge.net/silgraphite/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export MULTILIB_BUILD=1
export CMAKE_FLAGS_32=(-DLIB_SUFFIX=32)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

configure_pre() {
  sed -i "s:share/graphite2:lib\${LIB_SUFFIX}/graphite2:" ../${PKGDIR}/src/CMakeLists.txt
}

configure_pre_32() {
  sed -i "s:share/graphite2:lib\${LIB_SUFFIX}/graphite2:" ../${PKGDIR}/src/CMakeLists.txt
}

. $(dirname $0)/master.sh
