#!/bin/bash -e

export VER=3.11.0
export DEST=/binary/valgrind-${VER}

pushd valgrind-${VER}

sed -i "s/-mt//g" configure

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf valgrind-${VER}

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
