#!/bin/bash -e

export PKGNAME=imlib2
export PKGVER=1.4.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/enlightenment/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/share ; do cp -rf --remove-destination \$dir /usr ; done\n"
                    "cp -rf --remove-destination usr/bin/imlib2-config /usr/bin")

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
