#!/bin/bash -e

VER=4.3.2
DEST=/binary/dhcp-${VER}

pushd dhcp-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/dhclient-script.patch

CFLAGS="-D_PATH_DHCLIENT_SCRIPT='\"/sbin/dhclient-script\"'             \
        -D_PATH_DHCPD_CONF='\"/etc/dhcp/dhcpd.conf\"'                   \
        -D_PATH_DHCLIENT_CONF='\"/etc/dhcp/dhclient.conf\"'             \
        -march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr                                               \
            --sysconfdir=/etc/dhcp                                      \
            --localstatedir=/var                                        \
            --with-srv-lease-file=/var/lib/dhcpd/dhcpd.leases           \
            --with-srv6-lease-file=/var/lib/dhcpd/dhcpd6.leases         \
            --with-cli-lease-file=/var/lib/dhclient/dhclient.leases     \
            --with-cli6-lease-file=/var/lib/dhclient/dhclient6.leases

make -j4

make -C dhcpctl install DESTDIR=${DEST}/client
make -C client install DESTDIR=${DEST}/client

rm -rf ${DEST}/client/etc/dhcp/*
rm -rf ${DEST}/client/usr/lib
rm -rf ${DEST}/client/usr/share/man/man3

mv ${DEST}/client/usr/sbin ${DEST}/client/

install -o root -g root -m 755 client/scripts/linux ${DEST}/client/sbin/dhclient-script
install -o root -g root -dm 755 ${DEST}/client/var/lib/dhclient/

cat > ${DEST}/client/etc/dhcp/dhclient.conf << "EOF"
# Begin /etc/dhcp/dhclient.conf
#
# Basic dhclient.conf(5)

#prepend domain-name-servers 127.0.0.1;
request subnet-mask, broadcast-address, time-offset, routers,
        domain-name, domain-name-servers, domain-search, host-name,
        netbios-name-servers, netbios-scope, interface-mtu,
        ntp-servers;
require subnet-mask, domain-name-servers;
#timeout 60;
#retry 60;
#reboot 10;
#select-timeout 5;
#initial-interval 2;

# End /etc/dhcp/dhclient.conf
EOF

make -C server install DESTDIR=${DEST}/server

rm -rf ${DEST}/server/etc/dhcp/*

install -o root -g root -d m755 ${DEST}/server/etc/default/
install -o root -g root -d m755 ${DEST}/server/etc/systemd/system/multi-user.target.wants/
install -o root -g root -d m755 ${DEST}/server/lib/systemd/system/
install -o root -g root -d m755 ${DEST}/server/var/lib/dhcpd/

ln -s /lib/systemd/system/dhcpd.service ${DEST}/server/etc/systemd/system/multi-user.target.wants/dhcpd.service

cat > ${DEST}/server/etc/default/dhcpd << "EOF"
# Begin /etc/default/dhcpd

# On which interfaces should the DHCP Server (dhcpd) serve DHCP requests?
# Separate multiple interfaces with spaces, e.g. "eth0 eth1".
# By default, dhcpd will listen on all available interfaces.
DHCPD_INTERFACES=""

# Additional options that you want to pass to the DHCP Server Daemon?
DHCPD_OPTS=""

# End /etc/default/dhcpd
EOF

cat > ${DEST}/server/etc/dhcp/dhcpd.conf << "EOF"
# Begin /etc/dhcp/dhcpd.conf
#
# Example dhcpd.conf(5)

# Use this to enble / disable dynamic dns updates globally.
ddns-update-style none;

# option definitions common to all supported networks...
option domain-name "example.org";
option domain-name-servers ns1.example.org, ns2.example.org;

default-lease-time 600;
max-lease-time 7200;

# This is a very basic subnet declaration.
subnet 10.254.239.0 netmask 255.255.255.224 {
  range 10.254.239.10 10.254.239.20;
  option routers rtr-239-0-1.example.org, rtr-239-0-2.example.org;
}

# End /etc/dhcp/dhcpd.conf
EOF

cat > ${DEST}/server/lib/systemd/system/dhcpd.service << "EOF"
[Unit]
Description=ISC DHCP Server
After=network.target

[Service]
Type=forking
PIDFile=/var/run/dhcpd.pid
EnvironmentFile=/etc/default/dhcpd
ExecStart=/usr/sbin/dhcpd -pf /var/run/dhcpd.pid -q $DHCPD_OPTS $DHCPD_INTERFACES
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
EOF

popd

rm -rf dhcp-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/client/INSTALL << "EOF"
#!/bin/bash

for dir in etc sbin usr var ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

cat > ${DEST}/server/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

touch /var/lib/dhcpd/dhcpd.leases

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/client/INSTALL ${DEST}/server/INSTALL
