#!/bin/bash -e

export PKGNAME=libtheora
export PKGVER=1.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://downloads.xiph.org/releases/theora/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--disable-examples --disable-sdltest)
export CONFIGURE_FLAGS_32=(--disable-asm --disable-examples --disable-sdltest)

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
