#!/bin/bash -e

export PKGNAME=libomxil-bellagio
export PKGVER=0.9.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/omxil/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("libomxil-bellagio-fixes.patch")
export DEFAULT_CC="gcc"
export DEFAULT_CXX="g++"

configure_pre() {
  autoreconf -fi
}

. $(dirname $0)/master.sh
