#!/bin/bash -e

export PKGNAME=libmnl
export PKGVER=1.0.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.netfilter.org/projects/libmnl/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libmnl.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libmnl.so) ${DEST}/usr/lib/libmnl.so
}

. $(dirname $0)/master.sh
