#!/bin/bash -e

export PKGNAME=docbook-xsl
export PKGVER=1.79.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/docbook/${PKGTAR}"
export KEEP_EMPTY_DIRS=1
export NO_STRIP=1

configure_override() {
  true
}

make_override() {
  true
}

make_install_override() {
  install -dm755 ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/{common,params}
  install -m644 common/*.{xml,xsl,dtd,ent} ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/common
  install -m644 params/*.xml ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/params

  for fn in fo highlighting html roundtrip
  do
    install -dm755 ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/${fn}
    install -m644 ${fn}/*.{xml,xsl} ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/${fn}
  done

  for fn in eclipse htmlhelp javahelp lib manpages profiling template website xhtml{,-1_1}
  do
    install -dm755 ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/${fn}
    install -m644 ${fn}/*.xsl ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/${fn}
  done

  install -dm755 ${DEST}/etc/xml
  install -m644 VERSION ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}

  ln -sf VERSION ${DEST}/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}/VERSION.xsl
}

generate_install_override() {
cat > ${DEST}/INSTALL << EOF
#!/bin/bash

for dir in etc usr ; do cp -r --remove-destination \$dir / ; done

if [ ! -e /etc/xml/catalog ]; then
  xmlcatalog --noout --create /etc/xml/catalog
fi

xmlcatalog --noout --add "rewriteSystem" \\
  "http://docbook.sourceforge.net/release/xsl/${PKGVER}" \\
  "/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}" \\
  /etc/xml/catalog
xmlcatalog --noout --add "rewriteURI" \\
  "http://docbook.sourceforge.net/release/xsl/${PKGVER}" \\
  "/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}" \\
  /etc/xml/catalog
xmlcatalog --noout --add "rewriteSystem" \\
  "http://docbook.sourceforge.net/release/xsl/current" \\
  "/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}" \\
  /etc/xml/catalog
xmlcatalog --noout --add "rewriteURI" \\
  "http://docbook.sourceforge.net/release/xsl/current" \\
  "/usr/share/xml/docbook/xsl-stylesheets-${PKGVER}" \\
  /etc/xml/catalog
EOF

chmod 755 ${DEST}/INSTALL
}

. $(dirname $0)/master.sh
