#!/bin/bash -e

export PKGNAME=check
export PKGVER=0.10.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/check/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
