#!/bin/bash -e

export PKGNAME=ocl-icd
export PKGVER=2.2.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://forge.imag.fr/frs/download.php/667/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

. $(dirname $0)/master.sh
