#!/bin/bash -e

export PKGNAME=pinentry
export PKGVER=1.0.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.gnupg.org/gcrypt/pinentry/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
