#!/bin/bash -e

export PKGNAME=libpng
export PKGVER=1.6.26
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://downloads.sourceforge.net/libpng/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

post_extract_action() {
  local APNG="libpng-${PKGVER}-apng.patch.gz"

  if [ ! -e ${SROOT}/${APNG} ]
  then
    wget -c https://downloads.sourceforge.net/apng/${APNG} -O ${SROOT}/${APNG} || exit ${PIPESTATUS}
  fi

  pushd ${PKGDIR}
    gunzip -c ${SROOT}/${APNG} | patch -Np0 -i -
  popd
}

. $(dirname $0)/master.sh
