#!/bin/bash -e

export VER=0.7.4
export DEST=/binary/a52dec-${VER}

pushd a52dec-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/a52dec-fixes.patch

autoreconf -fi

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr   \
            --enable-shared \
            --disable-static

make -j4
make install DESTDIR=${DEST}

install -m644 liba52/a52_internal.h ${DEST}/usr/include/a52dec

popd

rm -rf a52dec-${VER}

find ${DEST} -name "*.la" -delete


pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
