#!/bin/bash -e

export VER=0.3.2.1
export DEST=/binary/lightdm-kde-greeter-${VER}

pushd lightdm-${VER}

sed -i "s:lightdm-qt-2:lightdm-qt-3:g" cmake/modules/FindQLightDM.cmake

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
      -Wno-dev

make -j4
make install DESTDIR=${DEST}

popd

rm -rf lightdm-${VER}

install -dm755 ${DEST}/etc/lightdm

cat > ${DEST}/etc/lightdm/lightdm-kde-greeter.conf << "EOF"
[greeter]
theme-name=classic
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done
EOF

chmod 755 ${DEST}/INSTALL
