#!/bin/bash -e

export PKGNAME=schroedinger
export PKGVER=1.0.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://diracvideo.org/download/schroedinger/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
