#!/bin/bash -e

case $(basename $0) in
  buildadwaita-icon-theme )
    export PKGNAME=adwaita-icon-theme
    export PKGVER=3.18.0
    export NO_STRIP=1
    export POSTINST_TRIGGER=("[ -x /usr/bin/gtk-update-icon-cache ] && echo \"Processing triggers for adwaita-icon-theme\" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/Adwaita")
  ;;
  builddconf )
    export PKGNAME=dconf
    export PKGVER=0.24.0
  ;;
  buildgcr )
    export PKGNAME=gcr
    export PKGVER=3.18.0
  ;;
  buildgeocode-glib )
    export PKGNAME=geocode-glib
    export PKGVER=3.18.0
  ;;
  buildgjs )
    export PKGNAME=gjs
    export PKGVER=1.44.0
    make_install_post() {
      rm -rf ${DEST}/usr/libexec
    }
  ;;
  buildglib-networking )
    export PKGNAME=glib-networking
    export PKGVER=2.46.1
  ;;
  buildgmime )
    export PKGNAME=gmime
    export PKGVER=2.6.20
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--enable-smime)
  ;;
  buildgnome-desktop )
    export PKGNAME=gnome-desktop
    export PKGVER=3.18.2
    export CONFIGURE_FLAGS=(--with-gnome-distributor=Krejzi)
  ;;
  buildgnome-online-accounts )
    export PKGNAME=gnome-online-accounts
    export PKGVER=3.18.3
    export CONFIGURE_FLAGS=(--enable-kerberos)
  ;;
  buildgnome-themes-standard )
    export PKGNAME=gnome-themes-standard
    export PKGVER=3.18.0
    export MULTILIB_BUILD=1
    export POSTINST_TRIGGER=("[ -x /usr/bin/gtk-update-icon-cache ] && echo \"Processing triggers for hicolor-icon-theme\" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/HighContrast")
    export MAKE_FLAGS_32="-C themes/Adwaita/gtk-2.0 libadwaita.la"
    make_install_override() {
      if [ ${MULTILIB} == 0 ]
      then
        make install ${ADDITIONAL_MAKE_INSTALL_FLAGS}
      else
        make -C themes/Adwaita/gtk-2.0 install-engineLTLIBRARIES ${ADDITIONAL_MAKE_INSTALL_FLAGS}
      fi
    }
  ;;
  buildgrilo )
    export PKGNAME=grilo
    export PKGVER=0.2.14
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgsettings-desktop-schemas )
    export PKGNAME=gsettings-desktop-schemas
    export PKGVER=3.18.1
    export NO_STRIP=1
  ;;
  buildgtksourceview )
    export PKGNAME=gtksourceview
    export PKGVER=3.18.1
  ;;
  buildgtk-vnc )
    export PKGNAME=gtk-vnc
    export PKGVER=0.5.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--with-gtk=3.0 --enable-vala)
  ;;
  buildgvfs )
    export PKGNAME=gvfs
    export PKGVER=1.26.2
  ;;
  buildjson-glib )
    export PKGNAME=json-glib
    export PKGVER=1.0.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildlibgdata )
    export PKGNAME=libgdata
    export PKGVER=0.17.4
  ;;
  buildlibgnome-keyring )
    export PKGNAME=libgnome-keyring
    export PKGVER=3.12.0
  ;;
  buildlibgtop )
    export PKGNAME=libgtop
    export PKGVER=2.32.0
  ;;
  buildlibgudev )
    export PKGNAME=libgudev
    export PKGVER=230
    export MULTILIB_BUILD=1
    export CONFIGURE_FLAGS_32=(--disable-introspection)
  ;;
  buildlibgweather )
    export PKGNAME=libgweather
    export PKGVER=3.18.1
  ;;
  buildlibgxps )
    export PKGNAME=libgxps
    export PKGVER=0.2.3.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildlibpeas )
    export PKGNAME=libpeas
    export PKGVER=1.16.0
    make_install_post() {
      rm -rf ${DEST}/usr/bin ${DEST}/usr/lib/peas-demo
    }
  ;;
  buildlibrsvg )
    export PKGNAME=librsvg
    export PKGVER=2.40.12
    export CONFIGURE_FLAGS=(--enable-vala)
    export POSTINST_TRIGGER=("[ -x /usr/bin/gdk-pixbuf-query-loaders ] && echo \"Processing triggers for gdk-pixbuf-2.0\" && /usr/bin/gdk-pixbuf-query-loaders --update-cache")
    make_install_post() {
      export SPACE_ADDED=1
    }
  ;;
  buildlibsecret )
    export PKGNAME=libsecret
    export PKGVER=0.18.3
  ;;
  buildlibsoup )
    export PKGNAME=libsoup
    export PKGVER=2.52.2
    export CONFIGURE_FLAGS=(--disable-tls-check)
  ;;
  buildlibwnck )
    export PKGNAME=libwnck
    export PKGVER=3.14.0
  ;;
  buildrest )
    export PKGNAME=rest
    export PKGVER=0.7.93
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildtotem-pl-parser )
    export PKGNAME=totem-pl-parser
    export PKGVER=3.10.6
  ;;
  buildvte )
    export PKGNAME=vte
    export PKGVER=0.42.1
    export CONFIGURE_FLAGS=(--enable-introspection)
    make_install_post() {
      rm -rf ${DEST}/etc
    }
  ;;
  buildyelp-xsl )
    export PKGNAME=yelp-xsl
    export PKGVER=3.18.1
    export NO_STRIP=1
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
if [ -z ${PKGURL} ]
then
  export PKGURL="http://ftp.gnome.org/pub/gnome/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
fi

. $(dirname $0)/master.sh
