#!/bin/bash -e

export PKGNAME=libevent
export PKGVER=2.0.22
export PKGTAR=${PKGNAME}-${PKGVER}-stable.tar.gz
export PKGDIR=${PKGNAME}-${PKGVER}-stable
export PKGURL="http://downloads.sourceforge.net/levent/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
