#!/bin/bash -e

export PKGNAME=libproxy
export PKGVER=0.4.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://libproxy.googlecode.com/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export MULTILIB_BUILD=1

export CMAKE_FLAGS=(-DCMAKE_SKIP_RPATH=ON
                    -DPERL_VENDORINSTALL=yes
                    -DWITH_WEBKIT=OFF
                    -DWITH_KDE4=OFF)

export CMAKE_FLAGS_32=(${CMAKE_FLAGS[@]}
                       -DLIB_INSTALL_DIR=/usr/lib32
                       -DWITH_GNOME3=OFF
                       -DWITH_NM=OFF
                       -DWITH_PERL=OFF
                       -DWITH_PYTHON=OFF)

. $(dirname $0)/master.sh
