#!/bin/bash -e

export PKGNAME=murrine
export PKGVER=0.98.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://download.gnome.org/sources/murrine/${PKGVER:0:3}/${PKGTAR}"
export DEST=/binary/mate/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-animation --enable-animationrtl)

. $(dirname $0)/master.sh
