#!/bin/bash -e

export PKGNAME=libdca
export PKGVER=0.0.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.videolan.org/pub/videolan/libdca/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

post_install_config() {
  find ${DEST} -name "*.a" -delete
}

. $(dirname $0)/master.sh
