#!/bin/bash -e

export PKGNAME=libusb
export PKGVER=1.0.21
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://github.com/libusb/libusb/releases/download/v${PKGVER}/${PKGTAR}"

. $(dirname $0)/master.sh
