#!/bin/bash -e

export VER=2.4.3
export DEST=/binary/ffmpeg-${VER}

pushd ffmpeg-${VER}

./configure --prefix=/usr              \
            --enable-fontconfig        \
            --enable-gnutls            \
            --enable-gpl               \
            --enable-ladspa            \
            --enable-libaacplus        \
            --enable-libass            \
            --enable-libbluray         \
            --enable-libbs2b           \
            --enable-libcaca           \
            --enable-libcelt           \
            --enable-libcdio           \
            --enable-libdc1394         \
            --enable-libfaac           \
            --enable-libfdk-aac        \
            --enable-libfreetype       \
            --enable-libfribidi        \
            --enable-libgme            \
            --enable-libgsm            \
            --enable-libiec61883       \
            --enable-libmodplug        \
            --enable-libmp3lame        \
            --enable-libopencore-amrnb \
            --enable-libopencore-amrwb \
            --enable-libopenjpeg       \
            --enable-libopus           \
            --enable-libpulse          \
            --enable-librtmp           \
            --enable-libschroedinger   \
            --enable-libsmbclient      \
            --enable-libspeex          \
            --enable-libssh            \
            --enable-libtheora         \
            --enable-libtwolame        \
            --enable-libv4l2           \
            --enable-libvo-aacenc      \
            --enable-libvo-amrwbenc    \
            --enable-libvorbis         \
            --enable-libvpx            \
            --enable-libwavpack        \
            --enable-libwebp           \
            --enable-libx264           \
            --enable-libx265           \
            --enable-libxvid           \
            --enable-libzvbi           \
            --enable-nonfree           \
            --enable-openal            \
            --enable-opencl            \
            --enable-opengl            \
            --enable-postproc          \
            --enable-shared            \
            --enable-vaapi             \
            --enable-vdpau             \
            --enable-version3          \
            --enable-x11grab           \
            --disable-debug            \
            --disable-static           \
            --extra-cflags='-march=native -mtune=native -O2 -pipe -fstack-protector-strong '   \
            --extra-cxxflags='-march=native -mtune=native -O2 -pipe -fstack-protector-strong '

make -j4
make install DESTDIR=${DEST}

popd

rm -rf ffmpeg-${VER}

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
