#!/bin/bash -e

export PKGNAME=virt-manager
export PKGVER=1.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://virt-manager.org/download/sources/virt-manager/${PKGTAR}"

configure_override() {
  true
}

make_override() {
  python setup.py build
}

make_install_override() {
  python setup.py --no-update-icon-cache --no-compile-schemas install --root=${DEST} --optimize=1
}

. $(dirname $0)/master.sh
