#!/bin/bash -e

export PKGNAME=pixman
export PKGVER=0.34.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://cairographics.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--disable-gtk --disable-libpng)
export CONFIGURE_FLAGS_32=(--disable-gtk --disable-libpng)

. $(dirname $0)/master.sh
