#!/bin/bash -e

export PKGNAME=libdvdcss
export PKGVER=1.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.videolan.org/pub/videolan/libdvdcss/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
