#!/bin/bash -e

export VER=2.3.4
export DEST=/binary/scons-${VER}

pushd scons-${VER}

python setup.py install --prefix=/usr  \
                        --standard-lib \
                        --optimize=1   \
                        --install-data=/usr/share \
                        --root=${DEST}

popd

rm -rf scons-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
