#!/bin/bash -e

export PKGNAME=harfbuzz
export PKGVER=1.3.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.freedesktop.org/software/harfbuzz/release/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-gobject --with-graphite2)

. $(dirname $0)/master.sh
