#!/bin/bash -e

export PKGNAME=xapian-core
export PKGVER=1.2.22
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://oligarchy.co.uk/xapian/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
