#!/bin/bash -e

export PKGNAME=portaudio
export PKGVER=19_20140130
export PKGTAR=pa_stable_v${PKGVER}.tgz
export PKGURL="http://www.portaudio.com/archives/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export PKGDIR=${PKGNAME}
export CONFIGURE_FLAGS=(--enable-cxx)

. $(dirname $0)/master.sh
