#!/bin/bash -e

export PKGNAME=wildmidi
export PKGVER=0.3.9
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-${PKGNAME}-${PKGVER}
export PKGURL="https://github.com/Mindwerks/wildmidi/archive/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export MULTILIB_BUILD=1
export CMAKE_FLAGS_32=(-DLIB_SUFFIX=32)

. $(dirname $0)/master.sh
