#!/bin/bash -e

export PKGNAME=libcacard
export PKGVER=2.5.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.spice-space.org/download/libcacard/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
