#!/bin/bash -e

export PKGNAME=hicolor-icon-theme
export PKGVER=0.15
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://icon-theme.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export KEEP_STATIC=1
export NO_STRIP=1

. $(dirname $0)/master.sh
