#!/bin/bash -e

export PKGNAME=glu
export PKGVER=9.0.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.freedesktop.org/pub/mesa/glu/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
