#!/bin/bash -e

export PKGNAME=make
export PKGVER=4.2.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://ftp.gnu.org/gnu/make/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--without-guile)

. $(dirname $0)/master.sh
