#!/bin/bash -e

export PKGNAME=ethtool
export PKGVER=4.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://www.kernel.org/pub/software/network/ethtool/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

. $(dirname $0)/master.sh
