#!/bin/bash -e

export VER=2015.4
export DEST=/binary/python-pytz-${VER}

cp -a pytz-${VER} pytz-${VER}-3

pushd pytz-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd pytz-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf pytz-${VER} pytz-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
