#!/bin/bash -e

export VER=4.1.2
export DEST=/binary/python-rdflib-${VER}

cp -a rdflib-${VER} rdflib-${VER}-3

pushd rdflib-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

for file in ${DEST}/usr/bin/*
do
  mv ${file} ${file}3
done

popd

pushd rdflib-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf rdflib-${VER} rdflib-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
