#!/bin/bash -e

export PKGNAME=ModemManager
export PKGVER=1.6.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.freedesktop.org/software/ModemManager/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-gtk-doc --with-polkit=permissive --disable-more-warnings)

. $(dirname $0)/master.sh
