#!/bin/bash -e

export VER=1.6.3
export DEST=/binary/v4l-utils-${VER}

cp -a v4l-utils-${VER} v4l-utils-${VER}-32

pushd v4l-utils-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

pushd v4l-utils-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --sysconfdir=/etc   \
            --libdir=/usr/lib32 \
            --disable-static    \
            --disable-qv4l2     \
            --disable-v4l-utils

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf v4l-utils-${VER} v4l-utils-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/bin/ivtv-ctl ${DEST}/usr/sbin

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
