#!/bin/bash -e

export VER=2.0.3
export DEST=/binary/SDL2-${VER}

cp -a SDL2-${VER} SDL2-${VER}-32

pushd SDL2-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr            \
            --enable-video-wayland   \
            --disable-alsa-shared    \
            --disable-x11-shared     \
            --disable-wayland-shared \
            --disable-pulseaudio-shared

make -j4
make install DESTDIR=${DEST}

popd

pushd SDL2-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --enable-video-wayland   \
            --disable-alsa-shared    \
            --disable-x11-shared     \
            --disable-wayland-shared \
            --disable-pulseaudio-shared

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf SDL2-${VER} SDL2-${VER}-32

rm -rf ${DEST}/usr/lib*/libSDL2.a

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
