#!/bin/bash -e

export VER=0.98.2
export DEST=/binary/murrine-${VER}

pushd murrine-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --enable-animation   \
            --enable-animationrtl

make -j4
make install DESTDIR=${DEST}

popd

rm -rf murrine-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
