#!/bin/bash -e

export VER=3.6
export DEST=/binary/recode-${VER}

tar xf /media/ntfs/Other/Linux/packages/recode-${VER}.tar.gz

pushd recode-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/recode-fixes.patch

rm -rf acinclude.m4
autoreconf -fi

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr    \
            --disable-static \
            --without-included-gettext

make -j4
make install DESTDIR=${DEST}

popd

rm -rf recode-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
