#!/bin/bash -e

export PKGNAME=libpaper
export PKGVER=1.1.24+nmu4
export PKGTAR=${PKGNAME}_${PKGVER}.tar.gz
export PKGURL="http://ftp.debian.org/debian/pool/main/libp/libpaper/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
