#!/bin/bash -e

export VER=9.45
export DEST=/binary/hdparm-${VER}

pushd hdparm-${VER}

sed -i "s:-O2:-march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" Makefile

make -j4
make install DESTDIR=${DEST}

popd

rm -rf hdparm-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
