#!/bin/bash -e

export VER=3.0.2
export DEST=/binary/wxWidgets-${VER}

cp -a wxWidgets-${VER} wxWidgets-${VER}-32

pushd wxWidgets-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/wxwidgets-abicheck.patch

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w" \
./configure --prefix=/usr             \
            --libdir=/usr/lib         \
            --disable-precomp-headers \
            --enable-graphics_ctx     \
            --enable-mediactrl        \
            --enable-unicode          \
            --enable-webview          \
            --with-gtk=2              \
            --with-libjpeg=sys        \
            --with-libpng=sys         \
            --with-libtiff=sys        \
            --with-libxpm=sys         \
            --with-opengl             \
            --with-regex=builtin

make -j4
make -C locale allmo -j4

make install DESTDIR=${DEST}

popd

pushd wxWidgets-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

patch -Np1 -i /media/ntfs/Other/Linux/patches/wxwidgets-abicheck.patch
patch -Np1 -i /media/ntfs/Other/Linux/patches/wxwidgets-multilib.patch

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong -w" \
./configure --prefix=/usr             \
            --libdir=/usr/lib32       \
            --disable-mediactrl       \
            --disable-webview         \
            --disable-precomp-headers \
            --enable-graphics_ctx     \
            --enable-unicode          \
            --with-gtk=2              \
            --with-libjpeg=sys        \
            --with-libpng=sys         \
            --with-libtiff=sys        \
            --with-libxpm=sys         \
            --with-opengl             \
            --with-regex=builtin      \
            --without-libnotify

make -j4
make -C locale allmo -j4

make install DESTDIR=${PWD}/dest

mv dest/usr/bin/* ${DEST}/usr/bin
mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf wxWidgets-${VER} wxWidgets-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
