#!/bin/bash -e

case $(basename $0) in
  buildspice-protocol )
    export PKGNAME=spice-protocol
    export PKGVER=0.12.11
  ;;
  buildspice )
    export PKGNAME=spice
    export PKGVER=0.13.1
  ;;
  buildspice-gtk )
    export PKGNAME=spice-gtk
    export PKGVER=0.32
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    export PKGURL="http://www.spice-space.org/download/gtk/${PKGTAR}"
    export CONFIGURE_FLAGS=(--enable-vala
                            --with-audio=pulse
                            --with-coroutine=gthread)
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export MAKE_JOBS_FLAGS="-j4"

if [ -z ${PKGURL} ]
then
  export PKGURL="http://www.spice-space.org/download/releases/${PKGTAR}"
fi

. $(dirname $0)/master.sh
