#!/bin/bash -e

export PKGNAME=qtwebkit
export PKGVER=5.6.1
export PKGTAR=${PKGNAME}-opensource-src-${PKGVER}.tar.xz
export PKGDIR=${PKGNAME}-opensource-src-${PKGVER}
export PKGURL="https://download.qt.io/community_releases/5.6/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export NO_OPTIMIZATION=1
export MAKE_INSTALL_FLAGS="INSTALL_ROOT=\${DEST}"

configure_post() {
  # No debug symbols for this module. Taken from Debian
  echo "QMAKE_CXXFLAGS -= -g" >> .qmake.conf
  echo "QMAKE_CXXFLAGS -= -gstabs" >> .qmake.conf
  echo "QMAKE_CXXFLAGS += -w" >> .qmake.conf

}

configure_override() {
  qmake
}

make_post() {
  find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;
}

make_install_post() {
  find ${DEST}/usr/lib -name "*.prl" -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
}

. $(dirname $0)/master.sh
