#!/bin/bash -e

export PKGNAME=cln
export PKGVER=1.3.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.ginac.de/CLN/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
