#!/bin/bash -e

export VER=1.8.5
export DEST=/binary/openmpi-${VER}

pushd openmpi-${VER}

rm -rf opal/libltdl

FC=/usr/bin/gfortran                       \
CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr             \
            --sysconfdir=/etc/openmpi \
            --with-hwloc=/usr         \
            --with-libltdl=/usr       \
            --with-threads=posix      \
            --with-valgrind           \
            --without-slurm

make -j4
make install DESTDIR=${DEST}

popd

rm -rf openmpi-${VER}

find ${DEST} -name "*.la" -delete

mv ${DEST}/usr/bin/otfinfo ${DEST}/usr/bin/otfinfompi

rm -rf ${DEST}/usr/share/vampirtrace/config.log

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
