#!/bin/bash -e

export PKGNAME=libmpeg2
export PKGVER=0.5.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://libmpeg2.sourceforge.net/files/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

configure_pre() {
  sed -i 's/static const/static/' libmpeg2/idct_mmx.c
}

. $(dirname $0)/master.sh
