#!/bin/bash -e

export PKGNAME=ffmpeg
export PKGVER=3.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ffmpeg.org/releases/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export NO_OPTIMIZATION=1

configure_override() {
  sed -i "s: -lstdc++::g" configure

  ./configure --prefix=/usr              \
              --enable-chromaprint       \
              --enable-gpl               \
              --enable-libass            \
              --enable-libbluray         \
              --enable-libcdio           \
              --enable-libfdk-aac        \
              --enable-libfontconfig     \
              --enable-libfreetype       \
              --enable-libfribidi        \
              --enable-libmp3lame        \
              --enable-libopenjpeg       \
              --enable-libopus           \
              --enable-libpulse          \
              --enable-librtmp           \
              --enable-libsoxr           \
              --enable-libspeex          \
              --enable-libssh            \
              --enable-libtheora         \
              --enable-libv4l2           \
              --enable-libvo-amrwbenc    \
              --enable-libvorbis         \
              --enable-libvpx            \
              --enable-libwavpack        \
              --enable-libwebp           \
              --enable-libx264           \
              --enable-libx265           \
              --enable-libxvid           \
              --enable-nonfree           \
              --enable-openal            \
              --enable-opencl            \
              --enable-opengl            \
              --enable-openssl           \
              --enable-postproc          \
              --enable-shared            \
              --enable-vaapi             \
              --enable-vdpau             \
              --enable-version3          \
              --enable-x11grab           \
              --disable-debug            \
              --disable-static           \
              --extra-cflags="${DEFAULT_CFLAGS}"   \
              --extra-cxxflags="${DEFAULT_CXXFLAGS}" \
              --cc="${CC}" --cxx="${CXX}"
}

. $(dirname $0)/master.sh
