#!/bin/bash -e

export PKGNAME=hdparm
export PKGVER=9.50
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/hdparm/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_override() {
  sed -i "s:-O2:${CFLAGS}:g" Makefile

  unset CFLAGS
}

. $(dirname $0)/master.sh
