#!/bin/bash -e

export PKGNAME=libtool
export PKGVER=2.4.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/libtool/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
