#!/bin/bash -e

export VER=3.1
export DEST=/binary/rhythmbox-${VER}

pushd rhythmbox-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr    \
            --disable-static \
            --enable-python  \
            --enable-vala

make -j4
make install DESTDIR=${DEST}

popd

rm -rf rhythmbox-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/usr/lib/rhythmbox/mozilla

mv ${DEST}/usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so ${DEST}/usr/lib/rhythmbox/mozilla
ln -sf ../../rhythmbox/mozilla/librhythmbox-itms-detection-plugin.so ${DEST}/usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
