#!/bin/bash -e

export PKGNAME=libndp
export PKGVER=1.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://libndp.org/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
