#!/bin/bash -e

export PKGNAME=xapian-core
export PKGVER=1.2.23
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://oligarchy.co.uk/xapian/${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
