#!/bin/bash -e

export VER=4.10.0
export DEST=/binary/xfwm4-themes-${VER}

pushd xfwm4-themes-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf xfwm4-themes-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
