#!/bin/bash -e

export PKGNAME=yaml
export PKGVER=0.1.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://pyyaml.org/download/libyaml/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
