#!/bin/bash -e

export VER=6.9.1-2
export DEST=/binary/ImageMagick-${VER}

pushd ImageMagick-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --enable-hdri     \
            --with-gslib      \
            --with-gvc        \
            --with-modules    \
            --with-perl       \
            --with-rsvg       \
            --with-dejavu-font-dir=/usr/share/fonts/truetype/dejavu \
            --with-gs-font-dir=/usr/share/ghostscript/fonts \
            --with-perl-options=INSTALLDIRS=vendor

make -j4
make install DESTDIR=${DEST}

popd

rm -rf ImageMagick-${VER}

rm -rf ${DEST}/usr/lib/*.la
rm -rf ${DEST}/usr/lib/perl
rm -rf ${DEST}/usr/lib/perl5/auto/Image/Magick/.packlist
rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
