#!/bin/bash -e

export PKGNAME=libgcrypt
export PKGVER=1.7.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.gnupg.org/gcrypt/libgcrypt/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-padlock-support)

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libgcrypt.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libgcrypt.so) ${DEST}/usr/lib/libgcrypt.so
}

. $(dirname $0)/master.sh
