#!/bin/bash -e

export PKGNAME=foomatic-db-engine
export PKGVER=4.0-20150819
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://www.openprinting.org/download/foomatic/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export KEEP_STATIC=1
export NO_STRIP=1
export CONFIGURE_FLAGS=(PERL_INSTALLDIRS=vendor)

. $(dirname $0)/master.sh
