#!/bin/bash -e

export PKGNAME=libxml2
export PKGVER=2.9.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://xmlsoft.org/sources/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-history)

. $(dirname $0)/master.sh
