#!/bin/bash -e

export PKGNAME=libproxy
export PKGVER=0.4.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://libproxy.googlecode.com/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_SKIP_RPATH=ON
                    -DPERL_VENDORINSTALL=yes
                    -DWITH_WEBKIT=OFF
                    -DWITH_KDE4=OFF)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
