#!/bin/bash -e

export PKGNAME=fontconfig
export PKGVER=2.12.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.freedesktop.org/software/fontconfig/release/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--disable-docs)
export CONFIGURE_FLAGS_32=(--disable-docs)

make_install_post() {
  install -dm755 ${DEST}/usr/share/man/man{1,3,5}

  install -m644 fc-*/*.1 ${DEST}/usr/share/man/man1
  install -m644 doc/*.3 ${DEST}/usr/share/man/man3
  install -m644 doc/fonts-conf.5 ${DEST}/usr/share/man/man5
}

. $(dirname $0)/master.sh
