#!/bin/bash -e

export VER=0.9.1
export DEST=/binary/python-cssselect-${VER}

cp -a cssselect-${VER} cssselect-${VER}-3

pushd cssselect-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd cssselect-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf cssselect-${VER} cssselect-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
