#!/bin/bash -e

export PKGNAME=libunwind
export PKGVER=1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://download.savannah.gnu.org/releases/libunwind/"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  sed -i "/LIBCRTS/s#-lgcc##g" configure
}

make_install_post() {
  rm -rf ${DEST}/usr/lib/libunwind-generic.a
}

. $(dirname $0)/master.sh
