#!/bin/bash -e

export VER=7.4.2
export DEST=/binary/libatomic_ops-${VER}

pushd libatomic_ops-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr   \
            --enable-shared \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libatomic_ops-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
