#!/bin/bash -e

export PKGNAME=valgrind
export PKGVER=3.11.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://valgrind.org/downloads/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export NO_OPTIMIZATION=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

configure_pre() {
  sed -i "s/-mt//g" configure
}

. $(dirname $0)/master.sh
