#!/bin/bash -e

export VER=3.18.1
export DEST=/binary/gtk+-${VER}

cp -a gtk+-${VER} gtk+-${VER}-32

pushd gtk+-${VER}

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --enable-broadway-backend \
            --enable-wayland-backend  \
            --enable-x11-backend

# Speed up build a little
sed -i "/SRC_SUBDIRS/s# demos tests testsuite examples##" Makefile
sed -i "/SUBDIRS/s#docs m4macros#m4macros#" Makefile

make -j4
make install DESTDIR=${DEST}

popd

pushd gtk+-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --libdir=/usr/lib32       \
            --enable-broadway-backend \
            --enable-wayland-backend  \
            --enable-x11-backend      \
            --disable-cloudprint      \
            --disable-introspection   \
            --disable-libcanberra

# Speed up build a little
sed -i "/SRC_SUBDIRS/s# demos tests testsuite examples##" Makefile
sed -i "/SUBDIRS/s#docs m4macros#m4macros#" Makefile

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr
mv dest/usr/bin/gtk-query-immodules-3.0 ${DEST}/usr/bin/gtk-query-immodules-3.0-32

popd

rm -rf gtk+-${VER} gtk+-${VER}-32

find ${DEST} -name "*.la" -delete

cat > ${DEST}/usr/share/gtk-3.0/settings.ini << "EOF"
[Settings]
gtk-icon-theme-name = Adwaita
gtk-theme-name = Adwaita
gtk-font-name = Cantarell 11
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/gtk-query-immodules-3.0 ] && echo "Processing triggers for gtk-3.0" && /usr/bin/gtk-query-immodules-3.0 --update-cache
[ -x /usr/bin/gtk-query-immodules-3.0-32 ] && echo "Processing triggers for gtk-3.0 (32 bit)" && /usr/bin/gtk-query-immodules-3.0-32 --update-cache
[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
