#!/bin/bash -e

export PKGNAME=libkate
export PKGVER=0.4.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://libkate.googlecode.com/files/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")

configure_pre() {
  export LEXLIB=/usr/lib/libfl.a
}

configure_pre_32() {
  export LEXLIB=/usr/lib32/libfl.a
}

. $(dirname $0)/master.sh
