#!/bin/bash -e

case $(basename $0) in
  buildxcb-util )
    export PKGNAME=xcb-util
    export PKGVER=0.4.0
  ;;
  buildxcb-util-cursor )
    export PKGNAME=xcb-util-cursor
    export PKGVER=0.1.2
  ;;
  buildxcb-util-errors )
    export PKGNAME=xcb-util-errors
    export PKGVER=1.0
  ;;
  buildxcb-util-image )
    export PKGNAME=xcb-util-image
    export PKGVER=0.4.0
  ;;
  buildxcb-util-keysyms )
    export PKGNAME=xcb-util-keysyms
    export PKGVER=0.3.9
  ;;
  buildxcb-util-renderutil )
    export PKGNAME=xcb-util-renderutil
    export PKGVER=0.3.9
  ;;
  buildxcb-util-wm )
    export PKGNAME=xcb-util-wm
    export PKGVER=0.4.1
  ;;
  buildxorg-xcb-util )
    export PKG_AUTO_INSTALL=1

    $(dirname $0)/buildxcb-util
    $(dirname $0)/buildxcb-util-errors
    $(dirname $0)/buildxcb-util-image
    $(dirname $0)/buildxcb-util-keysyms
    $(dirname $0)/buildxcb-util-renderutil
    $(dirname $0)/buildxcb-util-wm
    $(dirname $0)/buildxcb-util-cursor

    find /binary/xorg/xcb -name "INSTALL" -exec grep -rl "exit 0" {} \; | while read f ; do head --lines -2 ${f} > ${f}.new ; mv ${f}.new ${f} ; chmod 755 ${f} ; done

    exit 0
  ;;
esac

export MAKE_JOBS_FLAGS="-j4"
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export DEST=/binary/xorg/xcb/${PKGNAME}-${PKGVER}
export PKGURL="http://xorg.freedesktop.org/releases/individual/xcb/${PKGTAR}"

. $(dirname $0)/master.sh
