#!/bin/bash -e

export VER=0.5.1
export DEST=/binary/python-isodate-${VER}

cp -a isodate-${VER} isodate-${VER}-3

pushd isodate-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd isodate-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf isodate-${VER} isodate-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
