#!/bin/bash -e

export VER=1.3.0
export DEST=/binary/lua-expat-${VER}

pushd luaexpat-${VER}

sed -i "s:-O2:-march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" Makefile

make LUA_V=5.2 -j4
make install LUA_V=5.2 DESTDIR=${DEST}

popd

rm -rf luaexpat-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
