#!/bin/bash -e

export PKGNAME=jemalloc
export PKGVER=4.2.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.canonware.com/download/jemalloc/${PKGVER}"
export MAKE_JOBS_FLAGS="-j4"

make_install_post() {
  rm -rf ${DEST}/usr/lib/*.a
}

. $(dirname $0)/master.sh
