#!/bin/bash -e

export PKGNAME=sqlitebrowser
export PKGVER=3.7.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/sqlitebrowser/sqlitebrowser/archive/v${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DUSE_QT5=ON)

. $(dirname $0)/master.sh
