#!/bin/bash -e

export PKGNAME=gperf
export PKGVER=3.0.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://ftp.gnu.org/gnu/gperf/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
