#!/bin/bash -e

export VER=1.7.0
export DEST=/binary/extra-cmake-modules-${VER}

pushd extra-cmake-modules-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf extra-cmake-modules-${VER}

rm -rf ${DEST}/usr/share/doc

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
