#!/bin/bash -e

export PKGNAME=libebml
export PKGVER=1.3.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://dl.matroska.org/downloads/libebml/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
   sed -i "/cstring/i #include <cstdlib>" ebml/EbmlBinary.h
}

. $(dirname $0)/master.sh
