#!/bin/bash -e

export VER=3.4.3
export DEST=/binary/python-lxml-${VER}

cp -a lxml-${VER} lxml-${VER}-3

pushd lxml-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd lxml-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf lxml-${VER} lxml-${VER}-3

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
