#!/bin/bash -e

export PKGNAME=libical
export PKGVER=2.0.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/libical/libical/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DCMAKE_INSTALL_LIBDIR=lib -DSHARED_ONLY=ON)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
