#!/bin/bash -e

export PKGNAME=poppler
export PKGVER=0.48.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://poppler.freedesktop.org/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-xpdf-headers)

export DEFAULT_CXX="clang++ -std=c++11"

make_install_post() {
  rm -rf ${DEST}/usr/bin/poppler-glib-demo
}

. $(dirname $0)/master.sh
