#!/bin/bash -e

export PKGNAME=mailnag-goa-plugin
export PKGVER=1.2.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/pulb/mailnag-goa-plugin/archive/v${PKGVER}.tar.gz"

configure_override() {
  true
}

make_override() {
  python setup.py build
}

make_install_override() {
  python setup.py install --root=${DEST} --optimize=1
}

. $(dirname $0)/master.sh
