#!/bin/bash -e

export VER=2.7.2
export DEST=/binary/man-db-${VER}

pushd man-db-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr                  \
            --sysconfdir=/etc              \
            --disable-setuid               \
            --with-browser=/usr/bin/lynx   \
            --with-vgrind=/usr/bin/vgrind  \
            --with-grap=/usr/bin/grap

make -j4
make install DESTDIR=${DEST}

popd

rm -rf man-db-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/doc ${DEST}/usr/share/man/{es,it}

sed -i "s:man root:root root:g" ${DEST}/usr/lib/tmpfiles.d/man-db.conf

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
