#!/bin/bash -e

export VER=5.6.0
export DEST=/binary/baloo-${VER}

pushd baloo-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr   \
      -DCMAKE_BUILD_TYPE=Release    \
      -DSYSCONF_INSTALL_DIR=/etc    \
      -DLIB_INSTALL_DIR=lib         \
      -DBUILD_TESTING=OFF           \
      -DQML_INSTALL_DIR=lib/qt5/qml \
      -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
      -Wno-dev

make -j4
make install DESTDIR=${DEST}/baloo-libs

popd

rm -rf baloo-${VER}

install -dm755 ${DEST}/baloo-binaries/usr/share

mv ${DEST}/baloo-libs/etc ${DEST}/baloo-binaries
mv ${DEST}/baloo-libs/usr/bin ${DEST}/baloo-binaries/usr
mv ${DEST}/baloo-libs/usr/share/dbus-1 ${DEST}/baloo-binaries/usr/share
mv ${DEST}/baloo-libs/usr/share/icons ${DEST}/baloo-binaries/usr/share
mv ${DEST}/baloo-libs/usr/share/polkit-1 ${DEST}/baloo-binaries/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/baloo-libs/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

cat > ${DEST}/baloo-binaries/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
EOF

chmod 755 ${DEST}/baloo-libs/INSTALL ${DEST}/baloo-binaries/INSTALL
