#!/bin/bash -e

export VER=2.9.4
export DEST=/binary/fuse-${VER}

pushd fuse-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-static

make -j4
make install DESTDIR=${DEST}

popd

rm -rf fuse-${VER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/dev ${DEST}/etc/init.d

install -dm755 ${DEST}/lib

mv ${DEST}/etc/udev ${DEST}/lib
mv ${DEST}/usr/lib/libfuse.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libfuse.so) ${DEST}/usr/lib/libfuse.so

cat > ${DEST}/etc/fuse.conf << "EOF"
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
#user_allow_other
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
