#!/bin/bash -e

export VER=2.24
export DEST=/binary/binutils-${VER}

mv binutils-${VER} src

pushd src

if [ -f /media/ntfs/Other/Linux/patches/binutils-fixes.patch ]; then
   patch -Np1 -i /media/ntfs/Other/Linux/patches/binutils-fixes.patch
fi

popd

mkdir build

pushd build

CFLAGS="-march=native -mtune=native -g -O2"   \
CXXFLAGS="-march=native -mtune=native -g -O2" \
../src/configure --prefix=/usr --with-pkgversion="Krejzi ${VER}"    \
                 --enable-gold --enable-ld=default --enable-plugins \
                 --enable-shared --enable-threads --disable-werror  \
                 --with-pic

# --enable-gold

make configure-host
make tooldir=/usr -j4

make install tooldir=/usr DESTDIR=${DEST}

popd

rm -rf src build

rm -rf ${DEST}/usr/lib/lib{bfd,opcodes}.so ${DEST}/usr/lib/*.la
rm -rf ${DEST}/usr/lib64

rm -rf ${DEST}/usr/share/man/man1/{dlltool,nlmconv,windres,windmc}.1
rm -rf ${DEST}/usr/share/info/{configure,standards}.info

rm -rf ${DEST}/usr/share/info/dir ${DEST}/usr/share/info/*.gz
gzip -9 ${DEST}/usr/share/info/*

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/install-info ] && echo "Processing triggers for texinfo" && for file in usr/share/info/* ; do /usr/bin/install-info /$file /usr/share/info/dir ; done
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL

install -dm755 ${DEST}-debug/usr/lib

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

mv ${DEST}/usr/lib/debug ${DEST}-debug/usr/lib
