#!/bin/bash -e

export PKGNAME=tidy-html5
export PKGVER=5.2.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/htacg/tidy-html5/archive/${PKGVER}.tar.gz"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1

. $(dirname $0)/master.sh
