#!/bin/bash -e

export PKGNAME=libdiscid
export PKGVER=0.6.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://ftp.musicbrainz.org/pub/musicbrainz/libdiscid/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
