#!/bin/bash -e

export VER=7.19.5.1
export DEST=/binary/python-pycurl-${VER}

cp -a pycurl-${VER} pycurl-${VER}-3

pushd pycurl-${VER}-3

python3 setup.py build --with-ssl
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd pycurl-${VER}

python setup.py build --with-ssl
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf pycurl-${VER} pycurl-${VER}-3

rm -rf ${DEST}/usr/share

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
