#!/bin/bash -e

export PKGNAME=libgpg-error
export PKGVER=1.21
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.gnupg.org/gcrypt/libgpg-error/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

make_install_post() {
  install -dm755 ${DEST}/lib

  mv ${DEST}/usr/lib/libgpg-error.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libgpg-error.so) ${DEST}/usr/lib/libgpg-error.so

  rm -rf ${DEST}/usr/share/common-lisp
}

. $(dirname $0)/master.sh
