#!/bin/bash -e

export PKGNAME=dosfstools
export PKGVER=3.0.28
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/dosfstools/dosfstools/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_FLAGS="PREFIX=/usr SBINDIR=/sbin"
export MAKE_INSTALL_FLAGS="PREFIX=/usr SBINDIR=/sbin"

export DEFAULT_CC="clang"

configure_override() {
  sed -i "s:-O2:${CFLAGS}:g" Makefile

  unset CFLAGS
}

. $(dirname $0)/master.sh
