#!/bin/bash -e

export PKGNAME=libepoxy
export PKGVER=1.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://github.com/anholt/libepoxy/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
