#!/bin/bash -e

export VER=1.6.0
export DEST=/binary/gst-plugins-bad-${VER}

pushd gst-plugins-bad-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --with-package-name="GStreamer Bad Plugins ${VER} BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/systemd/"

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gst-plugins-bad-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
