#!/bin/bash -e

export PKGNAME=p11-kit
export PKGVER=0.23.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://p11-glue.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-doc)

. $(dirname $0)/master.sh
