#!/bin/bash -e

export VER=2.31.6
export DEST=/binary/gdk-pixbuf-${VER}

cp -a gdk-pixbuf-${VER} gdk-pixbuf-${VER}-32

pushd gdk-pixbuf-${VER}

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr \
            --with-x11    \
            --with-libjasper

make -j4
make install DESTDIR=${DEST}

popd

pushd gdk-pixbuf-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --with-x11          \
            --with-libjasper    \
            --disable-introspection

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr
mv dest/usr/bin/gdk-pixbuf-query-loaders ${DEST}/usr/bin/gdk-pixbuf-query-loaders-32

popd

rm -rf gdk-pixbuf-${VER} gdk-pixbuf-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gdk-pixbuf-query-loaders ] && echo "Processing triggers for gdk-pixbuf-2.0" && /usr/bin/gdk-pixbuf-query-loaders --update-cache
[ -x /usr/bin/gdk-pixbuf-query-loaders-32 ] && echo "Processing triggers for gdk-pixbuf-2.0 (32 bit)" && /usr/bin/gdk-pixbuf-query-loaders-32 --update-cache
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
