#!/bin/bash -e

export PKGNAME=speech-dispatcher
export PKGVER=0.8.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://devel.freebsoft.org/pub/projects/speechd/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export CONFIGURE_FLAGS=(--without-flite)

configure_pre() {
  sed -i "s/cicero //g" configure.ac
  sed -i "s/sd_cicero//g" src/modules/Makefile.am

  autoreconf -fi
}

make_install_post() {
  sed -i 's|includedir=.*|includedir=${prefix}/include/speech-dispatcher|g' ${DEST}/usr/lib/pkgconfig/speech-dispatcher.pc

  install -dm755 ${DEST}/lib/systemd/system ${DEST}/var/log/speech-dispatcher

cat > ${DEST}/lib/systemd/system/speech-dispatcherd.service << "EOF"
[Unit]
Description=High-level device independent layer for speech synthesis.

[Service]
Type=forking
ExecStart=/usr/bin/speech-dispatcher -d

[Install]
WantedBy=multi-user.target
EOF
}

. $(dirname $0)/master.sh
