#!/bin/bash -e

export VER=1.1
export DEST=/binary/perl-sgmls-${VER}

pushd SGMLSpm-${VER}

perl Makefile.PL INSTALLDIRS=vendor

make -j4
make install DESTDIR=${DEST}

popd

rm -rf SGMLSpm-${VER}

rm -rf ${DEST}/usr/lib

ln -sf sgmlspl.pl ${DEST}/usr/bin/sgmlspl

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
