#!/bin/bash -e

export VER=5.32
export DEST=/binary/xscreensaver-${VER}

pushd xscreensaver-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

make -j4
make install install_prefix=${DEST}

popd

rm -rf xscreensaver-${VER}

echo "NotShowIn=KDE;GNOME;MATE;" >> ${DEST}/usr/share/applications/xscreensaver-properties.desktop

install -dm755 ${DEST}/etc/pam.d

cat > ${DEST}/etc/pam.d/xscreensaver << "EOF"
# Begin /etc/pam.d/xscreensaver

auth     include        system-auth
-auth    optional       pam_gnome_keyring.so

account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/xscreensaver
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
