#!/bin/bash -e

export PKGNAME=bc
export PKGVER=1.06.95
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://alpha.gnu.org/gnu/bc/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("bc-fixes.patch")
export CONFIGURE_FLAGS=(--with-readline)

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
