#!/bin/bash -e

export VER=3.3.4
export DEST=/binary/fftw-${VER}

pushd fftw-${VER}

F77="gfortran" \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr    \
            --enable-shared  \
            --enable-threads \
            --enable-sse     \
            --enable-single

make -j4
make install DESTDIR=${DEST}

make clean

F77="gfortran" \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr    \
            --enable-shared  \
            --enable-threads \
            --enable-sse2
make -j4
make install DESTDIR=${DEST}

make clean

F77="gfortran" \
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr    \
            --enable-shared  \
            --enable-threads \
            --enable-long-double

make -j4
make install DESTDIR=${DEST}

popd

rm -rf fftw-${VER}

find ${DEST} -name "*.la" -delete
find ${DEST} -name "*.a" -delete

rm -rf ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
