#!/bin/bash -e

export PKGNAME=firebird
export PKGVER=2.5.5.26952
export PKGTAR=Firebird-${PKGVER}-0.tar.bz2
export PKGDIR=Firebird-${PKGVER}-0
export PKGURL="https://downloads.sourceforge.net/firebird/${PKGTAR}"

export CONFIGURE_FLAGS=(--with-system-icu
                        --without-fbudf
                        --without-fbsbin
                        --without-fbconf
                        --without-fbdoc
                        --without-fbsample
                        --without-fbsample-db
                        --without-fbintl
                        --without-fbmisc
                        --without-fbhelp
                        --without-fbsecure-db
                        --without-fblog
                        --without-fbglock
                        --without-fbplugins
                        --with-fbmsg=/usr/share/firebird)

make_install_override() {
  install -dm755 ${DEST}/usr/bin ${DEST}/usr/share/firebird

  cp -rf gen/firebird/{lib,include} ${DEST}/usr
  rm -rf ${DEST}/usr/lib/libedit.a

  install -m644 gen/firebird/*.msg ${DEST}/usr/share/firebird
  install -m755 gen/firebird/bin/fb_config ${DEST}/usr/bin
}

. $(dirname $0)/master.sh
