#!/bin/bash -e

export PKGNAME=libmbim
export PKGVER=1.14.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.freedesktop.org/software/libmbim/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-more-warnings)

. $(dirname $0)/master.sh
