#!/bin/bash -e

export PKGNAME=SDL
export PKGVER=1.2.15
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://www.libsdl.org/release/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export COMMON_CONFIGURE_FLAGS=(--disable-alsa-shared
                               --disable-x11-shared
                               --disable-pulseaudio-shared)

export CONFIGURE_FLAGS=("${COMMON_CONFIGURE_FLAGS[@]}")
export CONFIGURE_FLAGS_32=("${COMMON_CONFIGURE_FLAGS[@]}")

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

configure_pre() {
  sed -i '/_XData32/s:register long:register _Xconst long:' src/video/x11/SDL_x11sym.h
}

configure_pre_32() {
  sed -i '/_XData32/s:register long:register _Xconst long:' src/video/x11/SDL_x11sym.h
}

. $(dirname $0)/master.sh
