#!/bin/bash -e

export PKGNAME=bogofilter
export PKGVER=1.2.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/bogofilter/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=("--sysconfdir=/etc/bogofilter")

. $(dirname $0)/master.sh
