#!/bin/bash -e

export PKGNAME=schroedinger
export PKGVER=1.0.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://download.videolan.org/contrib/schroedinger/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
