#!/bin/bash -e

export VER=0.2.6
export DEST=/binary/sni-qt-${VER}

cp -a sni-qt-${VER} sni-qt-${VER}-32

pushd sni-qt-${VER}

sed -i '/tests/ d' CMakeLists.txt

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"

make -j4
make install DESTDIR=${DEST}

popd

pushd sni-qt-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

sed -i '/tests/ d' CMakeLists.txt

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DQT_PLUGINS_DIR=/usr/lib32/qt4/plugins \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong $(pkg-config --cflags QtCore)"   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong $(pkg-config --cflags QtCore)"

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd


rm -rf sni-qt-${VER} sni-qt-${VER}-32

install -dm755 ${DEST}/etc

cat > ${DEST}/etc/sni-qt.conf << "EOF"
[need-activate-action]
clementine=1
mumble=1
skype=1
speedcrunch=1
keepassx=1
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done
EOF

chmod 755 ${DEST}/INSTALL
