#!/bin/bash -e

export PKGNAME=libasyncns
export PKGVER=0.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://0pointer.de/lennart/projects/libasyncns/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
