#!/bin/bash -e

export VER=1.10.0
export GTKVER=3.16
export DEST=/binary/mate-themes-${VER}

pushd mate-themes-gtk${GTKVER}-${VER}

./configure --prefix=/usr --enable-all-themes

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mate-themes-gtk${GTKVER}-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for mate-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/mate
EOF

chmod 755 ${DEST}/INSTALL
