#!/bin/bash -e

export PKGNAME=mariadb
export PKGVER=10.1.16
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.mariadb.org/interstitial/${PKGNAME}-${PKGVER}/source/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export USER_CFLAGS="-fPIC -fno-strict-aliasing -DBIG_JOINS=1 -w"
export USER_CXXFLAGS="-fPIC -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors -fno-rtti -w"

export CMAKE_FLAGS=(-DSYSCONFDIR=/etc/mysql
                    -DMYSQL_DATADIR=/var/lib/mysql
                    -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock
                    -DINSTALL_DOCDIR=share/doc/mysql
                    -DINSTALL_DOCREADMEDIR=share/doc/mysql
                    -DINSTALL_INCLUDEDIR=include/mysql
                    -DINSTALL_INFODIR=share/info
                    -DINSTALL_MANDIR=share/man
                    -DINSTALL_MYSQLSHAREDIR=share/mysql
                    -DINSTALL_PLUGINDIR=lib/mysql/plugin
                    -DINSTALL_SBINDIR=sbin
                    -DINSTALL_SCRIPTDIR=bin
                    -DINSTALL_SUPPORTFILESDIR=share/mysql
                    -DDEFAULT_CHARSET=utf8
                    -DDEFAULT_COLLATION=utf8_general_ci
                    -DENABLED_LOCAL_INFILE=ON
                    -DWITH_EXTRA_CHARSETS=complex
                    -DWITH_EMBEDDED_SERVER=ON
                    -DWITH_JEMALLOC=ON
                    -DWITH_PCRE=system
                    -DWITH_READLINE=ON
                    -DWITH_SSL=system
                    -DWITH_SYSTEMD=yes
                    -DWITH_ZLIB=system
                    -DCMAKE_EXE_LINKER_FLAGS="-ljemalloc")

configure_pre() {
  rm -rf ../${PKGDIR}/storage/tokudb

  #sed -i '/colpat.*%/s#"%"#(char *) &#g' ../${PKGDIR}/storage/connect/jdbconn.cpp
}

make_install_post() {
  rm -rf ${DEST}/usr/data ${DEST}/usr/mysql-test ${DEST}/usr/sql-bench
  rm -rf ${DEST}/usr/lib/mysql/plugin/daemon_example.ini ${DEST}/usr/lib/mysql/plugin/libdaemon_example.so

  install -dm755 ${DEST}/etc/mysql ${DEST}/etc/systemd/system/multi-user.target.wants
  install -dm755 ${DEST}/lib/systemd/system ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/etc/mysql/my.cnf << "EOF"
# Begin /etc/mysql/my.cnf

# The following options will be passed to all MySQL clients
[client]
#password       = your_password
port            = 3306
socket          = /run/mysqld/mysqld.sock

# The MySQL server
[mysqld]
port            = 3306
socket          = /run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
skip-external-locking
key_buffer_size = 16M
max_allowed_packet = 1M
sort_buffer_size = 512K
net_buffer_length = 16K
myisam_sort_buffer_size = 8M

# Don't listen on a TCP/IP port at all.
skip-networking

# required unique id between 1 and 2^32 - 1
server-id       = 1

# Uncomment the following if you are using BDB tables
#bdb_cache_size = 4M
#bdb_max_lock = 10000

# Uncomment the following if you are using InnoDB tables
#innodb_data_home_dir = /var/lib/mysql
#innodb_data_file_path = ibdata1:10M:autoextend
#innodb_log_group_home_dir = /var/lib/mysql
# You can set .._buffer_pool_size up to 50 - 80 %
# of RAM but beware of setting memory usage too high
#innodb_buffer_pool_size = 16M
#innodb_additional_mem_pool_size = 2M
# Set .._log_file_size to 25 % of buffer pool size
#innodb_log_file_size = 5M
#innodb_log_buffer_size = 8M
#innodb_flush_log_at_trx_commit = 1
#innodb_lock_wait_timeout = 50

[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash
# Remove the next comment character if you are not familiar with SQL
#safe-updates

[isamchk]
key_buffer = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[myisamchk]
key_buffer_size = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[mysqlhotcopy]
interactive-timeout

# End /etc/mysql/my.cnf
EOF

cat > ${DEST}/lib/systemd/system/mysqld.service << "EOF"
[Unit]
Description=MySQL Server
After=network.target

[Service]
Type=notify
User=mysql
Group=mysql
CapabilityBoundingSet=CAP_IPC_LOCK
ExecStart=/usr/sbin/mysqld
KillMode=process
KillSignal=SIGTERM
SendSIGKILL=no
Restart=on-abort
RestartSec=5s
UMask=007
PrivateTmp=true
LimitNOFILE=16364

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/mysqld.conf << "EOF"
d /run/mysqld 0755 mysql mysql -
EOF

  ln -sf /lib/systemd/system/mysqld.service ${DEST}/etc/systemd/system/multi-user.target.wants/mysqld.service
}

generate_install_override() {
cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group mysql > /dev/null || groupadd -g 40 mysql
getent passwd mysql > /dev/null || useradd -c "MySQL Server" -d /var/lib/mysql -g mysql -s /bin/false -u 40 mysql

systemctl daemon-reload

if [ ! -e /var/lib/mysql ]
then
   install -dm755 /var/lib/mysql
   /usr/bin/mysql_install_db --user=mysql --datadir=/var/lib/mysql --basedir=/usr
   chown -R mysql:mysql /var/lib/mysql
fi

if [ ! -e /run/mysqld ]
then
   install -m755 -d -o mysql -g mysql /run/mysqld
fi

if [ -e /run/systemd ]
then

  if [ ! -e /run/mysqld/mysqld.pid ];
  then
     systemctl start mysqld
  else
     systemctl restart mysqld
  fi

  echo "Upgrading MySQL tables, please enter root password:"
  /usr/bin/mysql_upgrade -u root -p

  systemctl restart mysqld

fi

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

  chmod 755 ${DEST}/INSTALL
}

. $(dirname $0)/master.sh
