#!/bin/bash -e

export PKGNAME=chromaprint
export PKGVER=1.3.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://bitbucket.org/acoustid/chromaprint/downloads/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DWITH_FFTW3=ON)

. $(dirname $0)/master.sh
