#!/bin/bash -e

export PKGNAME=libraw
export PKGVER=0.17.0
export PKGTAR=LibRaw-${PKGVER}.tar.gz
export PKGDIR=LibRaw-${PKGVER}
export PKGURL="http://www.libraw.org/data/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")

. $(dirname $0)/master.sh
