#!/bin/bash -e

export VER=1.8.1
export DEST=/binary/mate-themes-${VER}

pushd mate-themes-${VER}

./configure --prefix=/usr --enable-all-themes

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mate-themes-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for mate-icon-theme" && for dir in Fog Quid ; do /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/${dir} ; done
EOF

chmod 755 ${DEST}/INSTALL
