#!/bin/bash -e

export VER=1.1.2
export DEST=/binary/qrupdate-${VER}

pushd qrupdate-${VER}

make solib PREFIX=/usr -j4
make install PREFIX=/usr DESTDIR=${DEST}

popd

rm -rf qrupdate-${VER}

find ${DEST} -name "*.a" -delete

chmod 755 ${DEST}/usr/lib/*.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
