#!/bin/bash -e

export PKGNAME=xerces-c
export PKGVER=3.1.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://apache.osuosl.org/xerces/c/3/sources/${PKGTAR}"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
