#!/bin/bash -e

export VER=5.5.0
export DEST=/binary/qtwebchannel-${VER}

pushd qtwebchannel-opensource-src-${VER}

qmake

make -j4

find . -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;

make install INSTALL_ROOT=${DEST}

find ${DEST}/usr/lib/*.prl -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

popd

rm -rf qtwebchannel-opensource-src-${VER}

rm -rf ${DEST}/usr/lib/*.la

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    mkdir -p usr/lib/debug/$(dirname ${BUILD_BINARY})
    objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
    strip --strip-unneeded ${BUILD_BINARY}
    objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
