#!/bin/bash -e

export PKGNAME=portaudio
export PKGVER=19_20140130
export PKGTAR=pa_stable_v${PKGVER}.tgz
export PKGURL="http://www.portaudio.com/archives/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export PKGDIR=${PKGNAME}
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--enable-cxx)
export CONFIGURE_FLAGS_32=(--enable-cxx)

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

. $(dirname $0)/master.sh
