#!/bin/bash -e

export VER=1.10.0
export DEST=/binary/mate-icon-theme-${VER}

pushd mate-icon-theme-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mate-icon-theme-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for mate-icon-theme" && for dir in mate menta ; do /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/${dir} ; done
EOF

chmod 755 ${DEST}/INSTALL
