#!/bin/bash -e

export PKGNAME=opus
export PKGVER=1.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://downloads.xiph.org/releases/opus/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-custom-modes)

. $(dirname $0)/master.sh
