#!/bin/bash -e

export PKGNAME=lsof
export PKGVER=4.89
export PKGTAR=${PKGNAME}_${PKGVER}.tar.bz2
export PKGDIR=${PKGNAME}_${PKGVER}_src
export PKGURL="ftp://sunsite.ualberta.ca/pub/Mirror/lsof/lsof_4.89.tar.bz2"
export MAKE_JOBS_FLAGS="-j4"

post_extract_action() {
  bsdtar xf lsof_${PKGVER}/lsof_${PKGVER}_src.tar
  rm -rf lsof_${PKGVER}
}

configure_override() {
  export LSOF_CC="${CC}"

  ./Configure -n linux

  sed -i "/DEBUG/s:-O:${CFLAGS}:" Makefile

  unset CFLAGS
}

make_install_override() {
  install -Dm755 lsof ${DEST}/usr/bin/lsof
  install -Dm644 lsof.8 ${DEST}/usr/share/man/man8/lsof.8
}

. $(dirname $0)/master.sh
