#!/bin/bash -e

export VER=0.2.4
export DEST=/binary/libtirpc-${VER}

pushd libtirpc-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/libtirpc-remove-nis.patch

autoreconf -fi

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --disable-gssapi

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libtirpc-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/lib

mv ${DEST}/usr/lib/libtirpc.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libtirpc.so) ${DEST}/usr/lib/libtirpc.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL

