#!/bin/bash -e

export VER=2.84
export DEST=/binary/transmission-${VER}

pushd transmission-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --without-gtk

make -j4
make install DESTDIR=${DEST}

install -Dm644 daemon/transmission-daemon.service ${DEST}/lib/systemd/system/transmission-daemon.service

pushd qt

qmake-qt5 "QMAKE_CFLAGS+=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" "QMAKE_CXXFLAGS+=-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"
make -j4
make install INSTALL_ROOT=${DEST}/usr

install -Dm644 transmission-qt.desktop ${DEST}/usr/share/applications/transmission-qt.desktop

for icons in icons/hicolor/*
do
   install -dm755 ${DEST}/usr/share/icons/hicolor/$(basename ${icons})/apps
   install -m644 ${icons}/* ${DEST}/usr/share/icons/hicolor/$(basename ${icons})/apps
done

popd

popd

rm -rf transmission-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
