#!/bin/bash -e

export VER=0.9.3
export DEST=/binary/libomxil-bellagio-${VER}

pushd libomxil-bellagio-${VER}
  patch -Np1 -i /media/ntfs/Other/Linux/patches/libomxil-bellagio-fixes.patch
  autoreconf -fi
popd

cp -a libomxil-bellagio-${VER} libomxil-bellagio-${VER}-32

pushd libomxil-bellagio-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr --disable-static

make -j4
make install DESTDIR=${DEST}

popd

pushd libomxil-bellagio-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-static

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr
mv dest/usr/bin/omxregister-bellagio ${DEST}/usr/bin/omxregister-bellagio-32

popd

rm -rf libomxil-bellagio-${VER} libomxil-bellagio-${VER}-32

rm -rf ${DEST}/usr/share/doc

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
