#!/bin/bash -e

export VER=3.60
export DEST=/binary/iso-codes-${VER}

pushd iso-codes-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf iso-codes-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
