#!/bin/bash -e

export VER=5.1.1
export DEST=/binary/plasma-workspace-${VER}

pushd plasma-workspace-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr             \
      -DCMAKE_BUILD_TYPE=Release              \
      -DSYSCONF_INSTALL_DIR=/etc              \
      -DLIB_INSTALL_DIR=lib                   \
      -DBUILD_TESTING=OFF                     \
      -DQML_INSTALL_DIR=lib/qt5/qml           \
      -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins \
      -DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
      -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
      -Wno-dev

make -j4
make install DESTDIR=${DEST}

popd

rm -rf plasma-workspace-${VER}

sed -i "s:qtpaths:&-qt5:g" ${DEST}/usr/bin/startkde

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
