#!/bin/bash -e

export PKGNAME=alsa-lib
export PKGVER=1.1.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="ftp://ftp.alsa-project.org/pub/lib/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS_32=(--disable-python)

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
