#!/bin/bash -e

export PKGNAME=tiff
export PKGVER=4.0.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://download.osgeo.org/libtiff/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done\n"
                    "cp -rf --remove-destination usr/share/man/man3 /usr/share/man")

. $(dirname $0)/master.sh
