#!/bin/bash -e

export VER=6.4
export DEST=/binary/smartmontools-${VER}

pushd smartmontools-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-drivedb  \
            --with-systemdsystemunitdir=/lib/systemd/system

make -j4

sed -e "s:sysconfig/smartmontools:default/smartd:" \
    -e "s:smartd_opts:SMARTD_OPTS:"                \
    -e "/syslog.target/d" -i smartd.service

make install DESTDIR=${DEST}

popd

rm -rf smartmontools-${VER}

rm -rf ${DEST}/usr/share/doc

mkdir -p ${DEST}/etc/default

cat > ${DEST}/etc/default/smartd << "EOF"
# Additional options to pass to smartd command line
SMARTD_OPTS=
EOF

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
