#!/bin/bash -e

export PKGNAME=php
export PKGVER=7.0.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.php.net/distributions/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export PATCHES_LIST=("php-configure.patch" "phpdb6.patch")
export MAKE_INSTALL_FLAGS="INSTALL_ROOT=\${DEST}"
export POSTINST_TRIGGER=("if [ ! -e /etc/php/php.ini ]" "then" "  cp -r /etc/php/php.ini.dist /etc/php/php.ini" "fi")

export EXTENSION_DIR=/usr/lib/php/modules
export PEAR_INSTALLDIR=/usr/share/pear

export CONFIGURE_FLAGS=(--sysconfdir=/etc/php
                        --libdir=/usr/lib/php
                        --sbindir=/usr/sbin
                        --disable-rpath
                        --enable-cli
                        --enable-embed=shared
                        --enable-fpm
                        --with-fpm-user=httpd
                        --with-fpm-group=httpd
                        --with-fpm-systemd
                        --with-fpm-acl
                        --enable-phpdbg
                        --enable-cgi
                        --with-layout=GNU
                        --with-config-file-path=/etc/php
                        --with-config-file-scan-dir=/etc/php/conf.d
                        --with-openssl
                        --with-pcre-regex=/usr
                        --with-sqlite3=shared,/usr
                        --with-zlib
                        --enable-bcmath=shared
                        --with-bz2=shared
                        --enable-calendar=shared
                        --with-curl=shared
                        --enable-dba=shared
                        --with-gdbm
                        --with-db4=/usr
                        --with-enchant=shared,/usr
                        --enable-exif=shared
                        --enable-ftp=shared
                        --with-gd=shared,/usr
                        --with-freetype-dir=/usr
                        --enable-gd-native-ttf
                        --with-gettext=shared
                        --with-gmp=shared
                        --with-mhash
                        --with-iconv=shared
                        --with-imap=shared
                        --with-kerberos=/usr
                        --with-imap-ssl
                        --enable-intl=shared
                        --with-ldap=shared
                        --with-ldap-sasl
                        --enable-mbstring
                        --with-mcrypt=shared
                        --with-mysql-sock=/run/mysqld/mysqld.sock
                        --with-mysqli=shared,mysqlnd
                        --with-unixODBC=shared,/usr
                        --enable-pcntl
                        --with-pdo-mysql=shared,mysqlnd
                        --with-pdo-odbc=shared,unixODBC,/usr
                        --with-pdo-pgsql=shared
                        --with-pdo-sqlite=shared,/usr
                        --with-pgsql=shared
                        --with-pspell=shared
                        --with-readline
                        --enable-shmop=shared
                        --enable-soap=shared
                        --enable-sockets=shared
                        --enable-sysvmsg=shared
                        --enable-sysvsem=shared
                        --enable-sysvshm=shared
                        --with-tidy=shared
                        --with-xmlrpc=shared
                        --with-xsl=shared
                        --enable-zip=shared
                        --with-libzip
                        --with-pear
                        --enable-zend-signals)

configure_pre() {
  sed -i "s#.default##g" sapi/fpm/Makefile.frag

  sed -i 's#;pid =.*#pid = /run/php-fpm/php-fpm.pid#' sapi/fpm/php-fpm.conf.in
  sed -i 's#;error_log =.*#error_log = syslog#' sapi/fpm/php-fpm.conf.in

  for f in owner group mode ; do sed -i "s#;listen.${f}#listen.${f}#" sapi/fpm/www.conf.in ; done

  sed -i 's#syslog.target ##g' sapi/fpm/php-fpm.service.in
  sed -i 's#@localstatedir@/run/#/run/php-fpm/#g' sapi/fpm/php-fpm.service.in

  sed -i "s#buffio.h#tidy&#g" ext/tidy/tidy.c
  sed -i "s#-lstdc++ ##g" configure
}

make_install_post() {
  rm -rf ${DEST}/var ${DEST}/{,usr/share/pear/}.{channels,depdb,depdblock,filemap,lock,registry}

  install -Dm644 sapi/fpm/php-fpm.service ${DEST}/lib/systemd/system/php-fpm.service

  install -m644 /media/ntfs/Other/Linux/php.ini ${DEST}/etc/php/php.ini.dist

  install -dm755 ${DEST}/etc/systemd/system/multi-user.target.wants ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/usr/lib/tmpfiles.d/php-fpm.conf << "EOF"
d /run/php-fpm 755 root root
EOF

  ln -sf /lib/systemd/system/php-fpm.service ${DEST}/etc/systemd/system/multi-user.target.wants/php-fpm.service
}

. $(dirname $0)/master.sh
