#!/bin/bash -e

export PKGNAME=gmp
export PKGVER=6.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGDIR=${PKGNAME}-${PKGVER}
export PKGURL="https://ftp.gnu.org/gnu/gmp/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export DEBUG_BUILD=1
export CONFIGURE_FLAGS=(--enable-cxx
                        --build=x86_64-unknown-linux-gnu
                        --host=x86_64-unknown-linux-gnu
                        --target=x86_64-unknown-linux-gnu)

. $(dirname $0)/master.sh
