#!/bin/bash -e

export PKGNAME=osgearth
export PKGVER=2.8
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGDIR=${PKGNAME}-${PKGNAME}-${PKGVER}
export PKGURL="https://github.com/gwaldron/osgearth/archive/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export CMAKE_FLAGS=(-DLIB_POSTFIX="")

configure_pre() {
  sed -i "/FIND_PACKAGE(GEOS)/d" ../${PKGDIR}/CMakeLists.txt
}

. $(dirname $0)/master.sh
