#!/bin/bash -e

export PKGNAME=libnotify
export PKGVER=0.7.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://download.gnome.org/sources/libnotify/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
