#!/bin/bash -e

export VER=1.4rc5
export PKGVER=1.4.0
export DEST=/binary/aalib-${VER}

pushd aalib-${PKGVER}

sed -i -e '/AM_PATH_AALIB,/s/AM_PATH_AALIB/[&]/' aalib.m4

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr     \
            --disable-static  \
            --infodir=/usr/share/info \
            --mandir=/usr/share/man

make -j4
make install DESTDIR=${DEST}

popd

rm -rf aalib-${PKGVER}

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/info/dir
gzip -9 ${DEST}/usr/share/info/*

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

cp -rf --remove-destination usr/bin/aalib-config /usr/bin

cp -rf --remove-destination usr/share/aclocal /usr/share
cp -rf --remove-destination usr/share/man/man3 /usr/share/man

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
