#!/bin/bash -e

export PKGNAME=startup-notification
export PKGVER=0.12
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.freedesktop.org/software/startup-notification/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
