#!/bin/bash -e

export VER=0.7.3
export DEST=/binary/python-alabaster-${VER}

cp -a alabaster-${VER} alabaster-${VER}-3

pushd alabaster-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd alabaster-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf alabaster-${VER} alabaster-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
