#!/bin/bash -e

export VER=0.63.0
export DEST=/binary/python-logilab-common-${VER}

cp -a logilab-common-${VER} logilab-common-${VER}-3

pushd logilab-common-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

mv ${DEST}/usr/bin/pytest{,3}

popd

pushd logilab-common-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf logilab-common-${VER} logilab-common-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
