#!/bin/bash -e

export VER=6.0
export PKGVER=60
export DEST=/binary/unzip-${VER}

pushd unzip${PKGVER}

sed -i -e 's/CFLAGS="-O -Wall/& -DNO_LCHMOD -march=native -mtune=native -O2 -pipe -fstack-protector-strong /' unix/Makefile

make -f unix/Makefile -j4 linux_noasm
make -f unix/Makefile prefix=${DEST}/usr MANDIR=${DEST}/usr/share/man/man1 install

popd

rm -rf unzip${PKGVER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
