#!/bin/bash -e

export VER=1.4.3
export DEST=/binary/python-pylint-${VER}

cp -a pylint-${VER} pylint-${VER}-3

pushd pylint-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

for file in ${DEST}/usr/bin/*
do
  mv ${file} ${file}3
done

popd

pushd pylint-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf pylint-${VER} pylint-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
