#!/bin/bash -e

export PKGNAME=babl
export PKGVER=0.1.14
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://download.gimp.org/pub/babl/${PKGVER:0:3}/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
