#!/bin/bash -e

export PKGNAME=transmission
export PKGVER=2.92
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download-origin.transmissionbt.com/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  sed -i "s:libsystemd-daemon:libsystemd:g" configure
}

make_install_post() {
  install -Dm644 daemon/transmission-daemon.service ${DEST}/lib/systemd/system/transmission-daemon.service
}

. $(dirname $0)/master.sh
