#!/bin/bash -e

export PKGNAME=x264
export PKGVER=20160720
export PKGTAR=${PKGNAME}-snapshot-${PKGVER}-2245.tar.bz2
export PKGDIR=${PKGNAME}-snapshot-${PKGVER}-2245
export PKGURL="http://download.videolan.org/pub/videolan/x264/snapshots/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

configure_override() {
  ./configure --prefix=/usr    \
              --enable-shared  \
              --system-libx264
}

configure_override_32() {
  ./configure --prefix=/usr       \
              --libdir=/usr/lib32 \
              --enable-shared     \
              --disable-cli       \
              --host=i686-linux-gnu
}

. $(dirname $0)/master.sh
