#!/bin/bash -e

export PKGVER=30
export VER=${PKGVER}pre9
export DEST=/binary/wireless_tools-${VER}

pushd wireless_tools.${PKGVER}

sed -i "s:BUILD_STATIC:# &:" Makefile
sed -i "s:-Os:& -march=native -mtune=native -O2 -pipe -fstack-protector-strong :g" Makefile

make
make PREFIX=${DEST}/usr INSTALL_MAN=${DEST}/usr/share/man install

popd

rm -rf wireless_tools.${PKGVER}

chmod 755 ${DEST}/usr/lib/libiw.so

install -dm755 ${DEST}/lib

mv ${DEST}/usr/sbin ${DEST}
mv ${DEST}/usr/lib/libiw.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libiw.so) ${DEST}/usr/lib/libiw.so

rm -rf ${DEST}/usr/share/man/cs ${DEST}/usr/share/man/fr*

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
