#!/bin/bash -e

export VER=1.6.0
export DEST=/binary/wayland-${VER}

cp -a wayland-${VER} wayland-${VER}-32

pushd wayland-${VER}

CFLAGS="-march=native -mtune=native -g -O2"   \
CXXFLAGS="-march=native -mtune=native -g -O2" \
./configure --prefix=/usr    \
            --disable-static \
            --disable-documentation

make -j4
make install DESTDIR=${DEST}

popd

pushd wayland-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -g -O2"   \
CXXFLAGS="-march=native -mtune=native -g -O2" \
./configure --prefix=/usr       \
            --libdir=/usr/lib32 \
            --disable-static    \
            --disable-documentation

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf wayland-${VER} wayland-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
mkdir -p usr/lib/debug/`dirname ${BUILD_BINARY}`
objcopy --only-keep-debug ${BUILD_BINARY} usr/lib/debug/${BUILD_BINARY}
strip --strip-unneeded ${BUILD_BINARY}
objcopy --add-gnu-debuglink=usr/lib/debug/${BUILD_BINARY} ${BUILD_BINARY}
esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
