#!/bin/bash -e

export VER=1.1.1
export DEST=/binary/xbitmaps-${VER}

pushd xbitmaps-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf xbitmaps-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
