#!/bin/bash -e

case $(basename $0) in
  buildadwaita-icon-theme )
    export PKGNAME=adwaita-icon-theme
    export PKGVER=3.22.0
    export NO_STRIP=1
    export POSTINST_TRIGGER=("[ -x /usr/bin/gtk-update-icon-cache ] && echo \"Processing triggers for adwaita-icon-theme\" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/Adwaita")
  ;;
  buildcaribou )
    export PKGNAME=caribou
    export PKGVER=0.4.21
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  builddconf )
    export PKGNAME=dconf
    export PKGVER=0.26.0
    export POSTINST_TRIGGER=("[ -x /usr/bin/gio-querymodules ] && echo \"Processing triggers for gio-2.0\" && /usr/bin/gio-querymodules /usr/lib/gio/modules")
    make_install_post() {
      export SPACE_ADDED=1
    }
  ;;
  buildevolution-data-server )
    export PKGNAME=evolution-data-server
    export PKGVER=3.22.0
    export CONFIGURE_FLAGS=(--disable-uoa
                            --with-krb5=/usr
                            --with-openldap
                            --enable-vala-bindings)
  ;;
  buildfolks )
    export PKGNAME=folks
    export PKGVER=0.11.3
    export CONFIGURE_FLAGS=(--disable-fatal-warnings)
  ;;
  buildgcr )
    export PKGNAME=gcr
    export PKGVER=3.20.0
  ;;
  buildgdm )
    export PKGNAME=gdm
    export PKGVER=3.22.0
    export KEEP_EMPTY_DIRS=1
    export CONFIGURE_FLAGS=(--enable-gdm-xsession --without-plymouth --with-default-pam-config=lfs)
    export POSTINST_TRIGGER=("getent group gdm > /dev/null || groupadd -g 21 gdm"
                             "getent passwd gdm > /dev/null || useradd -c \"GDM Daemon Owner\" -d /var/lib/gdm -g gdm -s /bin/false -u 21 gdm\n"
                             "if [ ! -e /var/log/gdm ]" "then"
                             "  install -dm755 -o root -g root /var/log/gdm" "fi\n"
                             "if [ ! -e /var/lib/gdm ]" "then"
                             "  install -dm1770 -o root -g gdm /var/lib/gdm" "fi\n"
                             "if [ ! -e /var/cache/gdm ]" "then"
                             "  install -dm1755 -o root -g gdm /var/cache/gdm" "fi\n"
                             "if [ ! -e /run/gdm ]" "then"
                             "  install -dm711 -o root -g gdm /run/gdm"
                             "  install -dm755 -o gdm  -g gdm /run/gdm/greeter" "fi")
    make_install_post() {
      rm -rf ${DEST}/var
      sed -i "/user = gdm/d" ${DEST}/etc/pam.d/gdm-launch-environment
    }
  ;;
  buildgeocode-glib )
    export PKGNAME=geocode-glib
    export PKGVER=3.20.1
  ;;
  buildgexiv2 )
    export PKGNAME=gexiv2
    export PKGVER=0.10.3
    export CONFIGURE_FLAGS=(--enable-introspection)
    configure_pre() {
      sed -i "s:-Wl,-lstdc++::g" Makefile.in
    }
  ;;
  buildgfbgraph )
    export PKGNAME=gfbgraph
    export PKGVER=0.2.3
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgjs )
    export PKGNAME=gjs
    export PKGVER=1.46.0
    make_install_post() {
      rm -rf ${DEST}/usr/libexec
    }
  ;;
  buildglib-networking )
    export PKGNAME=glib-networking
    export PKGVER=2.50.0
    export POSTINST_TRIGGER=("[ -x /usr/bin/gio-querymodules ] && echo \"Processing triggers for gio-2.0\" && /usr/bin/gio-querymodules /usr/lib/gio/modules")
  ;;
  buildgmime )
    export PKGNAME=gmime
    export PKGVER=2.6.20
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--enable-smime)
  ;;
  buildgnome-autoar )
    export PKGNAME=gnome-autoar
    export PKGVER=0.1.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgnome-backgrounds )
    export PKGNAME=gnome-backgrounds
    export PKGVER=3.22.0
    export KEEP_STATIC=1
    export NO_STRIP=1
  ;;
  buildgnome-bluetooth )
    export PKGNAME=gnome-bluetooth
    export PKGVER=3.18.3
  ;;
  buildgnome-control-center )
    export PKGNAME=gnome-control-center
    export PKGVER=3.22.0
  ;;
  buildgnome-desktop )
    export PKGNAME=gnome-desktop
    export PKGVER=3.22.0
    export CONFIGURE_FLAGS=(--with-gnome-distributor=Krejzi)
  ;;
  buildgnome-keyring )
    export PKGNAME=gnome-keyring
    export PKGVER=3.20.0
    export POSTINST_TRIGGER=("setcap cap_ipc_lock=ep /usr/bin/gnome-keyring-daemon")
    export CONFIGURE_FLAGS=(--with-pam-dir=/lib/security)
  ;;
  buildgnome-menus )
    export PKGNAME=gnome-menus
    export PKGVER=3.13.3
  ;;
  buildgnome-online-accounts )
    export PKGNAME=gnome-online-accounts
    export PKGVER=3.22.0
    export CONFIGURE_FLAGS=(--enable-kerberos --disable-compile-warnings)
  ;;
  buildgnome-online-miners )
    export PKGNAME=gnome-online-miners
    export PKGVER=3.22.0
  ;;
  buildgnome-session )
    export PKGNAME=gnome-session
    export PKGVER=3.22.0
  ;;
  buildgnome-settings-daemon )
    export PKGNAME=gnome-settings-daemon
    export PKGVER=3.22.0
    export MAKE_INSTALL_FLAGS="udevrulesdir=/lib/udev/rules.d"
  ;;
  buildgnome-shell )
    export PKGNAME=gnome-shell
    export PKGVER=3.22.0
    make_install_post() {
      install -dm755 ${DEST}/usr/lib/gnome-shell/mozilla

      mv ${DEST}/usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so ${DEST}/usr/lib/gnome-shell/mozilla
      ln -sf ../../gnome-shell/mozilla/libgnome-shell-browser-plugin.so ${DEST}/usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
    }
  ;;
  buildgnome-shell-extensions )
    export PKGNAME=gnome-shell-extensions
    export PKGVER=3.22.0
    export KEEP_STATIC=1
    export NO_STRIP=1
  ;;
  buildgnome-themes-standard )
    export PKGNAME=gnome-themes-standard
    export PKGVER=3.20.2
    export POSTINST_TRIGGER=("[ -x /usr/bin/gtk-update-icon-cache ] && echo \"Processing triggers for hicolor-icon-theme\" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/HighContrast")
  ;;
  buildgnome-user-docs )
    export PKGNAME=gnome-user-docs
    export PKGVER=3.22.0
    export KEEP_STATIC=1
    export NO_STRIP=1
  ;;
  buildgnome-user-share )
    export PKGNAME=gnome-user-share
    export PKGVER=3.18.3
    export CONFIGURE_FLAGS=(--with-httpd=/usr/sbin/httpd --with-modules-path=/usr/lib/httpd/modules)
  ;;
  buildgnome-video-effects )
    export PKGNAME=gnome-video-effects
    export PKGVER=0.4.1
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export KEEP_STATIC=1
    export NO_STRIP=1
  ;;
  buildgom )
    export PKGNAME=gom
    export PKGVER=0.3.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgrilo )
    export PKGNAME=grilo
    export PKGVER=0.3.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--disable-compile-warnings)
  ;;
  buildgrilo-plugins )
    export PKGNAME=grilo-plugins
    export PKGVER=0.3.3
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--disable-compile-warnings)
  ;;
  buildgsettings-desktop-schemas )
    export PKGNAME=gsettings-desktop-schemas
    export PKGVER=3.22.0
    export KEEP_STATIC=1
    export NO_STRIP=1
  ;;
  buildgsound )
    export PKGNAME=gsound
    export PKGVER=1.0.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgspell )
    export PKGNAME=gspell
    export PKGVER=1.2.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildgtksourceview )
    export PKGNAME=gtksourceview
    export PKGVER=3.22.0
  ;;
  buildgtk-vnc )
    export PKGNAME=gtk-vnc
    export PKGVER=0.6.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--with-gtk=3.0 --enable-vala)
  ;;
  buildgvfs )
    export PKGNAME=gvfs
    export PKGVER=1.30.0
    export POSTINST_TRIGGER=("[ -x /usr/bin/gio-querymodules ] && echo \"Processing triggers for gio-2.0\" && /usr/bin/gio-querymodules /usr/lib/gio/modules")
    make_install_post() {
      export SPACE_ADDED=1
    }
  ;;
  buildjson-glib )
    export PKGNAME=json-glib
    export PKGVER=1.2.2
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildlibchamplain )
    export PKGNAME=libchamplain
    export PKGVER=0.12.14
  ;;
  buildlibgdata )
    export PKGNAME=libgdata
    export PKGVER=0.17.6
  ;;
  buildlibgee )
    export PKGNAME=libgee
    export PKGVER=0.18.0
  ;;
  buildlibgepub )
    export PKGNAME=libgepub
    export PKGVER=0.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER}/${PKGTAR}"
  ;;
  buildlibgnome-keyring )
    export PKGNAME=libgnome-keyring
    export PKGVER=3.12.0
  ;;
  buildlibgrss )
    export PKGNAME=libgrss
    export PKGVER=0.7.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildlibgsf )
    export PKGNAME=libgsf
    export PKGVER=1.14.40
  ;;
  buildlibgtop )
    export PKGNAME=libgtop
    export PKGVER=2.34.1
  ;;
  buildlibgudev )
    export PKGNAME=libgudev
    export PKGVER=230
  ;;
  buildlibgweather )
    export PKGNAME=libgweather
    export PKGVER=3.20.3
  ;;
  buildlibgxps )
    export PKGNAME=libgxps
    export PKGVER=0.2.4
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--disable-compile-warnings)
  ;;
  buildlibmediaart )
    export PKGNAME=libmediaart
    export PKGVER=1.9.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--disable-qt)
  ;;
  buildlibpeas )
    export PKGNAME=libpeas
    export PKGVER=1.20.0
    make_install_post() {
      rm -rf ${DEST}/usr/bin ${DEST}/usr/lib/peas-demo
    }
  ;;
  buildlibrsvg )
    export PKGNAME=librsvg
    export PKGVER=2.40.16
    export POSTINST_TRIGGER=("[ -x /usr/bin/gdk-pixbuf-query-loaders ] && echo \"Processing triggers for gdk-pixbuf-2.0\" && /usr/bin/gdk-pixbuf-query-loaders --update-cache")
    export CONFIGURE_FLAGS=(--enable-vala)
    make_install_post() {
      export SPACE_ADDED=1
    }
  ;;
  buildlibsecret )
    export PKGNAME=libsecret
    export PKGVER=0.18.5
  ;;
  buildlibsoup )
    export PKGNAME=libsoup
    export PKGVER=2.56.0
    export CONFIGURE_FLAGS=(--disable-tls-check)
  ;;
  buildlibwnck )
    export PKGNAME=libwnck
    export PKGVER=3.20.1
  ;;
  buildlibzapojit )
    export PKGNAME=libzapojit
    export PKGVER=0.0.3
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildmutter )
    export PKGNAME=mutter
    export PKGVER=3.22.0
    export CONFIGURE_FLAGS=(--enable-compile-warnings=minimum
                            --disable-maintainer-flags
                            --disable-Werror)
  ;;
  buildrest )
    export PKGNAME=rest
    export PKGVER=0.8.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
  ;;
  buildtotem-pl-parser )
    export PKGNAME=totem-pl-parser
    export PKGVER=3.10.7
  ;;
  buildtracker )
    export PKGNAME=tracker
    export PKGVER=1.10.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
    export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:3}/${PKGTAR}"
    export CONFIGURE_FLAGS=(--disable-miner-firefox --disable-miner-thunderbird)
  ;;
  buildvte )
    export PKGNAME=vte
    export PKGVER=0.46.0
    export CONFIGURE_FLAGS=(--enable-introspection)
    make_install_post() {
      rm -rf ${DEST}/etc
    }
  ;;
  buildyelp-xsl )
    export PKGNAME=yelp-xsl
    export PKGVER=3.20.1
    export NO_STRIP=1
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}

if [ -z ${PKGURL} ]
then
  export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
fi

. $(dirname $0)/master.sh
