#!/bin/bash -e

export VER=1.6.7
export DEST=/binary/cryptsetup-${VER}

pushd cryptsetup-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr    \
            --disable-static \
            --enable-cryptsetup-reencrypt

make -j4
make install DESTDIR=${DEST}

popd

rm -rf cryptsetup-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/lib

mv ${DEST}/usr/sbin ${DEST}/
mv ${DEST}/usr/lib/libcryptsetup.so.* ${DEST}/lib

ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libcryptsetup.so) ${DEST}/usr/lib/libcryptsetup.so

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
