#!/bin/bash -e

export PKGNAME=colord
export PKGVER=1.3.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://www.freedesktop.org/software/colord/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1

export POSTINST_TRIGGER=("getent group colord > /dev/null || groupadd -g 71 colord"
                         "getent passwd colord > /dev/null || useradd -c \"Color Daemon Owner\" -d /var/lib/colord -u 71 -g colord -s /bin/false colord\n"
                         "chown -R colord:colord /var/lib/colord")

export CONFIGURE_FLAGS=(--with-daemon-user=colord
                        --disable-argyllcms-sensor
                        --disable-bash-completion
                        --disable-sane
                        --enable-vala)

. $(dirname $0)/master.sh
