#!/bin/bash -e

export PKGNAME=libvdpau
export PKGVER=1.1.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://people.freedesktop.org/~aplattner/vdpau/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

. $(dirname $0)/master.sh
