#!/bin/bash -e

export VER=3.16.2
export DEST=/binary/gnome-themes-standard-${VER}

cp -a gnome-themes-standard-${VER} gnome-themes-standard-${VER}-32

pushd gnome-themes-standard-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

pushd gnome-themes-standard-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr  --libdir=/usr/lib32

make -C themes/Adwaita/gtk-2.0 libadwaita.la
make -C themes/Adwaita/gtk-2.0 install-engineLTLIBRARIES DESTDIR=${DEST}

popd

rm -rf gnome-themes-standard-${VER} gnome-themes-standard-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/HighContrast
EOF

chmod 755 ${DEST}/INSTALL
