#!/bin/bash -e

export VER=1.8.12
export DEST=/binary/dbus-${VER}

cp -a dbus-${VER} dbus-${VER}-32

pushd dbus-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr                         \
            --sysconfdir=/etc                     \
            --localstatedir=/var                  \
            --disable-static                      \
            --enable-systemd                      \
            --with-console-auth-dir=/run/console/ \
            --with-systemdsystemunitdir=/lib/systemd/system

make -j4
make install DESTDIR=${DEST}

popd

pushd dbus-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr                  \
            --sysconfdir=/etc              \
            --localstatedir=/var           \
            --libdir=/usr/lib32            \
            --disable-static               \
            --disable-systemd              \
            --without-x

make -C dbus libdbus-1.la -j4
make -C dbus lib_LTLIBRARIES=libdbus-1.la \
     install-libLTLIBRARIES \
     install-dbusincludeHEADERS \
     install-nodist_dbusarchincludeHEADERS DESTDIR=${PWD}/dest

make install-pkgconfigDATA DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf dbus-${VER} dbus-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/usr/share/doc ${DEST}/var/run

mv ${DEST}/usr/lib/libdbus-1.so.* ${DEST}/lib
ln -sf ../../lib/$(readlink ${DEST}/usr/lib/libdbus-1.so) ${DEST}/usr/lib/libdbus-1.so

ln -sf /etc/machine-id ${DEST}/var/lib/dbus

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

chgrp messagebus /usr/libexec/dbus-daemon-launch-helper
chmod 4754 /usr/libexec/dbus-daemon-launch-helper

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
