#!/bin/bash -e

export PKGNAME=liblqr
export PKGVER=0.4.2
export PKGTAR=${PKGNAME}-1-${PKGVER}.tar.bz2
export PKGDIR=${PKGNAME}-1-${PKGVER}
export PKGURL="http://liblqr.wikidot.com/local--files/en:download-page/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
