#!/bin/bash -e

export PKGNAME=gdb
export PKGVER=7.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/gdb/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--with-system-readline
                        --without-guile
                        --with-system-gdbinit=/etc/gdb/gdbinit)

export MAKE_INSTALL_FLAGS="-C gdb"

. $(dirname $0)/master.sh
