#!/bin/bash -e

export PKGNAME=libatomic_ops
export PKGVER=7.4.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.ivmaisoft.com/_bin/atomic_ops/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--enable-shared)

make_install_post() {
  rm -rf ${DEST}/usr/share
}

. $(dirname $0)/master.sh
