#!/bin/bash -e

export PKGNAME=shadow
export PKGVER=4.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export MAKE_JOBS_FLAGS="-j4"

export POSTINST_TRIGGER=("chmod 4755 /bin/su /usr/bin/chage /usr/bin/chfn"
                         "chmod 4755 /usr/bin/chsh /usr/bin/expiry /usr/bin/gpasswd"
                         "chmod 4755 /usr/bin/newgidmap /usr/bin/newgrp"
                         "chmod 4755 /usr/bin/newuidmap /usr/bin/passwd\n"
                         "grpconv"
                         "pwconv")

export CONFIGURE_FLAGS=(--with-group-name-max-length=32)

if [ $1 ] && [ $1 == "gentarball" ]
then
  rm -rf shadow-${PKGVER}
  wget https://github.com/shadow-maint/shadow/archive/${PKGVER}.tar.gz -O - | bsdtar xfz -
  pushd shadow-${PKGVER}
    sed -i "s#SUBDIRS = .*#SUBDIRS =#g" man/Makefile.am
    sed -i "s#groups login#login#g" src/Makefile.am
    sed -i "/man1\/groups\.1/d" man/Makefile.am

    ./autogen.sh --without-selinux
    make dist-xz
    mv shadow-${PKGVER}.tar.xz ..
  popd
  rm -rf shadow-${PKGVER}

  exit 0
fi


configure_pre() {
  sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
         -e 's@/var/spool/mail@/var/mail@' etc/login.defs

  sed -i -e 's@PATH=/sbin:/bin:/usr/sbin:/usr/bin@&:/usr/local/sbin:/usr/local/bin@' \
         -e 's@PATH=/bin:/usr/bin@&:/usr/local/bin@' etc/login.defs
}

post_install_config() {
  for FUNCTION in FAIL_DELAY FAILLOG_ENAB \
                  LASTLOG_ENAB \
                  MAIL_CHECK_ENAB \
                  OBSCURE_CHECKS_ENAB \
                  PORTTIME_CHECKS_ENAB \
                  QUOTAS_ENAB \
                  CONSOLE MOTD_FILE \
                  FTMP_FILE NOLOGINS_FILE \
                  ENV_HZ PASS_MIN_LEN \
                  SU_WHEEL_ONLY \
                  CRACKLIB_DICTPATH \
                  PASS_CHANGE_TRIES \
                  PASS_ALWAYS_WARN \
                  CHFN_AUTH ENCRYPT_METHOD \
                  ENVIRON_FILE
  do
    sed -i "s/^${FUNCTION}/# &/" ${DEST}/etc/login.defs
  done

  sed -i 's/yes/no/' ${DEST}/etc/default/useradd

cat > ${DEST}/etc/pam.d/login << "EOF"
# Begin /etc/pam.d/login

auth	 requisite      pam_nologin.so
auth	 required       pam_securetty.so
auth	 optional       pam_faildelay.so delay=3000000
auth     optional       pam_group.so

auth     include        system-auth

account  required       pam_access.so
account	 include        system-account

password include        system-password

session  required       pam_env.so
session  required       pam_limits.so
session  optional       pam_lastlog.so
session  optional       pam_motd.so
session  optional       pam_mail.so standard

session	 include        system-session

# End /etc/pam.d/login
EOF

cat > ${DEST}/etc/pam.d/su << "EOF"
# Begin /etc/pam.d/su

auth	 sufficient     pam_rootok.so
auth	 include        system-auth

account  include        system-account

session  required       pam_env.so
session  optional       pam_mail.so nopen
session  include        system-session

# End /etc/pam.d/su
EOF

cat > ${DEST}/etc/pam.d/passwd << "EOF"
# Begin /etc/pam.d/passwd

password   include      system-password

# End /etc/pam.d/passwd
EOF

cat > ${DEST}/etc/pam.d/chage << "EOF"
# Begin /etc/pam.d/chage

auth     sufficient	pam_rootok.so

auth     include	system-auth
account  include	system-account
session  include	system-session

password required	pam_permit.so

# End /etc/pam.d/chage
EOF

  for PROGRAM in chfn chgpasswd chpasswd chsh groupadd groupdel \
                 groupmems groupmod newusers useradd userdel usermod
  do
    sed "s:chage:${PROGRAM}:g" ${DEST}/etc/pam.d/chage > ${DEST}/etc/pam.d/${PROGRAM}
  done
}

. $(dirname $0)/master.sh
