#!/bin/bash -e

export VER=3.19
export DEST=/binary/highlight-${VER}

pushd highlight-${VER}

make CFLAGS="-Wall -O2 -pipe -fstack-protector-strong -march=native -mtune=native -DNDEBUG" -j4
make CFLAGS="-Wall -O2 -pipe -fstack-protector-strong -march=native -mtune=native -DNDEBUG" -j4 gui

make install DESTDIR=${DEST}
make install-gui DESTDIR=${DEST}

popd

rm -rf highlight-${VER}

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
