#!/bin/bash -e

export VER=0.27.2
export DEST=/binary/npapi-sdk-${VER}

pushd npapi-sdk-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf npapi-sdk-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
