#!/bin/bash -e

export PKGNAME=libmypaint
export PKGVER=1.3.0-beta.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://github.com/mypaint/libmypaint/releases/download/v${PKGVER}/${PKGTAR}"
export MAKE_JOBS_FLAGS=-j4

. $(dirname $0)/master.sh
