#!/bin/bash -e

export VER=20120614
export DEST=/binary/mobile-broadband-provider-info-${VER}

pushd mobile-broadband-provider-info-${VER}

./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf mobile-broadband-provider-info-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
