#!/bin/bash -e

export VER=9.15
export DEST=/binary/ghostscript-${VER}

pushd ghostscript-${VER}

rm -rf cups/libs/ expat/ freetype/ ijs/ jpeg/ jpegxr/ lcms/ lcms2/ libpng/ openjpeg/ tiff/ zlib/

sed -i 's/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac configure

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr \
            --enable-dynamic \
            --with-ijs \
            --with-jbig2dec \
            --with-omni \
            --with-x \
            --with-drivers=ALL \
            --enable-fontconfig \
            --enable-freetype \
            --without-luratech \
            --without-omni \
            --with-system-libtiff \
            --disable-compile-inits \
            --disable-gtk \
            --with-fontpath=/usr/share/fonts/ghostscript:/usr/share/fonts/truetype:/usr/share/fonts/opentype

make all so SHARE_JPEG=1 SHARE_LIBPNG=1 SHARE_LIBTIFF=1 SHARE_ZLIB=1 SHARE_IJS=1 SHARE_EXPAT=1 WHICH_CMS=lcms2 \
            SHARE_LCMS=1 LCMS2DIR=/usr SHARE_JPX=1 SHARE_FT=1 -j4
make install soinstall DESTDIR=${DEST}

rm -rf ${DEST}/usr/share/man/de

rm -rf ${DEST}/usr/bin/*.sh
rm -rf ${DEST}/usr/bin/gsx

popd

rm -rf ghostscript-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
