#!/bin/bash -e

export VER=4.99.4
export SHLIBVER=4.99
export DEST=/binary/pulseaudio-${VER}

cp -a pulseaudio-${VER} pulseaudio-${VER}-32

pushd pulseaudio-${VER}

find . -name "Makefile.in" | xargs sed -i "s|(libdir)/@PACKAGE@|(libdir)/pulse|"

CFLAGS="-march=native -mtune=native -g -O2"   \
CXXFLAGS="-march=native -mtune=native -g -O2" \
./configure --prefix=/usr         \
            --sysconfdir=/etc     \
            --localstatedir=/var  \
            --libexecdir=/usr/lib \
            --disable-bluez4      \
            --disable-rpath       \
            --with-module-dir=/usr/lib/pulse/modules

make -j4
make install DESTDIR=${DEST}/pulseaudio bashcompletiondir=/usr/share/bash-completion/completions

# Disable autospawn
sed -e '/autospawn/iautospawn=no' -i ${DEST}/pulseaudio/etc/pulse/client.conf

# Speed up pulseaudio shutdown so that it exits immediately with
# the last user session (module-systemd-login keeps it alive)
sed -e '/exit-idle-time/iexit-idle-time=0'  -i ${DEST}/pulseaudio/etc/pulse/daemon.conf

# Disable cork-request module, can result in e.g. media players unpausing
# when there's a Skype call incoming
sed -e 's|/usr/bin/pactl load-module module-x11-cork-request|#&|' -i ${DEST}/pulseaudio/usr/bin/start-pulseaudio-x11

rm -rf ${DEST}/pulseaudio/etc/dbus-1

install -dm755 ${DEST}/libpulse/etc/pulse
install -dm755 ${DEST}/libpulse/usr/bin
install -dm755 ${DEST}/libpulse/usr/lib/pulse
install -dm755 ${DEST}/libpulse/usr/share/man/man1
install -dm755 ${DEST}/libpulse/usr/share/man/man5

_clientprogs="pacat pactl padsp pamon paplay parec parecord"
_clientmans="pacat pactl padsp paplay"
_clientlibs="libpulse-mainloop-glib libpulse-simple libpulse"
_clientpkglibs="libpulsecommon-${SHLIBVER}.so libpulsedsp.so"

mv ${DEST}/pulseaudio/etc/pulse/client.conf ${DEST}/libpulse/etc/pulse
mv ${DEST}/pulseaudio/usr/share/man/man5/pulse-client.conf.5 ${DEST}/libpulse/usr/share/man/man5

mv ${DEST}/pulseaudio/usr/include ${DEST}/libpulse/usr
mv ${DEST}/pulseaudio/usr/lib/cmake ${DEST}/libpulse/usr/lib
mv ${DEST}/pulseaudio/usr/lib/pkgconfig ${DEST}/libpulse/usr/lib
mv ${DEST}/pulseaudio/usr/share/vala ${DEST}/libpulse/usr/share

for file in ${_clientprogs}
do
  mv ${DEST}/pulseaudio/usr/bin/${file} ${DEST}/libpulse/usr/bin
done

for file in ${_clientmans}
do
  mv ${DEST}/pulseaudio/usr/share/man/man1/${file}.1 ${DEST}/libpulse/usr/share/man/man1
done

for file in ${_clientlibs}
do
  mv ${DEST}/pulseaudio/usr/lib/${file}.so* ${DEST}/libpulse/usr/lib
done

for file in ${_clientpkglibs}
do
  mv ${DEST}/pulseaudio/usr/lib/pulse/${file} ${DEST}/libpulse/usr/lib/pulse
done

popd

pushd pulseaudio-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

find . -name "Makefile.in" | xargs sed -i "s|(libdir)/@PACKAGE@|(libdir)/pulse|"

CFLAGS="-march=native -mtune=native -g -O2"   \
CXXFLAGS="-march=native -mtune=native -g -O2" \
./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --localstatedir=/var      \
            --libdir=/usr/lib32       \
            --libexecdir=/usr/lib32   \
            --disable-bluez4          \
            --disable-rpath           \
            --with-module-dir=/usr/lib/pulse/modules

_libs="libpulse.la libpulse-simple.la libpulse-mainloop-glib.la"
_pkglibs="libpulsecommon-${SHLIBVER}.la libpulsedsp.la"

make -C src ${_libs} ${_pkglibs} -j4

make -C src lib_LTLIBRARIES="${_libs}" pkglib_LTLIBRARIES="${_pkglibs}" install-libLTLIBRARIES install-pkglibLTLIBRARIES DESTDIR=${PWD}/dest
make install-pkgconfigDATA DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/libpulse/usr

popd

rm -rf pulseaudio-${VER} pulseaudio-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/pulseaudio/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

cat > ${DEST}/libpulse/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/pulseaudio/INSTALL ${DEST}/libpulse/INSTALL
