#!/bin/bash -e

export PKGVER=15.12.1
export MAKE_JOBS_FLAGS="-j4"
export CMAKE_BUILD=1
export KEEP_DOC=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

export CMAKE_FLAGS=(-DSYSCONF_INSTALL_DIR=/etc
                    -DLIB_INSTALL_DIR=lib
                    -DBUILD_TESTING=OFF
                    -DQML_INSTALL_DIR=lib/qt5/qml
                    -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins
                    -DECM_MKSPECS_INSTALL_DIR=/usr/lib/qt5/mkspecs/modules)

case $(basename $0) in
  buildkdepim )
    export PKGNAME=kdepim
  ;;
  buildkdepim-runtime )
    export PKGNAME=kdepim-runtime
  ;;
esac

export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.kde.org/stable/applications/${PKGVER}/src/${PKGTAR}"
export DEST=/binary/kdepim/${PKGNAME}-${PKGVER}

if [ ${PKGNAME} == "kdepim-runtime" ]
then
  configure_pre() {
    find ../${PKGDIR} -name "*.cpp" -exec grep -l "qDebug" {} \; | sort | uniq | while read f
    do
      sed -i "s:qDebug:qt_noop(); // &:g" ${f}
    done
  }
fi


. $(dirname $0)/master.sh
