#!/bin/bash -e

export BAEKMUK_VER=2.2
export CANTARELL_VER=0.0.17
export CM_UNICODE_VER=0.7.0
export DEJAVU_VER=2.35
export FREEFONT_VER=20120503
export GENTIUMBASIC_VER=110
export GENTIUMPLUS_VER=5.000
export HANNOM_VER=2005
export LIBERATION_VER=2.00.1
export MGOPEN_VER=1.1
export OPENDESKTOP_VER=1.4.2
export PARATYPE_VER=20140730
export SCHEHERAZADE_VER=2.100
export VLGOTHIC_VER=20141206

# Begin baekmuk

wget -c https://kldp.net/frs/download.php/1429/baekmuk-ttf-${BAEKMUK_VER}.tar.gz -O - | tar xfz -

export DEST=/binary/fonts-baekmuk-${BAEKMUK_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/baekmuk
install -m644 baekmuk-ttf-${BAEKMUK_VER}/ttf/*.ttf ${DEST}/usr/share/fonts/truetype/baekmuk

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/baekmuk
EOF

chmod 755 ${DEST}/INSTALL

rm -rf baekmuk-ttf-${BAEKMUK_VER}

# End baekmuk

# Begin cantarell

wget -c http://ftp.gnome.org/pub/gnome/sources/cantarell-fonts/0.0/cantarell-fonts-${CANTARELL_VER}.tar.xz -O - | tar xfJ -

export DEST=/binary/fonts-cantarell-${CANTARELL_VER}

pushd cantarell-fonts-${CANTARELL_VER}

./configure --prefix=/usr --with-fontdir=/usr/share/fonts/opentype/cantarell

make install DESTDIR=${DEST}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/opentype/cantarell
EOF

chmod 755 ${DEST}/INSTALL

popd

rm -rf cantarell-fonts-${CANTARELL_VER}

# End cantarell

# Begin cm-unicode

wget -c http://downloads.sourceforge.net/cm-unicode/cm-unicode-${CM_UNICODE_VER}-ttf.tar.xz -O - | tar xfJ -

export DEST=/binary/fonts-cm-unicode-${CM_UNICODE_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/cm-unicode
install -m644 cm-unicode-${CM_UNICODE_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/cm-unicode

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/cm-unicode
EOF

chmod 755 ${DEST}/INSTALL

rm -rf cm-unicode-${CM_UNICODE_VER}

# End cm-unicode

# Begin dejavu

wget -c http://downloads.sourceforge.net/dejavu/dejavu-fonts-ttf-${DEJAVU_VER}.tar.bz2 -O - | tar xfj -

export DEST=/binary/fonts-dejavu-${DEJAVU_VER}

install -dm755 ${DEST}/usr/share/fontconfig/conf.avail ${DEST}/usr/share/fonts/truetype/dejavu

install -m644 dejavu-fonts-ttf-${DEJAVU_VER}/fontconfig/*.conf ${DEST}/usr/share/fontconfig/conf.avail
install -m644 dejavu-fonts-ttf-${DEJAVU_VER}/ttf/*.ttf ${DEST}/usr/share/fonts/truetype/dejavu

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/dejavu
EOF

chmod 755 ${DEST}/INSTALL

rm -rf dejavu-fonts-ttf-${DEJAVU_VER}

# End dejavu

# Begin freefont

wget -c https://ftp.gnu.org/pub/gnu/freefont/freefont-ttf-${FREEFONT_VER}.zip -O - | bsdtar xf -

export DEST=/binary/fonts-freefont-${FREEFONT_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/freefont
install -m644 freefont-${FREEFONT_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/freefont

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/freefont
EOF

chmod 755 ${DEST}/INSTALL

rm -rf freefont-${FREEFONT_VER}

# End freefont

# Begin gentiumbasic

export DEST=/binary/fonts-gentiumbasic-${GENTIUMBASIC_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/gentiumbasic

wget -c "http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=GentiumBasic_${GENTIUMBASIC_VER}&filename=GentiumBasic_${GENTIUMBASIC_VER}.zip" -O - | bsdtar xf - --strip-components=1 -C ${DEST}/usr/share/fonts/truetype/gentiumbasic

rm -f ${DEST}/usr/share/fonts/truetype/gentiumbasic/*.txt

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/gentiumbasic
EOF

chmod 755 ${DEST}/INSTALL

# End gentiumbasic

# Begin gentiumplus

wget -c "https://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=GentiumPlus-${GENTIUMPLUS_VER}.zip&filename=GentiumPlus-${GENTIUMPLUS_VER}.zip" -O - | bsdtar xf -

export DEST=/binary/fonts-gentiumplus-${GENTIUMPLUS_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/gentiumplus
install -m644 GentiumPlus-${GENTIUMPLUS_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/gentiumplus

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/gentiumplus
EOF

chmod 755 ${DEST}/INSTALL

rm -rf GentiumPlus-${GENTIUMPLUS_VER}

# End gentiumplus

# Begin hannom

export DEST=/binary/fonts-hannom-${HANNOM_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/hannom

wget -c http://downloads.sourceforge.net/vietunicode/hannomH.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/hannom

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/hannom
EOF

chmod 755 ${DEST}/INSTALL

# End hannom

# Begin liberation

wget -c https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-ttf-${LIBERATION_VER}.tar.gz -O - | tar xfz -

export DEST=/binary/fonts-liberation-${LIBERATION_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/liberation
install -m644 liberation-fonts-ttf-${LIBERATION_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/liberation

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/liberation
EOF

chmod 755 ${DEST}/INSTALL

rm -rf liberation-fonts-ttf-${LIBERATION_VER}

# End liberation

# Begin mgopen

wget -c http://http.debian.net/debian/pool/main/f/fonts-mgopen/fonts-mgopen_${MGOPEN_VER}.orig.tar.bz2 -O - | tar xfj -

export DEST=/binary/fonts-mgopen-${MGOPEN_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/mgopen
install -m644 fonts-mgopen-${MGOPEN_VER}/TTFs/*.ttf ${DEST}/usr/share/fonts/truetype/mgopen

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/mgopen
EOF

chmod 755 ${DEST}/INSTALL

rm -rf fonts-mgopen-${MGOPEN_VER}

# End mgopen

# Begin opendesktop

wget -c https://sources.archlinux.org/other/opendesktop-fonts/opendesktop-fonts-${OPENDESKTOP_VER}.tar.gz -O - | tar xfz -

export DEST=/binary/fonts-opendesktop-${OPENDESKTOP_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/opendesktop
install -m644 opendesktop-fonts-${OPENDESKTOP_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/opendesktop

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/opendesktop
EOF

chmod 755 ${DEST}/INSTALL

rm -rf opendesktop-fonts-${OPENDESKTOP_VER}

# End opendesktop

# Begin paratype

export DEST=/binary/fonts-paratype-${PARATYPE_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/paratype

wget -c http://www.paratype.com/uni/public/PTSans.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/paratype
wget -c http://www.paratype.com/uni/public/PTSerif.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/paratype
wget -c http://www.paratype.com/uni/public/PTMono.zip -O - | bsdtar xf - -C ${DEST}/usr/share/fonts/truetype/paratype

rm -f ${DEST}/usr/share/fonts/truetype/paratype/*.txt

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/paratype
EOF

chmod 755 ${DEST}/INSTALL

# End paratype

# Begin scheherazade

wget -c "http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=Scheherazade-${SCHEHERAZADE_VER}.zip&filename=Scheherazade-${SCHEHERAZADE_VER}.zip" -O - | bsdtar xf -

export DEST=/binary/fonts-scheherazade-${SCHEHERAZADE_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/scheherazade
install -m644 Scheherazade-${SCHEHERAZADE_VER}/*.ttf ${DEST}/usr/share/fonts/truetype/scheherazade

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/scheherazade
EOF

chmod 755 ${DEST}/INSTALL

rm -rf Scheherazade-${SCHEHERAZADE_VER}

# End scheherazade

# Begin vlgothic

wget -c http://jaist.dl.sourceforge.jp/vlgothic/62375/VLGothic-${VLGOTHIC_VER}.tar.xz -O - | tar xfJ -

export DEST=/binary/fonts-vlgothic-${VLGOTHIC_VER}

install -dm755 ${DEST}/usr/share/fonts/truetype/vlgothic
install -m644 VLGothic/*.ttf ${DEST}/usr/share/fonts/truetype/vlgothic

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/fc-cache ] && echo "Processing triggers for fontconfig" && /usr/bin/fc-cache /usr/share/fonts/truetype/vlgothic
EOF

chmod 755 ${DEST}/INSTALL

rm -rf VLGothic

# End vlgothic
