#!/bin/bash -e

export PKGNAME=libunique
export PKGVER=3.0.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://download.gnome.org/sources/libunique/${PKGVER:0:3}/${PKGTAR}"
export DEST=/binary/mate/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
