#!/bin/bash -e

export VER=0.22.3
export DEST=/binary/python-m2crypto-${VER}

export SWIG_VER=3.0.4

pushd M2Crypto-${VER}

# swig-3.0.5 and later produce a broken package.
wget -c http://downloads.sourceforge.net/swig/swig-${SWIG_VER}.tar.gz

tar xf swig-${SWIG_VER}.tar.gz

pushd swig-${SWIG_VER}

./configure --prefix=${PWD}/../swig

make -j4
make install

popd

export PATH=${PWD}/swig/bin:$PATH

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf M2Crypto-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
