#!/bin/bash -e

export VER=0.6.31
export DEST=/binary/avahi-${VER}

pushd avahi-${VER}

sed -i 's/\(CFLAGS=.*\)-Werror \(.*\)/\1\2/' configure

sed -i -e 's/-DG_DISABLE_DEPRECATED=1//' \
       -e '/-DGDK_DISABLE_DEPRECATED/d' avahi-ui/Makefile.in

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-static \
            --disable-qt3 \
            --disable-mono \
            --disable-monodoc \
            --enable-compat-libdns_sd \
            --enable-compat-howl \
            --with-distro=none \
            --with-systemdsystemunitdir=/lib/systemd/system

make -j4
make install DESTDIR=${DEST}

popd

rm -rf avahi-${VER}

rm -rf ${DEST}/usr/lib/*.la
rm -rf ${DEST}/etc/avahi/services/* ${DEST}/var

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

mkdir -p ${DEST}/avahi-autoipd/etc/avahi
mkdir -p ${DEST}/avahi-autoipd/usr/sbin
mkdir -p ${DEST}/avahi-autoipd/usr/share/man/man8

mkdir -p ${DEST}/avahi-common/usr/lib/python2.7/site-packages
mkdir -p ${DEST}/avahi-common/usr/share/avahi

mkdir -p ${DEST}/avahi-dnsconfd/etc/avahi
mkdir -p ${DEST}/avahi-dnsconfd/etc/systemd/system/multi-user.target.wants
mkdir -p ${DEST}/avahi-dnsconfd/lib/systemd/system
mkdir -p ${DEST}/avahi-dnsconfd/usr/sbin
mkdir -p ${DEST}/avahi-dnsconfd/usr/share/man/man8

mkdir -p ${DEST}/avahi-daemon/usr/share/avahi
mkdir -p ${DEST}/avahi-daemon/usr/share/man

mkdir -p ${DEST}/avahi-utils

mv ${DEST}/etc/avahi/avahi-autoipd.action ${DEST}/avahi-autoipd/etc/avahi
mv ${DEST}/usr/sbin/avahi-autoipd ${DEST}/avahi-autoipd/usr/sbin
mv ${DEST}/usr/share/man/man8/avahi-autoipd.8 ${DEST}/avahi-autoipd/usr/share/man/man8
mv ${DEST}/usr/share/man/man8/avahi-autoipd.action.8 ${DEST}/avahi-autoipd/usr/share/man/man8

mv ${DEST}/usr/include ${DEST}/avahi-common/usr
mv ${DEST}/usr/lib/avahi ${DEST}/avahi-common/usr/lib
mv ${DEST}/usr/lib/girepository-1.0 ${DEST}/avahi-common/usr/lib
mv ${DEST}/usr/lib/pkgconfig ${DEST}/avahi-common/usr/lib
mv ${DEST}/usr/lib/python2.7/site-packages/avahi ${DEST}/avahi-common/usr/lib/python2.7/site-packages
mv ${DEST}/usr/share/gir-1.0 ${DEST}/avahi-common/usr/share
mv ${DEST}/usr/share/locale ${DEST}/avahi-common/usr/share

mv ${DEST}/usr/lib/lib*.so* ${DEST}/avahi-common/usr/lib
mv ${DEST}/usr/share/avahi/service-types ${DEST}/avahi-common/usr/share/avahi

mv ${DEST}/etc/avahi/avahi-dnsconfd.action ${DEST}/avahi-dnsconfd/etc/avahi
mv ${DEST}/lib/systemd/system/avahi-dnsconfd.service ${DEST}/avahi-dnsconfd/lib/systemd/system
mv ${DEST}/usr/sbin/avahi-dnsconfd ${DEST}/avahi-dnsconfd/usr/sbin
mv ${DEST}/usr/share/man/man8/avahi-dnsconfd.8 ${DEST}/avahi-dnsconfd/usr/share/man/man8
mv ${DEST}/usr/share/man/man8/avahi-dnsconfd.action.8 ${DEST}/avahi-dnsconfd/usr/share/man/man8

ln -s /lib/systemd/system/avahi-dnsconfd.service ${DEST}/avahi-dnsconfd/etc/systemd/system/multi-user.target.wants/avahi-dnsconfd.service

mv ${DEST}/etc ${DEST}/avahi-daemon
mv ${DEST}/lib ${DEST}/avahi-daemon
mv ${DEST}/usr/sbin ${DEST}/avahi-daemon/usr
mv ${DEST}/usr/share/dbus-1 ${DEST}/avahi-daemon/usr/share
mv ${DEST}/usr/share/man/man5 ${DEST}/avahi-daemon/usr/share/man
mv ${DEST}/usr/share/man/man8 ${DEST}/avahi-daemon/usr/share/man
mv ${DEST}/usr/share/avahi/avahi-service.dtd ${DEST}/avahi-daemon/usr/share/avahi

mkdir -p ${DEST}/avahi-daemon/etc/systemd/system/multi-user.target.wants
mkdir -p ${DEST}/avahi-daemon/etc/systemd/system/sockets.target.wants

ln -s /lib/systemd/system/avahi-daemon.service ${DEST}/avahi-daemon/etc/systemd/system/dbus-org.freedesktop.Avahi.service
ln -s /lib/systemd/system/avahi-daemon.service ${DEST}/avahi-daemon/etc/systemd/system/multi-user.target.wants/avahi-daemon.service
ln -s /lib/systemd/system/avahi-daemon.socket ${DEST}/avahi-daemon/etc/systemd/system/sockets.target.wants/avahi-daemon.socket

mv ${DEST}/usr ${DEST}/avahi-utils

cat > ${DEST}/avahi-autoipd/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

getent group avahi-autoipd > /dev/null || groupadd -g 85 avahi-autoipd
getent passwd avahi-autoipd > /dev/null || useradd -c "Avahi AutoIPD Owner" -d /var/lib/avahi-autoipd -u 85 -g avahi-autoipd -s /bin/false avahi-autoipd

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/avahi-autoipd/INSTALL

cat > ${DEST}/avahi-common/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

getent group netdev > /dev/null || groupadd -g 86 netdev

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/avahi-common/INSTALL

cat > ${DEST}/avahi-daemon/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

getent group avahi > /dev/null || groupadd -g 84 avahi
getent passwd avahi > /dev/null || useradd -c "Avahi Daemon Owner" -d /var/run/avahi-daemon -u 84 -g avahi -s /bin/false avahi

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/avahi-daemon/INSTALL

cat > ${DEST}/avahi-dnsconfd/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/avahi-dnsconfd/INSTALL

cat > ${DEST}/avahi-utils/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/avahi-utils/INSTALL

cat > ${DEST}/UNINSTALL << "EOF"
#!/bin/bash

for dir in avahi-autoipd avahi-common avahi-daemon avahi-dnsconfd avahi-utils
do
  cd ${dir}
  find * -type f -o -type l | for file in `xargs` ; do rm -v /$file ; done
  find * -type d | sort -r | for file in `xargs` ; do rmdir -v /$file ; done
  cd ..
done
EOF

chmod 755 ${DEST}/UNINSTALL
