#!/bin/bash -e

export PKGNAME=freetype
export PKGVER=2.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/freetype/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

configure_pre() {
  sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg

  sed -ri "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:g" \
          include/freetype/config/ftoption.h
}

. $(dirname $0)/master.sh
