#!/bin/bash -e

export LUA_MAJOR=5.3
export PKGNAME=lua
export PKGVER=${LUA_MAJOR}.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://www.lua.org/ftp/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export PATCHES_LIST=("lua-shared-lib.patch")

configure_override() {
  sed -i '/#define LUA_ROOT/s:/usr/local:/usr:' src/luaconf.h
}

make_override() {
  make MYCFLAGS="${CFLAGS} -fPIC" linux ${MAKE_JOBS_FLAGS}
}

make_install_override() {
  make INSTALL_TOP=${DEST}/usr TO_LIB="liblua.so liblua.so.${LUA_MAJOR} liblua.so.${PKGVER}" \
       INSTALL_DATA="cp -d" INSTALL_MAN=${DEST}/usr/share/man/man1 install

  install -dm755 ${DEST}/usr/lib/pkgconfig

cat > ${DEST}/usr/lib/pkgconfig/lua.pc << EOF
prefix=/usr
INSTALL_BIN=\${prefix}/bin
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
INSTALL_MAN=\${prefix}/man/man1
INSTALL_LMOD=\${prefix}/share/lua/${LUA_MAJOR}
INSTALL_CMOD=\${prefix}/lib/lua/${LUA_MAJOR}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: ${PKGVER}
Requires:
Libs: -L\${libdir} -llua -lm
Cflags: -I\${includedir}
EOF
}

. $(dirname $0)/master.sh
