#!/bin/bash -e

export PKGNAME=libmpcdec
export PKGVER=1.2.6
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://files.musepack.net/source/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

. $(dirname $0)/master.sh
