#!/bin/bash -e

export PKGVERSION=5.6.5
export DEST=/binary/php-${PKGVERSION}

export EXTENSION_DIR=/usr/lib/php/modules
export PEAR_INSTALLDIR=/usr/share/pear

pushd php-${PKGVERSION}

patch -Np1 -i /media/ntfs/Other/Linux/patches/php-configure.patch
patch -Np1 -i /media/ntfs/Other/Linux/patches/phpdb6.patch

sed -i "s|lsystemd-daemon|lsystemd|g" configure
sed -i "s|-i -a -n php5|-i -n php5|g" configure

sed -i "/APACHE_THREADED_MPM=/d" sapi/apache2handler/config.m4 configure

./configure --prefix=/usr \
            --sysconfdir=/etc/php \
            --localstatedir=/var \
            --disable-rpath \
            --with-apxs2 \
            --enable-cli \
            --enable-fpm \
            --with-fpm-user=httpd \
            --with-fpm-group=httpd \
            --with-fpm-systemd \
            --enable-phpdbg \
            --enable-cgi \
            --with-layout=GNU \
            --with-config-file-path=/etc/php \
            --with-config-file-scan-dir=/etc/php/conf.d \
            --with-openssl=shared \
            --with-pcre-regex=/usr \
            --with-sqlite3=shared,/usr \
            --with-zlib \
            --enable-bcmath=shared \
            --with-bz2=shared \
            --enable-calendar=shared \
            --with-curl=shared \
            --enable-dba=shared \
            --with-gdbm \
            --with-db4=/usr \
            --with-enchant=shared,/usr \
            --enable-exif=shared \
            --enable-ftp=shared \
            --with-gd=shared,/usr \
            --with-vpx-dir=/usr \
            --with-jpeg-dir=/usr \
            --with-png-dir=/usr \
            --with-xpm-dir=/usr \
            --with-freetype-dir=/usr \
            --with-t1lib=shared,/usr \
            --enable-gd-native-ttf \
            --with-gettext=shared \
            --with-gmp=shared \
            --with-mhash \
            --with-iconv=shared \
            --with-imap=shared \
            --with-imap-ssl \
            --enable-intl=shared \
            --with-icu-dir=/usr \
            --with-ldap=shared \
            --with-ldap-sasl \
            --enable-mbstring \
            --with-mcrypt=shared \
            --with-mysql=shared,mysqlnd \
            --with-mysql-sock=/run/mysqld/mysqld.sock \
            --with-mysqli=shared,mysqlnd \
            --with-unixODBC=shared,/usr \
            --enable-pcntl \
            --with-pdo-mysql=shared,mysqlnd \
            --with-pdo-odbc=shared,unixODBC,/usr \
            --with-pdo-pgsql=shared \
            --with-pdo-sqlite=shared,/usr \
            --with-pgsql=shared \
            --enable-phar=shared \
            --enable-posix=shared \
            --with-pspell=shared \
            --with-readline \
            --enable-shmop=shared \
            --enable-soap=shared \
            --enable-sockets=shared \
            --enable-sysvmsg=shared \
            --enable-sysvsem=shared \
            --enable-sysvshm=shared \
            --with-tidy=shared \
            --with-xmlrpc=shared \
            --with-xsl=shared \
            --enable-zip=shared \
            --with-libzip \
            --with-pear

make -j4
make install INSTALL_ROOT=${DEST}

popd

rm -rf php-${PKGVERSION}

rm -rf ${DEST}/etc/httpd ${DEST}/etc/php/php-fpm.conf.default ${DEST}/var
rm -rf ${DEST}/usr/share/pear/.{channels,depdb,depdblock,filemap,lock,registry}

find ${DEST} -name "*.a" -delete

install -m644 /media/ntfs/Other/Linux/php-fpm.conf ${DEST}/etc/php/php-fpm.conf
install -m644 /media/ntfs/Other/Linux/php.ini ${DEST}/etc/php/php.ini.dist

install -dm755 ${DEST}/etc/httpd/extra ${DEST}/etc/php/fpm.d ${DEST}/etc/systemd/system/multi-user.target.wants
install -dm755 ${DEST}/lib/systemd/system ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/etc/httpd/extra/php.conf << "EOF"
LoadModule php5_module /usr/lib/httpd/modules/libphp5.so

<IfModule dir_module>
	<IfModule php5_module>
		DirectoryIndex index.php index.html
		<FilesMatch "\.php$">
			SetHandler application/x-httpd-php
		</FilesMatch>
		<FilesMatch "\.phps$">
			SetHandler application/x-httpd-php-source
		</FilesMatch>
	</IfModule>
</IfModule>
EOF

cat > ${DEST}/lib/systemd/system/php-fpm.service << "EOF"
[Unit]
Description=The PHP FastCGI Process Manager
After=network.target

[Service]
Type=notify
PIDFile=/run/php-fpm/php-fpm.pid
PrivateTmp=true
ExecStart=/usr/sbin/php-fpm --nodaemonize --pid /run/php-fpm/php-fpm.pid
ExecReload=/bin/kill -USR2 $MAINPID

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/php-fpm.conf << "EOF"
d /run/php-fpm 755 root root
EOF

ln -sf /lib/systemd/system/php-fpm.service ${DEST}/etc/systemd/system/multi-user.target.wants/php-fpm.service

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

if [ ! -e /etc/php/php.ini ]; then
   cp -r /etc/php/php.ini.dist /etc/php/php.ini
fi

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
