#!/bin/bash -e

case $(basename $0) in
  buildpyatspi )
    export PKGNAME=pyatspi
    export PKGVER=2.18.0
    export MULTILIB_BUILD=1
    export CONFIGURE_FLAGS=(PYTHON=/usr/bin/python3)
    export CONFIGURE_FLAGS_32=(PYTHON=/usr/bin/python --libdir=/usr/lib)
    configure_pre_32() {
      unset PKG_CONFIG_PATH
    }
    make_install_override() {
      make install DESTDIR=${DEST}
    }
  ;;
  buildpy2cairo )
    export PKGNAME=py2cairo
    export PKGVER=1.10.0
  ;;
  buildpycairo )
    export PKGNAME=pycairo
    export PKGVER=1.10.0
    export PATCHES_LIST=("pycairo-fixes.patch")
    configure_pre() {
      export PYTHON=/usr/bin/python3
    }
  ;;
  buildpygobject2 )
    export PKGNAME=pygobject
    export PKGVER=2.28.6
    export PATCHES_LIST=("pygobject-fixes.patch")
    export CONFIGURE_FLAGS=(--disable-introspection)
  ;;
  buildpygobject3 )
    export PKGNAME=pygobject
    export PKGVER=3.22.0
    export MULTILIB_BUILD=1
    export CONFIGURE_FLAGS=(--with-python=/usr/bin/python3)
    export CONFIGURE_FLAGS_32=(--with-python=/usr/bin/python --libdir=/usr/lib)
    configure_pre_32() {
      unset PKG_CONFIG_PATH
    }
    make_install_override() {
      make install DESTDIR=${DEST}
    }
  ;;
  buildpygtk )
    export PKGNAME=pygtk
    export PKGVER=2.24.0
    export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
    make_install_post() {
      rm -rf ${DEST}/usr/bin/pygtk-demo
      rm -rf ${DEST}/usr/lib/pygtk
    }
  ;;
esac

if [ -z ${PKGTAR} ]
then
  export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
fi

export PKGURL="https://download.gnome.org/sources/${PKGNAME}/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export DEFAULT_CC_M32="clang"

if [ ${PKGNAME} == "py2cairo" ] || [ ${PKGNAME} == "pycairo" ]
then
  configure_override() {
    ./waf configure --prefix=/usr
  }
  make_override() {
    ./waf build ${MAKE_JOBS_FLAGS}
  }
  make_install_override() {
    ./waf install --destdir=${DEST}
  }

  export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
  export PKGURL="https://www.cairographics.org/releases/${PKGTAR}"
fi

. $(dirname $0)/master.sh
