#!/bin/bash -e

export PKGNAME=youtube-dl
export PKGVER=2016.07.13
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://github.com/rg3/youtube-dl/archive/${PKGVER}.tar.gz"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export NO_STRIP=1

configure_override() {
  true
}

make_override() {
  true
}

make_install_override() {
  python setup.py install --prefix=/usr --root=${DEST} --optimize=1
  rm -rf ${DEST}/usr/etc
}

. $(dirname $0)/master.sh
