#!/bin/bash -e

export PKGNAME=slang
export PKGVER=2.3.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://www.jedsoft.org/releases/slang/${PKGTAR}"
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export KEEP_EMPTY_DIRS=1
export KEEP_STATIC=1
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--with-readline=gnu)
export CONFIGURE_FLAGS_32=(--with-readline=gnu)

make_install_override() {
  if [ ${MULTILIB} == 1 ]
  then
    local D=${PWD}/dest
  else
    local D=${DEST}
  fi

  make install-all DESTDIR=${D}
}

post_install_config() {
  find ${DEST} -name "*.a" -delete
}

. $(dirname $0)/master.sh
