#!/bin/bash -e

export VER=2.20
export DEST=/binary/perl-xml-simple-${VER}

pushd XML-Simple-${VER}

perl Makefile.PL INSTALLDIRS=vendor

make -j4
make install DESTDIR=${DEST}

popd

rm -rf XML-Simple-${VER}

rm -rf ${DEST}/usr/lib

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
