#!/bin/bash -e

export VER=1.2.0-beta1-android9
export DEST=/binary/FreeRDP-${VER}

pushd FreeRDP-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/freerdp-fixes.patch

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_LIBDIR=lib  \
      -DWITH_CUPS=ON              \
      -DWITH_GSM=ON               \
      -DWITH_JPEG=ON              \
      -DWITH_PULSE=ON             \
      -DCMAKE_C_FLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong $(pkg-config --cflags gstreamer-1.0)"

make -j4
make install DESTDIR=${DEST}

popd

rm -rf FreeRDP-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
    chrpath -d ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
