#!/bin/bash -e

export TKMAJOR=8.6
export VER=${TKMAJOR}.4
export DEST=/binary/tk-${VER}

pushd tk${VER}/unix

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --enable-64bit

make -j4

sed -e "s@^\(TK_SRC_DIR='\).*@\1/usr/include'@" \
    -e "/TK_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
    -i tkConfig.sh

make install install-private-headers DESTDIR=${DEST}

ln -sf wish${TKMAJOR} ${DEST}/usr/bin/wish

chmod 644 ${DEST}/usr/lib/libtkstub${TKMAJOR}.a
chmod 755 ${DEST}/usr/lib/libtk${TKMAJOR}.so

popd

rm -rf ${DEST}/usr/lib/tk${TKMAJOR}/demos

rm -rf tk${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
