#!/bin/bash -e

export PKGNAME=evolution-data-server
export PKGVER=3.18.3
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://download.gnome.org/sources/evolution-data-server/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--disable-uoa
                        --with-krb5=/usr
                        --with-openldap
                        --enable-vala-bindings)

. $(dirname $0)/master.sh
