#!/bin/bash -e

export VER=2.0.3
export DEST=/binary/python-pyparsing-${VER}

cp -a pyparsing-${VER} pyparsing-${VER}-3

pushd pyparsing-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

popd

pushd pyparsing-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf pyparsing-${VER} pyparsing-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
