#!/bin/bash -e

export PKGNAME=hostname
export PKGVER=3.18
export PKGDIR=${PKGNAME}
export PKGTAR=${PKGNAME}_${PKGVER}.tar.gz
export PKGURL="http://http.debian.net/debian/pool/main/h/hostname/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MAKE_INSTALL_FLAGS="BASEDIR=\${DEST}"

configure_override() {
  true
}

. $(dirname $0)/master.sh
