#!/bin/bash -e

export PKGNAME=strace
export PKGVER=4.11
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://downloads.sourceforge.net/strace/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
