#!/bin/bash -e

export PKGNAME=libdbusmenu
export PKGVER=16.04.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://launchpad.net/libdbusmenu/${PKGVER:0:5}/${PKGVER}/+download/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--disable-dumper --disable-tests)
export CONFIGURE_FLAGS_32=(--disable-dumper
                           --disable-introspection
                           --disable-tests
                           --disable-vala)

export HAVE_VALGRIND_TRUE='#'
export HAVE_VALGRIND_FALSE=''

. $(dirname $0)/master.sh
