#!/bin/bash -e

export VER=1.4.21
export DEST=/binary/iptables-${VER}

pushd iptables-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr                \
            --sbindir=/sbin              \
            --with-xtlibdir=/lib/xtables \
            --enable-libipq

make -j4
make install DESTDIR=${DEST}

popd

rm -rf iptables-${VER}

find ${DEST} -name "*.la" -delete

ln -sf ../../sbin/xtables-multi ${DEST}/usr/bin/iptables-xml

for file in ip4tc ip6tc ipq iptc xtables
do
  mv ${DEST}/usr/lib/lib${file}.so.* ${DEST}/lib
  ln -sf ../../lib/$(readlink ${DEST}/usr/lib/lib${file}.so) ${DEST}/usr/lib/lib${file}.so
done

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
