#!/bin/bash -e

export VER=2.1.0
export DEST=/binary/mjpegtools-${VER}

pushd mjpegtools-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr    \
            --disable-static \
            --enable-largefile

make -j4
make install DESTDIR=${DEST}

install -m644 mpeg2enc/mpeg2syntaxcodes.h ${DEST}/usr/include/mjpegtools/mpeg2enc/

popd

rm -rf mjpegtools-${VER}

find ${DEST} -name "*.la" -delete

gzip -9 ${DEST}/usr/share/info/*

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
