#!/bin/bash -e

export VER=3.14.0
export DEST=/binary/gnome-font-viewer-${VER}

pushd gnome-font-viewer-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf gnome-font-viewer-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
EOF

chmod 755 ${DEST}/INSTALL
