#!/bin/bash -e

export PKGNAME=wireshark
export PKGVER=2.0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://www.wireshark.org/download/src/all-versions/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export POSTINST_TRIGGER=("getent group wireshark > /dev/null || groupadd -g 62 wireshark\n"
                         "chown root:wireshark /usr/bin/tshark"
                         "chown root:wireshark /usr/bin/dumpcap\n"
                         "chmod 6550 /usr/bin/tshark"
                         "chmod 6550 /usr/bin/dumpcap")

. $(dirname $0)/master.sh
