#!/bin/bash -e

export PKGNAME=faac
export PKGVER=1.28
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://downloads.sourceforge.net/faac/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export INSTALL_CMD=("for dir in usr/include usr/lib ; do cp -rf --remove-destination \$dir /usr ; done")
export PATCHES_LIST=("faac-fixes.patch")

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"

configure_pre() {
  sed -i -e '/obj-type/d' -e '/Long Term/d' frontend/main.c
}

. $(dirname $0)/master.sh
