#!/bin/bash -e

export PKGNAME=openssh
export PKGVER=7.3p1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

export POSTINST_TRIGGER=("getent group sshd > /dev/null || groupadd -g 50 sshd"
                         "getent passwd sshd > /dev/null || useradd -c \"OpenSSH PrivSep\" -d /var/run/sshd -g sshd -s /sbin/nologin -u 50 sshd\n"
                         "chmod 4711 /usr/libexec/ssh-keysign\n"
                         "/usr/bin/ssh-keygen -A")

export CONFIGURE_FLAGS=(--sysconfdir=/etc/ssh
                        --with-mantype=doc
                        --with-4in6
                        --with-privsep-path=/var/run/sshd
                        --with-kerberos5=/usr
                        --with-pam
                        --with-ssl-engine
                        --with-xauth=/usr/bin/xauth
                        --with-default-path=/usr/local/bin:/usr/bin:/bin
                        --with-superuser-path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

make_install_post() {
  rm -rf ${DEST}/var

  install -m755 contrib/ssh-copy-id ${DEST}/usr/bin
  install -m644 contrib/ssh-copy-id.1 ${DEST}/usr/share/man/man1

  sed -i "/OpenBSD/d" ${DEST}/etc/ssh/moduli

  install -dm755 ${DEST}/etc/pam.d ${DEST}/lib/systemd/system ${DEST}/usr/lib/tmpfiles.d

cat > ${DEST}/etc/pam.d/sshd << "EOF"
# Begin /etc/pam.d/sshd

auth     required       pam_nologin.so
auth     optional       pam_group.so

auth     include        system-auth

account  required       pam_access.so
account  include        system-account

password include        system-password

session  required       pam_env.so
session  required       pam_limits.so
session  optional       pam_lastlog.so
session  optional       pam_motd.so
session  optional       pam_mail.so standard

session  include        system-session

# End /etc/pam.d/sshd
EOF

cat > ${DEST}/etc/ssh/ssh_config << "EOF"
# This is the ssh client system-wide configuration file.  See
# ssh_config(5) for more information.  This file provides defaults for
# users, and the values can be changed in per-user configuration files
# or on the command line.

# Configuration data is parsed as follows:
#  1. command line options
#  2. user-specific file
#  3. system-wide file
# Any configuration value is only changed the first time it is set.
# Thus, host-specific definitions should be at the beginning of the
# configuration file, and defaults at the end.

# Site-wide defaults for some commonly used options.  For a comprehensive
# list of available options, their meanings and defaults, please see the
# ssh_config(5) man page.

Host *
#   ForwardAgent no
#   ForwardX11 no
#   RhostsRSAAuthentication no
#   RSAAuthentication yes
#   PasswordAuthentication yes
#   HostbasedAuthentication no
#   GSSAPIAuthentication no
#   GSSAPIDelegateCredentials no
#   BatchMode no
#   CheckHostIP yes
#   AddressFamily any
#   ConnectTimeout 0
#   StrictHostKeyChecking ask
#   IdentityFile ~/.ssh/identity
#   IdentityFile ~/.ssh/id_rsa
#   IdentityFile ~/.ssh/id_dsa
#   Port 22
#   Protocol 2,1
#   Cipher 3des
#   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc
#   MACs hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160
#   EscapeChar ~
#   Tunnel no
#   TunnelDevice any:any
#   PermitLocalCommand no
#   VisualHostKey no
#   ProxyCommand ssh -q -W %h:%p gateway.example.com
#   RekeyLimit 1G 1h
EOF

cat > ${DEST}/etc/ssh/sshd_config << "EOF"
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

# The default requires explicit activation of protocol 1
#Protocol 2

# HostKey for protocol version 1
#HostKey /etc/ssh/ssh_host_key
# HostKeys for protocol version 2
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Lifetime and size of ephemeral version 1 server key
#KeyRegenerationInterval 1h
#ServerKeyBits 1024

# Ciphers and keying
#RekeyLimit default none

# Logging
# obsoletes QuietMode and FascistLogging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#RSAAuthentication yes
#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#RhostsRSAAuthentication no
# similar for protocol version 2
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# RhostsRSAAuthentication and HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to no to disable s/key passwords
#ChallengeResponseAuthentication yes

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
UsePrivilegeSeparation sandbox		# Default for new installations.
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

Banner /etc/issue.net

# override default of no subsystems
Subsystem	sftp	/usr/libexec/sftp-server
EOF

cat > ${DEST}/usr/lib/tmpfiles.d/sshd.conf << "EOF"
d /run/sshd 755 root root -
EOF

cat > ${DEST}/lib/systemd/system/sshd.service << "EOF"
[Unit]
Description=OpenSSH Daemon

[Service]
ExecStart=/usr/sbin/sshd -D
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
EOF

cat > ${DEST}/lib/systemd/system/sshd@.service << "EOF"
[Unit]
Description=SSH Per-Connection Server

[Service]
ExecStart=/usr/sbin/sshd -i
StandardInput=socket
StandardError=syslog
EOF

cat > ${DEST}/lib/systemd/system/sshd.socket << "EOF"
[Unit]
Conflicts=sshd.service

[Socket]
ListenStream=22
Accept=yes

[Install]
WantedBy=sockets.target
EOF
}

. $(dirname $0)/master.sh
