#!/bin/bash -e

export VER=7.0
export SHLIBVER=${VER}
#export SHLIBVER=6.99
export DEST=/binary/pulseaudio-${VER}

cp -a pulseaudio-${VER} pulseaudio-${VER}-32

pushd pulseaudio-${VER}

sed -i "s#; flat-volumes = yes#flat-volumes = no#" src/daemon/daemon.conf.in

find . -name "Makefile.in" | xargs sed -i "s|(libdir)/@PACKAGE@|(libdir)/pulse|"

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-bluez4     \
            --disable-rpath      \
            --with-module-dir=/usr/lib/pulse/modules

make -j4
make install DESTDIR=${DEST} bashcompletiondir=/usr/share/bash-completion/completions

popd

pushd pulseaudio-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

find . -name "Makefile.in" | xargs sed -i "s|(libdir)/@PACKAGE@|(libdir)/pulse|"

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --libdir=/usr/lib32  \
            --disable-bluez4     \
            --disable-rpath      \
            --with-module-dir=/usr/lib/pulse/modules

_libs="libpulse.la libpulse-simple.la libpulse-mainloop-glib.la"
_pkglibs="libpulsecommon-${SHLIBVER}.la libpulsedsp.la"

make -C src ${_libs} ${_pkglibs} -j4

make -C src lib_LTLIBRARIES="${_libs}" install-libLTLIBRARIES DESTDIR=${PWD}/dest
make -C src pkglib_LTLIBRARIES="${_pkglibs}" install-pkglibLTLIBRARIES DESTDIR=${PWD}/dest
make install-pkgconfigDATA DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf pulseaudio-${VER} pulseaudio-${VER}-32

find ${DEST} -name "*.la" -delete

rm -rf ${DEST}/etc/dbus-1

# Speed up pulseaudio shutdown so that it exits immediately with
# the last user session (module-systemd-login keeps it alive)
sed -e '/exit-idle-time/iexit-idle-time=0'  -i ${DEST}/etc/pulse/daemon.conf

# Disable cork-request module, can result in e.g. media players unpausing
# when there's a Skype call incoming
sed -e 's|/usr/bin/pactl load-module module-x11-cork-request|#&|' -i ${DEST}/usr/bin/start-pulseaudio-x11

for file in client.conf daemon.conf default.pa system.pa
do
  mv ${DEST}/etc/pulse/${file} ${DEST}/etc/pulse/${file}.dist
done

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr ; do cp -rf --remove-destination $dir / ; done

for file in client.conf daemon.conf default.pa system.pa
do
  if [ ! -e /etc/pulse/${file} ]
  then
    cp -f /etc/pulse/${file}.dist /etc/pulse/${file}
  fi
  diff -Naur /etc/pulse/${file}.dist /etc/pulse/${file} > /dev/null
  if [ $? -gt 0 ]
  then
    echo "Files /etc/pulse/${file}.dist and /etc/pulse/${file} differ."
  fi
done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
