#!/bin/bash -e

export PKGNAME=libglade
export PKGVER=2.6.4
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="https://download.gnome.org/sources/libglade/${PKGVER:0:3}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export POSTINST_TRIGGER=("xmlcatalog --noout --add \"system\" \"http://glade.gnome.org/glade-2.0.dtd\" /usr/share/xml/libglade/glade-2.0.dtd /etc/xml/catalog")

configure_pre() {
  sed -i '/DG_DISABLE_DEPRECATED/d' glade/Makefile.in
}

. $(dirname $0)/master.sh
