#!/bin/bash -e

export VER=1.2.12
export DEST=/binary/colord-${VER}

cp -a colord-${VER} colord-${VER}-32

pushd colord-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr              \
            --sysconfdir=/etc          \
            --localstatedir=/var       \
            --with-daemon-user=colord  \
            --enable-sane              \
            --enable-vala              \
            --disable-bash-completion  \
            --disable-argyllcms-sensor \
            --disable-static

make -j4
make install DESTDIR=${DEST}

popd

pushd colord-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -g -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr              \
            --sysconfdir=/etc          \
            --localstatedir=/var       \
            --libdir=/usr/lib32        \
            --with-daemon-user=colord  \
            --disable-argyllcms-sensor \
            --disable-bash-completion  \
            --disable-gusb             \
            --disable-introspection    \
            --disable-polkit           \
            --disable-sane             \
            --disable-static           \
            --disable-vala

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf colord-${VER} colord-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc lib usr var ; do cp -rf --remove-destination $dir / ; done

getent group colord > /dev/null || groupadd -g 71 colord
getent passwd colord > /dev/null || useradd -c "Color Daemon Owner" -d /var/lib/colord -u 71 -g colord -s /bin/false colord

chown -R colord:colord /var/lib/colord

[ -x /usr/bin/glib-compile-schemas ] && echo "Processing triggers for glib-2.0" && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
