#!/bin/bash -e

export VER=4.13.80-19-g1b6ba68
export DEST=/binary/libkcddb-${VER}

pushd libkcddb-${VER}

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DLIB_INSTALL_DIR=lib       \
      -DBUILD_TESTING=OFF         \
      -DQT_PLUGIN_INSTALL_DIR=lib/qt5/plugins \
      -DCMAKE_C_FLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
      -DCMAKE_CXX_FLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
      -Wno-dev

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libkcddb-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
