#!/bin/bash -e

export PKGNAME=libytnef
export PKGVER=1.5
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/ytnef/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("libytnef-fixes.patch")

. $(dirname $0)/master.sh
