#!/bin/bash -e

export VER=3.17.4
export DEST=/binary/nss-${VER}

export XCFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"

pushd nss-${VER}
  patch -Np1 -i /media/ntfs/Other/Linux/patches/nss-standalone.patch
popd

cp -a nss-${VER} nss-${VER}-32

pushd nss-${VER}/nss

make nss_build_all BUILD_OPT=1       \
  NSPR_INCLUDE_DIR=/usr/include/nspr \
  USE_SYSTEM_ZLIB=1                  \
  ZLIB_LIBS=-lz                      \
  USE_64=1                           \
  NSS_USE_SYSTEM_SQLITE=1

popd

pushd nss-${VER}/dist

install -dm755 ${DEST}/usr/bin
install -dm755 ${DEST}/usr/include/nss
install -dm755 ${DEST}/usr/lib/pkgconfig

install -m755 Linux*/lib/*.so ${DEST}/usr/lib
install -m644 Linux*/lib/libcrmf.a ${DEST}/usr/lib
install -m644 Linux*/lib/*.chk ${DEST}/usr/lib

install -v -m644 Linux*/lib/pkgconfig/nss.pc ${DEST}/usr/lib/pkgconfig

cp -RL public/nss/* ${DEST}/usr/include/nss
cp -RL private/nss/* ${DEST}/usr/include/nss

install -v -m755 Linux*/bin/certutil ${DEST}/usr/bin
install -v -m755 Linux*/bin/nss-config ${DEST}/usr/bin
install -v -m755 Linux*/bin/pk12util ${DEST}/usr/bin

popd

pushd nss-${VER}-32/nss

export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

make nss_build_all BUILD_OPT=1       \
  NSPR_INCLUDE_DIR=/usr/include/nspr \
  USE_SYSTEM_ZLIB=1                  \
  ZLIB_LIBS=-lz                      \
  NSS_USE_SYSTEM_SQLITE=1

popd

pushd nss-${VER}-32/dist

install -dm755 ${DEST}/usr/lib32/pkgconfig

install -m755 Linux*/lib/*.so ${DEST}/usr/lib32
install -m644 Linux*/lib/libcrmf.a ${DEST}/usr/lib32
install -m644 Linux*/lib/*.chk ${DEST}/usr/lib32

sed "s@/lib@&32@g" Linux*/lib/pkgconfig/nss.pc > ${DEST}/usr/lib32/pkgconfig/nss.pc

popd

rm -rf nss-${VER} nss-${VER}-32

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
