#!/bin/bash -e

export PKGNAME=mate-screensaver-hacks
export PKGVER=5.34
export NO_STRIP=1

prepare_src_override() {
  install -dm755 ${PKGDIR}
}

configure_override() {
cat > ${PWD}/migrate-xscreensaver-config.sh << "EOF"
#!/bin/sh

DIST_BIN=`dirname "$0"`

CMD=xsltproc
XSL=${DIST_BIN}/xscreensaver-config.xsl

if test "x$1" = "x" -o  "x$1" = "x-h" -o "x$1" = "x--help"; then
    echo "usage: $0 [file] ..."
    exit 1
fi

if [ ! -r ${XSL} ]; then
    echo "Cannot find XSLT file"
    exit 1
fi

FILES="$@"
for FILE in $FILES; do
    echo "${FILE}" | grep ".xml$" > /dev/null
    if [ $? -ne 0 ]; then
        echo "Skipping non-xml file: ${FILE}"
        continue
    fi

    d=`dirname ${FILE}`
    b=`basename ${FILE} .xml`

    outfile="${b}.desktop"
    echo "Creating: ${outfile}"
    ${CMD} -o ${outfile} ${XSL} ${FILE}
done

 exit 0
EOF

cat > ${PWD}/xscreensaver-config.xsl << "EOF"
<?xml version='1.0'?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.0">
<xsl:output method="text" indent="no" />
<xsl:strip-space elements="*"/>

<xsl:template match="screensaver">
[Desktop Entry]
Encoding=UTF-8
Name=<xsl:value-of select="@_label" />
Comment=<xsl:value-of select="normalize-space(_description)" />
<xsl:if test="count(command/@name) != 0">
TryExec=<xsl:value-of select="normalize-space(command/@name)" />
Exec=<xsl:value-of select="normalize-space(command/@name)" /><xsl:text> </xsl:text><xsl:value-of select="normalize-space(command/@arg)" />
</xsl:if>
<xsl:if test="count(command/@name) = 0">
TryExec=<xsl:value-of select="normalize-space(@name)" />
Exec=<xsl:value-of select="normalize-space(@name)" /><xsl:text> </xsl:text><xsl:value-of select="normalize-space(command/@arg)" />
</xsl:if>
StartupNotify=false
Terminal=false
Type=Application
Categories=Screensaver;
OnlyShowIn=MATE;
</xsl:template>

</xsl:stylesheet>
EOF
}

make_override() {
  chmod +x ${PWD}/migrate-xscreensaver-config.sh
}

make_install_override() {
  install -dm755 ${DEST}/usr/share/applications/screensavers

  pushd ${DEST}/usr/share/applications/screensavers
    ${OLDPWD}/migrate-xscreensaver-config.sh /usr/share/xscreensaver/config/*.xml
    rm -rf popsquares.desktop
  popd
}

. $(dirname $0)/master.sh
