#!/bin/bash -e

export VER=0.6.2
export DEST=/binary/mpv-${VER}

pushd mpv-${VER}

./bootstrap.py

CC=clang CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -I/usr/include/samba-4.0" \
./waf configure --prefix=/usr      \
                --confdir=/etc/mpv \
                --lua=52           \
                --enable-cdda      \
                --enable-joystick  \
                --enable-openal    \
                --enable-portaudio \
                --enable-sdl2      \
                --enable-libmpv-shared

./waf build -j4
./waf install --destdir=${DEST}

popd

rm -rf mpv-${VER}

rm -rf ${DEST}/usr/share/doc

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

#!/bin/bash

for dir in etc usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/gtk-update-icon-cache ] && echo "Processing triggers for hicolor-icon-theme" && /usr/bin/gtk-update-icon-cache -qf /usr/share/icons/hicolor
[ -x /usr/bin/update-desktop-database ] && echo "Processing triggers for desktop-file-utils" && /usr/bin/update-desktop-database
[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
