#!/bin/bash -e

export PKGNAME=gnome-bluetooth
export PKGVER=3.18.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/${PKGVER:0:4}/${PKGTAR}"
export DEST=/binary/gnome/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
