#!/bin/bash -e

export PKGNAME=gettext
export PKGVER=0.19.7
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="https://ftp.gnu.org/gnu/gettext/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1

export DEFAULT_CC="clang"
export DEFAULT_CXX="clang++ -stdlib=libc++"
export DEFAULT_CC_M32="clang -m32"
export DEFAULT_CXX_M32="clang++ -m32 -stdlib=libc++"

configure_pre() {
  sed -i "s:fopenmp:&=libgomp:g" gettext-tools/configure
}

configure_pre_32() {
  sed -i "s:fopenmp:&=libgomp:g" gettext-tools/configure
}

. $(dirname $0)/master.sh
