#!/bin/bash -e

export VER=1.0.6
export DEST=/binary/bzip2-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"

cp -a bzip2-${VER} bzip2-${VER}-32

pushd bzip2-${VER}

sed -e 's/^CFLAGS=\(.*\)$/CFLAGS=\1 \$(BIGFILES)/' -i ./Makefile-libbz2_so

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

sed -i "s|-O2|${CFLAGS}|g" Makefile
sed -i "s|-O2|${CFLAGS}|g" Makefile-libbz2_so

make -f Makefile-libbz2_so
make clean
make

make PREFIX=${DEST}/usr install

install -dm755 ${DEST}/{bin,lib}

install -m755 bzip2-shared ${DEST}/bin/bzip2
ln -s bzip2 ${DEST}/bin/bunzip2
ln -s bzip2 ${DEST}/bin/bzcat

install -m755 libbz2.so.${VER} ${DEST}/lib

ln -s libbz2.so.${VER} ${DEST}/lib/libbz2.so.1.0
ln -s libbz2.so.${VER} ${DEST}/lib/libbz2.so.1
ln -s ../../lib/libbz2.so.${VER} ${DEST}/usr/lib/libbz2.so

rm ${DEST}/usr/bin/{bunzip2,bzcat,bzip2}

popd

pushd bzip2-${VER}-32

sed -e 's/^CFLAGS=\(.*\)$/CFLAGS=\1 \$(BIGFILES)/' -i ./Makefile-libbz2_so

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

sed -i "s|-O2|${CFLAGS}|g" Makefile
sed -i "s|-O2|${CFLAGS}|g" Makefile-libbz2_so

sed -i "s|CC=gcc|CC=gcc -m32|" Makefile
sed -i "s|CC=gcc|CC=gcc -m32|" Makefile-libbz2_so

make -f Makefile-libbz2_so
make libbz2.a

install -dm755 ${DEST}/usr/lib32

install -m755 libbz2.so.${VER} ${DEST}/usr/lib32

ln -s libbz2.so.${VER} ${DEST}/usr/lib32/libbz2.so.1.0
ln -s libbz2.so.${VER} ${DEST}/usr/lib32/libbz2.so.1
ln -s libbz2.so.${VER} ${DEST}/usr/lib32/libbz2.so

popd

rm -rf ${DEST}/usr/lib/libbz2.a

rm -rf bzip2-${VER} bzip2-${VER}-32

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in bin lib usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
