#!/bin/bash -e

export PKGNAME=desktop-file-utils
export PKGVER=0.22
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://freedesktop.org/software/desktop-file-utils/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_STATIC=1

export DEFAULT_CC="clang"

. $(dirname $0)/master.sh
