#!/bin/bash -e

export PKGNAME=transmission
export PKGVER=2.84
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download-origin.transmissionbt.com/files/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export CONFIGURE_FLAGS=(--without-gtk)

configure_post() {
  pushd qt
    qmake "QMAKE_CFLAGS+=${CFLAGS}" "QMAKE_CXXFLAGS+=${CXXFLAGS}"
  popd
}

make_post() {
  make -C qt ${MAKE_JOBS_FLAGS}
}

make_install_post() {
  install -Dm644 daemon/transmission-daemon.service ${DEST}/lib/systemd/system/transmission-daemon.service

  make -C qt install INSTALL_ROOT=${DEST}/usr

  install -Dm644 qt/transmission-qt.desktop ${DEST}/usr/share/applications/transmission-qt.desktop

  for icons in qt/icons/hicolor/*
  do
    install -dm755 ${DEST}/usr/share/icons/hicolor/$(basename ${icons})/apps
    install -m644 ${icons}/* ${DEST}/usr/share/icons/hicolor/$(basename ${icons})/apps
  done
}

. $(dirname $0)/master.sh
