#!/bin/bash -e

export VER=0.9.14
export DEST=/binary/lmdb-${VER}

pushd lmdb-LMDB_${VER}/libraries/liblmdb

sed -i "s:man/:share/&:g" Makefile

make prefix=/usr OPT="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"

install -dm755 ${DEST}/usr/bin ${DEST}/usr/share/man/man1
install -dm755 ${DEST}/usr/include ${DEST}/usr/lib

make prefix=/usr OPT="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" install DESTDIR=${DEST}

popd

rm -rf lmdb-LMDB_${VER}

rm -rf ${DEST}/usr/lib/liblmdb.a

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in usr/include usr/lib ; do cp -rf --remove-destination $dir /usr ; done

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
