#!/bin/bash -e

export PKGNAME=p11-kit
export PKGVER=0.23.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://p11-glue.freedesktop.org/releases/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export CONFIGURE_FLAGS=(--enable-doc)
export CONFIGURE_FLAGS_32=(--with-module-path=/usr/lib32/pkcs11)

export DEFAULT_CC="clang"
export DEFAULT_CC_M32="clang -m32"

. $(dirname $0)/master.sh
