#!/bin/bash -e

export PKGNAME=libarchive
export PKGVER=3.2.2
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="http://libarchive.org/downloads/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
