#!/bin/bash -e

export PKGNAME=webrtc-audio-processing
export PKGVER=0.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://freedesktop.org/software/pulseaudio/webrtc-audio-processing/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"

. $(dirname $0)/master.sh
