#!/bin/bash -e

export VER=19
export DEST=/binary/kmod-${VER}

pushd kmod-${VER}

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr          \
            --bindir=/bin          \
            --sysconfdir=/etc      \
            --with-rootlibdir=/lib \
            --with-xz              \
            --with-zlib

make -j4
make install DESTDIR=${DEST}

popd

rm -rf kmod-${VER}

find ${DEST} -name "*.la" -delete

install -dm755 ${DEST}/sbin

for file in depmod insmod lsmod modinfo modprobe rmmod; do
  ln -sf ../bin/kmod ${DEST}/sbin/${file}
done

ln -sf kmod ${DEST}/bin/lsmod

sed -i "s:.so modules.dep.5:.so man5/modules.dep.5:" ${DEST}/usr/share/man/man5/modules.dep.bin.5

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in bin lib sbin usr ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
