#!/bin/bash -e

export VER=0.9.20131130
export DEST=/binary/libquvi-scripts-${VER}

pushd libquvi-scripts-${VER}

./configure --prefix=/usr --with-nsfw

make -j4
make install DESTDIR=${DEST}

popd

rm -rf libquvi-scripts-${VER}

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
