#!/bin/bash -e

export VER=2.11.93
export DEST=/binary/fontconfig-${VER}

cp -a fontconfig-${VER} fontconfig-${VER}-32

pushd fontconfig-${VER}

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-docs       \
            --disable-static

make -j4
make install DESTDIR=${DEST}

install -dm755 ${DEST}/usr/share/man/man{1,3,5}

install -m644 fc-*/*.1 ${DEST}/usr/share/man/man1
install -m644 doc/*.3 ${DEST}/usr/share/man/man3
install -m644 doc/fonts-conf.5 ${DEST}/usr/share/man/man5

popd

pushd fontconfig-${VER}-32

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig

CFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr        \
            --libdir=/usr/lib32  \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-docs       \
            --disable-static

make -j4
make install DESTDIR=${PWD}/dest

mv dest/usr/lib32 ${DEST}/usr

popd

rm -rf fontconfig-${VER} fontconfig-${VER}-32

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

for dir in etc usr var ; do cp -rf --remove-destination $dir / ; done

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
