#!/bin/bash -e

export VER=1.0.1
export DEST=/binary/python-mako-${VER}

cp -a Mako-${VER} Mako-${VER}-3

pushd Mako-${VER}-3

python3 setup.py build
python3 setup.py install --root=${DEST} --optimize=1

mv ${DEST}/usr/bin/mako-render{,3}

popd

pushd Mako-${VER}

python setup.py build
python setup.py install --root=${DEST} --optimize=1

popd

rm -rf Mako-${VER} Mako-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
