#!/bin/bash -e

export VER=7.1
export DEST=/binary/dvd+rw-tools-${VER}

pushd dvd+rw-tools-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/dvd+rw-tools-fixes.patch

sed -i "s:-O2:-march=sandybridge -fomit-frame-pointer -O2 -pipe -fstack-protector-strong:g" Makefile.m4

make all rpl8 -j4
make install prefix=${DEST}/usr

popd

rm -rf dvd+rw-tools-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
