#!/bin/bash -e

export PKGNAME=vlc
export PKGVER=2.2.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.xz
export PKGURL="http://download.videolan.org/pub/videolan/vlc/${PKGVER}/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export POSTINST_TRIGGER=("/usr/lib/vlc/vlc-cache-gen /usr/lib/vlc/plugins")

export CONFIGURE_FLAGS=(--enable-a52
                        --enable-aa
                        --enable-faad
                        --enable-gles1
                        --enable-gles2
                        --enable-ncurses
                        --enable-opus
                        --enable-realrtsp
                        --enable-upnp
                        --enable-vcdx
                        --disable-freerdp)

configure_pre() {
  sed -i "/LUA_COMPAT_MODULE/i #define LUA_COMPAT_APIINTCASTS" modules/lua/vlc.h
}

. $(dirname $0)/master.sh
