#!/bin/bash -e

export PKGNAME=libffi
export PKGVER=3.2.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="ftp://sourceware.org/pub/libffi/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export PATCHES_LIST=("libffi.patch")
export CONFIGURE_FLAGS=(--enable-pax_emutramp)

. $(dirname $0)/master.sh
