#!/bin/bash -e

export PKGNAME=libdv
export PKGVER=1.0.0
export PKGTAR=${PKGNAME}-${PKGVER}.tar.gz
export PKGURL="https://downloads.sourceforge.net/libdv/${PKGTAR}"
export DEST=/binary/multimedia/${PKGNAME}-${PKGVER}
export MAKE_JOBS_FLAGS="-j4"
export MULTILIB_BUILD=1
export INSTALL_CMD=("for dir in usr/include usr/lib usr/lib32 ; do cp -rf --remove-destination \$dir /usr ; done")
export CONFIGURE_FLAGS=(--disable-xv)
export CONFIGURE_FLAGS_32=(--disable-asm --disable-xv)

. $(dirname $0)/master.sh
