#!/bin/bash -e

export VER=2.15.90
export DEST=/binary/pyatspi-${VER}

cp -a pyatspi-${VER} pyatspi-${VER}-3

pushd pyatspi-${VER}-3

PYTHON=/usr/bin/python3 ./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

pushd pyatspi-${VER}

PYTHON=/usr/bin/python ./configure --prefix=/usr

make -j4
make install DESTDIR=${DEST}

popd

rm -rf pyatspi-${VER} pyatspi-${VER}-3

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /
EOF

chmod 755 ${DEST}/INSTALL
