#!/bin/bash -e

export VER=2.2pre2
export DEST=/binary/java-rxtx-${VER}

pushd rxtx-${VER}

patch -Np1 -i /media/ntfs/Other/Linux/patches/rxtx-fixes.patch

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong"   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong" \
./configure --prefix=/usr

make -j4

install -dm755 ${DEST}/usr/lib ${DEST}/usr/share/java/rxtx

make install JHOME=${DEST}/usr/share/java/rxtx RXTX_PATH=${DEST}/usr/lib

popd

rm -rf rxtx-${VER}

find ${DEST} -name "*.la" -delete

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /sbin/ldconfig ] && echo "Processing triggers for glibc" && /sbin/ldconfig
EOF

chmod 755 ${DEST}/INSTALL
