#!/bin/bash -e

export PKGNAME=Linux-PAM
export PKGVER=1.2.1
export PKGTAR=${PKGNAME}-${PKGVER}.tar.bz2
export PKGURL="http://linux-pam.org/library/${PKGTAR}"
export MAKE_JOBS_FLAGS="-j4"
export KEEP_EMPTY_DIRS=1
export POSTINST_TRIGGER=("chmod 4755 /sbin/unix_chkpwd")
export CONFIGURE_FLAGS=(--enable-securedir=/lib/security)

export DEFAULT_CC="clang"

post_install_config() {
  chmod 4755 ${DEST}/sbin/unix_chkpwd

  for file in pam pam_misc pamc
  do
    mv ${DEST}/usr/lib/lib${file}.so.* ${DEST}/lib
    ln -sf ../../lib/$(readlink ${DEST}/usr/lib/lib${file}.so) ${DEST}/usr/lib/lib${file}.so
  done

cat > ${DEST}/etc/pam.conf << "EOF"
# ---------------------------------------------------------------------------#
# /etc/pam.conf								     #
# ---------------------------------------------------------------------------#
#
# NOTE
# ----
#
# NOTE: Most program use a file under the /etc/pam.d/ directory to setup their
# PAM service modules. This file is used only if that directory does not exist.
# ---------------------------------------------------------------------------#

# Format:
# serv.	module	   ctrl	      module [path]	...[args..]		     #
# name	type	   flag							     #
EOF

install -dm755 ${DEST}/etc/pam.d

cat > ${DEST}/etc/pam.d/system-account << "EOF"
# Begin /etc/pam.d/system-account

account	  required       pam_unix.so

# End /etc/pam.d/system-account
EOF

cat > ${DEST}/etc/pam.d/system-auth << "EOF"
# Begin /etc/pam.d/system-auth

auth      required       pam_unix.so nullok_secure
-auth     optional       pam_cap.so

# End /etc/pam.d/system-auth
EOF

cat > ${DEST}/etc/pam.d/system-password << "EOF"
# Begin /etc/pam.d/system-password

password  required       pam_unix.so sha512
-password optional       pam_gnome_keyring.so

# End /etc/pam.d/system-password
EOF

cat > ${DEST}/etc/pam.d/system-session << "EOF"
# Begin /etc/pam.d/system-session

session   required       pam_unix.so
session   required       pam_loginuid.so
-session  optional       pam_systemd.so

# End /etc/pam.d/system-session
EOF

cat > ${DEST}/etc/pam.d/other << "EOF"
# Begin /etc/pam.d/other

auth      required       pam_warn.so
auth      required       pam_deny.so
account   required       pam_warn.so
account   required       pam_deny.so
password  required       pam_warn.so
password  required       pam_deny.so
session   required       pam_warn.so
session   required       pam_deny.so

# End /etc/pam.d/other
EOF
}

. $(dirname $0)/master.sh
