#!/bin/bash -e

export VER=008
export DEST=/binary/usbutils-${VER}

pushd usbutils-${VER}

wget -c http://www.linux-usb.org/usb.ids

CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong "   \
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong " \
./configure --prefix=/usr  \
            --disable-zlib \
            --datadir=/usr/share/misc

make -j4
make install DESTDIR=${DEST}

install -Dm644 usb.ids ${DEST}/usr/share/misc/usb.ids

popd

rm -rf usbutils-${VER}

pushd ${DEST}

find * -type f 2>/dev/null | while read BUILD_BINARY ; do
  case "$(file -bi "${BUILD_BINARY}")" in *application/x-sharedlib* | *application/x-executable*)
    strip --strip-unneeded ${BUILD_BINARY}
  esac
done

popd

cat > ${DEST}/INSTALL << "EOF"
#!/bin/bash

cp -rf --remove-destination usr /

[ -x /usr/bin/mandb ] && echo "Processing triggers for man-db" && /usr/bin/mandb -q
EOF

chmod 755 ${DEST}/INSTALL
