#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf bzip2-${BZIP2_VER} ${LOGDIR}/bzip2-${BZIP2_VER}.log

tar xf ${SROOT}/bzip2-${BZIP2_VER}.tar.gz

{

  time {
  pushd bzip2-${BZIP2_VER}
    make -f Makefile-libbz2_so
    make clean
    make
    make PREFIX=/tools install
    cp -v bzip2-shared /tools/bin/bzip2
    cp -av libbz2.so* /tools/lib
    ln -sv libbz2.so.1.0 /tools/lib/libbz2.so
  popd
  }

} 2>&1 | tee ${LOGDIR}/bzip2-${BZIP2_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf bzip2-${BZIP2_VER}
