#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf texinfo-${TEXINFO_VER} ${LOGDIR}/texinfo-${TEXINFO_VER}.log

tar xf ${SROOT}/texinfo-${TEXINFO_VER}.tar.xz

{

  time {
  pushd texinfo-${TEXINFO_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/texinfo-${TEXINFO_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf texinfo-${TEXINFO_VER}
