#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf shadow-${SHADOW_VER} ${LOGDIR}/shadow-${SHADOW_VER}.log

tar xf ${SROOT}/shadow-${SHADOW_VER}.tar.xz

{

  time {
  pushd shadow-${SHADOW_VER}
    ./configure --prefix=/tools
    make
    cp -v src/su /tools/bin
  popd
  }

} 2>&1 | tee ${LOGDIR}/shadow-${SHADOW_VER}.log

rm -rf shadow-${SHADOW_VER}
