#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf libcap-${LIBCAP_VER} ${LOGDIR}/libcap-${LIBCAP_VER}.log

tar xf ${SROOT}/libcap-${LIBCAP_VER}.tar.xz

{

  time {
  pushd libcap-${LIBCAP_VER}
    make PAM_CAP=no
    make PAM_CAP=no RAISE_SETFCAP=no prefix=/tools install
  popd
  }

} 2>&1 | tee ${LOGDIR}/libcap-${LIBCAP_VER}.log

rm -rf libcap-${LIBCAP_VER}
